### ISSUE TITLE
BTER order API returns 'true' instead of order id.

### ISSUE THREAD

**Issue by dimecoin** [timmolter/XChange#1001]
Sending order returns 'true', instead of order id.

    PollingTradeService.placeLimitOrder(LimitOrder);

From their document, it should return order ID in message:
https://bter.com/api#trade (under: Place order API)

	{
		"result":"true",
		"order_id":"123456",
		"msg":"Success"
    }

**Comment by dimecoin** [comment]
I think this is a easy fix (but haven't tested it).  In file:  XChange/xchange-bter/src/main/java/com/xeiam/xchange/bter/service/polling/BTERPollingTradeServiceRaw.java

Just change the return from:

    return handleResponse(orderId).isResult();

to:

    return handleResponse(orderId);

change method return type.

 64   public boolean placeBTERLimitOrder(CurrencyPair currencyPair, BTEROrderType orderType, BigDecimal rate, BigDecimal amount) throws IOException {
 65 
 66     String pair = String.format("%s_%s", currencyPair.baseSymbol, currencyPair.counterSymbol).toLowerCase();
 67     BTERPlaceOrderReturn orderId = bter.placeOrder(pair, orderType, rate, amount, apiKey, signatureCreator, exchange.getNonceFactory());
 68 
 69     return handleResponse(orderId).isResult();
 70   }

**Comment by timmolter** [comment]
@dimecoin Thanks. I was going to makes changes like you suggested but I found a comment in `BTERTradeDemo`, line 67: " // Returned order id is currently broken for BTER, rely on open orders instead for demo :("

Since I cannot properly test thing without a Bter account, would you be willing to make the change, test and submit a pull request?

**Comment by dimecoin** [comment]
ok, I fixed and tested - but I'm still newbie at git, sorry!

Can you submit change?  Please see Paste: http://pastebin.com/sTtau9qY

1) changed placeBTERLimitOrder and placeBTERLimitOrder to return string

2) change placeBTERLimitOrder to return order id:

    return handleResponse(orderId).getOrderId();

3) Updated javadoc's return value.

4) BTERTradeDemo.java needs to change [not included] on line 36/37 to:

                String orderId = tradeService.placeLimitOrder(limitOrder);
                System.out.println("OrderId: " +orderId); 


I tested change with live orders, live account and returns proper id.  It throws exception like other trade feeds on invalid orders.

**Comment by dimecoin** [comment]
Closing, this has been fixed in Merge #1025 

https://github.com/timmolter/XChange/pull/1025
