### ISSUE TITLE
[btce] BTC-E getTradeHistory() doesn't work.

### ISSUE THREAD

**Issue by dimecoin** [timmolter/XChange#1002]
BTC-E

    PollingTradeService.getTradeHistory() doesn't work (throws exception)

Order data works.

I tested quick in php and there side is working for TradeHistory (https://btc-e.com/api/documentation)

**Comment by timmolter** [comment]
what version of XChange are you using? The latest release or snapshots?

**Comment by dimecoin** [comment]
Was trying on 3 relaes branch, but tried today directly from sources on github.  

Here is exepction:

    java.lang.ClassCastException: com.xeiam.xchange.currency.CurrencyPair cannot be cast to java.lang.Long
    at com.xeiam.xchange.btce.v3.service.polling.BTCETradeService.getTradeHistory(BTCETradeService.java:91)
    at com.dimecoingames.cryptotrade.feed.ExchangeFeed.getTrades(ExchangeFeed.java:178)
    at com.dimecoingames.cryptotrade.feed.Feed.start(Feed.java:113)
    at com.dimecoingames.cryptotrade.feed.FeedService$FeedThread.run(FeedService.java:64)    


It looks like a casting issue in :  XChange/xchange-btce/src/main/java/com/xeiam/xchange/btce/v3/service/polling/BCETradeService.java  

The feature is there, so hopefully it's as simple as just changing the data type?

**Comment by rafalkrupinski** [comment]
@dimecoin vararg parameters are specific to the implementation. Please see the javadoc for this method.

**Comment by dimecoin** [comment]
ok, I see the issue.

On these exchanges : (cryptsy, bter, bittrex, and bitfinex), the tradeService.getTradeHistory() takes a CurrencyPair and returns trades for that pair.  But btce does not, it throws that casting exception (from CurrencyPair to long) that I noted above.

Is this an inconsistent api or if I'm using it incorrectly?

    PollingTradeService tradeService =  exchange.getPollingTradeService();


    // This works for cryptsy, bter, bittrex, and bitfinex, but throws cast exception for btce
    UserTrades trades = tradeService.getTradeHistory(new CurrencyPair("LTC", "BTC"));

    // This works for btce, but bter throws exception
    UserTrades trades = tradeService.getTradeHistory();

**Comment by rafalkrupinski** [comment]
I'd advice against changing BTC-e version, even though accepting (String, String) instead of CurrencyPair is inconsistent with all other interfaces. I think `PollingTradeServive.getTradeHistory(Object...)` is to be deprecated in favour of `getTradeHistory(TradeHistoryParams)` (@timmolter #933?). See if the new method suits your needs.

**Comment by dimecoin** [comment]
ok fair enough. I have already worked around it in my code and will test moving to the new API with TradeHistoryParams if that is the furture.  

I'll let either of you decide if this issue request should be closed or kept open.

**Comment by timmolter** [comment]
@rafalkrupinski Yeah, i'll remove that deprecated method eventually.
