### ISSUE TITLE
Cryptsy public order book data requires login.

### ISSUE THREAD

**Issue by dimecoin** [timmolter/XChange#1003]
This requires a api keys (XChange throws an exception)

    PollingMarketDataService.getOrderBook 

According to their documentation, orderBook data is public and doesn't require a authentication:

https://www.cryptsy.com/pages/publicapi

**Comment by timmolter** [comment]
Hmmm. Maybe they changed it. Good to know. Thanks.

**Comment by dimecoin** [comment]
Actucally, this is working without auth from github sources today.  Can be closed.
