### ISSUE TITLE
Cryptsy 502 error

### ISSUE THREAD

**Issue by tmlee** [timmolter/XChange#1011]
I was wondering if anybody is experiencing random or 502 errors from making calls to Cryptsy.

For instance one of the domain (ie. pubapi1, http://pubapi1.cryptsy.com/api.php?method=singlemarketdata&marketid=132) would give me a 502 error, and the other (ie. pubapi2, http://pubapi2.cryptsy.com/api.php?method=singlemarketdata&marketid=132) works fine. 

The default pubapi, gives me error from time to time. Are you experiencing this?

Was wondering if anybody is voting to migrate the API endpoint to Cryptsy's V2 API over at https://www.cryptsy.com/pages/apiv2/markets ?

**Comment by ahmedbodi** [comment]
I'd like it to use a combination of V1 and V2. e.g. the withdrawal stuff in V2 requires a callback url in the settings. so id say use V2 for everything besides deposits and withdrawals.

**Comment by Achterhoeker** [comment]
For several hours i'm getting only errors 502 and 503 from cryptsy. And indeed, pubapi2 seems to work with the given link where pubapi1 gives the 502.

So I agree with tmlee, why not change to v2 if that is giving less problems ?

**Comment by whitfa99** [comment]
I too was also getting this.  For me anyway, I reached the conclusion that I was making too many (too frequent) getExchangeSymbols calls in an effort to populate CryptsyCurrencyUtils.  The reason I'm confident that it was this is that I changed my API key in between making sequential calls and it allowed one to go through immediately after the new key.
