### ISSUE TITLE
Is there a way to format the output into json or XML?

### ISSUE THREAD

**Issue by whitfa99** [timmolter/XChange#1012]
Hi,

Sorry if this isn't the right place for questions, and forgive my Java inexperience, but I'm just wondering if there is a straight forward way of turning the output of say marketDataService.getOrderBook() into a json output?

I'm using the XChange library in a groovy script operator inside a java application (Rapidminer), and it would be much easier for me to parse the output data if it were json.  Would the library need to be rewritten significantly in order to change this?

Also, does XChange take care of honouring each exchanges' rules as regards to delay between requests, or should my script handle that aspect?

Love this library, thank you!

**Comment by timmolter** [comment]
1) Not really possible. You could use Jackson and simply serialize the DTOs into JSON if you wanted.
2) No. You need to handle that separately. @bryan4887 worked on something like that though recently.

**Comment by whitfa99** [comment]
1) That Jackson suggestion looks very straight forward,  thanks Tim. 
2) For any given exchange and method type I am currently calling that method for each pair one after the other without a delay. Is that generally accepted, or should I also be delaying each individual pair request as well as each type of method request?

Sorry, I know there are lots of exchanges with different rules and this question might be too ambiguous.

**Comment by timmolter** [comment]
2) No, that's probably not a good idea. Most exchanges, but not all, will publish their allowed refresh rate and it you go over that, they will ban your access to the API. Each exchange has different rules and some don't even publish that info.

**Comment by whitfa99** [comment]
Okay, thanks for the info Tim, really appreciate it, and your work.

**Comment by bryan4887** [comment]
@whitfa99 Take a look at https://github.com/timmolter/XChange/tree/develop/xchange-core/src/main/java/com/xeiam/xchange/utils/retries

Also, the max polling rates are in the json in  src/main/resources of each exchange.  Some you can query via the API.  If you find that this information is missing or inaccurate, we'd all appreciate you adding it or updating it.
