### ISSUE TITLE
BTCChina socket keeps disconnecting

### ISSUE THREAD

**Issue by supraniti** [timmolter/XChange#1013]
i'm using btcchina.service.straeming for market data,
however - the socket keep disconnecting after a few seconds than reconnects, and over again.
the result is about 50% down time on market data streaming.
anybode experienced this kind of problem? knows how to create a steady socket connection?

my socket configuration:
  @Override
  public int getMaxReconnectAttempts() {

    return 5;
  }

  @Override
  public int getReconnectWaitTimeInMs() {

    return 1000;
  }

  @Override
  public int getTimeoutInMs() {

    return 5000;
  }

  @Override
  public boolean isEncryptedChannel() {

    return false;
  }

  @Override
  public boolean keepAlive() {

    return true;
  }

**Comment by jheusser** [comment]
Connectivity to China is very bad, highly likely you will not be able to keep a connection alive. Best to use just polling.
