### ISSUE TITLE
ItBit getOpenOrders returns only XBTUSD orders

### ISSUE THREAD

**Issue by Panchen** [timmolter/XChange#1018]
XBTEUR and XBTSGD open orders aren't returned. 

ItBitTradeServiceRaw.getItBitOpenOrders() contains a hard coded "XBTUSD" supplied as the instrument parameter to the ItBit api call. However, instrument is an optional api parameter. 

For consistency with other exchanges I think the hard coded instrument parameter should be removed.
Thoughts?

**Comment by rafalkrupinski** [comment]
Go ahead :)

BTW, could you please update api-specification.txt file?

**Comment by timmolter** [comment]
Yes. Making it consistent would be a good idea.

**Comment by jheusser** [comment]
Yeah vaguely remember hardcoding it, before any of them were liquid. Should be easy to change this now.
