### ISSUE TITLE
Can you add c-cex.com

### ISSUE THREAD

**Issue by cryptow** [timmolter/XChange#1019]
Can anyone add c-cex.com please?

**Comment by litecoinmessiah** [comment]
They use a similar api to bittrex v1.1 at the moment from what the admin has told me,

[public]:
GetBalanceDistribution
getorderbook
getmarkets

[private]:
getbalances
getbalance
getopenorders
buylimit
selllimit
cancel
getorder

here is example how to call it:
https://c-cex.com/t/api.html?a=buylimit&apikey=API_KEY&market=BTC-LTC&nonce=NONCE&quantity=5&rate=0.0001

public calls are here:
https://c-cex.com/t/api_pub.html?a=getorderbook&market=BTC-LTC&type=both&depth=2
https://c-cex.com/t/api_pub.html?a=GetBalanceDistribution&currencyName=xtp
https://c-cex.com/t/api_pub.html?a=getmarkets

**Comment by timmolter** [comment]
added to Wiki
