### ISSUE TITLE
Add asset info to OkCoinFunds

### ISSUE THREAD

**Issue by inheaven** [timmolter/XChange#1028]
# Request

POST https://www.okcoin.com/api/v1/userinfo.do
# Response

{
    "info": {
        "funds": {
            "asset": {
                "net": "0",
                "total": "0"
            },
            "borrow": {
                "btc": "0",
                usd: "0",
                "ltc": "0"
            },
            "free": {
                "btc": "0",
                usd: "0",
                "ltc": "0"
            },
            "freezed": {
                "btc": "0",
                usd: "0",
                "ltc": "0"
            },
            "union_fund": {
                "btc": "0",
                "ltc": "0"
            }
        }
    },
    "result": true
}

**Comment by jheusser** [comment]
A lot of API changes since this issue was raised.
