### ISSUE TITLE
Maven Build Fails on Cointrader

### ISSUE THREAD

**Issue by bryan4887** [timmolter/XChange#1030]
```
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.2:compile (default-compile) on project xchange-cointrader: Compilation failure: Compilation failure:
[ERROR] /Users/bryanh/XChange/XChange/xchange-cointrader/src/main/java/com/xeiam/xchange/cointrader/dto/CointraderBaseResponse.java:[3,17] cannot find symbol
[ERROR] symbol  : class Objects
[ERROR] location: package java.util
[ERROR] /Users/bryanh/XChange/XChange/xchange-cointrader/src/main/java/com/xeiam/xchange/cointrader/Cointrader.java:[3,17] cannot find symbol
[ERROR] symbol  : class Objects
[ERROR] location: package java.util
[ERROR] /Users/bryanh/XChange/XChange/xchange-cointrader/src/main/java/com/xeiam/xchange/cointrader/dto/CointraderBaseResponse.java:[20,10] cannot find symbol
[ERROR] symbol  : variable Objects
[ERROR] location: class com.xeiam.xchange.cointrader.dto.CointraderBaseResponse<D>
[ERROR] /Users/bryanh/XChange/XChange/xchange-cointrader/src/main/java/com/xeiam/xchange/cointrader/Cointrader.java:[66,73] cannot find symbol
[ERROR] symbol  : variable Objects
[ERROR] location: class com.xeiam.xchange.cointrader.Cointrader.Pair
[ERROR] /Users/bryanh/XChange/XChange/xchange-cointrader/src/main/java/com/xeiam/xchange/cointrader/Cointrader.java:[71,14] cannot find symbol
[ERROR] symbol  : variable Objects
[ERROR] location: class com.xeiam.xchange.cointrader.Cointrader.Pair
[ERROR] -> [Help 1]
```

So I see the cause of this.  I've handled these problems internally in Eclipse easily by just changing the java library used to java 7 within that maven module, however, when I want to `mvn install` all of XChange, I can't figure out how to avoid this problem.  

If we are using Java 7 objects (`java.utils.Objects`), how can we continue to require Java 6 compilation?
```
<!-- Ensure compilation is done under Java 6 in all environments -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.2</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
					<showDeprecation>true</showDeprecation>
					<showWarnings>true</showWarnings>
				</configuration>
			</plugin>
```

Any help is greatly appreciated!

**Comment by bryan4887** [comment]
...well, I wish I had a better answer to this in case someone else hits this problem as well, but this is what I did to fix it.
1. change my local environment from java 8 to java 7.  `mvn install` then worked.
2. change my local environment back to java 8.  `mvn install` also works....which I don't understand.  But hey, at least it's working now.

**Comment by rafalkrupinski** [comment]
Does `mvn clean install` still work?

**Comment by timmolter** [comment]
@bryan4887 I cannot repeat the issue. I wasn't aware that `java.utils.Objects` was Java 1.7+ until now, and I'm confused now why the build is even working at all. 

I did some research and I think we should bump the compiler plugin up to use 1.7. I wanted to keep it at 1.6 for Android, but it looks like Android is now 7 and 8 compatible.

**Comment by bryan4887** [comment]
@rafalkrupinski `mvn clean install` did not work.
@timmolter Yeah—I have a feeling that it has something to do with the way my maven environment is setup.  If I have to deal with it again, I'll report back here for posterity's sake.

+1 for bumping to 1.7.
