### ISSUE TITLE
Coinbase returns false when querying account info

### ISSUE THREAD

**Issue by Muffon** [timmolter/XChange#1035]
Hello,

can someone test that coinbase account info query is correct?

Btce and Kraken queries are working well. But when I try coinbase it returns

{"success":false,"error":"ACCESS_KEY not matched with a user"}

But I am sure that my api key, secret key and login with password are set well. 

Can I view a request to the coinbase server to check the JSON? How?

If the library worked, where could be another problem? Thanks for advice

v3.0.0

**Comment by timmolter** [comment]
Try the latest snapshot jars. Also, see the Wiki pages for how to view the raw JSON.

**Comment by Muffon** [comment]
Hello, in 3.1 it returns 
"HTTP status code was not OK: 401"

**Comment by Muffon** [comment]
I have solved my problem. I did not set specific echxange parameter "passphrase" for Coinbase account
