### ISSUE TITLE
Cryptsy - Issue with getting fees

### ISSUE THREAD

**Issue by kevkid** [timmolter/XChange#1037]
I have an issue getting the correct value for the trade fees in cryptsy. From what I understand these fees are per account and can be accessed with "/api/v2/markets/:id/fees" which works in a web browser as long as you are logged in. So I tried to do this:

system.out.println("\nCalculateFees:\n"
                + ((CryptsyTradeServiceRaw) TradeService).calculateCryptsyFees(CryptsyOrderType.Buy, new BigDecimal("1"), new BigDecimal("288.63643561")));

I get this:

CalculateFees:
CryptsyReturn[OK: CryptsyOpenOrder[Fee='0.95250024',Net Amount='289.58893585']]

But on cryptsys website I get a different value

![image](https://cloud.githubusercontent.com/assets/1369930/9144592/0f8caefc-3d1c-11e5-9247-4f7e0a469f76.png)

Why is this different? can I just get the percentage?

**Comment by kevkid** [comment]
It may be an issue on cryptsys side:

https://github.com/wishhhmaster/CoinTNet/issues/6

**Comment by kevkid** [comment]
I figured it out, here is my solution:
if(VolumeInBTC < 0.5){
			PairFee = 0.0033; //0.33%
		}
		else if(VolumeInBTC >= 0.5 && VolumeInBTC < 1.0){
			PairFee = 0.0031; //0.31%
		}
		else if(VolumeInBTC >= 1.0 && VolumeInBTC < 5.0){
			PairFee = 0.0029; //0.29%
		}
		else if(VolumeInBTC >= 5 && VolumeInBTC < 20){
			PairFee = 0.0027; //0.27%
		}
		else if(VolumeInBTC >= 20){
			PairFee = 0.0025; //0.25%
		}
		else{
			System.exit(1);//something went wrong
		}
		return PairFee;
	}

How silly of me to not see this. Just get the volume in btc and run the switch statement.

**Comment by timmolter** [comment]
Thanks for posting the solution!
