### ISSUE TITLE
[coinbase] NPE when the user's balance is zero

### ISSUE THREAD

**Issue by doublesharp** [timmolter/XChange#1047]
When the user's balance is 0 the Coinbase API is returning null for the `user.balance`, which should be a `CoinbaseMoney` instance. When the adapter code is running to create the wallet it calls CoinbaseMoney.getAmount() which is causing a `NullPointerException`.

The code triggering the exception can be found here: https://github.com/timmolter/XChange/blob/develop/xchange-coinbase/src/main/java/com/xeiam/xchange/coinbase/CoinbaseAdapters.java#L39

**Comment by timmolter** [comment]
I think this is the same issue reported here: https://github.com/timmolter/XChange/issues/1062. The Coinbase V1 API is deprecated and the XChange implementation should be udpated.
