### ISSUE TITLE
Bitcurex getPollingAccountService returns null

### ISSUE THREAD

**Issue by Muffon** [timmolter/XChange#1048]
Hello,
BitcurexExchange does not return an account service. It returns null.

**Comment by rafalkrupinski** [comment]
Only market data is implemented for bitcurex; see
https://github.com/timmolter/XChange/wiki/Exchange-Support

**Comment by Muffon** [comment]
Ok, sorry

**Comment by rafalkrupinski** [comment]
Don't be :) We would all appreciate if you or anyone else have implemented the missing functionality :)
