### ISSUE TITLE
OKCoin returning  CNY/BTC value instead of USD/BTC

### ISSUE THREAD

**Issue by Muffon** [timmolter/XChange#1051]
Hello following code returns CNY/BTC value instead of USD/BTC 
```java

  Ticker ticker = null;
        try {
            ticker = xchange.getPollingMarketDataService()
                    .getTicker(new CurrencyPair("BTC/USD"));

        } catch (ExchangeException | NotAvailableFromExchangeException | NotYetImplementedForExchangeException | IOException ex) {
            logger.error(ex);
        }
```

**Comment by rafalkrupinski** [comment]
Are you  using OKCoin international?

**Comment by Muffon** [comment]
What do you mean by international? I just use XChange OKCOin library. I am sorry if I have missed something but I didn't find  anything at wiki about OKCoin International.

**Comment by rafalkrupinski** [comment]
A snippet from examples:
`specification.setExchangeSpecificParametersItem("Use_Intl", true);`

**Comment by Muffon** [comment]
Thank you very much! I have missed that.

**Comment by rafalkrupinski** [comment]
No wonder, it's not really a documentation :)

**Comment by jheusser** [comment]
I'll write a brief wiki entry on how to configure OkCoin.

**Comment by Muffon** [comment]
It would be grate because I did not succeeded with setting 
```java
specification.setExchangeSpecificParametersItem("Use_Intl", true);
```
I'm still getting CNY.

**Comment by jheusser** [comment]
Please see the many examples how to instantiate an exchange from an exchange specification and how to set exchange specific parameters. Basic framework is:
```
ExchangeSpecification exSpec = new ExchangeSpecification(exchangeClass);
exSpec.setExchangeSpecificParameters(params);
...
Exchange exchange = ExchangeFactory.INSTANCE.createExchange(exSpec);
```

**Comment by Muffon** [comment]
Thanks jheusser, I did set specs after I the exchange instance was created. Now it's fine.
