### ISSUE TITLE
[itbit] API response codes/errors swallowed by IOException

### ISSUE THREAD

**Issue by doublesharp** [timmolter/XChange#1053]
The ItBit API will respond with an HTTP error code along with details about the error in a JSON encoded body, however this information is not available to the exchange implementation or downstream projects because rescu is not being exported. With a superclass of IOException the actual error coming from the exchange is lost (still visible in debugging, but not for realtime error handling).

Example: https://api.itbit.com/docs#trading-new-order

Currently available

> IOException message: `HTTP status code was not OK: 422`

Additional error information that is being lost

> HttpStatusIOException httpStatusCode: `422`
> HttpStatusIOException httpbody: `{"code":81001,"description":"The wallet provided does not have the funds required to place the order.","requestId":"9c1c6aa0-39f7-4f3c-8486-xxxxxxxxxx"}`

As HTTP Code 422 is returned for multiple types of errors the only way to handle this error properly is to look at the code returned in the HTTP body. 

Do you have a suggestion for how these properties can be exposed? Should they be wrapped by an Exception in XChange rather than including rescu in downstream projects so they can cast to HttpStatusIOException?

**Comment by timmolter** [comment]
There is an elegant way to do this. See: <https://github.com/mmazi/rescu/wiki/Exception-handling>

**Comment by mmazi** [comment]
Basically, all  `ItBitAuthenticated` should declare they throw a custom exception, eg. ItBitException.

It's easy. Here are quick instructions:

0. Create `class ItBitException extends HttpStatusExceptionSupport` (or without extends if you don't want rescu dependency, but this automatically adds the http status code to the exception object). Jackson-annotate it to conform to the itbit error json: https://api.itbit.com/docs#error-codes
0. Declare `throws ItBitException` on all API methods

That's it. Now you can catch ItBitException and get the itbit error code. (If you want to get the http status code in the exception object, you'll need to depend on rescu.)
