### ISSUE TITLE
BitStamp returns BTC_USD pair ticker info for nonexisting currency pairs

### ISSUE THREAD

**Issue by Muffon** [timmolter/XChange#1061]
Hello, I have tried to query a ticker from BitStamp and when I set a currency pair for example as BTC_CZK,  it returns  BTC_USD value. This is a very dangerous bug. 
I have not tried this behaviour on all exchanges, only on  BitStamp

**Comment by timmolter** [comment]
Good catch. I'll look into it.

**Comment by timmolter** [comment]
I pushed a fix for this that does an assert.
