### ISSUE TITLE
Coinbase account info - NullReferenceException

### ISSUE THREAD

**Issue by Muffon** [timmolter/XChange#1062]
Hello, I have found that in 3.1.0, the CoinbaseAdapters.java fails in adaptAccountInfo method

```java
    final CoinbaseMoney balance = user.getBalance();    
    
    final List<Wallet> wallets = new ArrayList<Wallet>();    
  
    final Wallet wallet = new Wallet(balance.getCurrency(), balance.getAmount());

    wallets.add(wallet);
```

Why this aproach? Why we are querying balance in this method? I have commented these lines and passed an empty array of wallets to new AccountInfo and it works well, I think. When I then query a concrete currency pair balance, it works well to. I am getting valid wallets.

**Comment by timmolter** [comment]
How does it fail exactly? Null?

**Comment by Muffon** [comment]
user.getBalance();  retruns null

But I don't understand even the purpose of querying a balance in this method.

**Comment by timmolter** [comment]
My guess is that when the class was created, there was only one wallet type and this was a good place to access it. I bet the API endpoint changed, and now the code needs to be updated. Yup actually V1 is now deprecated: https://developers.coinbase.com/api/v1

Maybe you should try the coinbaseex module instead?

**Comment by Muffon** [comment]
Can I automatically withdraw funds from CoinbaseEx? I guess not. So I need to stick with classic Coinbase.

**Comment by timmolter** [comment]
I'm happy to accept a  pul request from you if you get this issue ironed out.

**Comment by Muffon** [comment]
I will make a fork. Please, give me an advice if there are best practices including api veersion migration. Do you think I could start from current code or I have to start from scratch?

**Comment by timmolter** [comment]
I bet you could start from the current code. I would recommend simply replacing v1 with v2 by adapting all the current code. See "best practices" wiki for tips on how to get access to the raw JSON for building and testing the correct DTOs for the JSON.

**Comment by Muffon** [comment]
OK, thanks

**Comment by timmolter** [comment]
Closing this, as the issue probably need an entire API version update.
