### ISSUE TITLE
100 mBTC Bounty - Wrap all exchange-specific Exceptions

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#1063]
... for all implementations. 

For an example of how it should be implemented: `BitfinexTradeServiceRaw.java`

**Comment by rafalkrupinski** [comment]
Does it require having accounts on all the exchanges?

**Comment by timmolter** [comment]
No. Just check all implementations and ones like `BitsoTradeService`, don't allow it to be thrown further, but wrap it in `ExchangeException`. Also, would there be a way to not allow people to be lazy and throw those exceptions like that?

**Comment by rafalkrupinski** [comment]
I should be doable with reflections

**Comment by rafalkrupinski** [comment]
I have a solution in mind. Should Rescu exceptions also be wrapped or just exchange specific exceptions declared in exchanges' REST interfaces?

**Comment by timmolter** [comment]
Declared Rescu exceptions should be wrapped - if it's defined in the Rescu interface. Otherwise, I believe Rescu throws a generic IOException.

**Comment by mmazi** [comment]
I don't think requiring every exchange implementation to include tons of try/catch boilerplate is a very good idea, for several reasons, including (but not limited to):
- There will be huge amounts of boilerplate (perhaps more than actual logic) which makes code unreadable and difficult to maintain.
- People just won't do it, or will do it wrong.

If this is indeed desirable ( @timmolter , could you state the intended purpose of this request?), I think we should find a general solution in XChange and leave the implementations clean.

I created a draft for discussion about general exception handling in XChange in #1233.

**Comment by timmolter** [comment]
Closing in order to discuss this first more in depth. Thanks @mmazi !
