### ISSUE TITLE
300 mBTC Bounty - Remove PollingTradeService deprecated `getTradeHistory`

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#1064]
... and update all implementations to use the `getTradeHistory(TradeHistoryParams params)` if necessary.

**Comment by rafalkrupinski** [comment]
Let me do it

**Comment by rafalkrupinski** [comment]
@felipelalli You were the original author of the MercadoBitcoin code, would you please verify if getTradeHistory works properly? Thanks!

**Comment by felipelalli** [comment]
Sure. I'm in vacation, next week I can see it. Is it OK?

- from mobile

**Comment by timmolter** [comment]
@rafalkrupinski Thank you! What BTC address should I send the bounty to?

**Comment by rafalkrupinski** [comment]
@felipelalli Sure thing, thanks again!

**Comment by timmolter** [comment]
Paid. Thanks!

**Comment by felipelalli** [comment]
@rafalkrupinski I am back from vacation, but to be honest I can't have a look on this soon. But eventually I'll use the API in the future, so if I find anything wrong I send a patch to fix. Thank you and I am sorry.
