### ISSUE TITLE
OkCoin getWebSocketStatus issue

### ISSUE THREAD

**Issue by lukaszaoralek** [timmolter/XChange#1067]
The method getWebSocketStatus() of the class OkCoinStreamingExchangeService always return READYSTATE.OPEN. Therefore it isn't possible to make any decisions based on the socket status for the OkCoin exchange (i.e. reconnect). Also an assertEqual check in TickerStreamingIntegration.java for the OkCoin (assertThat(service.getWebSocketStatus()).isNotEqualTo(WebSocket.READYSTATE.CLOSED);) doesn't make sense now.

**Comment by jheusser** [comment]
OkCoin streaming is mostly unmaintained at the moment, closing this for now. Be on the look out for Okcoin commits if anything changes.
