### ISSUE TITLE
Support for `tid` / `since` in trades method

### ISSUE THREAD

**Issue by jangorecki** [timmolter/XChange#1071]
I cannot find this anywhere in the docs so writing question here.
Not all markets supports fetching historical trades from particular trade id. For example, kraken does, btce doesn't, bitstamp was supporting till October 2013.
The question is which markets are handled by XChange in terms of that `tid`/`since` param to trades method? Are there any examples available for usage of that argument?

**Comment by timmolter** [comment]
Yes each exchange does it differnetly as you observed. Here is the getTrades method:

      Trades getTrades(CurrencyPair currencyPair, Object... args)

You need to pass the correct `args` that match the code for each XChange module. It's not documented though - you just need to peek at the code, but it should all be heavily commented.

**Comment by jangorecki** [comment]
OK, thanks for clarifying.
