### ISSUE TITLE
AccountInfo.getTradingFee() in currency or percent?

### ISSUE THREAD

**Issue by Muffon** [timmolter/XChange#1072]
Hello, do you know, is  the trading fee returned in currency or in percents? Or does it depends on each Exchange? Thank you!

**Comment by mmazi** [comment]
I think the fee should generally be returned as a fraction, e.g. 0.005 for 0.5% trading fee. It is possible though that there is not much consistency here across exchange implementations in XChange. Those that provide this information will generally simply return whatever the API returns so you should check the API docs of particular exchanges. I just tried a few exchange implementations in XChange: Taurus returns what the API returns (but the API docs don't clearly say what it is), and Bitso, Bitmarkets, Cointrader, IndependentReserve and The Rock don't return anything at all.

**Comment by baffo32** [comment]
I think two kinds of fees have been confused:
1. fee for doing trades on the exchange (usually %)
2. "network transaction fee" for withdrawing currency (usually flat)
The exchanges I've looked at so far tend to provide #2 in the api, but I think it's #1 that xchange stores and cares about.

**Comment by timmolter** [comment]
`getTradingFee() ` should be 1. above and in a percentage. I don;t think we have a "network transaction fee", but it could be that some implementors falsely added that to `getTradingFee() ` impl.

**Comment by Muffon** [comment]
Thanks for reponses.
