### ISSUE TITLE
ANX - status code was not OK 403

### ISSUE THREAD

**Issue by Muffon** [timmolter/XChange#1078]
Hi, I have been using ANX library since summer without problems. Now I am getting this exception. Is anyone experiencing same problem?

**Comment by Muffon** [comment]
Mistake on my side

**Comment by radumiron** [comment]
@Muffon how did you get to fix your mistake? I'm experiencing the same issue.

**Comment by Muffon** [comment]
@radumiron I think it was my mistake with bad auth token.
