### ISSUE TITLE
KrakenTradeHistory limited to 50 results

### ISSUE THREAD

**Issue by mrosseel** [timmolter/XChange#1083]
The Kraken API returns a count with which one can advance an offset and retrieve all history results. This count is known in the KrakenTradeHistoryResult but subsequently lost when returning the result.
Is this a bug or did I miss something?

```
public Map<String, KrakenTrade> getKrakenTradeHistory(String type, boolean includeTrades, Long start, Long end, Long offset) throws IOException {

    KrakenTradeHistoryResult result = kraken.tradeHistory(type, includeTrades, start, end, offset, exchange.getExchangeSpecification().getApiKey(),
        signatureCreator, exchange.getNonceFactory());

    return checkResult(result).getTrades();
  }
```

**Comment by timmolter** [comment]
I use the timestamp:

    marketDataService.getTrades(currencyPair, since);

rather than the count.

**Comment by timmolter** [comment]
But yes, that's not a bug, but the design of XChange. If you want exchange-specific data, you need to operate at the level of the specific exchange (raw).
