### ISSUE TITLE
[EFunding:Unknown withdraw key] in kraken withdrawal

### ISSUE THREAD

**Issue by Cocongo** [timmolter/XChange#1085]
I've have an issue when i try to withdraw funds from kraken.

I've 
" com.xeiam.xchange.exceptions.ExchangeException: [EFunding:Unknown withdraw key]
exception after i use method krakenExchange.getPollingAccountService().withdrawFunds("XXBT",
                new BigDecimal(1), ADDRESS);

The api key is correct and it's works for AccountInfo.
The api-key is abilitated for withdrawal.

Thanks for your time

**Comment by Garritt** [comment]
Were you ever able to resolve the issue? I have tried all values for the withdrawal key and still am receiving the same error

Thanks!

**Comment by viethuyphan** [comment]
Hi guys,

Did you resolve this issue? I still got this error while I tried to withdraw with API.

Thanks!

**Comment by timmolter** [comment]
Not that I'm aware of. Make sure to try the latest snapshot jars.

**Comment by viethuyphan** [comment]
Thanks @timmolter,

I use the .NET API, but I'll try the latest version.

**Comment by mmazi** [comment]
I also ran into this issue. Kraken's API doesn't allow the caller to specify an arbitrary bitcoin address for withdrawal; rather, the name of one of the withdrawal addresses register via the Web UI (at https://www.kraken.com/u/funding/withdraw?asset=XXBT, `Add address`) must be used.

The easiest workaround that enables using the Kraken XChange API consistently with the XChange API contracts is to specify all the required withdrawal address via Kraken's WEB UI with the name equal to the address.

**Comment by mmazi** [comment]
@Cocongo @Garritt  @viethuyphan does my workaround work for you? (I've used it myself for a while now without problems.) Do you think we can still help you in some way? If not, I'd like to close this issue.

**Comment by thche** [comment]
erm so i tried this workaround.. still not working proper i added the withdrawalkey in kraken as identifier. but it doesn't allow me to do a test withdrawal.

**Comment by mmazi** [comment]
The "key" referred to in "EFunding:Unknown withdraw key" does _not_ refer to the the API key, but rather the *name* of the address that you register via the Web UI. (I've clarified this above - see my full answer above. )

> How do I add the "key" for the work around,

Via the Kraken Web UI (plus you need to confirm via e-mail): https://www.kraken.com/u/funding/withdraw?asset=XXBT

**Comment by rsparrow** [comment]
@mmazi yes, sorry I've got the name from the UI just trying to figure out how to plug it into ccxt api. I've got the email verified the name all that stuff. I'm just trying to figure out how make the "withdraw" call with that name of the address.

**Comment by ch3ll0v3k** [comment]
@mmazi  Thank you dude!
