### ISSUE TITLE
Clarification of Trade OrderType

### ISSUE THREAD

**Issue by baffo32** [timmolter/XChange#1094]
Does the OrderType of a Trade reflect that of the limit order it closes or the market order it represents?

i.e. should a market trade which decreases a limit BID order be marked as an ASK or a BID?

**Comment by jheusser** [comment]
It's out of the view of the trader, so a BID is buy, and ASK is sell independent of the order type. A market or marketable order where you buy is a BID. A market or marketable order where you sell is ASK. Same for a limit where where you passively buy/sell.

**Comment by baffo32** [comment]
Thank you.

I think you're saying that if there is an open BID in the orderbook, and this order is closed via a successful trade, I should provide:
- A Trade with OrderType = ASK for the trade
- An OrderBookUpdate with OrderType = BID for the depth decrease
- I'm presuming that OrderBookUpdate will have negative volume.

I'll update comments so if somebody as dense as me reads them it will be more clear.

**Comment by andrewlin0410** [comment]
Can someone clarify this even more? This is really confusing
