### ISSUE TITLE
Standard Streaming Interface

### ISSUE THREAD

**Issue by baffo32** [timmolter/XChange#1096]
There is no standard streaming service interface at the moment.

`ExchangeEvent` and `ExchangeEventType` are not currently used in a consistent way.  Coinfloor made up its own structure in order to provide both raw and generic data.  Only two of the `ExchangeEventType`s have consistent and specified usage.  Different exchanges are providing streaming order data in conflicting ways (e.g. Bitstamp uses DEPTH for an orderbook delta, and others use DEPTH for an orderbook snapshot of the top so-many orders).

These have happened because the API is unspecified.

I propose encouraging exchanges to provide two streaming services, one which gives raw dtos and uses exchange-specific eventtypes, and one which uses only official xchange-provided ExchangeEvent subclasses.  The conforming service will wrap the raw service, as in polling.

This could be improved by providing a class the conforming service is required to use, which has one method to register what eventtypes the exchange will be sending, and one method for each eventtype to dispatch that event.

One could have the model for streaming and polling services be the same, differing only in whether the service is providing the data or responding to requests for it -- i.e. they would both register something equivalent to an 'EventType' so that clients can enumerate what data is available.

**Comment by timmolter** [comment]
I agree. The streaming API is currently a hodge-podge of code and needs consistency and a good cleanup. It'd be a huge undertaking though, and I don't see the amount of community interest around the streaming APIs necessary to justify the amount of effort. I'd be pleased to be proven wrong though and I'd definitely support such a refactor. Your suggestion of a raw and generic services like for the polling API would be the way to go.

**Comment by rafalkrupinski** [comment]
It seems to me that more applications would benefit from unified streaming API. I'd rather see the streaming API implemented upon the polling API.

**Comment by langfors** [comment]
+1 for reconciling streaming; I use this and have loads of custom code to accommodate the differences in the exchange implementations.

**Comment by timmolter** [comment]
Streaming now dropped in this lib: https://github.com/timmolter/XChange/issues/1235
