### ISSUE TITLE
Service Interface Refactoring

### ISSUE THREAD

**Issue by baffo32** [timmolter/XChange#1098]
Right now each exchange implementation is responsible for providing the features exposed to the application, by implementing appropriate `*Service` interfaces.

I think the features provided by each implementation should be separated from the features exposed to the application.  If implementation features can be generalized, then a single middle-layer can compose them together to provide a unified interface to the application.  Streaming can be emulated via polling the polling services.  Polling can be emulated via caching the streaming services.  If a new exchange implementation provides a feature in some way that does not mesh well with the system, the implementer is encouraged to expand the middle-layer to fully support the new exchange, so that their code may be used by future exchanges with a similar feature.

This means rather than providing the application a set of interfaces, the application sees a set of concrete classes, the middle layer, which can handle any exchange.  This middle layer could even be a separate project.  But it relies on a unified set of information available from exchanges.

Here is one design idea for a more general interface available to exchange implementations:
- Each service type has a base class, the protected constructor of which takes a set of enums of provided features.
- Polling features are implemented as overridden methods of the base class.
- Streaming features are implemented as calls to protected methods of the base class.

This would resolve #1096, #578, and the polling interface issue mentioned in #933 .

**Comment by timmolter** [comment]
I think this would be more appropriate for a separate project. XChange has already grown to a massive size and adding that extra complexity, while beneficial to some people, would vastly increase both the learning curve steepness for newcomers (implementors) and the maintenance/refactor load on the maintainers' part, not to mention all the addition code to implement the new standard across all the implementations. I think the best option for XChange is to stay as "bare metal" as possible for now.

**Comment by baffo32** [comment]
What about simply the second half of the idea, changing the services to be implemented as extending base classes which are passed supported features?  This would enforce streaming services provide data in a standard format, and allow the services to be queried for what features are supported in advance of using the features.

**Comment by baffo32** [comment]
I'm closing this as I understand it is out of the scope of this project.
