### ISSUE TITLE
Full Support for Services Providing Only a Subset of Features

### ISSUE THREAD

**Issue by baffo32** [timmolter/XChange#1101]
This means
- No extra code is required by implementations for features they do not support
- Applications can query exchanges for what features they provide

I am interested in coding a solution to this issue.  I think it will require at least a little refactoring.

This could provide
- The supported featureset to expand without increasing maintenance and implementation work immediately
- Ease of supporting exchanges with poor featuresets
- The creation of generic applications which can query exchanges for feature support in order to intelligently consolidate the data they provide

From #578:

> Now that so many exchanges are supported, we could re-work the polling services so that when it is
> extended, not every method needs be implemented. A generic "method not implemented" exception
> could be thrown.
> 
> For instance, say someone is adding a new exchange implementation to XChange. They're doing the
> market data service implementation. The exchange doesn't have an API method for bulk tickers. The dev
> doesn't have to think about getBulkTickers(). They don't even mention it in their
> NewExchangePollingMarketDataService, and if an end user attempts to call the method, they just see
> that the method is not available for NewExchange

This would also help allow #1096 #1098 .

Ideas for how this might be implemented:
1. Base classes for exchange services (rather than interfaces)
   - takes e.g. EnumSet of supported features in constructor
   - provides default implementations which throw NotAvailableFromExchangeException
   - this new base class would break inheritance tree for exchanges where generic services inherit from raw services.  composition could be used instead, providing a getter.
2. Providing registerServiceFeature() on e.g. Exchange to register features as callbacks or add them to a list
3. other?

**Comment by baffo32** [comment]
An additional thought is that many exchanges provide multiple datastreams, each which provides its own featureset.  A more thorough solution to this would allow the application to enumerate the datastreams, the featuresets each provides, and decide which ones to access.

**Comment by timmolter** [comment]
I'm not convinced, but willing to hear you out more.

> No extra code is required by implementations for features they do not support

Yeah, but there's a lot of extra code needed to define what featureset each impl. provides.

> The creation of generic applications which can query exchanges for feature support in order to intelligently consolidate the data they provide. Applications can query exchanges for what features they provide

That's the main feature you're going for right?

> takes e.g. EnumSet of supported features in constructor

So the client has to pass an EnumSet? Seems weird.

> this new base class would break inheritance tree for exchanges where generic services inherit from raw services. composition could be used instead, providing a getter.

Which services inherit from the raw services? I didn't know there was anything like that.

**Comment by baffo32** [comment]
> > No extra code is required by implementations for features they do not support

> Yeah, but there's a lot of extra code needed to define what featureset each impl. provides.
> So the client has to pass an EnumSet? Seems weird.

The implementation I'm currently playing with adds a protected specifyFeatures() method to BaseExchangeService which derived classes override to specify the features they provide.  It returns a collection of enums.  I've then changed BasePollingExchangeService to override this function and return a set of features which are automatically inferred via reflection from which interfaces are implemented by the class.  So a polling service implementer needs only derive from BasePollingExchangeService and implement interfaces, and the enumset is populated automatically.

For this approach I've split the interfaces up so that there is one for each possible function call.  The class signature for the services changes to implement many interfaces rather than just one.  I feel it's a little messy to infer the features via reflection, but it means that the implementer only has to specify them in one place, hopefully easing service maintenance.

I imagine one might have BaseStreamingExchangeService such that the enums are passed as a variable argument list to the constructor, alongside the Exchange instance.  Polling exchanges could do this as well if reflection were to be avoided.

> > The creation of generic applications which can query exchanges for feature support in order to intelligently consolidate the data they provide. Applications can query exchanges for what features they provide

> That's the main feature you're going for right?

The intent of this issue is to address the comment I quoted in #578 and take advantage of that addressing to introduce whatever extra generality to the system that the maintainers will allow.  I have a personal desire to consolidate streaming depth data which is not readily available from the current api, which requires resolving #1096 .  It seems like if I'll be going through many exchanges anyway changing things, I should come up with some more generic solution so it doesn't have to happen much in the future, so I'm trying to come up with something powerful enough to fit that.

> Which services inherit from the raw services? I didn't know there was anything like that.

There's a pattern in the implementations of the generic services inheriting from the raw services.  For example, BitstampMarketDataService extends BitstampMarketDataServiceRaw .  What I'm currently trying out is keeping that inheritance hierarchy where it exists, allowing the overload/interface reflection technique to specify that the Raw services simply provide no standard features at all.

I'm definitely looking for input on good ideas or changes that will or won't be accepted to the project.

**Comment by timmolter** [comment]
I like the reflection idea and the way of automatically generating that Collection. The need for separate interfaces for each method is the only negative I can see. Perhaps each interface should inherit from a parent interface like "MarketDataService" and appear in its own package to maintain that separation we have now with the 3 different services.

All in all, I think it's a good idea and it seems like you are willing to do the refactor and address the other issies, which is a lot of work.

I'd be interested to get feedback from others on this too!

**Comment by baffo32** [comment]
Here are two ideas to remove some of the clutter for separate interfaces for each method:
- Creating interfaces which consolidate common methods together, for exchanges to implement in fewer keystrokes
- Using annotations on methods, rather than implementing interfaces, to identify that they provide service features.  I suppose validation would then happen at runtime rather than compile time.
Do either of those sound preferable to just a lot of small interfaces?

I'd also like to split some of the current features out into multiple features.  For example, I'd like to split getOrderBook into getDepthFull and getDepthTop depending on whether the exchange provides the entire orderbook or only a few entries from the top for display to the user.  I think they should be separate functions because it's possible for an exchange to provide both, and they have different benefits.  The recent trades are similar -- some exchanges only provide recent trades, some allow to query historical trades, and for example hitbtc has a separate function for each.  There's a similar situation with the streaming services, where some exchanges provide an orderbook delta (changes made to orderbook since last update), some exchanges provide orderbook snapshots (entire orderbook), and many exchanges provide both.

May I rename and split out the features to make such situations more precise?

**Comment by timmolter** [comment]
> Do either of those sound preferable to just a lot of small interfaces?

Not really. Others are welcome to comment.

Isn't there a `getPartialOrderbook` method or was that already removed? I know that was originally there.

> some exchanges only provide recent trades, some allow to query historical trades, and for example hitbtc has a separate function for each. 

Right now there is one method and depending on the args passed, the implementation is responsible for calling the appropriate exchange methods in *Raw. Do you think having separate methods is better? There's need to be more examples than not across all exchanges to justify it in my opinion.

> There's a similar situation with the streaming services, where some exchanges provide an orderbook delta (changes made to orderbook since last update), some exchanges provide orderbook snapshots (entire orderbook), and many exchanges provide both.

Yeah, go for it in this case for sure.

**Comment by baffo32** [comment]
> Isn't there a getPartialOrderbook method or was that already removed? I know that was originally there.

Huh.

10fc7884ee9456420846b2bce7951f669a24835c (Nov 26 2013) condensed getPartial and getFull into just plain getOrderbook with variable arguments.  It added an OrderBookType enum to make up for this change.

d06922c3873a9c996cd464799c1628375ac1414d (Feb 18 2014) removed the OrderBookType enum and changed uses of it to the strings "partial" and "full".  This would have been a great thing to add to the OrderBook class itself to specify what kind of data it contains.

Unfortunately, not specifying how the generic getOrderBook should be used resulted in exchanges implementing it in different ways, leading to the present situation of an application needing to understand the individual exchange's implementations.

I don't think it's important whether there is one function or two (although I would prefer two), but I would like there to be a standard interface to differentiate between them.  Here are some ideas:
- A separate function for each query possibility ("getFull" gets full orderbook, "getPartial" gets partial, "getSize" allows the caller to specify the number of items to return)
- A single function with a formal signature which takes all possible query parameters and throws if an invalid one is passed.  i dislike this because it makes the implementation responsible for validation.
- A single function which takes a variable argument list of e.g. OrderBookQueryParameter objects, and separate parameter possibilities derive from OrderBookQueryParameter.
- A single function which takes a single argument of e.g. OrderBookQueryParameters, could perhaps be created with builder pattern.

I'm leaning towards either many functions or a single OrderBookQueryParameters.

**Comment by baffo32** [comment]
I guess at this point this is justified mostly because there are multiple exchanges which allow querying the depth table in different ways and their method signatures are not consistent.  For example ANX allows either partial and full, and BTCE allows to specify the number of entries.

**Comment by baffo32** [comment]
I've found TradeHistoryParams and its paradigm of using instanceof to identify features.  For now I suppose I'll bring back getPartialOrderBook for orderbooks and generalize TradeHistoryParams for marketdata trade history as well.

**Comment by timmolter** [comment]
How about introducing `OrderBookQueryParameters` and sticking with the one method `getOrderBook`? That would be great and it'd be consistent with `TradeHistoryParams`. Maybe the `OrderBook` object can have an enum field for identifying partial or full?

**Comment by baffo32** [comment]
Sounds great.  And also some `TradesParams` to give market trades the same interface as user trades?

There would be nearly-identical classes shared between these parameters groups.  I guess I'll move the shared interfaces to some `QueryParams` base interface.

**Comment by timmolter** [comment]
Yup, sounds good!
