### ISSUE TITLE
NPE when placing BTCE MarketOrder 

### ISSUE THREAD

**Issue by johndemic** [timmolter/XChange#1102]
I'm getting an NPE when trying to place a MarketOrder with BTCE. I suspect the getBtceExchangeInfo() call in BTCETradeService is returning a Null but not sure.

java.lang.NullPointerException
   at com.xeiam.xchange.btce.v3.BTCEAdapters.createLimitOrder(BTCEAdapters.java:265) 
   at com.xeiam.xchange.btce.v3.service.polling.BTCETradeService.placeMarketOrder(BTCETradeService.java:63)

**Comment by johndemic** [comment]
Not sure if this is an issue or not but I was able to fix by calling "remoteInit()" on the Exchange instance.

**Comment by timmolter** [comment]
Have you by chance tried the latests snapshot jars? I think it would just work right out of the box.

**Comment by johndemic** [comment]
Not yet, but will give them a try.  Thanks Tim!
