### ISSUE TITLE
Huobi USD spot - no USD wallet

### ISSUE THREAD

**Issue by Muffon** [timmolter/XChange#1104]
Hello, how can I get the USD wallet from Huobi? By default I get CNY, BTC and LTC wallets as well as loan wallets.

I set 
 specs.setExchangeSpecificParametersItem("market", "usd");
but getWallet returns the same wallets as before.

Thank you!

**Comment by jheusser** [comment]
Huobi does not have a spot USD market directly. You can access that by setting the exchange specific parameter `use_bitvc` to True, which then enables BitVC.

**Comment by jheusser** [comment]
Consequently, you can't have USD and CNY currency pairs within the same exchange. If you need that you need to instantiate two `Exchange` instances with the relevant exchange specific parameters.

**Comment by Muffon** [comment]
Thanks, I will try it.

**Comment by Muffon** [comment]
I used 

   specs.setExchangeSpecificParametersItem("use_bitvc", true);

and provided bitvc api keys  but I still get CNY, BTC and LTC. Still missing something...

**Comment by jheusser** [comment]
@Muffon Actually just realised that this is not supported/tested. BitVC is just the leveraged Huobi platform for CNY and only recently merged in BitYes which had a USD spot market. So getting USD is untested for now and will most likely not work.

**Comment by Muffon** [comment]
Thanks, I am implementing USD spot in BitVC.

**Comment by jheusser** [comment]
Great, let me know how you get on.

**Comment by jheusser** [comment]
@Muffon Updates? Should we close this issue?
