### ISSUE TITLE
"Fills" for coinbaseEx

### ISSUE THREAD

**Issue by geigerzaehler242** [timmolter/XChange#1108]
the coinbase exchange API has an endpoint to return trade fills. (example response below).

it would be useful to have a function in the wrapper getFills() which would return this. right now it seems all i can do is search the open orders list for the order i just placed and monitor when it disappears to know if i was filled. but that still doesn't provide me with extra detail i need like "fee" etc.

am i missing some existing function that provides this Fill detail?

[
    {
        "trade_id": 74,
        "product_id": "BTC-USD",
        "price": "10.00",
        "size": "0.01",
        "order_id": "d50ec984-77a8-460a-b958-66f114b0de9b",
        "created_at": "2014-11-07T22:19:28.578544Z",
        "liquidity": "T",
        "fee": "0.00025",
        "settled": true,
        "side": "buy"
    }
]

**Comment by baffo32** [comment]
https://github.com/timmolter/XChange/blob/develop/xchange-coinbaseex/src/main/java/com/xeiam/xchange/coinbaseex/service/polling/CoinbaseExTradeService.java#L58

The function exists but nobody has written it yet.

**Comment by jheusser** [comment]
@geigerzaehler242 Is this still relevant to GDAX?

**Comment by jheusser** [comment]
Closing this as exchange changed name, API, etc. Please reopen if this persists for GDAX.
