### ISSUE TITLE
Need help with deserialization

### ISSUE THREAD

**Issue by Muffon** [timmolter/XChange#1112]
Hi, I am writing a withdrawal support for Bitfinex and it works fine instead of deserialization of the response.  

I get:

>ex = (si.mazi.rescu.HttpStatusIOException) si.mazi.rescu.HttpStatusIOException: Can not >deserialize instance of com.xeiam.xchange.bitfinex.v1.dto.account.BitfinexWithdrawalResponse out >of START_ARRAY token
> at [Source: [{"status":"error","message":"Insufficient available balance or invalid amount entered >for the selected wallet.","withdrawal_id":0}]; line: 1, column: 1]

My  new mapping class is generated:

```java
package com.xeiam.xchange.bitfinex.v1.dto.account;

import java.util.HashMap;
import java.util.Map;
import javax.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Bitfinex withdrawal response mapping class
 * @author Ondrej Novotny <ondrej.novotny@onlab.cz>
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("org.jsonschema2pojo")
@JsonPropertyOrder({
    "status",
    "message",
    "withdrawal_id"
})
public class BitfinexWithdrawalResponse {

    @JsonProperty("status")
    private String status;
    @JsonProperty("message")
    private String message;
    @JsonProperty("withdrawal_id")
    private String withdrawalId;
    @JsonIgnore
    private Map<String, Object> additionalProperties = new HashMap<String, Object>();

    /**
     *
     * @return The status
     */
    @JsonProperty("status")
    public String getStatus() {
        return status;
    }

    /**
     *
     * @param status The status
     */
    @JsonProperty("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     *
     * @return The message
     */
    @JsonProperty("message")
    public String getMessage() {
        return message;
    }

    /**
     *
     * @param message The message
     */
    @JsonProperty("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     *
     * @return The withdrawalId
     */
    @JsonProperty("withdrawal_id")
    public String getWithdrawalId() {
        return withdrawalId;
    }

    /**
     *
     * @param withdrawalId The withdrawal_id
     */
    @JsonProperty("withdrawal_id")
    public void setWithdrawalId(String withdrawalId) {
        this.withdrawalId = withdrawalId;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @JsonAnySetter
    public void setAdditionalProperty(String name, Object value) {
        this.additionalProperties.put(name, value);
    }
}
```

**Comment by baffo32** [comment]
Your response is nested inside an array.

You could configure your object mapper with `DeserializationFeature.UNWRAP_SINGLE_VALUE_ARRAYS`.

**Comment by timmolter** [comment]
Thanks @baffo32 , that looks like the issue to me too.

**Comment by Muffon** [comment]
Hello, thanks for advice, I don't know how and when to access the object mapper from BitfinexAccountServiceRaw to set it up. Is there an attribute setter for this flag to use it directly in a mapping class?

**Comment by baffo32** [comment]
Hi,
you can set this by passing a ClientConfig to RestProxyFactory.createProxy in BitfinexBasePollingService.java .  It is like at https://github.com/CurrencyCloud/currencycloud-java/blob/master/src/main/java/com/currencycloud/client/CurrencyCloudClient.java#L60 , except you will set a different feature.

**Comment by Muffon** [comment]
Thanks again, it's good to know. I have solved this issue by requesting BitfinexWithdrawalResponse[] array instead of changing ObjectMapper behavior. I was wondering why all other requests in Bitfinex polling service count with reponse arrays and that's the answer :-)
