### ISSUE TITLE
unable to get base currency and quote currency from currencyPair after today's build

### ISSUE THREAD

**Issue by douggie** [timmolter/XChange#1114]
HI,

seems like might be related to the latest 4.0.0-SNAPSHOT  on https://oss.sonatype.org/content/repositories/snapshots with today's time stamp.

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project cointrader: Compilation failure: Compilation failure:
[ERROR] /Users/douggieclarke/Development/cointrader/src/main/java/org/cryptocoinpartners/schema/SpecificOrder.java:[140,87] cannot find symbol
[ERROR] symbol:   variable baseSymbol
[ERROR] location: class com.xeiam.xchange.currency.CurrencyPair
[ERROR] /Users/douggieclarke/Development/cointrader/src/main/java/org/cryptocoinpartners/schema/SpecificOrder.java:[141,61] cannot find symbol
[ERROR] symbol:   variable counterSymbol
[ERROR] location: class com.xeiam.xchange.currency.CurrencyPair

**Comment by timmolter** [comment]
@baffo32 Any ideas?

**Comment by douggie** [comment]
Hi 

It is odd, the fields are public in the com.xeiam.xchange.currency.CurrencyPair class:

  public final String baseSymbol;
  public final String counterSymbol;

**Comment by douggie** [comment]
here is the call I am making:

limitOrder.getCurrencyPair().counterSymbol.toUpperCase() where limitorder is an instance of com.xeiam.xchange.dto.trade.LimitOrder

**Comment by douggie** [comment]
wonder if the merge did not pick evertyhing up, in source I see 

-  public final String baseSymbol;
-  public final String counterSymbol;
+  public final Currency base;
+  public final Currency counter;

trying to build from source.

**Comment by douggie** [comment]
seems to work for source, might have been a classh in my repo

**Comment by baffo32** [comment]
I intended to delete the baseSymbol and counterSymbol fields and replace them with base and counter in the patch merged thus morning.  Will check

**Comment by baffo32** [comment]
I don't find a 4.0.0-SNAPSHOT on https://oss.sonatype.org/content/repositories/snapshots .  But yeah I changed counterSymbol/baseSymbol to counter/base so code using them will need an update.

**Comment by timmolter** [comment]
It's definitely there: <https://oss.sonatype.org/content/groups/public/com/xeiam/xchange/xchange-core/4.0.0-SNAPSHOT/>

**Comment by gmkarl** [comment]
Thanks, I found it on sonatype.  Looks like the code usually the library just needed to be updated.

I couldn't reproduce the issue using intellij.  I think whatever IDE was being used perhaps had some decompilation cached from the snapshot jar.
