### ISSUE TITLE
Help with merge or pull

### ISSUE THREAD

**Issue by Muffon** [timmolter/XChange#1115]
Hi,I think I did something wrong with my Fork. 

I was confused with this message "This branch is 3 commits ahead, 104 commits behind timmolter:develop."

I wanted to have the most actual sources in my fork, so I just manually updated all sources and then committed them with my changes to develop branch in my fork.

Now it won't auto merge, because git thinks that I changed all sources :). What can I do? And how can I make my fork up to date with timmolter develop branch? I did not found a button to merge main branch with mine.

 Thanks for explanation. I am quite new to GitHub

**Comment by timmolter** [comment]
> I wanted to have the most actual sources in my fork, so I jsut manually updated all sources and then committed them with my changes to develop branch in my fork.

Yeah, don't ever do that. You need to sync a fork of a repository to keep it up-to-date with the upstream repository. See: <https://help.github.com/articles/syncing-a-fork/>

That example is for `master`, so just change everything to `develop`.

**Comment by Muffon** [comment]
Thanks!
