### ISSUE TITLE
One Set of Tests that All Exchanges Must Pass

### ISSUE THREAD

**Issue by baffo32** [timmolter/XChange#1120]
I think it would be nice if there were a small set of testcases that would test features exposed by the standard interface of an arbitrary exchange, and then code to run these tests on every exchange in the repository.

I'm new to maven, surefire, and multi-jar projects, and am not sure yet how to implement this myself.

**Comment by timmolter** [comment]
Can you give a couple examples of what exactly you had in mind for tests?

**Comment by baffo32** [comment]
For example, to be able to run integration tests for every single exchange:
```
ExchangeMetaData exchangeMetaData = exchange.getMetaData();
Map<CurrencyPair,MarketMetaData> marketMetaDataMap = exchangeMetaData.getMarketMetaDataMap();
PollingMarketDataService pollingMarketDataService = exchange.getPollingMarketDataService();

for (CurrencyPair currencyPair : marketMetaDataMap.keys()) {
  if (pollingMarketDataService != null) {
    Ticker ticker = pollingMarketDataService.getTicker(currencyPair);
    System.out.println(ticker.toString());
    assertThat(ticker).isNotNull();
  }
}
```

**Comment by baffo32** [comment]
That is, if that code were in one place and could somehow iterate all the exchanges.  Then a more thorough test suite could be developed and maintained in one place for API changes.

**Comment by timmolter** [comment]
One idea would be to put it in `xchange-examples` since that module has all the other modules defined as dependencies. Then one could look for all the exchanges on the classpath, loop through, calling certain methods to test like you said. I have some code that is sort of similar for creating a Set of classes `assignable` to another class. 

 private void filterJobClassWithExceptionCatch(String className, Set<Class<? extends Job>> classes) {
      try {
  
        Class clazz = loadClass(className);
        if (Modifier.isAbstract(clazz.getModifiers())) {
            return;
        }
        if (Modifier.isInterface(clazz.getModifiers())) {
            return;
        }
        if (Job.class.isAssignableFrom(clazz)) {
          classes.add(clazz);
        }
      } catch (ClassNotFoundException e) {
        throw new RuntimeException("Unexpected ClassNotFoundException loading class '" + className + "'");
      }
    }
