### ISSUE TITLE
Come up with solution to multiple-orderbook situations

### ISSUE THREAD

**Issue by baffo32** [timmolter/XChange#1129]
Some exchanges do not have one single orderbook but rather offer a few different ones for the same currencypairs, differing perhaps on the party which is offering the service or the source of the currency.  Currently these exchanges cannot be accessed in a generic way because there is no unified interface for this situation.  I believe examples include ripple and cryptofacilities.

One solution I imagine could be subclassing or extending the Currency class to add one additional field.  Then the existing interfaces could be used.

**Comment by jheusser** [comment]
That's probably best done outside of XChange.
