### ISSUE TITLE
Improving the Unit test coverage.

### ISSUE THREAD

**Issue by mfarid** [timmolter/XChange#1131]
Hey 

I would like to understand if it will be helpful if I work on improving the Unit Tests coverage for certain modules.

Regards
Farid

**Comment by timmolter** [comment]
Yes, it'd definitely be useful. What did you have in mind?

Did you see this: <https://github.com/timmolter/XChange/wiki/New-Implementation-Best-Practices>, Step 5?

**Comment by mfarid** [comment]
Thanks for your quick response. I will take a detailed look at the same and certainly follow it in my code.

My team is working on contributing to open source projects by improving the unit tests coverage. We are planning to start with following two modules:  
* xchange-bleutrade 
* xchange-btcmarkets 

I look forward to your active support in terms of review and feedback.
