### ISSUE TITLE
Trouble with Kraken exchange advanced orders

### ISSUE THREAD

**Issue by zygon4** [timmolter/XChange#1139]
I'm attempting to generate and execute a "KrakenStandardOrder" that uses an advanced order.

E.g.

KrakenStandardOrder stopProfitLimit = KrakenStandardOrder.getStopLossProfitLimitOrderBuilder(CurrencyPair.BTC_EUR, KrakenType.SELL, "#1", "#1", BigDecimal.valueOf(.01)).buildOrder();

And I'm getting:

Exception in thread "main" com.xeiam.xchange.exceptions.ExchangeException: [EGeneral:Invalid arguments:ordertype]

Any ideas? Using the same KrakenStandardOrder I can issue vanilla market and limit orders.

My hypothesis is: the KrakenOrderType enum defines the order types as underscored values. "STOP_LOSS_PROFIT", "TRAILING_STOP", "MARKET", etc. The KrakenOrderType toString() lowercases the values before they go to the wire, however it does not turn the underscores back into hyphens.  You can see the fromString perform the one-way translation. "MARKET" and "LIMIT" orders probably work because there is no hyphens.

**Comment by timmolter** [comment]
Did you ever figure this out exactly? I could update the code if you've fixed it.

**Comment by zygon4** [comment]
I never went beyond this initial triage but I strongly suspect this was the issue.  We need to add a parallel underbar-to-hypthen translation in KrakenOrderType to be congruent.
