### ISSUE TITLE
XChange-bitmarket module converts order types in wrong way

### ISSUE THREAD

**Issue by airleks** [timmolter/XChange#1140]
com.xeiam.xchange.bitmarket.BitMarketUtils class converts order types in the following way
Order.OrderType.ASK <-> buy
Order.OrderType.BID <-> sell

The same convertation presents in com.xeiam.xchange.bitmarket.service.polling.BitMarketTradeServiceRaw:51

Should be 

Order.OrderType.ASK <-> sell
Order.OrderType.BID <-> buy

(like in other modules like xchange-bleutrade)

**Comment by timmolter** [comment]
good catch. Fixed.

**Comment by gryffus** [comment]
I think that conversion from BitmarketOrder to Order is still wrong.
If i request an order with: `accountService.getOpenOrders().getOpenOrders().get(0);`
My (Ask) order gets returned as:
LimitOrder [limitPrice=367.3905, Order [type=BID, tradableAmount=0.01000000, averagePrice=0, currencyPair=BTC/EUR, id=42637602, timestamp=Wed Apr 06 22:46:23 CEST 2016, status=PENDING_NEW]]

**Comment by gryffus** [comment]
Also placing BID Limit order (Bitmarket supports only Limit orders, no Market orders) places ASK limit on the auction. IMHO this patch should be reverted
