### ISSUE TITLE
XChange-bitmarket: Incorrect Exchange trades processing

### ISSUE THREAD

**Issue by airleks** [timmolter/XChange#1141]
BitMarketAdapters.adaptTrades (line 108) use OrderType.BID as default trade type which is not correct since BitMarket API /{currencypair}/trades.json returns items with "type" field (with 'bid'/'ask' values). 

This field is ignored during json unmarshalling (see json example at https://www.bitmarket.pl/json/BTCPLN/trades.json, https://www.bitmarket.pl/json/LTCPLN/trades.json)

The "type" field should be included in BitMarketTrade dto.

**Comment by timmolter** [comment]
fixed
