### ISSUE TITLE
XChange-bleutrade: Adapted balances throw NPE on equals() call

### ISSUE THREAD

**Issue by airleks** [timmolter/XChange#1145]
BleutradeAdapters.adaptBleutradeMarketHistory creates Trades with null id Trade items. Hence we can't compare them. The following code wil throw NullPointerException at last line:

public void compareTrades() throws IOException {

```
final BleutradeMarketHistoryReturn response = ...;   // getting parsed market history response

Trades trades1 = BleutradeAdapters.adaptBleutradeMarketHistory(response.getResult(), CurrencyPair.BTC_AUD);
Trades trades2 = BleutradeAdapters.adaptBleutradeMarketHistory(response.getResult(), CurrencyPair.BTC_AUD);

trades1.getTrades().get(0).equals(trades2.getTrades().get(0));    // throws NullPointerException
```

  }

**Comment by timmolter** [comment]
I guess it should either be hardcoded to some ID such as 0, or if IDs are actually coming back from the exchange, that should be implemented. Did you ever implement a fix?
