### ISSUE TITLE
XChange-bitmarket module BitMarketTrades to Trades timestamp convertion issue

### ISSUE THREAD

**Issue by airleks** [timmolter/XChange#1149]
Bitmarket API provides trades with timestamps in Unix format (doc reference https://www.bitmarket.net/docs.php?file=api_public.html, response example - https://www.bitmarket.pl/json/BTCPLN/trades.json). That means that timestamps have "second" precision (not "millisecond"). 

BitMarketAdapters.adaptTrades don't multiply Unix timestamp values on 1000 when creating timestamps in java Date object format. So, all Trade timestamps have incorrect values.

**Comment by timmolter** [comment]
Thanks for reporting the issue.

**Comment by airleks** [comment]
@timmolter This issue has been fixed in accepted pull request (https://github.com/timmolter/XChange/pull/1154). Please check it.
