### ISSUE TITLE
Okcoin: cannot place market order on futures contracts.

### ISSUE THREAD

**Issue by vladmelnyk** [timmolter/XChange#1152]
// I am trying to place order on the future market with the  following parameteres enabled : 

exSpec.setExchangeSpecificParametersItem("Use_Futures", true);
 exSpec.setExchangeSpecificParametersItem("Futures_Contract", FuturesContract.ThisWeek);

// but after the following code

        MarketOrder marketOrder = new MarketOrder(Order.OrderType.ASK,new BigDecimal(0.01), CurrencyPair.BTC_USD);
        PollingTradeService pollingTradeService =  okcoinExchange.getPollingTradeService();

        try {
            pollingTradeService.placeMarketOrder(marketOrder);
        }
        catch(ExchangeException e) {
            System.out.println("EXCEPTION");
            e.printStackTrace();
            System.out.println( e.getMessage() );
        }

// I get the following output

EXCEPTION
Illegal parameter
com.xeiam.xchange.exceptions.ExchangeException: Illegal parameter
	at com.xeiam.xchange.okcoin.service.polling.OKCoinBaseTradePollingService.returnOrThrow(OKCoinBaseTradePollingService.java:40)
	at com.xeiam.xchange.okcoin.service.polling.OkCoinTradeServiceRaw.futuresTrade(OkCoinTradeServiceRaw.java:55)
	at com.xeiam.xchange.okcoin.service.polling.OkCoinFuturesTradeService.placeMarketOrder(OkCoinFuturesTradeService.java:76)
	at com.vladik.Main.main(Main.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

Process finished with exit code 0

**Comment by jheusser** [comment]
@vladmelnyk Are you sure you are instantiating the `Exchange` instance correctly? E.g.

```
    ExchangeSpecification exSpec = new ExchangeSpecification(exchangeConfig.exchangeClass());
    exSpec.setExchangeSpecificParameters(exchangeConfig.exchangeSpecificParameters());

    exSpec.setSecretKey(exchangeConfig.secretKey());
    exSpec.setApiKey(exchangeConfig.apiKey());

    if(!Strings.isNullOrEmpty(exchangeConfig.userName())) {
      exSpec.setUserName(exchangeConfig.userName());
    }

    if(!Strings.isNullOrEmpty(exchangeConfig.password())) {
      exSpec.setPassword(exchangeConfig.password());
    }

    Exchange exchange = ExchangeFactory.INSTANCE.createExchange(exSpec);
```

**Comment by vladmelnyk** [comment]
well, it seems that exchange instance authorizes through API key correctly. However, I noticed that I can place market orders with the amount multiple by 0.24 btc( which is apparently the underlying feature of Okcoin exchange itself). 
I have another question.
Is there a way to get my Market order in order to liquidate position through API since we only have the following method: pollingTradeService.liquidateMarketOrder(marketOrder);  
and we have to send already initialized market order?
how do we get market order from the API not locally?

**Comment by jheusser** [comment]
you can't place a normal market order to liquidate an open futures position. You will have to liquidate it.

**Comment by vladmelnyk** [comment]
Ok, having this method: pollingTradeService.liquidateMarketOrder(MarketOrder mo); how do we liquidate futures position? 
Or if there is other way to do it?

**Comment by douggie** [comment]
HI,

You can now do this with setting the order type to EXIT_BID (exit long position) or EXIT_ASK (exit short position), if you don't specify a limit price it will place a market liquidating order, if you specify a limit price it will place a limit liquidating order.

https://github.com/timmolter/XChange/issues/1188

**Comment by jheusser** [comment]
This looks resolved.

**Comment by douggie** [comment]
I fixed this a while back

**Comment by jheusser** [comment]
@douggie cool, even better :)
