### ISSUE TITLE
Huobi: getTradeHistory

### ISSUE THREAD

**Issue by andre77** [timmolter/XChange#1161]
currently the service throws a NotAvailableFromExchangeException
https://github.com/timmolter/XChange/blob/develop/xchange-huobi/src/main/java/com/xeiam/xchange/huobi/service/polling/GenericTradeService.java#L107

is the information really not provided by huobi api?

**Comment by kmels** [comment]
The official docs are here: https://github.com/huobiapi/API_Docs_en/wiki

The closest is "Get Latest 10 Deal Orders", which isn't very parameterized as you can see (i.e. no pagination)
