### ISSUE TITLE
CryptoFacilities: getOrderBook returns null for all tradeable forward contracts

### ISSUE THREAD

**Issue by Panchen** [timmolter/XChange#1162]
When I run the test code in FetchIntegration.Publictest() from 4.0.0-SNAPSHOT the returned public order books are null for all tradeable contracts:

CryptoFacilitiesContracts [contracts=CryptoFacilitiesContract [tradeable=F-XBT:USD-Jan16-W5, unit=USD, lastTradingDayAndTime=2016-01-29 04:00:00, contractSize=1, tickSize=0.01, suspended=false ], CryptoFacilitiesContract [tradeable=F-XBT:USD-Sep16, .....

Ticker [currencyPair=F-XBT:USD-JAN16-W5/USD, last=null, bid=null, ask=null, high=null, low=null,avg=null, volume=null, timestamp=null]

CryptoFacilitiesContract [tradeable=F-XBT:USD-Jan16-W5, unit=USD, lastTradingDayAndTime=2016-01-29 04:00:00, contractSize=1, tickSize=0.01, suspended=false ]
OrderBook [timestamp: null, asks=[], bids=[]]

CryptoFacilitiesContract [tradeable=F-XBT:USD-Sep16, unit=USD, lastTradingDayAndTime=2016-09-16 04:00:00, contractSize=1, tickSize=0.01, suspended=false ]
OrderBook [timestamp: null, asks=[], bids=[]]

CryptoFacilitiesContract [tradeable=F-XBT:USD-Jan16-W4, unit=USD, lastTradingDayAndTime=2016-01-22 04:00:00, contractSize=1, tickSize=0.01, suspended=false ]
OrderBook [timestamp: null, asks=[], bids=[]]

CryptoFacilitiesContract [tradeable=F-XBT:USD-Mar16, unit=USD, lastTradingDayAndTime=2016-03-18 04:00:00, contractSize=1, tickSize=0.01, suspended=false ]
OrderBook [timestamp: null, asks=[], bids=[]]

CryptoFacilitiesContract [tradeable=F-XBT:USD-Jan16-W2, unit=USD, lastTradingDayAndTime=2016-01-08 04:00:00, contractSize=1, tickSize=0.01, suspended=false ]
OrderBook [timestamp: null, asks=[], bids=[]]

CryptoFacilitiesContract [tradeable=F-XBT:USD-Jun16, unit=USD, lastTradingDayAndTime=2016-06-17 04:00:00, contractSize=1, tickSize=0.01, suspended=false ]
OrderBook [timestamp: null, asks=[], bids=[]]

CryptoFacilitiesContract [tradeable=F-XBT:USD-Jan16-W3, unit=USD, lastTradingDayAndTime=2016-01-15 04:00:00, contractSize=1, tickSize=0.01, suspended=false ]
OrderBook [timestamp: null, asks=[], bids=[]]

CryptoFacilitiesIndex [cfbpi=430.50]
CryptoFacilitiesVolatility [volatility=17.79]

No exceptions (ExchangeNotImplemented, etc ) are thrown and I get other public api values back.

**Comment by timmolter** [comment]
I'm afraid you're probably going to have to debug that yourself. If you find and fix the problem, which shouldn't be too hard, I'll happily accept a  PR for the fix. The following Wiki page may be helpful to you: https://github.com/timmolter/XChange/wiki/New-Implementation-Best-Practices

**Comment by Panchen** [comment]
No problem. I have tracked it down to an issue with capitalization of the contract month text sent to the api. 
16:55:14.247 Http call returned 200; response body:
{ "result" : "success", "contracts" : [ { "unit" : "USD", "tradeable" : "F-XBT:USD-Jan16-W5",  "contractSize" : 1,  ...
CryptoFacilitiesContracts [contracts=CryptoFacilitiesContract [tradeable=F-XBT:USD-Jan16-W5, unit=USD, lastTradingDayAndTime=2016-01-29 ...
16:55:14.297 Executing GET request at https://www.cryptofacilities.com/derivatives/api/cumulativebidask?tradeable=F-XBT%3AUSD-JAN16-W5&unit=USD
versus:
https://www.cryptofacilities.com/derivatives/api/cumulativebidask?tradeable=F-XBT%3AUSD-Jan16-W5&unit=USD
PR for code fix to follow.

**Comment by Panchen** [comment]
This is not that straight forward to fix in code. For interface consistency, we are putting a forward contract code through the CurrencyPair class as a base currency. The CurrencyPair(String, String) and CurrencyPair(String) constructors sensibly enforce toUpperCase on base and counter currencies. 

However, there is a work around. The CurrencyPair(Currency, Currency) constructor doesn't enforce uppercase so the forward contract gets passed through  to the  exchange with the correct, mixed capitalization.

I will update the test cases  to illustrate this work around usage.
I have also requested CryptoFacilites change their api to be case insensitive on contract code (tradeable).

**Comment by Panchen** [comment]
@timmolter I have forked from develop to my branch crypto-facilities-contract-uppercase and submitted a Pull Request linking to this issue. I'm getting "Sync failed to publish local changes. It seems you do not have permission to push your changes to this repository."
Do I need to be permissioned to submit a PR?

**Comment by Panchen** [comment]
Closed with https://github.com/timmolter/XChange/pull/1164
