### ISSUE TITLE
Bitfinex Websocket Market Data

### ISSUE THREAD

**Issue by jheusser** [timmolter/XChange#1165]
Is anyone working or intending to work on the new Bitfinex streaming market data?

http://docs.bitfinex.com/#websocket

**Comment by brobits** [comment]
duplicate issue here: https://github.com/timmolter/XChange/issues/630

was closed by @timmolter almost a year ago.  either the feed didn't exist at the time, or its docs had evaded tim

**Comment by jheusser** [comment]
@brobits it didn't exist at the time, it's quite new, or at least it's an updated version.

**Comment by Kelvin-Chen** [comment]
Bitfinex did have a streaming API for a while, but it used to be an internal API meant for the website and not developers. They recently released an official websocket API and the documentation can be found [here](http://docs.bitfinex.com/#websocket).

**Comment by blbradley** [comment]
I'm willing to work on this. Any initial work already?

**Comment by jheusser** [comment]
@blbradley No work done as far as I understand. Happy to help with questions if there were any (and I can answer). Spec is here http://docs.bitfinex.com/#websocket and example Go implementation of spec here https://github.com/bitfinexcom/bitfinex-api-go

**Comment by blotter123** [comment]
I am personally working on an implementation after having used most of the other available StreamingExchangeServices. However, a brief Python test showed me that updates to the order book come incremental, i.e. only one full order order book on CONNECT and single quote updates thereafter - has this been dealt with before ? It would require holding and updating a state of the order book.

**Comment by blotter123** [comment]
As state in the API documentation: "The Order Books channel allow you to keep track of the state of the Bitfinex order book. It is provided on a price aggregated basis, with customizable precision. After receiving the response, you will receive **a snapshot** of the book, followed by **updates upon any changes** to the book."

**Comment by jheusser** [comment]
@blotter123 that's correct, you will have to reconstruct the book, applying incremental updates. I believe Coinbase websockets is doing the same, but most Bitcoin exchanges only provide snapshots.

**Comment by btiernay** [comment]
@jheusser does XChange support this approach for Coinbase? I've seen others [do this](https://github.com/nof20/ThreadMarketData/blob/001f0b21c42bd6be6186eb58f33d271dbbe65f2b/src/main/RealtimeOrderBookBuilder.java).

**Comment by evdubs** [comment]
I have this working, but there doesn't seem to be a consistent protocol for WebSocket data handling across XChange. Has this gotten better? I can either try to shoehorn something in it at least make the code available if someone else wants to port it.

**Comment by timmolter** [comment]
Unfortunately not. Streaming in XChange is quite sloppy and inconsistent. While that's not a good state to be in, I think having stuff that (at least) works is slightly better. Either that or completely removing all streaming code was also something I was considering.
