### ISSUE TITLE
Add OkCoin WebSocket Spot Trade API

### ISSUE THREAD

**Issue by zer0hedge** [timmolter/XChange#1168]
Add at least the following:
-  ok_spotusd_trade - Place Orders
-  ok_spotusd_cancel_order - Cancel Orders
-  ok_spotusd_order_info - Get Order Info

Actually I'd be happy to develop it myself and would like to know your thoughts about the way to do this

**Comment by timmolter** [comment]
Hello @zer0hedge Best to start by looking at the other streaming examples. A handful of modules have this. Unfortunately the websocket code in XChange is not too clean. :(

**Comment by jheusser** [comment]
Agree, streaming is too unreliable at the moment and unmaintained. Close?
