### ISSUE TITLE
Kraken: EAPI:Invalid nonce

### ISSUE THREAD

**Issue by andre77** [timmolter/XChange#1169]
Hi,
from time to time i get this exception using kraken excahnge
com.xeiam.xchange.exceptions.NonceException: EAPI:Invalid nonce

looking into the code here https://github.com/timmolter/XChange/blob/develop/xchange-kraken/src/main/java/com/xeiam/xchange/kraken/KrakenExchange.java#L18
CurrentTimeNonceFactory is used, which returns simply System.currentTimeMillis()
imho it could cause problems, since we can get into a situation, where we send two request to kraken directly one after another. this can lead to the same nonce value sent to kraken

would ie AtomicLongCurrentTimeIncrementalNonceFactory not be a better alternative ?

**Comment by abelgo** [comment]
Yes, I also get these problem having an atomic millisecond counter would seem like a sensible solution. 
One work around I have been using is to set up a more than one api key pair at t per thread level to avoid conflicts.

**Comment by timmolter** [comment]
You can add your preferred NonceFactory when instantiating your Exchange setup. The default one could also be swapped out via a pull request if you feel like submitting one. @abelgo 's solution makes sense too.
