### ISSUE TITLE
Adding getOrderStatus(orderid) method to PollingTradeService to support okcoin transactions

### ISSUE THREAD

**Issue by douggie** [timmolter/XChange#1172]
Hi,

Just working on the okcoin futures implementation to get transactions ( https://www.okcoin.com/api/v1/future_trades_history.do) , unfortunately the get historical transaction API does not return the orderid the fill was associated with.

https://www.okcoin.com/about/rest_api.do

Okcoin, along with a number of other exchanges, do provide an api call to get the status of the order (https://www.okcoin.com/api/v1/future_order_info.do,https://www.bitstamp.net/api/order_status/)  from which one could work out the fills but keep the date from the last request, to this request, the delta in the price and the quantity would be the fill. This would also required adding avergerfillprice to the limit (com.xeiam.xchange.dto.trade.LimitOrder) and market orders (com.xeiam.xchange.dto.trade.MarketOrder)

What are the thoughts on adding getOrderStatus(orderid) to the PollingTraderService intreface, the interface does have verifyOrder, but this seems to be more for checking if an order is well formed rather than the status of an order at the exchange.

**Comment by douggie** [comment]
another option could be to return the order status from the getTransactionHistory, as the order history seems more useful that a list of uncorrelated transactions. I guess we could get the list of all transactions and based on the time, price the client application could work out based on the orders it has which fill could go with which order, but this does not seem very robust.

**Comment by timmolter** [comment]
@douggie how many exchanges approx. have you seen this API call?

**Comment by douggie** [comment]
Hi Tim,

I have not checked all the exchanges, but it is widely supported.

ANX	/order/info
Bitcurex	no
bitfinex	/order/status
BitKonan	no
bitstamp	https://www.bitstamp.net/api/order_status/
bitc-e	OrderInfo
cointbase	GET /orders/<order-id>
kracken	https://api.kraken.com/0/private/QueryOrders
okcoin	 https://www.okcoin.com/api/v1/order_info.do

**Comment by douggie** [comment]
Sorry above, is just a quick sample of exchanges I picked, as you can see most support it.

**Comment by douggie** [comment]
Hi Tim,

Was thinking of adding the average price and the following states to com.xeiam.xchange.dto.order;

There are a few builder functions I have updated too, but might need a review to ensure i have extended and not broken existing builder functions

  /**
   * @return The type (PENDING_NEW, NEW, PARTIALLY_FILLED, FILLED, PENDING_CANCEL, CANCELED, PENDING_REPLACE, REPLACED, STOPPED, REJECTED or EXPIRED)
   */
  public OrderStatus getStatus() {

    return status;
  }

**Comment by timmolter** [comment]
Yeah, I can see justifying adding that method (`getOrderStatus(orderid) `) to the main API.

**Comment by douggie** [comment]
Hi Tim,

Great! will pop a pulll request in, I was thinking of making it getOrderStatus(orderid) where orderId is an array of strings, as some exchanges allow you to pass in a list of order id's too, so it is just one request, if there is only one order id, just one element in the array.

I got stuck on an encoding issue, https://github.com/timmolter/XChange/issues/1173, i am sure we have fixed this for kraken but could not figure out how.

You ok with the below appraoch?

I will add the following to the com.xeiam.xchange.dto, update getters, setters,and builder functions in limit and market order and add appropriate new constructors.

* status - order status, this will be PENDING_NEW by default i.eon orders instituted with existing methods.
* averagePrice - The weighted average price of the fills belonging to the order , this will be 0 by default i.e on orders instituted with existing methods.
* cumulativeAmount - The total filled quantity that has been matched against resting order on the exchange, so that the tradableAmount - cumulativeAmount is the amount working/open on exchange. This will be 0 by default i.e. on orders instituted with existing methods.

Update the com.xeiam.xchange.service.polling.trade.PollingTradeService interface to have the following method:

 public OpenOrders getOrder(String[] orderIds) throws ExchangeException, NotAvailableFromExchangeException, NotYetImplementedForExchangeException, IOException;


Add an implementation of getOrder to okcion, for other exchanges just update them to throw NotYetImplementedForExchangeException

**Comment by douggie** [comment]
just if you have 100 orders, and you want the status of them all, if one request is avaiable it seems better so you don't fire off 100 requests and start getting cloudfare 503 errors as too many requests in a given time period.

**Comment by abelgo** [comment]
There are a couple of other order states used on some exchanges that might be useful to add now.
Such as ARCHIVED or CANCEL_REJECTED, its always a bit of an unknown if you should return a success state or not for an cancel request on an order not found on the exchange.  
some exchanges have also use a secondary order state as well or return and ERROR state with error code.  I suppose NEW would be the same as ACTIVE and TERMINATED or COMPLETED the same as STOPPED, however there are cases when the orders states is different depending on if it was an exchange side termination or a client side initiated cancel

**Comment by douggie** [comment]
HI Abelgo,

I was thinking is just taking the standard fix order states, from tag 39. I would have thought it was exchange side, we would set it to stopped, as the exchange as forced you out. 

http://www.fixtradingcommunity.org/FIXimate/FIXimate3.0/latestEP/en/FIX.5.0SP2_EP196/tag39.html

**Comment by abelgo** [comment]
The old Tag 39, yeah seems like a good place to start to a least use a convention

**Comment by timmolter** [comment]
@douggie sounds good.

Feel free to add the other order states as well.
