### ISSUE TITLE
CEX returns null accountInfo

### ISSUE THREAD

**Issue by dimecoin** [timmolter/XChange#1175]
This works for every exchange I've tried, expect for cex.io (CexIOExchange.class).  Returns null:

```
// Get the account information
AccountInfo accountInfo = accountService.getAccountInfo();
System.out.println("AccountInfo as String: " + accountInfo.toString());
```

Output: 

```
10:26:50.013 [default] [main] DEBUG com.xeiam.xchange.ExchangeFactory - Creating exchange from specification 
10:26:50.095 [default] [main] DEBUG c.xeiam.xchange.cexio.CexIOExchange - ExchangeMetaData{currencyPairs={BTC/USD=MarketMetaData{tradingFee=null, minimumAmount=0.010000000, priceScale=4}, GHS/USD=MarketMetaData{tradingFee=null, minimumAmount=1.000000000, priceScale=8}, LTC/USD=MarketMetaData{tradingFee=null, minimumAmount=1.200000000, priceScale=3}, GHS/BTC=MarketMetaData{tradingFee=null, minimumAmount=1.000000000, priceScale=8}, LTC/BTC=MarketMetaData{tradingFee=null, minimumAmount=1.200000000, priceScale=8}, BTC/EUR=MarketMetaData{tradingFee=null, minimumAmount=0.010000000, priceScale=4}, LTC/EUR=MarketMetaData{tradingFee=null, minimumAmount=1.200000000, priceScale=3}, BTC/RUB=MarketMetaData{tradingFee=null, minimumAmount=0.010000000, priceScale=2}}, currency={}} 
AccountInfo as String: null
```

Version is : 4.0.0-SNAPSHOT

edit: 

I tested quite a bit of functions on this feed and couldn't get trades, orders, send orders, cancel orders, etc working.  Prices do work.

Looking at the source it looks like a lot of features aren't implemented yet.

**Comment by dimecoin** [comment]
Close as known issue?

**Comment by timmolter** [comment]
@dimecoin, it looks like the features just aren't implemented yet. You can leave this issue open if you like. I added the "Feature Request" tag. If you really need the functionality, I'm afraid you'll have to implement it yourself.

**Comment by Achterhoeker** [comment]
i'm using the getAccountInfo without any problem on CexIO. Also placing orders, requesting open orders and cancel open orders are working without any problems. I'm on the develop branch. I didn't check the 4.0.0-SNAPSHOT label.

**Comment by dimecoin** [comment]
Hi Achterhoeker, can I ask how you are building from dev branch?  I've spent a lot of time on this, but getting same results.  Here is how I'm getting .jars from XChange:

    git clone -b develop https://github.com/timmolter/XChange.git
    cd XChange
    git pull
    mvn clean install


I've also tried just a 'git clone  https://github.com/timmolter/XChange.git' with same results.

**Comment by Achterhoeker** [comment]
Hi @dimecoin ,
You are using the same version as i do, the latest develop (head) version. Sorry that it cost you extra time, i was mislead by the 4.0.0-snapshot label. I made the assumption that was a fixed label in the past. (i can not find that tag/label in git?)
It seems that all authenticated calls are not working for you, are you sure that your api keys are correct and the xchange is created without any errors ?
I also found out in the past that the creation of xchanges can be different per exchange. This is how i create a working cexio xchange:

public Exchange createCexIOExchange() {
    ExchangeSpecification exSpec = new ExchangeSpecification(CexIOExchange.class);
    exSpec.setUserName("MyName");
    exSpec.setSecretKey("Mysecretkey");
    exSpec.setApiKey("MyApiKey");
    exSpec.setSslUri("https://cex.io");
    Exchange exchange = ExchangeFactory.INSTANCE.createExchange(exSpec);
    try {
		exchange.remoteInit();
	} catch (ExchangeException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	} catch (IOException e) {
		// TODO Auto-generated catch block
		e.printStackTrace();
	}
    return exchange;
}

**Comment by dimecoin** [comment]
Hi @Achterhoeker , Thanks for the time to write this up.  

One thing I was doing wrong, was that I didn't have `exSpec.setUserName()` set for cexio (most exchange don't have this).

I am able to successfully connect now, but still have two outstanding issues :

**getTradeHistory()**
(PollingTradeService) `tradeService.getTradeHistory(new TradeHistoryParamsZero());` throws a `NotAvailableFromExchangeException` Exception.  That can be seen in [CexIOTradeService.java](https://github.com/timmolter/XChange/blob/develop/xchange-cexio/src/main/java/com/xeiam/xchange/cexio/service/polling/CexIOTradeService.java)  Line 65 to 69.

Is this another case of user error?  Most other exchange use this for trade history.

**getAccountInfo()...getTotal()**
The second issues is that (PollingAccountService)  `accountService.getAccountInfo()` returns wallets with 'null' balances (instead of BigDecimal.ZERO).  This in it's self could be worked around on user's side, but `accountInfo.getWallet().getBalances().getCurrency(currency).getTotal()` will throw a NullPointerException if internal values are null (and no way to work around this).


Example: 

    accountInfo.getWallet().getBalances().getCurrency(Currency.LTC)

return this data:

> Balance [currency=LTC, **total=null**, available=0E-8, **frozen=null**, borrowed=0, loaned=0,  withdrawing=0, depositing=0]

If you call this (`getTotal()`)

    accountInfo.getWallet().getBalances().getCurrency(Currency.LTC).getTotal()

It throws this error:

    Exception in thread "main" java.lang.NullPointerException
	at java.math.BigDecimal.add(BigDecimal.java:1288)
	at com.xeiam.xchange.dto.account.Balance.getTotal(Balance.java:131)
	at com.packagename.tradesystem.feed.TestAccountInfo.main(TestAccountInfo.java:35)

[Balances.java](https://github.com/timmolter/XChange/blob/develop/xchange-core/src/main/java/com/xeiam/xchange/dto/account/Balance.java) Line 128 and 135.

If 'total' is null, then it will try to calculate it.  But in this case if you look at data above, the 'fozen' balance is also null which is what is causing `getTotal()` to throw NullPointerException.

    public BigDecimal getTotal() {
        if (total == null) {
          return available.add(frozen).subtract(borrowed).add(loaned).add(withdrawing).add(depositing);
        } else {
          return total;
        }
    }

I'll defer to you, but it seems that using BigDecimal.ZERO might be a better choice than nulls?

**Comment by Achterhoeker** [comment]
@dimecoin Good to hear that you are getting now a better working cexio xchange. The issues left for you are no blocking issues for me. 
My trading bot isn't using order history, but looking into it, is seems indeed that that functionality isn't implemented yet. 
And the balance issue, i've checked it and do also see null pointers for the total balance. But my trading bot ignores the total and is only interested in the available balance. (but the frozen amount is always available in my logs, only total is reported as null)
I agree this seems to be a bug. If you have the time to fix it, i can check it with my trading bot and see in the logs the null pointers are gone in the account info.

**Comment by dimecoin** [comment]
Thanks for confirming.  On a side note,  what kind of trading strategy do you use that doesn't rely on order/trade history?

**Comment by Achterhoeker** [comment]
My trading bot is doing arbitrage between 10 different exchanges in different coins. (Eur, usd, btc, and 23 other coins) 
Calls used are order book info, getting available balance, open order information ,placing new orders, cancel open order and exchange information like trading pairs and minimal amounts. I'm logging the real netto profits (or losses). No need to query the trading history per exchange.

**Comment by dimecoin** [comment]
I do a little price arbitrage too, but like to see trades to confirm orders went though and as a second check against of positions.  How do you confirm order traded or got filled?  Is there a way to query order status for most exchanges?  My orders will return send errors, but that's about it.

**Comment by Achterhoeker** [comment]
My trading bot is continuous monitoring for open orders. (there shouldn't be any open order in theory, but sometimes the book has changed before the order is executed)  If it finds open orders it is following them to see if they get filled slowly. And if a current book on another xchange is better it moves them to that other xchange. If some time has passed the price is slowly changed.
