### ISSUE TITLE
Bleutrade - getTradeHistory not supported in the Exchange API

### ISSUE THREAD

**Issue by dimecoin** [timmolter/XChange#1177]
This is very odd, I haven't seen another exchange do this, but apparently BleuTrade doesn't support a "trade history" type of function : https://bleutrade.com/help/API

In Xchange: 

```
@Override
public UserTrades getTradeHistory(TradeHistoryParams params) throws IOException {

    throw new NotAvailableFromExchangeException();
}
```

Their 'getorders' api call, does have a 'QuantityBaseTraded' field for each order.  Would it be possible to have Xchange wrap the getTradeHistory so it creates "trades" based on orders that are reported being filled ?  It could get tricky though (with partial fills).

I'm going to ask the exchange if they would consider supporting a 'gettrades' api call.

**Comment by timmolter** [comment]
Yeah, easiest would be for them to add an API endpoint for that. Otherwise, yes, XChange could be modified to handle that like you said.
