### ISSUE TITLE
Bitstamp streaming trades channel has double converted price and volume

### ISSUE THREAD

**Issue by blbradley** [timmolter/XChange#1178]
Some prices and volumes look like this:

    {"event":"trade","data":"{\"price\": 386.42000000000002, \"amount\": 0.13773725000000001, \"id\": 10548846}","channel":"live_trades"}

This doesn't seem to happen on the other channel. Looks like it is in the raw bytes coming from the websocket. But Bitstamp's javascript example doesn't do this.

**Comment by timmolter** [comment]
Weird. Any update on this?

**Comment by blbradley** [comment]
I've quit using XChange in my project. So, I have nothing else to report. Sorry!

**Comment by timmolter** [comment]
OK, thanks!
