### ISSUE TITLE
BTER returns bad ID on sendLimitOrder

### ISSUE THREAD

**Issue by dimecoin** [timmolter/XChange#1180]
Most exchange return a valid order id when sending a limit order, but not BTER, it returns an id, but not a valid one.  It can't be used to cancel orders.  When you use getOpenOrders() it returns different ids (which are valid for canceling orders).  

This seems to be an issue on their side.  There are a lot of forum threads about this going back to 2013, so doubt they will fix it on their side.    

Is there anything that can be done on feed side to help match up?  I've tried setting 'id' (in LimitOrder constructor) when sending orders, but don't know how to get it back.  Is there sometime of free form text field that could be set to help with matching?

---

```
String orderID = tradeService.placeLimitOrder(order);
```

1454808972188 [INFO]: Exchange Feed**: bter sendOrder: 9420284**
**Order Id: 9420284**

..

```
OpenOrders orders = tradeService.getOpenOrders();
```

Order: LimitOrder [limitPrice=0.00910000, Order [type=ASK, tradableAmount=1, currencyPair=LTC/BTC,**id=174106304**, timestamp=n

**Comment by timmolter** [comment]
I looked at the BTER code, and you cannot pass an ID like you tried. No, there is no mechanism for matching. It sounds like their API is messed up, which is a bummer. The best you can do probably is to contact them directly.
