### ISSUE TITLE
General newbie questions

### ISSUE THREAD

**Issue by dimecoin** [timmolter/XChange#1181]
Sorry in advance if these are dumb questions, but I couldn't find documentation on them.  Is there a forum or message board for XChange?

1) Is it possible to force XChange connections though an http proxy?  I tried this, but isn't working:

    System.setProperty("http.proxyHost", Global.PROXY_SERVER_HOST);
    System.setProperty("http.proxyPort", Global.PROXY_SERVER_PORT);

2) How do you build latest XChange from github source?  I'm doing this, but think it's just pulling down snap shots instead of building directly from source?

    git pull
    mvn clean install

**Comment by timmolter** [comment]
1) I'm not sure.
2) You're doing it right.

**Comment by timmolter** [comment]
There is no forum, so you are free to ask all your questions here.

**Comment by dimecoin** [comment]
What HTTP libraries are you using for most connections?

**Comment by timmolter** [comment]
We're using ResCu. <https://github.com/mmazi/rescu>

**Comment by dimecoin** [comment]
How do you build from develop branch?

I tried this, but binaries *.jar didn't change (and not seeing updated from https://github.com/timmolter/XChange/issues/1175)

    git clone -b develop https://github.com/timmolter/XChange.git
    cd XChange
    git pull
    mvn clean install

**Comment by timmolter** [comment]
`mvn clean install` is exactly right. This will create the jars in the `target` folders in each module as well as put them in your local Maven repo. Something else must be causing the issues.
