### ISSUE TITLE
Currency pairs missing in btce.json

### ISSUE THREAD

**Issue by xplaza** [timmolter/XChange#1183]
Hi,

Is there any reason for the BTCE json file not containing the currency pairs?

**Comment by rafalkrupinski** [comment]
https://btc-e.com/api/3/info

:)

**Comment by xplaza** [comment]
Ah, cool, direct from the api. 

Unless I'm missing something, I see no method to retrieve them, does it need to be implemented? For other exchanges I was getting the list via getMarketMetaDataMap(). 

I could give it a go with some minimal guidance.

**Comment by timmolter** [comment]
@xplaza It looks like no one implemented it yet. the easiest would be to add the pairs to `btce.json`. We'd appreciate a pull request for the change too!

**Comment by xplaza** [comment]
Sorry for the confusion, the pairs are already being retrieved online, but I wasn't calling remoteInit()
