### ISSUE TITLE
GLD/BTC Vaultoro exchange

### ISSUE THREAD

**Issue by kyipi** [timmolter/XChange#1184]
ztrader: bids prices are wrong. And, its not updating.

**Comment by timmolter** [comment]
@zholmes1 Can yo confirm this issue?

**Comment by jaminunit** [comment]
We have had a few members complaining that z-trader is not showing graphing info.

**Comment by zholmes1** [comment]
Graphing is separate from XChange. I will deal with that separately. As far
as the other issue, I am not able to replicate it. It might have been fixed
with XChange 4.0, as the current version of zTrader is using an older
version of XChange. The update should be going out within the next few days.

**Comment by kyipi** [comment]
hi there, unfortunately this was not solved.
