### ISSUE TITLE
Include a proper license header in source files

### ISSUE THREAD

**Issue by hegjon** [timmolter/XChange#1185]
It would make it easier to redistribute XChange if each source file contains a license header.

Check https://bugzilla.redhat.com/show_bug.cgi?id=1303764#c11 for details.

Missing or generated license headers: https://bugzilla.redhat.com/attachment.cgi?id=1123699

**Comment by timmolter** [comment]
We used to do this, and it's even automated by Maven, but we decided it just cluttered up the source files. I looked into the Apache 2.0 license and what people have discussed about the topic and came to the conclusion that it's not **necessary**. I'm happy to hear your opinion about it though and reconsider.

**Comment by hegjon** [comment]
As a developer I find that the license header just takes up space.

But I understand that the organizations that redistribute software want to have a clear license for all the files they distribute. As a side note, license issues via bundling are easier to detect when projects have a license header in each of their source files.

As a packager it makes my life easier to follow the guidelines for Fedora when the headers are included.

Do you have a reference to previous discussions? Then I can ask the legal mailing list for clarifications.

**Comment by timmolter** [comment]
Sorry I don't have a reference to previous discussions about it. Could you, as a packager, just run `mvn license:format` and add them just for your needs? Or do you want to pull the sources from Maven Central and have the headers already in there?

I guess I could run `mvn license:format` right before I do a release and then remove them thereafter. But it's a manual step that is prone to human error.

**Comment by hegjon** [comment]
I don't think running `mvn license:format` would make a difference, the source RPM consists of a tarball from this source `https://github.com/timmolter/XChange/archive/%{name}-%{version}.tar.gz
` + a RPM spec file that is specific for Fedora. The final RPM does not contain the .java files from the build. I think getting the source from Maven Central would make things more complicated.

**Comment by rafalkrupinski** [comment]
@hegjon I don't know about Redhat distributions, but I've noticed many Debian packages have a diff file attached to the original source. I'd expect RPM had similar mechanism. HTH
