### ISSUE TITLE
OKCoin PollingMarketDataService getTicker returns yuan values with any currency pair

### ISSUE THREAD

**Issue by blbradley** [timmolter/XChange#1187]
I'm using this library with Scala. So, bear with me.

```
val marketDataService = exchange.getPollingMarketDataService
val ticker = marketDataService.getTicker(CurrencyPair.BTC_USD)
```

Here is `ticker` serialized to json:
```
{"currencyPair":"BTC/USD","last":2730.1,"bid":2731.01,"ask":2731.03,"high":2799.0,"low":2709.0,"vwap":null,"volume":1661767.2859,"timestamp":1455552406000}
```

If the currency pair is not supported, I feel that an exception or error should be thrown.

Possible workaround: use `Exchange.getMetaData.getMarketMetaDataMap` to get valid currency pairs.

Thanks!

**Comment by timmolter** [comment]
We actually had that in the beginning, but took it out. Two reasons:

1. XChange grew very big and it was impossible to enforce the check in every pull request. We opted to leave that work to the client IF they even wanted it.
2. The map can become outdated, an exchange can drop or add a currency pair, then you'll get that exception when you really shouldn't be.

**Comment by blbradley** [comment]
@timmolter Have you considered a default currency pair for an exchange?

**Comment by timmolter** [comment]
no we haven't.

**Comment by blbradley** [comment]
It may be something to consider if other implemented exchanges have this
behavior.
