### ISSUE TITLE
add EXIT_BID and EXIT_ASK to OrderType to com.xeiam.xchange.dto.Order

### ISSUE THREAD

**Issue by douggie** [timmolter/XChange#1188]
currently Bid,Ask are supported in the Enum, for derivatives such as swaps and futures, additional order types are of exit long and exit short are supported to closed out existing positions, would be be possible to add EXIT_BID and EXIT_ASK to represent these order types.

  public enum OrderType {

    /**
     * Buying order (the trader is providing the counter currency)
     */
    BID, /**
     * Selling order (the trader is providing the base currency)
     */
    ASK
  
  }

**Comment by timmolter** [comment]
I don't understand why there would be an order type needed to close an already opened order. Can you explain this a bit more and justify why this should be added at the XChange generic level?

**Comment by douggie** [comment]
Hi Tim,

When trading derivatives products such as swaps/futures/CFD you can sell
what you don't have as they are derivatives, so I might want to go long
(bid) and short (ask) as the same time, so these would both be opening
positions, you don't necessarily want the sell to cancel out you buy,  you
may want to be both long and short at the same time, as this may be what a
particular trading strategy wants as they might want any movements up or
down to cancel each other out (mean reversion strategy)

Some exchanges that support derivatives products allow you to specify if
you want the trade to be an open/enter long/short or to close/exit an
existing long or short position.

OKCOIN

POST https://www.okcoin.com/api/v1/future_trade.do

type

1: open long position    2: open short position    3:liquidate long
position    4: liquidate short position




I can be both long and short at the same time, as this may be what a
particular trading strategy wants as they might want any movements up or
down to cancel each other out (mean reversion strategy)


Example

Buy 100@439.61 - This is entering a long position
May be the market starts to fall, so rather than exit my long, I just want
to hedge it a bit
Sell 100@435.61 - This is entering a short
Then the market start to recover and I want to exit the short
Exit 100 short position @ 436.17
and then ride the recovery and exit the log position at 445.

So I end up wih the following
Enter Long 100 @439.61
Enter Short 100@435.61
Exit Short 100@ 436.71 (making -110 ticks (435.61-436.71 x 100))
Exit Long 100@ 445 (making 539 ticks (445-439.61 x 100))

making a total profit of 429 ticks on the 100 lots, if the we can only
enter buys and sells and let them net out on first in first out the
following would have happened

Enter Long 100 @439.61
Exit Long  100@435.61(making -400 ticks (435.61-439.61 x 100))
Enter Short 100@ 436.71
Exit Short 100@ 445 (making -829 ticks (436.71 -445  x 100))

making a total loss of 1229 ticks on the 100 lots.

**Comment by timmolter** [comment]
Thanks for the explanation.  Could you update the PR with a better description of the order types in `Order` making it more clear to the un-educated user what those are for? It'd be nice to make it clear that those are for derivates along with a thorough description.

**Comment by douggie** [comment]
just in the PR or in the code?

**Comment by timmolter** [comment]
In the code.

**Comment by douggie** [comment]
comment in PR updated
