### ISSUE TITLE
Update okcoin futures trades to return the order quantity in TradeableAmount not the working quantity

### ISSUE THREAD

**Issue by douggie** [timmolter/XChange#1190]
The limit order tradeable ammount appears to be used for the total quanity of the order,

    public OpenOrders getOpenOrders() throws IOException, BitstampException {

        BitstampOrder[] openOrders = getBitstampOpenOrders();

        List<LimitOrder> limitOrders = new ArrayList<LimitOrder>();
        for (BitstampOrder bitstampOrder : openOrders) {
            OrderType orderType = bitstampOrder.getType() == 0 ? OrderType.BID : OrderType.ASK;
            String id = Integer.toString(bitstampOrder.getId());
            BigDecimal price = bitstampOrder.getPrice();
            limitOrders.add(new LimitOrder(orderType, bitstampOrder.getAmount(), CurrencyPair.BTC_USD, id, bitstampOrder.getTime(), price));
        }

Rather than the working quanity that is calculated by the ok coin futures order adapters:

    return new LimitOrder(adaptOrderType(order.getType()), order.getAmount().subtract(order.getDealAmount()), adaptSymbol(order.getSymbol()),
        String.valueOf(order.getOrderId()), order.getCreateDate(), order.getPrice());
  }

  public static LimitOrder adaptOpenOrderFutures(OkCoinFuturesOrder order) {
    return new LimitOrder(adaptOrderType(order.getType()), order.getAmount().subtract(order.getDealAmount()), adaptSymbol(order.getSymbol()),
        String.valueOf(order.getOrderId()), order.getCreatedDate(), order.getPrice(), order.getAvgPrice(), order.getDealAmount(),
        adaptOrderStatus(order.getStatus()));
  }
update to : 
 return new LimitOrder(adaptOrderType(order.getType()), order.getAmount(), adaptSymbol(order.getSymbol()), String.valueOf(order.getOrderId()),
        order.getCreateDate(), order.getPrice());
  }

  public static LimitOrder adaptOpenOrderFutures(OkCoinFuturesOrder order) {
    return new LimitOrder(adaptOrderType(order.getType()), order.getAmount(), adaptSymbol(order.getSymbol()), String.valueOf(order.getOrderId()),
        order.getCreatedDate(), order.getPrice(), order.getAvgPrice(), order.getDealAmount(), adaptOrderStatus(order.getStatus()));
  }

**Comment by timmolter** [comment]
@douggie We'd love to have your bug fix for this. Could you create a PR?

**Comment by douggie** [comment]
Hi Tim,

It is already in PR https://github.com/timmolter/XChange/pull/1195.

it was just if you don't feel the ASK_EXIT and BID_EXIT is the right
approach, I can reimplment it.
