### ISSUE TITLE
getMetaData() always returns null for BTC-e

### ISSUE THREAD

**Issue by mjagemann** [timmolter/XChange#1197]
Hi All,

I am trying to execute getMetaData() on an BTCEExchange instance to get a list of traded CurrencyPairs, unfortunately it always returns null. Anyone else experiences the same issue? Is there a fix known for this?

Is there another way to get a list of traded CurrencyPairs?

Best Regards,
Marcel

**Comment by rafalkrupinski** [comment]
@timmolter is it time to start calling remoteInit() from *Exchanges' constructors?

**Comment by mjagemann** [comment]
@rafalkrupinski Thanks for that incredible quick feedback ... calling remoteInit after instance creation indeed helped fixing this issue

**Comment by rafalkrupinski** [comment]
@mjagemann I'm glad it worked, but users keep reporting it as an issue, so I wonder if we should move this call to the constructor, or maybe it's missing from some documentation or examples?

**Comment by kmels** [comment]
+1 to call remoteInit() in ExchangeFactory. Not every exchange needs that invocation so it may be missing e.g. in the bitstamp docs. I pulled a request: https://github.com/timmolter/XChange/pull/1198

**Comment by timmolter** [comment]
@rafalkrupinski A lot of exchanges don't have remoteInit implemented, so the `loadMetaData` is preferred. Sometimes people might want to provide their own metadata json file as well and load that. The remoteInit just logs a message if it's not implemented, so it could be always called, falling back on the config file loading. What do you think?

**Comment by rafalkrupinski** [comment]
@timmolter 
I've made it requirement for the users to call remoteInit() but now I can see it creates many issues, especially for new users.
People expect the Exchange object to be ready to use when they get it from the factory, and if someone needs to use non-default meta data, we can provide a parameter to skip remoteInit().

**Comment by timmolter** [comment]
How about this:

`remoteInit()` throws NotYetImplementedException if not overridden. So if someone calls it explicity, they are notified of the fact that it probably won't give the results they're expecting.

In our init code in `BaseExchange` we first try to load init. If it catches an exception, it default to loading a user provided or the standard JSON config file. If the user REALLY wants to load a JSON config file when a remoteInit exists, they just call it afterwards.

What do you think?

**Comment by rafalkrupinski** [comment]
How many exchanges provide metadata and we don't use it? I'm not sure it's a good idea.

Consider a case, when an exchange uses meta merged from both local file an remote call. Currently it goes like this:
- load json file (possibly provided by user)
- remoteInit() downloads remote meta and merges it with the file.

If you want to allow users to override meta after creation:
- createExchange()
    - remoteInit() called automatically
    - load json file
    - merge
- user
    - load(file)
    - configure() - merge local and remote meta

I'd rather have it all configured with ExchangeSpecification so the exchange object ready for immediate use. Explicit remoteInit() was just a way to handle remote API call limits, but I think something like `boolean ExchangeSpecification.initialisesRemotely()` would suffice.

Another matter is, do we want user to override remote metadata? The original idea was to provide anything that was missing from the remote.

**Comment by timmolter** [comment]
@rafalkrupinski Thanks for your feedback. So you think it should be like this?:

In `BaseExchange.applySpecification` first call `remoteInit()`. The always call `loadMetaData(is)` right afterwards. Is it safe to assume that loading the metadata from file will not override the remotely-loaded metadata? Is it always merged or always overridden or different depending on how it was coded?

**Comment by rafalkrupinski** [comment]
IIRC local metadata was overridden by my implementations of remoteInit(), because it was meant only to supplement the remote API.

**Comment by timmolter** [comment]
Please see: Exchange Metadata Update and Discussion #1282
