### ISSUE TITLE
BitStamp updating OrderBook trouble

### ISSUE THREAD

**Issue by goldaster** [timmolter/XChange#1199]
I'm starting to implement a data miner based on xchange. As a first step to ensure my implementation, I do these simple steps (based on the examples provided):

1) Get BitStamp OrderBook (through HTTP API)
2) Subscribe to WebSocket API to channels LIVE ORDER BOOK and LIVE FULL ORDER BOOK streams.
3)Update original OrderBook with the changes (I've tried updating changes from both or each one only)
4)Get BitStamp OrderBook (through HTTP API) and compare both.

When comparing both OrderBooks, I'm getting differences. The longer I stay connected to the WebSocket API, the bigger the differences are. Therefore, they are not due to changes between getting the OrderBook and connect/disconnect the WebSocket API.

I don't have a clue whats happening, any help would be welcome! :D

Thanks!

**Comment by timmolter** [comment]
@goldaster I don't have any experience with BitStamp streaming so I cannot give any comment based on my experience. Maybe someone else will see this and leave a comment.

**Comment by blbradley** [comment]
@goldaster I'm having trouble understanding what you are comparing.

**Comment by Panchen** [comment]
A potential reason you are seeing a difference between the BitStamp OrderBook on the HTTP API and the streaming Websocket API is that the the HTTP API returns a snapshot of the order book which is cached and only refreshed every 10 secs or so versus real time updates.
E.g. log on to the website and when the order book best bid changes in TradeView keep refreshing  https://www.bitstamp.net/api/order_book/ in a browser to see that it is behind.

**Comment by goldaster** [comment]
@blbradley I'm checking I can keep an updated orderbook adding the updates received through the websocket api. Therefore, I get an orderbook and update it with the websocket api data, and then compare it with a new orderbook.

@Panchen Thanks, this helped! 

The problem is solved. I was applying updates without validating the timestamp... Sorry for being so idiot that I didn't realize it... xD
