### ISSUE TITLE
OKCoin streaming has empty disconnect function

### ISSUE THREAD

**Issue by blbradley** [timmolter/XChange#1200]
See [here](https://github.com/timmolter/XChange/blob/4e59f9c74c45b14646da82876c2f3ebdcce073c9/xchange-okcoin/src/main/java/com/xeiam/xchange/okcoin/service/streaming/OkCoinStreamingExchangeService.java#L47).

It should explicitly remove the channels added by `connect`.

PS: I had a ton of trouble getting OKCoin streaming to be performant on Amazon EC2. Tested with multiple instance types (up to c4.large). Bitstamp streaming works well for me though. I couldn't figure it out.

**Comment by timmolter** [comment]
Can you post a pull request with the fix if you have figured out the exact details? Or if it's really simple, you could post the code here and tell us where to put it. Thanks!

**Comment by blbradley** [comment]
It will be a while before I can post a PR. And that is if I choose to use this library's implementation for my data collection needs. But I can say that it is likely that undoing what `connect` does will work. The base of the OKCoin streaming code was pulled from [here](https://github.com/OKCoin/websocket), FWIW.

**Comment by timmolter** [comment]
Streaming now dropped in this lib: https://github.com/timmolter/XChange/issues/1235
