### ISSUE TITLE
CryptoFacilities v2 api

### ISSUE THREAD

**Issue by Panchen** [timmolter/XChange#1204]
CryptoFacilities are about to release a new version of their api with significant modifications to existing functions, e.g. 
    

- https://www.cryptofacilities.com/derivatives/api/trades?number=3

 
becomes 
   

-  https://www.cryptofacilities.com/derivatives/api/v2/fills?lastFillTime=2016-02-26T00:00:00.000Z

as well as adding new end points like:

- https://www.cryptofacilities.com/derivatives/api/v2/openpositions
- https://www.cryptofacilities.com/derivatives/api/v2/transfers?lastTransferTime=2016-02-26T00:00:00.000Z
- https://www.cryptofacilities.com/derivatives/api/v2/withdrawal?targetAddress=1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa&amount=0.12345678

The v2 version will run in parallel to the v1 version for a while I believe.

Happy to collaborate on upgrading but wanted to check first on the recommended way of doing / structuring this exercise bearing in mind the v1 api has only existed in 4.0.0 snapshot versions rather than previous major/minor released versions of the libs.

**Comment by Panchen** [comment]
Comparing the v1 and v2 api specs in more detail I can see that the new / changed v2 endpoints run on different urls so I plan to:

1. Implement the new / changed endpoints as new functions in the raw interface.
2. Deprecate old v1 raw functions.
3. Change the generic functions to adapt the new v2 functions thus providing more complete info, etc.

Let me know if this causes any issues.

**Comment by timmolter** [comment]
@Panchen Sounds like you're good to go on the new implementation. As in other exchanges in XChange, people usually just created a `v1` and `v2` sub package in the module and allowed the two version to co-exist side by side.

**Comment by Panchen** [comment]
@timmolter thanks. Can you suggest an example exchange with v1 / v2 sub packages as above I can use for reference.

**Comment by timmolter** [comment]
Thanks for the implementation. Closing...
