### ISSUE TITLE
Update Coinbase Api to use the new Coinbase Exchange api V2

### ISSUE THREAD

**Issue by SeanRobb** [timmolter/XChange#1205]
Currently for Coinbase the V1 api is being used which is not set up for the Coinbase exchange. The new exchange api information is https://docs.exchange.coinbase.com/ .  To utilize the Coinbase exchange via this library the update to use the V2 Coinbase exchange is required.

**Comment by soks86** [comment]
The new exchange is now named GDAX. API information is at https://docs.gdax.com/.

I'm in the middle of implementing updates to this and am going to commit a rename of Coinbaseex to Gdax unless someone suggests otherwise.

**Comment by timmolter** [comment]
sounds good!

**Comment by DaveTheAve** [comment]
@soks86 It would be awesome if I could get access to your development build of the new GDax implementation. Would you mind committing it to a feature-branch? I would not mind providing any updates I personally require that may not already be implemented.

**Comment by brandonio21** [comment]
@soks86  - Any updates? I've started working on my own implementation and don't want to duplicate work. (I also don't have much clue what I'm doing.. I'm new to _XChange_ .. Trying my best!)

**Comment by timmolter** [comment]
@brandonio21 I haven't heard anything regarding updates on this implementation.

**Comment by brandonio21** [comment]
@timmolter - Okay, great. I've been working on it in my spare time and will submit a PR when ready :)

**Comment by timmolter** [comment]
great!

**Comment by kennethjor** [comment]
@brandonio21 @soks86 Can I be of help? I'd love to get GDAX support implemented.

**Comment by brandonio21** [comment]
@kennethjor I linked a feature branch above. Feel free to contribute to it or change what I've done. (I've been pretty busy lately). 

I've pretty much just been stepping through [The GDAX API Reference](https://docs.gdax.com), using Coinbase as a reference. I haven't tested any of it yet and I'm sure some parts (like the JSON deserializing) could use some work. Looking forward to your contribution! :)

**Comment by Unbr8kbal** [comment]
@SeanRobb Do you still need this? and if so do you want it to go implement: https://docs.gdax.com/#api or https://developers.coinbase.com/api/v2 ??

**Comment by SeanRobb** [comment]
Yes i would like it if the coinbase exchange endpoints were updated for the new v2 endpoints.

**Comment by tdiesler** [comment]
I'll take a stab at this, if that's ok.

**Comment by npomfret** [comment]
@tdiesler it would be great if you could work on this.  I've been meaning to do it for a while but have not had the time.  Let me know if you get stuck.

I'm particularly interested in getting the deposit and withdrawal information.  If you need help testing just shout!

https://github.com/timmolter/XChange/issues/1728

**Comment by npomfret** [comment]
I wonder if using [this](https://github.com/irufus/gdax-java) might be a quick win ?

**Comment by tdiesler** [comment]
This project shows (very) low [activity](https://github.com/irufus/gdax-java/graphs/contributors) and has no [releases](https://github.com/irufus/gdax-java/releases).

You can monitor progress [here](https://github.com/tdiesler/XChange/tree/ghi1205). The functionality you're asking for is already implemented. This branch is still work in progress i.e. pls beware of incompatible changes.
