### ISSUE TITLE
Change the default NounceFactory or make it possible to have a custom factory

### ISSUE THREAD

**Issue by hegjon** [timmolter/XChange#1214]
I run into the same issue getting `Nonce must be greater than 1441530791414. You provided 406231706.`.

I assume the reason is that I used their API a while ago with another library.

It seems like the nonce factory is hard coded to AtomicLongIncrementalTime2013NonceFactory and I can not find a way to reset the nonce on Poloniex.

**Comment by abelgo** [comment]
Thanks for bringing this one back up.  
They way I understand it, This almost seems like a fundamental flaw whit using a REST API. Give the way the TCP/IP works we have no grantee that requests are going to arrive at the host on poloniex in the any given order. So at some stage when they get out of sink we are going to need to reset the nonce.

**Comment by timmolter** [comment]
@hegjon I heard that people just created another API key at the exchange as a way to reset the nonce. You can pass in your own nonce generator implementation when initing the Exchange object.

**Comment by hegjon** [comment]
It is a newly created API key, so that is a bit strange

**Comment by timmolter** [comment]
@hegjon Please see <https://github.com/timmolter/XChange/wiki/Design-Notes> and <https://github.com/timmolter/XChange/wiki/Frequently-Asked-Questions> to address your issue. I just updated it for you specifically. Cheers!
