### ISSUE TITLE
Support BitMex

### ISSUE THREAD

**Issue by douggie** [timmolter/XChange#1215]
https://www.bitmex.com/api/explorer/

**Comment by evdubs** [comment]
Has this been left out due to the products being futures and not spot currency pairs? Is that a concern for an XChange implementation?

**Comment by jheusser** [comment]
@evdubs I would assume so yes. The different APIs of the spot exchanges are already quite hard to represent in a single useful API. However XChange has some futures exchanges (Okcoin.com, Bitvc etc) implemented where you can use the underlying classes directly and essentially not use the XChange API for some things like getting positions etc. 

Another issue is that I believe Bitmex focusses more on websockets, where XChange ditched all websocket support for the time being.

**Comment by sirajperson** [comment]
That doesn't seem to make sense because the okcoin adapter offers futures api access.

**Comment by jheusser** [comment]
@sirajperson that's true, kinda agree. However okcoin/okex futures are closer to spot than bitmex (kinda like the perpetual swap on bitmex, with a persistent reference to 3 currency pairs) and naming works better with the current `CurrenyPair` approach of XChange.

**Comment by sirajperson** [comment]
BitMex rest API explorer and spec

https://www.bitmex.com/api/explorer/

**Comment by sirajperson** [comment]
@jheusser, thanks for the speedy reply. I was under the influence that continuous swap influenced the settlement rather than the order process.

**Comment by sirajperson** [comment]
Is there any reason that one wouldn't be able to enum an alias inside the a BitMex adapter so that the CurrencyPair would have to take on new jargo ?

**Comment by jheusser** [comment]
Sure, it's definitely possible. I think if someone implemented Bitmex in XChange it would get merged. I'm saying the terminology, reference data etc of a future contract might not fit well in the already bloated API of XChange which is more written with spot fx in mind.

**Comment by makarid** [comment]
If you can support bitmex,it would be great!

**Comment by timmolter** [comment]
https://github.com/timmolter/XChange/issues/1747
