### ISSUE TITLE
Implement Bitmarket trading

### ISSUE THREAD

**Issue by gryffus** [timmolter/XChange#1224]
I was looking into code for Bitmarket trading and it looks like it's almost implemented, but missing some bits.
I would like to help with implementation, but i need some info on what needs to be done, since i'm new to both Java and XChange, but i learn fast :)
BTW, is there some IRC channel for XChange devs/users?
Thanks for any help :)

**Comment by timmolter** [comment]
No IRC channel, just these issues. :) Feel free to post all you like.

Make sure to check both:
<https://github.com/timmolter/XChange/wiki/Getting-Started-with-XChange-for-Noobies>
<https://github.com/timmolter/XChange/wiki/New-Implementation-Best-Practices>

For BitMarket, just take a look at the code and you'll see what's missing, if anything. Unit tests and example code are the icing on the cake and help make sure everything is working. 

Cheers.

**Comment by gryffus** [comment]
Well, there seems to be Raw trading part done:
https://github.com/timmolter/XChange/blob/develop/xchange-bitmarket/src/main/java/com/xeiam/xchange/bitmarket/service/polling/BitMarketTradeServiceRaw.java

But placing order returns exception here:
https://github.com/timmolter/XChange/blob/develop/xchange-bitmarket/src/main/java/com/xeiam/xchange/bitmarket/service/polling/BitMarketTradeService.java

And i haven't so far figured out how to use the Raw trade service directly.
@krzysiekbarca ?

**Comment by gryffus** [comment]
Could placeMarketOrder() use placeBitMarketOrder() in the same way as placeLimitOrder() does?

**Comment by timmolter** [comment]
If there are exceptions thrown, it's highly likely that the exchange changed their API and the code in XChnage is no longer working and needs to be fixed.

Look at the xchange-examples module for many examples of using the raw service directly.

> Could placeMarketOrder() use placeBitMarketOrder() in the same way as placeLimitOrder() does?

Probably not, but possibly, depending on the details of the exchange. You need to see what REST endpoint the exchange has for placing market orders, and work up from that.

**Comment by gryffus** [comment]
Ok, so it works even with the generic API, the market just does not support market orders.
I have updated wiki with supported markets to reflect that.
But in my test i have found following issue:
If i send this LimitOrder to the market:
`LimitOrder [limitPrice=367.3905, Order [type=ASK, tradableAmount=0.01000000, averagePrice=0, currencyPair=BTC/EUR, id=null, timestamp=null, status=PENDING_NEW]]`
and then request it with 
`accountService.getOpenOrders().getOpenOrders().get(0);`
I get this result:
`LimitOrder [limitPrice=367.3905, Order [type=BID, tradableAmount=0.01000000, averagePrice=0, currencyPair=BTC/EUR, id=42637602, timestamp=Wed Apr 06 22:46:23 CEST 2016, status=PENDING_NEW]]`
The BID/ASK got negated. Am i using it wrong or is it a bug?
Also, is there some clever way to check if my trade is still on market or already sold?

**Comment by gryffus** [comment]
Ok, so the problem should be solved by https://github.com/timmolter/XChange/pull/1227, so please review it.
But my second question still remains, what is the recommended way of verifying if my trade is still on the market and not sold?

**Comment by timmolter** [comment]
Thanks, I'm happy you figured that out.

To answer your second question, I'd like to ask this one: "What API does Bitmarket provide to query open orders?

**Comment by gryffus** [comment]
It implements getOpenOrders() in pollingTradeService(), so i'm fetching it from market with
`orders = tradeService.getOpenOrders();`
and then searching in it with
`orders.getOpenOrders().stream().anyMatch(l -> l.getId().equals(placedAskId));`

**Comment by timmolter** [comment]
That sounds like a good way to do it.

**Comment by timmolter** [comment]
fixed in #1227
