### ISSUE TITLE
XChange 4.1.0 Wish List 

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#1235]
1. ~~Purge all streaming code/implementations, fork into a separate project?? (Curious to hear opinions on this. I find it a huge un-maintainable mess, and I have no time to dedicate to it)~~
2. Exception handling cleanup (#1233)
3. ???

Not everything in the [4.0.0 wish list](https://github.com/timmolter/XChange/issues/933) got implemented. We can/should transfer things forward from that list that we still think are needed.

**Comment by br0x** [comment]
> Purge all streaming code/implementations, fork into a separate project
Sounds reasonable to me. I stopped using streaming as unreliable feature long time ago

**Comment by andre77** [comment]
Not sure, whether this is right place, but anyway, what is about support for:
 - quadrigacx.com
 - bitcoin.de
any chance they would make it into the lib?

**Comment by veken0m** [comment]
@andre77 Are you interested in MarketData API (Orderbook, Ticker, Transactions) or full trading capabilities for QuadrigaCX and Bitcoin.de? I might implement these in the next couple of weeks but was only planning to do MarketData for now.

I noticed is that there are a lot of obsolete exchanges module. I think we should compile a list and start getting rid of them.

Here are modules that I've found are obsolete. I haven't gone through all, so if you know of others please feel free to add to the list.

- xchange-cavirtex (was acquired by Coinsetter, then by Kraken)
- xchange-coinsetter (acquired by Kraken)
- xchange-cryptsy (closed down)

**Comment by andre77** [comment]
@veken0m actually i'm interested in a complete API implementation. but its not about my wishes ;-)

**Comment by andre77** [comment]
@timmolter another nice feature would be the possibility to set the http read and connection timeout. currently one can set it globally using the rescu.properties file like this
`# Read timeout in milliseconds when performing HTTP requests. The default is 30000 (30 seconds).`
`rescu.http.readTimeoutMillis = 5000`
`rescu.http.connTimeoutMillis = 5000`
see https://github.com/mmazi/rescu/issues/1

i would like to provide different timeout values at runtime while creating the exchange, for example using ExchangeSpecification

**Comment by jheusser** [comment]
@timmolter 👍 for getting rid of streaming

**Comment by timmolter** [comment]
@jheusser Thanks for you comment on this. It looks like most people are or dropping streaming.

**Comment by douggie** [comment]
I found it too unreiable,  polling works well for now i feel even with
realtively fast trading strategies.

**Comment by kennethjor** [comment]
@timmolter If streaming isn't maintained and unreliable, get rid of it. Personally I'd prefer to use streaming where possible, but if it's not maintained.

**Comment by rafalkrupinski** [comment]
Since this is a "wish list", I'd wish the streaming was stable and consistent across exchanges :)

**Comment by jheusser** [comment]
I think it would be quite a successful and in-demand project to provide an API for websocket-only marketdata-only access to Bitcoin exchanges.

**Comment by timmolter** [comment]
@jheusser Definitely. Either one single umbrella project or I can imagine people taking over a single exchange's streaming API and creating a standalone dedicated project.

**Comment by timmolter** [comment]
@veken0m 
I removed some obsolete exchanges:

Yacuna shut down: <http://www.coindesk.com/european-bitcoin-exchange-yacuna-announces-closure/>
BTC-Central ==> Paymium
Coinsetter and CAVirtex: http://www.coindesk.com/bitcoin-kraken-coinsetter-acquired/
Cryptsy: https://news.bitcoin.com/cryptsy-big-vern-speaks-press/

**Comment by timmolter** [comment]
@andre77 Both are supported already it looks like

**Comment by jheusser** [comment]
@timmolter close?
