### ISSUE TITLE
Euro support on bitstamp

### ISSUE THREAD

**Issue by Achterhoeker** [timmolter/XChange#1244]
https://www.bitstamp.net/article/bitstamp-first-nationally-licensed-btc-exchange/

Is somebody already working on this ? Adding the new eur/btc pair in the json file isn't enough. The api has been changed to support euro trading.

**Comment by Achterhoeker** [comment]
I've implemented the api calls my bot needs: https://github.com/timmolter/XChange/pull/1245

**Comment by mmazi** [comment]
Most of the new API (v2) is done in #1247 (everything that was in v1 is now also in v2, but some things are missing from both). Euro support is done in full.
