### ISSUE TITLE
Add support for optimal TX fees

### ISSUE THREAD

**Issue by Polve** [timmolter/XChange#1261]
Modern wallets have the need to use dynamic fees in order to transact when the blocks are full (i.e.: almost always). It would be handy to be able to use XChange for that too.

An example source of current fees is this one:
https://bitcoinfees.21.co/api/v1/fees/recommended

**Comment by jheusser** [comment]
IMO this is probably better pushed to clients using XChange, to keep the library simpler and more focussed on trading. But I agree wallets do get more complex.

**Comment by kennethjor** [comment]
@Polve Could you elaborate a little? XChange is a library for dealing with third-party exchanges, not the Bitcoin network in itself. Why do you want Bitcoin network fee code in XChange?

**Comment by Polve** [comment]
I don't mean to connect directly to the bitcoin network, but to parse and present as a uniform interface third party services that give this information, like aforementioned 21.co

**Comment by kennethjor** [comment]
@Polve But XChange is an API for connecting to the crypto currency exchanges. These fee services are for the bitcoin network. To me it seems this is out of scope for XChange.
