### ISSUE TITLE
Thread pool and connection re-use

### ISSUE THREAD

**Issue by kennethjor** [timmolter/XChange#1277]
I just got an exception while trying to fetch data from Kraken, and noticed the name of the thread name was `Thread-1060227`. That's thread number 1,060,227. The REST client, does it not execute requests on a thread pool and employ connection re-use? If possible, how do I make sure this is enabled? I had a look around the API, but wasn't immediately able to find anything.

I did find the method `HttpTemplate::getHttpURLConnection` in ResCU, which has the line

    HttpURLConnection connection = (HttpURLConnection) new URL(urlString).openConnection(proxy);

I didn't see any code in there that implied connection and thread re-use was even possible.

**Comment by timmolter** [comment]
@mmazi would be able to answer this best.

**Comment by kennethjor** [comment]
@timmolter Ah quite, perhaps I should have raised a ticket over there instead.

**Comment by mmazi** [comment]
Rescu itself doesn't use any kind of multithreading, and I'm pretty sure XChange doesn't either. The application that uses rescu/XChange may create new threads though (eg. to issue HTTP requests simultaneously).

If you don't see immediately where your application (or another library you are using) creates new threads, perhaps you are using Java 8's high-level multithreading facilities like parallel streams or Executors/ExecutorServices.

**Comment by kennethjor** [comment]
@mmazi Interesting, perhaps it's my application then, I'll check it out. However all my code is indeed wrapped inside thread pools and such, so it shouldn't be creating that many threads, and especially not using that naming structure. I'll have a closer look.
