### ISSUE TITLE
Exchange Metadata Update and Discussion

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#1282]
Hi all,

After a long time of issues and confusion regarding exchange metadata, I finally implemented a solution, which I think is best based on feedback and discussions from the community.

Please see: <https://github.com/timmolter/XChange/wiki/Design-Notes> section **Exchange Metadata**.

The metadata for the exchanges (including the currency pairs) should be loaded and accessed from one place and one place only - the `Exchange` object. This data can be accessed from all the service classes and is loaded once during initialization.

Please test where you can, as I don't have access to all the affected exchanges, especially Kraken, as I had to change the way the currency pairs are parsed. 

Also, only a few of the exchanges actually have this 100% perfectly implemented as of right now. It would be appreciated if you could take a look at the code for the exchanges you actively deal with and update the `remoteInit` method and the hard-coded JSON file appropriately. A good working example is: `BleutradeExchange.java`.

Please also give feedback on any parts of my implementation including throwing an `ExchangeException` surrounding the `remoteInit()` call in `BaseExchange`.

**Comment by timmolter** [comment]
I should also mention that the default behavior has now changed to always call `remoteInit()` during the creation of the `Exchange` instance. It's talked about in the above Wiki link, but for the lazy, I wanted to make that clear here.

**Comment by timmolter** [comment]
If you are going to create an exchange, you will be using the network, right? I wasn't a big fan of that either at first, but can you name one concrete problem with that? Unit testing maybe? Do we need a different mechanism? I'm open to solid reasoning. 

It's now `exchange.getExchangeSymbols()`. I updated the Wiki now. I had a typo there previously.

> Can we at least get getExchangeSymbols() back until remoteInit() works as intended?

You can call whatever methods you like on the Raw interfaces. If I took one out somewhere, I apologize.

I purposely do not want the ability to get exchange symbols from both metadata AND through the base service or any generic service method because that causes one of the main problems I'm trying to solve, which is that people are confused on where to code in that functionality and where to call for that data. People seem to be using both places and coding in both places and it's diverging into somewhat of a mess both for devs and users. At version 4.0.0, we decided to move that metadata to it's own special object, and provided some needed functionality for supplementing data not on the exchanges, via the JSON files. V4.1.0 I see as ironing out this mess, and there will be some pain at first, i understand your frustration, but I honestly think it's a small price to pay for what will be a huge step in the right direction for devs and users alike (and for me tending to the resulting issues that keep coming up).

**Comment by zholmes1** [comment]
I can think of two good reasons not to make a network call when an `Exchange` instance is created.

1. There are going to be times when a user needs to make an `Exchange` instance directly before placing an order. Most of the demos are examples of this. In the case of exchanges with overly-aggressive throttling (like Kraken), consecutive API calls with no pause in between may result in the second request being rejected. So now a proper implementation would include Thread.sleep being used after getting an `Exchange`.

2. In Android, all network calls need to be made on a background thread. This change forces lines  where an `Exchange` instance is initialized to be put on a background thread, which I don't think is how XChange was meant to be implemented.

**Comment by mmazi** [comment]
I'm also very much against calling `remoteInit()` (or any other network calls) during Exchange initialization. All of the issues mentioned above seem very valid.

There is no recovery mechanism for situations when `remoteInit()` repeatedly fails (eg. server/network issues, incorrect/outdated implementation of remoteInit() in the XChange submodule, or others) but other API calls (like market data or placing orders) may succeed, which makes XChange unusable in such cases.

@timmolter can you provide reasons why you decided to include remoteInit in the initialization? (I looked for them both in the wiki and in your above comments, sorry if I missed it.)

**Comment by rafalkrupinski** [comment]
@mmazi it was added because many users complaint about exceptions when getting available currency pairs.

My proposition was to add a flag to skip remoteInit() and leave the default behavior as is now.

**Comment by zholmes1** [comment]
That solution seems reasonable to me.

**Comment by timmolter** [comment]
Thanks for your input. I'm mostly concerned with a solution that is the most useful/helpful for the most people. So it sounds like a remoteInit flag is all that is now needed, with it being `true` by default. I'll add that. Feel free to provide more feedback.

**Comment by mmazi** [comment]
> My proposition was to add a flag to skip remoteInit() and leave the default behavior as is now.

Seems fine to me too.

**Comment by timmolter** [comment]
OK, I refactored this. See `BTERMetaDataDemo` for how it works. 

One question I have is: What should be the default setting `remoteInit` true or false?

**Comment by rafalkrupinski** [comment]
@timmolter remoteInit should be true, we're adding it to allow a custom initialization for more advanced scenarios. Multiple issue reports showed that most users expect exchange client just working.

**Comment by zholmes1** [comment]
I agree with it defaulting to true. The case where it needs to be turned
off is not common, and the average user will probably just expect all meta
data to be up to date automatically.

**Comment by timmolter** [comment]
OK, I set it to true. Thanks!
