### ISSUE TITLE
Exchange Metadata json broken

### ISSUE THREAD

**Issue by mmazi** [timmolter/XChange#1285]
The commit c1073a930e230 broke HitbtcMetaData and possibly others as well. The json structure doesn't match the annotated POJO -- note the `currencies` vs. `currency` mismatch:

hitbtc.json:

    "currencies": { ...}

HitbtcMetaData.java:

    @JsonProperty
    public Map<Currency, CurrencyMetaData> currency;

**Comment by timmolter** [comment]
Fixed.
