### ISSUE TITLE
ExchangeException doesn't use exception wrapping

### ISSUE THREAD

**Issue by kennethjor** [timmolter/XChange#1294]
I just noticed that the XChange libraries contain a lot of code like this:

    throw new ExchangeException(e.getMessage());

It's common practice to wrap exceptions to preserve stack traces and allow for better debugging, like so:

    throw new ExchangeException(e);

Is there a reason why ExchangeException is often thrown while discarding the original cause?

**Comment by timmolter** [comment]
There's definitely room for improvement regarding Exception handling. 

See related: 
https://github.com/timmolter/XChange/issues/1233

**Comment by kennethjor** [comment]
Thank you.
