### ISSUE TITLE
100 mBTC Bounty - QuadrigaCX implementation (1:1 Bitso API)

### ISSUE THREAD

**Issue by ICFiedler** [timmolter/XChange#1299]
It would be great to see Canada's largest Bitcoin exchange QuadrigaCX implemented. It is exactly the same APi as the one from Bitso, which is already in the library. Just the currencies are different, of course.

**Comment by ICFiedler** [comment]
I would like to offer a 0,1BTC bounty on this one. How can I do this?

**Comment by timmolter** [comment]
I've added the bounty tag and updated the title. If someone wants to complete this for the bounty, first claim it here and indicate you will work on it. Then @ICFiedler should send us (Knowm Inc.) the BTC and we will hold it until the code is complete and passes all functionality and quality checks. We will then forward the funds to the person carrying out the bounty.

**Comment by veken0m** [comment]
I'm starting work on QuadrigaCx implementation so I'd like to claim this bounty.

**Comment by ICFiedler** [comment]
Amazing! I am looking forward to your results. Let me know when you want me to test it.

**Comment by ICFiedler** [comment]
any update as of yet?

**Comment by veken0m** [comment]
@ICFiedler Drive in my laptop gave out and lost all my progress... I'll do my best to hammer it out this weekend. Should be much quicker the second time around.

**Comment by ICFiedler** [comment]
Is it working now?

**Comment by timmolter** [comment]
@veken0m Is this finished?

**Comment by veken0m** [comment]
@timmolter yes, it's complete. @ICFiedler Let me know if you find any issues. 

Bounty can be sent to this address: 1NqLkzEkortCzBeXM5hWW95LRBVbHw1Wbp

Thanks!

**Comment by ICFiedler** [comment]
it works! thank you! send the bounty now

**Comment by timmolter** [comment]
@veken0m Let me know when you've received the BTC and I'll close this issue.

**Comment by veken0m** [comment]
@timmolter @ICFiedler Got the BTC, closing issue. Thanks!
