### ISSUE TITLE
itBit Authenticated Requests Intermittently Yield Invalid Signature

### ISSUE THREAD

**Issue by matthewdowney** [timmolter/XChange#1300]
I'm getting an issue with itBit where intermittently requests will fail with 

```Exception in thread "Thread-0" org.knowm.xchange.itbit.v1.dto.ItBitException: Your request lacked a valid signature, and could not be authenticated. (HTTP status code: 401)```

but the rest of the time they work fine. If I run some simple polling code:

```java
    public static void main(String[] args) {
		final Exchange itBit = ExchangeFactory.INSTANCE.createExchange(ItBitExchange.class.getName());
		ExchangeSpecification spec = itBit.getExchangeSpecification();
		spec.setApiKey(System.getenv("ITBIT_API_KEY"));
		spec.setSecretKey(System.getenv("ITBIT_SECRET_KEY"));
		spec.getExchangeSpecificParameters().put("userId", System.getenv("ITBIT_USERNAME"));
		spec.getExchangeSpecificParameters().put("walletId", System.getenv("ITBIT_WALLET"));
		itBit.applySpecification(spec);

		new Thread(new Runnable() {
			@Override
			public void run() {
				try {
					for (;; Thread.sleep(5000)) {
						AccountInfo ai = itBit.getPollingAccountService().getAccountInfo();
						System.out.println("Got account info: " + ai.toString());
					}
				} catch (InterruptedException | NotAvailableFromExchangeException | NotYetImplementedForExchangeException | ExchangeException | IOException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}).start();
	}
```

I'll get 5 or 10 successful responses

```Got account info: AccountInfo [username=something, tradingFee=null, wallets={something=Wallet [id=something, name=Wallet, balances=[Balance [currency=SGD, total=0E-8, available=0E-8, frozen=0E-8, borrowed=0, loaned=0, withdrawing=0, depositing=0], Balance [currency=XBT, total=0.01990000, available=0.01990000, frozen=0E-8, borrowed=0, loaned=0, withdrawing=0, depositing=0], Balance [currency=EUR, total=0E-8, available=0E-8, frozen=0E-8, borrowed=0, loaned=0, withdrawing=0, depositing=0], Balance [currency=USD, total=0.05708100, available=0.05708100, frozen=0E-8, borrowed=0, loaned=0, withdrawing=0, depositing=0]]]}]```

and then suddenly I'll get the invalid signature message. I've turned on trace logging for Rescu and verified that the nonce values and timestamps are correct, and I've looked at the code in `ItBitHmacPostBodyDigest` and it looks fine. Has anyone else had this issue, or could possible shed some light on what's happening?

**Comment by timmolter** [comment]
are you using the latest code on the `develop` branch?

**Comment by bryan4887** [comment]
Yeah, he is.  We've also filed a bug with ItBit.  It would be nice to know if anyone else can reproduce this behavior as well.

**Comment by matthewdowney** [comment]
@timmolter Yeah I am. Are you not getting the same issue that I am?

**Comment by jheusser** [comment]
@bryan4887 @matthewdowney I get the same issue for a few years now, extensively debugged it with ItBit with no result. So unless there's a bug in the XChange code I haven't found (which is very possible) then it's a ItBit bug.

**Comment by matthewdowney** [comment]
@jheusser Interesting! Thanks for the input. I feel like it has to be something on the itBit side of things, because if the signing algorithm were incorrect every request should fail, and printing the timestamp and nonce values doesn't show anything strange. Maybe itBit is incorrectly handling some *other* error as an invalid signature?

**Comment by jheusser** [comment]
@matthewdowney I think we had a similar bug where only every so many calls used a timestamp that somehow lead to a wrongly signed message, but I don't think this is the case here. I kind of just came to the conclusion it's due to ItBit under load. Also the account request is usually the one that needs to hit the database making sure your balance is up to date, so takes longest.

**Comment by matthewdowney** [comment]
Just to follow up, ItBit never responded so I went with the approach of a retry handler that would give it three tries, because I've seen the request succeed the second time every time so far.

**Comment by mmazi** [comment]
I've been frequently getting the "request lacked a valid signature" errors from ItBit too.

I've seen, on several occasions, signature problems that stem from the fact that the server calculates the signature from a _normalized_ form of the request body instead of the verbatim form that is sent in the request. E.g. the body may be reformatted, possibly because the json is first parsed, then serialized back to json, and the serialized form is used to calculate the signature.

I'm not claiming this is the case with ItBit, just something I've seen elsewhere.
