### ISSUE TITLE
adding additional parameters to api rest call 

### ISSUE THREAD

**Issue by matthiasamberg** [timmolter/XChange#1306]
Hi all,

sorry if this has been covered before (actually is there a forum I couldn't find regarding XChange, where things like this could be discussed?):

I am fetching the orderbook of the QuoineExchange and noticed that it always returns exactly 20 bid and 20 ask limit orders. Reading through the Quoine API Specs the following statement is made: 

> Pagination
> 
> Unless otherwise specified, all API requesting lists will be paginated with the following format:
> The default number of items returned is 20. To get more, you can specify parameter `limit`. For example GET /trades?limit=100. Note that the maximum number of items we can return at a time is 1000 
> (https://developers.quoine.com/#code)

I tried passing an optional argument for getOrderBook() but noticed that those aren't actually passed on or used in the called function.

Now my question: is there a way to circumvent this limit of 20 entries per returned list from Quoine while using xchange and if there is, how do I do it?

**Comment by timmolter** [comment]
This is the correct place to ask such questions. You'll have to look at the XChange source code to see exactly what's going on. And if something needs to be changed to suit your needs, you'll have to change it. A PR would be nice with the fix. :)
