### ISSUE TITLE
Issues with Bitfinex

### ISSUE THREAD

**Issue by aditya-radhakrishnan** [timmolter/XChange#1309]
I'm currently using the Xchange library to stream data from various Bitcoin exchanges, including Bitfinex. I'm having a problem with some of the Bitfinex ticker data I'm receiving, namely, some samples have an execution timestamp that comes after in time from the received timestamp, which doesn't make much sense. I ran some tests by querying Bitfinex's API directly, and I didn't seem to receive any data samples where the execution timestamp was after the received timestamp. I've attached a histogram showing the difference in seconds between the received and execution timestamps (positive is what I want, as it means the received timestamp came later in time). I've also contacted Bitfinex directly, and when they ran their own tests, they didn't seem to have this problem either. 
[bitfinex_ticker.pdf](https://github.com/timmolter/XChange/files/505236/bitfinex_ticker.pdf)

**Comment by timmolter** [comment]
I don't see both "execution timestamp" and "received timestamp" on the Ticker from bitfinex so I'm not sure what you're trying to compare. Here's the adapter method. One thing is that it looks like the time resolution on the timestamp from bitfinex is seconds and not milliseconds. that could be your issue.

public static Ticker adaptTicker(BitfinexTicker bitfinexTicker, CurrencyPair currencyPair) {

    BigDecimal last = bitfinexTicker.getLast_price();
    BigDecimal bid = bitfinexTicker.getBid();
    BigDecimal ask = bitfinexTicker.getAsk();
    BigDecimal high = bitfinexTicker.getHigh();
    BigDecimal low = bitfinexTicker.getLow();
    BigDecimal volume = bitfinexTicker.getVolume();

    Date timestamp = DateUtils.fromMillisUtc((long) (bitfinexTicker.getTimestamp() * 1000L));

    return new Ticker.Builder().currencyPair(currencyPair).last(last).bid(bid).ask(ask).high(high).low(low).volume(volume).timestamp(timestamp)
        .build();
  }

**Comment by aditya-radhakrishnan** [comment]
Apologies, I meant to say "receivedAt" instead of received timestamp and "timestamp" instead of execution timestamp. Essentially what's going on is that the value for "receivedAt" (when I get the data) is often lower (earlier in time) than the value for "timestamp," which doesn't make sense as this is saying I'm getting ticker values for data from the future. You can see from the histogram that these values are pretty significant, too (the numbers are all in seconds).

Could this issue be reopened?

**Comment by timmolter** [comment]
What is `receivedAt`? I cannot find what your referencing. What object is it contained in?

**Comment by aditya-radhakrishnan** [comment]
receivedAt is a field for a TickerWrapper object we constructed as a wrapper around the Xchange Ticker object. When we receive a new Ticker, we set receivedAt = new Date(). I can send you the code if you would like.

**Comment by timmolter** [comment]
Well that's the answer. `new Date()` is your computer's time. `timestamp` is Bitfinex's time they send.

**Comment by aditya-radhakrishnan** [comment]
I understand. Since new Date() is my computer's current time, I'm setting receivedAt = new Date() to show when I get the ticker while timestamp is just the ticker timestamp. The ticker timestamp should be much earlier than when I get the ticker value, but my issue is that the ticker timestamp is often higher in value than receivedAt.

**Comment by timmolter** [comment]
Your issue is not in the code in `XChange`, so we cannot help you here. `XChange` is unmarshalling the JSON correctly. Without full control and insight into your and Bitfinex's servers, how are you expecting to figure out your problem? It's simply a matter of unsynchronized clocks and it's not in your control, so better not to worry about it and design your system with that fact in consideration.
