### ISSUE TITLE
GDAXAdapters.java #L63

### ISSUE THREAD

**Issue by unk1911** [timmolter/XChange#1329]
There is an issue in org.knowm.xchange.gdax.GDAXAdapters.class on line #63:

---

 private static Date parseDate(String rawDate) {
        try {
            if(rawDate.length() == 21) {
                rawDate = rawDate.substring(0, 20) + "000";
            } else if(rawDate.length() == 22) {
                rawDate = rawDate.substring(0, 21) + "00";
            } else if(rawDate.length() == 23) {
                rawDate = rawDate.substring(0, 22) + "0";
            } else {
                rawDate = rawDate.substring(0, 23);
            }

```
        return dateFormat.parse(rawDate);
    } catch (ParseException var2) {
        return null;
    }
}
```

---

rawDate = rawDate.substring(0, 23)   throws a StringIndexOutOfBoundsException:

java.lang.StringIndexOutOfBoundsException: String index out of range: 23
    at java.lang.String.substring(String.java:1963)
    at org.knowm.xchange.gdax.GDAXAdapters.parseDate(GDAXAdapters.java:63)
    at org.knowm.xchange.gdax.GDAXAdapters.adaptTradeHistory(GDAXAdapters.java:153)
    at org.knowm.xchange.gdax.service.GDAXTradeService.getTradeHistory(GDAXTradeService.java:65)

**Comment by unk1911** [comment]
i did some more research into it, it looks like the following input date was causing the exception:  2016-10-28T14:24:02Z     you have to check for length size 20...

**Comment by unk1911** [comment]
might want to change that last else statement to something like:

rawDate = rawDate.substring(0, rawDate.length() < 23 ? rawDate.length() : 23);

this way it will still throw ParseException on inputs that are shorter than 23 characters.



Here's a junit test for it:

   @Test
    public void testParseDate() {
        try {
            String rawDate = "2016-10-28T14:24:02Z";
            Date dt = GDAXAdapters.parseDate(rawDate);
            assertThat(dt == null);
        } catch (Exception e) {
            e.printStackTrace();
            fail("Barfed");
        }
    }

**Comment by kennethjor** [comment]
I'm not fully familiar with this code, but I'm wondering why [SimpleDateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html) isn't being used to output dates in the correct format, rather than checking the length and appending zeroes to it?

**Comment by timmolter** [comment]
Sorry to be ignoring this issue. I'm currently up to my neck in another project. I'll help out with this when I can, if you don't solve it yourself and create a pull request.

**Comment by unk1911** [comment]
sorry i am having issues with the pull request.   i ended up just tweaking your code and doing a local maven release.     here's what i changed the function to:


`    static Date parseDate(String rawDate) {

        //    System.out.println("before: " + rawDate);
        try {
            if (rawDate.length() == 20 && rawDate.endsWith("Z")) {
                rawDate = rawDate.substring(0, 19) + ".000Z";
            } else if (rawDate.length() == 21) {
                rawDate = rawDate.substring(0, 20) + "000";
            } else if (rawDate.length() == 22) {
                rawDate = rawDate.substring(0, 21) + "00";
            } else if (rawDate.length() == 23) {
                rawDate = rawDate.substring(0, 22) + "0";
            } else {
                rawDate = rawDate.substring(0, rawDate.length() < 23 ? rawDate.length() : 23);
            }
            //      System.out.println("after: " + rawDate);
            //      System.out.println("");

            return dateFormat.parse(rawDate);
        } catch (ParseException e) {
            System.err.println("rawDate: " + rawDate);
            e.printStackTrace();
            return null;
        }
    }`

**Comment by timmolter** [comment]
Thanks, I updated the code.
