### ISSUE TITLE
get Funds Information (Deposits and Withdrawals)

### ISSUE THREAD

**Issue by kisapmata** [timmolter/XChange#1334]
Hi, i'm just new user of xchange library. I am not aware yet how to raise a request or issue so bear with me. My concern basically is that I wanted to get the history of the deposits and withdrawals for certain exchanges but I dont think it is fully supported by the library , please feel free to correct me. I am able to do this for Bitfinex by adding below codes. I would like to suggest in adding such feature for reporting/accounting purpose. Let me know if this is possible or how do I go about this. Thanks.

-------- BitfinexAccountServiceRaw  -------
    public BitfinexMovementsResponse[] getBitfinexMovements() throws IOException {
        try {
            BitfinexMovementsResponse[] e = this.bitfinex.movements(this.apiKey, this.payloadCreator, this.signatureCreator, new BitfinexMovementsRequest(String.valueOf(this.exchange.getNonceFactory().createValue())));
            return e;
        } catch (BitfinexException var2) {
            throw new ExchangeException(var2.getMessage());
        }
    }

-------- xchange-core  -------
public final class FundsInfo {
    private final List<FundsRecord> fundsRecordList;

    public FundsInfo(List<FundsRecord> fundsRecordList) {
        this.fundsRecordList = fundsRecordList;
    }

    public List<FundsRecord> getFundsRecordList() {
        return this.fundsRecordList;
    }

    public String toString() {
        return "FundsInfo [fundsRecordList=" + this.fundsRecordList + "]";
    }
}

-------- BitfinexAccountService  -------
    public FundsInfo getFundsInfo() throws IOException {
        return BitfinexAdapters.adaptFundsInfo(this.getBitfinexMovements());
    }

-------- BitfinexAdapters -----
  public static FundsInfo adaptFundsInfo(BitfinexMovementsResponse[] bitfinexMovementsResponses){
    List<FundsRecord> fundsRecords = new ArrayList<FundsRecord>();
    for (BitfinexMovementsResponse responseEntry : bitfinexMovementsResponses) {
      String address = "";
      String description = responseEntry.getDescription();
      if (responseEntry.getCurrency().equals("BTC") && responseEntry.getType().equals("WITHDRAWAL") && description.contains(",")){
        address = description.substring(0,description.indexOf(",")-1);
        description = description.substring(description.indexOf("txid: ")+ "txid: ".length());
      }
      FundsRecord fundsRecordEntry = new FundsRecord(address,responseEntry.getTimestamp() * 1000L,
              responseEntry.getCurrency(),responseEntry.getAmount(),
              description,responseEntry.getType());

      fundsRecords.add(fundsRecordEntry);
    }
    return new FundsInfo(fundsRecords);
  }

**Comment by kisapmata** [comment]
FundInfo object here
------- xchange-core-----
public final class FundsRecord {
  public FundsRecord(String address, Long date, String ccy, BigDecimal amount, String ref, String fundsType){
    this.address = address;
    this.date = date;
    this.ccy = ccy;
    this.amount = amount;
    this.ref = ref;
    this.fundsType = fundsType;
  }
}

**Comment by mmazi** [comment]
You are right, XChange generic API doesn't support this yet. I think this would be a useful addition to the generic API (I myself would use it immediately for some of my projects).

I already suggested it in #21 (though the issue discussion mostly digressed to other topics).

If someone starts implementing this, please ping me and I'll help with code review, suggestions, and possibly implementations for some exchanges with testing. I don't currently have the time to start writing this myself though.

**Comment by kisapmata** [comment]
Hi, can I work on this for 4 exchanges to get Withdraw/Deposit history? I have the codes ready for Kraken, Bitfinex, OkCoin and BTCChina ... I will have to throw NotYetImplementedForExchangeException for all the rest. If yes, i need some kick start guide, e.g. branching, issue naming conventions etc.....  I also plan to fix around 3 to 4 issues I found as well for other exchanges like BTC China and Bitstamp. Its my first time trying to contribute to github open source repositories so I still don't know where to start

**Comment by mmazi** [comment]
@kisapmata That sounds great! I'll do my best to help. I'll try to give you some pointers today if I manage to, otherwise next week.

**Comment by mmazi** [comment]
So I suggest we start with what you have.

Your contributions should be separate and self-contained, so if you have the FundsInfo addition plus 4 other issues, these should be all in separate git branches, so 5 branches altogether. Branch names are not very important, but try to make them a bit descriptive, like `generic-fundsinfo`, `bitstamp-timestamp-fix` and such.

First make sure you have your code committed to these branches locally. Each branch should be rebased on the latest state of the `develop` branch.

Whenever possible, each branch should contain unit tests that test new code, or in case of bug fixes, tests that demonstrate the bug (ie. tests that fail before the bug fix and pass with the bug fix included).

When your local branches are ready, push them into your XChange clone repository on GitHub (https://github.com/kisapmata/XChange). Submit a Pull Request (PR) against the develop branch timmolter/XChange for each branch, together with a short description, or a reference to an existing issue, eg. #1334 (this issue). GitHub should offer a one-click PR submit option, or you can click on the branch in your repo and submit a PR there.

When a PR is submitted, I'll review the code and add some suggestions. You can then simply switch to the corresponding branch locally, code any additions/changes, and push into your GitHub repo; the PR will be updated automatically.

When we're satisfied with the result, I'll merge the issue into timmolter/XChange. Done!

If you need help with any of the above, please ask. You can also reach me by e-mail (see my GitHub profile page).

Thanks a lot for contributing, it's greatly appreciated!

**Comment by mmazi** [comment]
Besides Kraken, Bitfinex, OkCoin and BTCChina implementations that @kisapmata will contribute, I'll do Bitstamp and Poloniex. I think this will be a good start.

**Comment by kisapmata** [comment]
I have made the commit and PR. I included adapter tests and also demo for each bitfinex, kraken, okcoin and btcchina

**Comment by kisapmata** [comment]
i have to cancel the PR. I need to sync first with the latest develop branch sorry

**Comment by kisapmata** [comment]
I initially missed out to re-base from develop branch. now its fine, PR should be updated.
