### ISSUE TITLE
BTCChina getTradeHistory not giving the Order ID.

### ISSUE THREAD

**Issue by kisapmata** [timmolter/XChange#1341]
existing BTCChinaTradeService.getTradeHistory has significant issues:
1st: it queries all kinds of transactions via api, not just trades. Though it filters it by buy/sell type afterwards.
2nd: the main problem is that the result  doesn't contain the order id, so the order submitted cannot be reconciled.

proposed solution:
use GetOrders instead with "with_details" flag to true. The details will have the amount, price and trade date. Order id and type can be picked up from the parent object. The only problem is that it doesnt have the trade id  (internal id used by btcchina, this is not even displayed in their page).

**Comment by kisapmata** [comment]
just fyi, I have just clarified with BTCChina that the getOrders API queries only 1 week worth of orders, beyond that the getArchivedOrders should be called instead. It gets complicated in this case as I think, if you need to query worth 2 weeks of record, you will have to make 2 API calls (1 getOrders for the 1st week and 1 getArchivedOrders for the 2nd week).

**Comment by kisapmata** [comment]
@timmolter @mmazi once you have time, please feedback on this if you think this needs fixing. Please take note that the main issue on this is that the current implementation (GetTransaction) doesn't provide order_id which makes it impossible to reconcile order submitted based on it's id.

**Comment by timmolter** [comment]
@kisapmata Do you have a well-defined solution to this?

**Comment by kisapmata** [comment]
@timmolter I have spoken to BTCChina regarding, their advise is to use the getOrders and getArchivedOrders. Note that GetOrders searches ONLY WITHIN the recent 1 week records while GetArchivedOrders searches ONLY AFTER 1st week records. The problem here is "since" (startDate) parameter is only present for the 1st method but not on 2nd one. This means there is no way to query a specific date record after 1st week. In an ideal scenario, 1st week record should be more than enough if the application is running everyday and saving their own copy of the Order/Trades history of their own transactions. What I've done for now is use this logic below. 

if limit is null { set limit = DEFAULT(1000) }
result = getOrders (limit, size, offset, since)
if (result.size < limit) {
    remainingLimit = limit-result.size 
    result = result + getArchivedOrders(remainingLlimit)
}

One more thing, based on my conversation with BTCChina, they will look into enhancing the GetTransaction method to include even the "order id" in future, but there's no guarantee or timeline for that. 

I will create a pull request for this, its all up to you if you want to approve the changes or not. I've tested the changes.
