### ISSUE TITLE
NPE while order placement @ BTCe

### ISSUE THREAD

**Issue by andre77** [timmolter/XChange#1349]
For some reason i see an NPE from time to time during the placement of a BTCe limit order

> Caused by: java.lang.NullPointerException: null
>         at org.knowm.xchange.btce.v3.service.polling.BTCEBasePollingService.checkResult(BTCEBasePollingService.java:40)
>         at org.knowm.xchange.btce.v3.service.polling.BTCETradeServiceRaw.placeBTCEOrder(BTCETradeServiceRaw.java:65)
>         at org.knowm.xchange.btce.v3.service.polling.BTCETradeService.placeLimitOrder(BTCETradeService.java:79)
> ...

here is the place, where it happens:
https://github.com/timmolter/XChange/blob/develop/xchange-btce/src/main/java/org/knowm/xchange/btce/v3/service/polling/BTCETradeServiceRaw.java#L63
the call btce.Trade simply returns a null object, how is that possible?
here i would expect from the rescu proxy either an exception or an instance of type  BTCEPlaceOrderReturn.

@mmazi  any idea, how it can come to a null reference here?

**Comment by mmazi** [comment]
Rescu will return `null` if the response body is empty.

Do you get any more relevant information in the log before the stack trace? If not, try setting up rescu to log more in your logback.xml (if you use Logback, otherwise the appropriate logging config file):

    <logger name="si.mazi.rescu" level="trace"/>

**Comment by andre77** [comment]
@mmazi cool, thanks for fast reply
as far i have found the place, you are talking about:
https://github.com/mmazi/rescu/blob/develop/src/main/java/si/mazi/rescu/ResponseReader.java#L61

so basically it looks like, BTCe replies with a valid 200 code, but there is "nothing" in the response body, right?
how can that be? i guess, only the guys from BTCe can know the answer... :-(

**Comment by mmazi** [comment]
> as far i have found the place, you are talking about:
> https://github.com/mmazi/rescu/blob/develop/src/main/java/si/mazi/rescu/ResponseReader.java#L61

Yes, that's it.

> so basically it looks like, BTCe replies with a valid 200 code, but there is "nothing" in the response body, right?

It seems so.

> how can that be? i guess, only the guys from BTCe can know the answer... :-(

Or you can get more info from the logs. Does this happen consistently (always or often), or was it a one-off? What do the BTC-e API docs say?

**Comment by andre77** [comment]
i will try to extend the logging, to get more informations
the error happens very rarely, so may be one time per thousand calls, and i can not really reproduce it in my local environment...

here is the BTCe doc: https://btc-e.com/tapi/docs
nothing about an "empty answer"

will try to open a ticket at BTCe support

**Comment by mmazi** [comment]
One in a thousand calls is very low. My view is that you should always expect a certain percentage, definitely one in a thousand or more, API calls to fail with *any* remote API you are using in any of your application. So this has nothing to do with either rescu or BTC-e.

The correct solution then would be to design your application to handle such failures gracefully.

Check out https://www.google.si/search?q=design+for+failure

**Comment by andre77** [comment]
its not a problem at all to handle such an error, i would love to get an exception or the like here...
but here we deal with a very strange server reply, which obviously has the correct status code 200, but no body, such a reply is not documented. my question here is: has the order been placed or not?
i will open a ticket at BTCe for that, may be i will get an answer.

since the problem has nothing to do with rescu or xchange, so it was ok to close the issue

**Comment by mmazi** [comment]
The thing here is that even in some cases when you _do_ get an error -- not an XChange error, but eg. a network error --, you _still_ won't know whether the order has been placed or not. For example, if the network connection drops after you've sent the request but before you received the response, there is no way for you to know whether the server processed the request or not.

So the point here is that the form of the error you get (null, NPE, XChangeException, IOException, ...)  is in fact irrelevant; there will always be cases when you get an error and cannot be sure how to recover.

Such problems are more or less inherent in network communication, or at least extremely hard to prevent. See https://en.wikipedia.org/wiki/Byzantine_fault_tolerance .
