### ISSUE TITLE
importing XChange to Processing

### ISSUE THREAD

**Issue by erikparr** [timmolter/XChange#1353]
Hi, I wanted to try importing XChange into Processing (processing.org) to try some more advanced visualizations. I imported xchange-core-4.1.1-SNAPSHOT library and xchange-yobit-4.1.1-SNAPSHOT. 

First I got an error that it couldn't find slf4j logger so I downloaded that and imported it.

Now I am getting: java.lang.NoClassDefFoundError: si/mazi/rescu/SynchronizedValueFactory

I thought it wanted the mazi rescu library so I got that and imported it but I am still getting the error. Any ideas or suggestions how to get this working is much appreciated.

**Comment by timmolter** [comment]
Sounds like you're missing classes on the classpath. This project uses Maven for handling the dependencies automatically. You'll just have to figure it out for yourself if you want/need to do it manually.

**Comment by EvanCoyle** [comment]
For those irritated by the lazy answer, this particular jar can be found here: 
https://jar-download.com/?detail_search=g%3A%22com.github.mmazi%22+AND+a%3A%22rescu%22+AND+v%3A%222.0.2%22&a=rescu
