### ISSUE TITLE
PollingTradeService.openOrders - currency pair param

### ISSUE THREAD

**Issue by dozd** [timmolter/XChange#1357]
Hi Timmolter,

I looked at `TheRockTradeService.getOpenOrders` and it's not implemented because `currencyPair` is needed. It's same in `ItBitTradeService` - there are all currency pairs loaded. In `BitstampTradeService` there is a "hack" that uses `getExchangeSpecificParameters()`.

What's the correct approach for this? I'd like to make PR for `TheRockTradeService` to implement this method.

**Comment by timmolter** [comment]
I created a demo class for The Rock called "TheRockMetaDataDemo". That's the best way to get the currency pairs for the exchange. Then you can use those pairs to fetch the open orders and combine all the results.

**Comment by dozd** [comment]
Yeah, that's similar to `ItBitTradeService` implementation i pointed out. But my question was more about what's the best approach. The problem I see in this implementation is that API is called many times for retrieval of open orders - API limits can be a problem here (rock has 14 currency pairs). 

Better way is to have a possibility to pass the argument. But I don't like "the Bistamp" way of implementation either.

As it's 3rd exchange (I didn't check many others) that needs this argument - is it possibility to change the interface and add optional arguments to this method?

**Comment by timmolter** [comment]
It would only be possible if the exchange (The Rock) offers an API endpoint that returns all open orders without specifying a currency pair. Do they?

**Comment by dozd** [comment]
No they don't. But I meant changing of `PollingTradeService` interface as `OpenOrders getOpenOrders()` is not sufficient at least for three exchanges.

**Comment by timmolter** [comment]
Ah, ok. So you're proposing to add an additional method in `PollingTradeService` like: `OpenOrders getOpenOrders(CurrencyPair c)`? Or perhaps even something like: `OpenOrders getOpenOrders(OpenOrdersParams p)` like for `getTradeHistory`.

**Comment by dozd** [comment]
Yeah. `OpenOrdersParams` looks like good approach - I like it. If you're ok with that I can propose PR.

**Comment by timmolter** [comment]
Yeah, i think that'd be good.
