### ISSUE TITLE
Streaming?

### ISSUE THREAD

**Issue by risingsun007** [timmolter/XChange#1362]
Would it be too hard to add streaming to this open source project?  For example, Poloniex has a push API

**Comment by timmolter** [comment]
We recently purged all streaming as it was a giant mess. You can look at past snapshots to dig for old code if you want to.

**Comment by risingsun007** [comment]
Thank you, I will have a look.  Why was it a mess though to do streaming?  Was it hard to make a generic function to encompass the different streams?

**Comment by timmolter** [comment]
Yeah, that was tricky. But also many people contributed their own homegrown implementation with different dependencies and ways of doing things, and it became a nightmare to maintain. Lot's of issues kept coming up and there was no way to keep it all maintained and tested and updated.

**Comment by dozd** [comment]
Hello @risingsun007,

I was in need for streaming API as well and noticed that it has been removed from Xchange library. I'm finishing initial draft of the library build on top of Xchange to provide such consolidated streaming API with simplicity and easy to use in mind (using Reactive streams).

What exchange are you interested? I can add it to my library to prove my design is working well.

I think i can release alpha version next week if everything works fine.

**Comment by jheusser** [comment]
@dozd cool, interested to have a look when initial commits are up.

**Comment by dozd** [comment]
@jheusser Initial commits up at https://github.com/bitrich-info/xchange-stream
@risingsun007 poloniex is using wamp protocol - it won't be hard to add, i'll look at it in some time
@timmolter I hope you're fine I named it xchange-stream.

I'm reworking some raw classes into library so large changes can be expected. But I want to follow my initial design. Take a look and tell me what your opinion and what I've forgotten and won't work with another exchanges :-).

**Comment by timmolter** [comment]
@dozd Great name. :) I'm excited for the project!

**Comment by dozd** [comment]
@timmolter When you are planning to release 4.1.1? I'd like to have same version numbers and release it at that time as well. I've made 3 different streaming backends (pusher, wamp, raw websocket) and 4 exchanges and everything works smooth and fine. So I'm happy with that state and ready to release first version.

**Comment by timmolter** [comment]
Cool! I can do it next week.

**Comment by risingsun007** [comment]
@dozd, which exchanges did you include?

**Comment by dozd** [comment]
- okcoin
- bitstamp
- coinmate
- poloniex (only ticker, but rest should be easy)
- rock (will do next)

**Comment by risingsun007** [comment]
@dozd, very well done. :)  I will be interested to see your code.  You might want to look at hitbtc if you get the chance.

**Comment by timmolter** [comment]
@dozd I bumped the version to 4.2.0-SNAPSHOT and did some refactoring. Please update and see if everything is still working for you. I'll put out a release soon.

**Comment by dozd** [comment]
@timmolter So, how's releasing goin? :)

**Comment by timmolter** [comment]
I'll try to get to it this weekend...

**Comment by timmolter** [comment]
@dozd done with release.
