### ISSUE TITLE
Use a proxy for platform communications

### ISSUE THREAD

**Issue by itiroisolo** [timmolter/XChange#1366]
Hi,

I want to all requests to plateforms (like kraken, poloniex, etc), pass by a proxy (with host, login and password).
What can I change in xchange-code (I suppose), to do that ?

**Comment by timmolter** [comment]
Isn't that something you can do at the OS level?

**Comment by jheusser** [comment]
@itiroisolo you could try to override `setSslUri` and `setHost` in the exchange specification or you can override the dns entries via `/etc/nsswitch.conf` and `/etc/hosts`.
