### ISSUE TITLE
XRP balances @ bitstamp

### ISSUE THREAD

**Issue by wvr** [timmolter/XChange#1368]
Bitstamp just added support for XRP using XRP/USD and XRP/EUR orderbooks. Getting the orderbooks work fine, but I'm not seeing XRP balances on the AccountInfo call:

[BitstampBalance.java](https://github.com/timmolter/XChange/blob/develop/xchange-bitstamp/src/main/java/org/knowm/xchange/bitstamp/dto/account/BitstampBalance.java)

**Comment by timmolter** [comment]
That code is probably going to need to be updated. You'll probably have to do it yourself/ A PR would be appreciated.
