### ISSUE TITLE
Add support for Coinfloor Exchange BIST API (Bounty available)

### ISSUE THREAD

**Issue by obi** [timmolter/XChange#1373]
Coinfloor has APIs for users looking to trade programmatically. We require an integration of Coinfloor's BIST API into the XChange library. Coinfloor's BIST API is very similar to the Bitstamp API, so the integration will be similar to the Bitstamp integration in XChange. Links to Coinfloor's BIST API and the Bitstamp implementation in the XChange library can be found below:

[https://github.com/coinfloor/API/blob/master/BIST.md](https://github.com/coinfloor/API/blob/master/BIST.md)
[https://github.com/timmolter/XChange/tree/develop/xchange-bitstamp](https://github.com/timmolter/XChange/tree/develop/xchange-bitstamp)

**There is a bounty for this available:** [https://bountify.co/integrate-coinfloor-s-bist-api-into-the-xchange-library](https://bountify.co/integrate-coinfloor-s-bist-api-into-the-xchange-library)

Please let us know if you have any questions.

**Comment by dozd** [comment]
I can have a look at it.

**Comment by timmolter** [comment]
@dozd Czech Republic is on the list.

**Comment by dozd** [comment]
@timmolter Only as nationality (left), not residency (right). So I cannot finish my account. I wanted to register for this exchange some time ago.

**Comment by obi** [comment]
Our Compliance team has reviewed and have found no reason not to include the Czech Republic as an allowed residency.  We will be modifying our policy and including this in the coming few days.

**Comment by obi** [comment]
Hi.  We have now updated our policies (support page update coming later) to allow for residents of the Czech Republic (assuming that they pass our KYC processes).

**Comment by ww3456** [comment]
This never got implemented while the bounty was open but I've just raised pull request #1408 to add the functionality.

**Comment by timmolter** [comment]
Done: https://github.com/timmolter/XChange/pull/1408
