### ISSUE TITLE
Feature Design Documentation 

### ISSUE THREAD

**Issue by datasmithtech** [timmolter/XChange#1403]
I don't seem to find any documentation that describes valid / typical values for entity attributes, such as the many attributes for site_user, or other classes.

I am very interested in contributing, however, it would be helpful if some sample json data for different classes was available to enable newcomers to be able to hit the ground running..

**Comment by timmolter** [comment]
What do you mean `site_user`?

**Comment by datasmithtech** [comment]
I found references to site_user in php code, such as 
$sql = "SELECT id FROM bank_accounts WHERE account_number = {$row['account']} AND site_user = {$row['site_user']}";

not sure what corresponding java class is, or where the database sql scripts are, or the configuration files for the exchange..

**Comment by timmolter** [comment]
Neither php nor SQL has anything to do with XChange.

**Comment by datasmithtech** [comment]
sorry, bad example of an Xchange class - i must have found another project which referenced Xchange. 

Is there documentation that describes the Xchange classes in detail?

**Comment by datasmithtech** [comment]
also, is there a configuration file that I should be using when i am running XChange?
