### ISSUE TITLE
Example is wrong?

### ISSUE THREAD

**Issue by rok-povsic** [timmolter/XChange#1405]
The example on [the example page](http://knowm.org/open-source/xchange/xchange-example-code/) uses `PollingMarketDataService` and `getPollingMarketDataService()`, but I've only found `MarketDataService` and `getMarketDataService()` in 4.2.0.

Is that a bug in the example code?

**Comment by timmolter** [comment]
Thanks for pointing that out. Yes, I need to update that page on knowm.org. I'll close this ater I got it all updated.

**Comment by rok-povsic** [comment]
Also, the `getBitstampTicker()` call on `BitstampMarketDataServiceRaw` is deprecated.

**Comment by timmolter** [comment]
done.
