### ISSUE TITLE
Support bitFlyer

### ISSUE THREAD

**Issue by jheusser** [timmolter/XChange#1410]
A lot of volume, free trading, good API: https://lightning.bitflyer.jp/docs?lang=en

**Comment by lukaszaoralek** [comment]
@jheusser 
I've just written PR with bitflyer websocket support https://github.com/bitrich-info/xchange-stream/pull/27. You can try/test it if it's still actual for you

**Comment by timmolter** [comment]
Closing as duplicate of: <https://github.com/timmolter/XChange/issues/1959>
