### ISSUE TITLE
BitFinex order id overflow

### ISSUE THREAD

**Issue by Panchen** [timmolter/XChange#1412]
BitFinex raw code uses int for storing order id's. E.g. BitfinexOrderStatusResponse 
Order ID's for BTCUSD on BitFinex have recently gone above max value for java int 2,147,483,647.

com.xeiam.xchange.bitfinex.v1.service.polling.BitfinexTradeServiceRaw.getBitfinexOpenOrders therefore now throws a "Numeric value (2149xxxxxx) out of range of int" exception when returning any open orders for a user.

Potentially same issue for other Bitfinex_...._Response DTO classes. E.g. BitfinexOfferStatusResponse

**Comment by jheusser** [comment]
@Panchen believe this has already been fixed, could you check with latest develop branch?
https://github.com/timmolter/XChange/pull/1409

**Comment by Panchen** [comment]
@jheusser thanks. Tested latest dev branch vs BitFinex this am and confirmed fixed.
Couldn't find an issue for above and missed #1409
