### ISSUE TITLE
What could cause the INVALID_MARKET exception?

### ISSUE THREAD

**Issue by bitsol** [timmolter/XChange#1414]
Following the example code for [the Bittrex marketdata demo](https://github.com/timmolter/XChange/blob/develop/xchange-examples/src/main/java/org/knowm/xchange/examples/bittrex/v1/marketdata/BittrexMarketDataDemo.java), the exchange responds with a disappointing HTTP message. Here's the exception:

`Exception in thread "main" si.mazi.rescu.HttpStatusIOException: Can not construct instance of org.knowm.xchange.bittrex.v1.dto.marketdata.BittrexTickerResponse, problem: null
 at [Source: {"success":false,"message":"INVALID_MARKET","result":null}; line: 1, column: 58]`

Is this reproducible on someone else's machine? Am I doing something wrong?

Thanks in advance!

**Comment by jheusser** [comment]
@bitsol maybe you're making a request  for a currency pair which does not exist?

**Comment by bitsol** [comment]
@jheusser I was using the exact code in the Bittrex demo. This is odd, because using the same currency pair in the code for [the BTC-e ticker demo](https://github.com/timmolter/XChange/blob/develop/xchange-examples/src/main/java/org/knowm/xchange/examples/btce/marketdata/BTCETickerDemo.java) works to return the orderbook object.

**Comment by adneerav** [comment]
Hello 

I am facing the same issue.

```
Exchange bitRex = ExchangeFactory.INSTANCE.createExchange(BittrexExchange.class.getName());
			ExchangeSpecification exchangeSpecification = bitRex.getDefaultExchangeSpecification();
			exchangeSpecification.setApiKey(BITREX_API_KEY);
			exchangeSpecification.setSecretKey(BITREX_SECRETE_KEY);
			bitRex.applySpecification(exchangeSpecification);
			MarketDataService marketDataService = bitRex.getMarketDataService();
			Ticker ticker = marketDataService.getTicker(new CurrencyPair("BTC", "1ST"));
			System.out.println(ticker.toString());
```

I've tried with valid API & secret key. And also tried the same which is given in sample demo but still the same issue.

Below I've given console output

> [main] INFO org.knowm.xchange.bittrex.v1.BittrexExchange - Calling Remote Init...
> [main] INFO org.knowm.xchange.bittrex.v1.BittrexExchange - Calling Remote Init...
> si.mazi.rescu.HttpStatusIOException: Can not construct instance of org.knowm.xchange.bittrex.v1.dto.marketdata.BittrexTickerResponse, problem: null
>  at [Source: {"success":false,"message":"INVALID_MARKET","result":null}; line: 1, column: 58]
> 	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:104)
> 	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:169)
> 	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:157)
> 	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:120)
> 	at com.sun.proxy.$Proxy16.getTicker(Unknown Source)
> 	at org.knowm.xchange.bittrex.v1.service.BittrexMarketDataServiceRaw.getBittrexTicker(BittrexMarketDataServiceRaw.java:58)
> 	at org.knowm.xchange.bittrex.v1.service.BittrexMarketDataService.getTicker(BittrexMarketDataService.java:41)
> 	at main.MainClass.printTickerBitRex(MainClass.java:46)
> 	at main.MainClass.main(MainClass.java:34)

Here its API giving a proper response: 

[https://bittrex.com/api/v1.1/public/getmarketsummary?market=BTC-1ST](https://goo.gl/tJMZqk)

values are passing as per bittrex documentation: https://bittrex.com/Home/Api

Can anyone please help in this?

What else change or anything I need to manage?

**Comment by bitsol** [comment]
Any updates on this?

**Comment by devsatish** [comment]
Any luck getting over this bug?

**Comment by npomfret** [comment]
INVALID_MARKET usually means you're passing the wrong currency pair in the http request.  It's possible the demo is broken.  Are you seeing this in places other than the demo?

**Comment by devsatish** [comment]
Yep..not just the demo.  Just did some debugging and found that the BittrexUtils.toPairString is causing it.  ` public static String toPairString(CurrencyPair currencyPair) {
    return currencyPair.counter.getCurrencyCode().toUpperCase() + "-" + currencyPair.base.getCurrencyCode().toUpperCase();
  }`

I guess its because of not properly constructed CurrencyPair object param.

My Request was like this:
` CurrencyPair cp = new CurrencyPair("btc", "ltc");
    List<BittrexUserTrade> lt = serviceRaw.getBittrexTradeHistory(cp);`

**Comment by npomfret** [comment]
Use the currency pairs constants.

**Comment by psuchecki** [comment]
Looks like:
`BittrexUtils.toPairString`
Is sending inverted pair instead of BTC-DOGE it returns DOGE-BTC. Just use:
`Ticker ticker = marketDataService.getTicker(new CurrencyPair(Currency.DOGE, Currency.BTC));`
and it works.
