### ISSUE TITLE
Poloniex CurrencyPair

### ISSUE THREAD

**Issue by Saloed123** [timmolter/XChange#1418]
```
private static Exchange poloniex;
private static CurrencyPair currencyPair;
public void start(){
                   poloniex = ExchangeFactory.INSTANCE.createExchange(PoloniexExchange.class.getName());
                    MarketDataService dataService = poloniex.getMarketDataService();
                    currencyPair = new CurrencyPair(Currency.XMR, Currency.BTC);
}
```
^^^this work fine, but
` 
public void start(){                  
                    poloniex = ExchangeFactory.INSTANCE.createExchange(PoloniexExchange.class.getName());
                    MarketDataService dataService = poloniex.getMarketDataService();
                    currencyPair = new CurrencyPair(Currency.BTC, Currency.USD);
}`

 org.knowm.xchange.exceptions.ExchangeException: BTC/USD not available

**Comment by Achterhoeker** [comment]
@Saloed123 I don't know what you are going to do with the btc/usd pair. But using on poloniex will not work. They don't have fiat currencies (like usd or eur)

**Comment by timmolter** [comment]
Thanks @Achterhoeker
