### ISSUE TITLE
Clean up diceased exchanges

### ISSUE THREAD

**Issue by altmind** [timmolter/XChange#1421]
It seems that some of implemented exchanges are defunct, their websites are offline or parked and I dont hear of them recently:
Atlas ATS
BitKonan
BTC38
LoyalBit
meXBT
Yacuna

Can we at least think what we should do with the implementations? Delete them, move to contrib, leave as as and just update docs?

**Comment by timmolter** [comment]
I've always just deleted them. Thanks for the heads up. It looks like BTC38 is still alive though.

**Comment by timmolter** [comment]
I removed LoyalBit and BitKonan. Besides BTC38, the other ones were already removed apparently.
