### ISSUE TITLE
xchange's poloniex example failure.

### ISSUE THREAD

**Issue by xy120303102** [timmolter/XChange#1422]
hello,I use vpn to run xchange's poloniex example:"PoloniexMarketDataDemo", then I receive a string,it is html layout,I put the string to a text,and open it with chrome browser,then I know the string's mean is:
"One More Step,Please complete the security check to proceed."
I use vpn is Shadowsocks,is xchange can not use under vpn?

**Comment by altmind** [comment]
It looks like you got cloudflare captcha page in response.
I think you should ask this question to poloniex. Normally, you should expect that if you use authentication on exchange, your requests should not be filtered.
