### ISSUE TITLE
Bitfinex: support maker/taker fees

### ISSUE THREAD

**Issue by ezhik97** [timmolter/XChange#1424]
Make possible to obtain maker/taker fees for account.

**Comment by ezhik97** [comment]
Infos available via
```
BigDecimal BitfinexTradeService.getMakerFee()
BigDecimal BitfinexTradeService.getTakerFee()
```

**Comment by ezhik97** [comment]
Please, merge my pull request.

**Comment by timmolter** [comment]
Did you see my comment here: https://github.com/timmolter/XChange/pull/1426

**Comment by ezhik97** [comment]
Hm, no, I still not see any comments there except my one.

**Comment by timmolter** [comment]
nevermind. I make a mistake anyway. Merged.

**Comment by ezhik97** [comment]
Thanks a lot :)
