### ISSUE TITLE
Okcoin batch trade question

### ISSUE THREAD

**Issue by wuqianming** [timmolter/XChange#1434]
Okcoin API support batch trade, is it available with xchange?

# Request
POST https://www.okcoin.com/api/v1/batch_trade.do
# Response
{
	"order_info":[{price:3,amount:5,type:'sell'},{price:3,amount:3,type:'buy'}] ,
	"result":true
}

**Comment by jheusser** [comment]
Not implemented. Also the XChange API does not really support submitting
batch trades.

**Comment by wuqianming** [comment]
thank you @jheusser

**Comment by jheusser** [comment]
Closing this for now.
