### ISSUE TITLE
Asynchronous I/O based on NIO

### ISSUE THREAD

**Issue by andre77** [timmolter/XChange#1448]
Hi,

we are using XChange library to connect to multiple exchanges using multiple api keys, so at the end we have a mass of parallel connections, where most of them are simply waiting for server response.
Due to this fact we have a high load average, since every waiting connection is blocking a thread.
I'm not sure, if it is a problem at all, since the cpu is not overstressed, when threads are waiting. But still it feels not very comfortable.

Just stumbled upon NIO, like for example [here](https://hc.apache.org/httpcomponents-core-ga/tutorial/html/nio.html)

What do you think, would it be possible to change the connection handling to NIO. Looking into rescu documentation, i did not see any hints for that.

Cheers
andre

**Comment by hleb-albau** [comment]
I just wondering about same idea too.

**Comment by br0x** [comment]
Better left it as is. You don't want to spend money before knowing exact state after previous request. As for public informational API calls like ticker, I created several accounts on exchange and run these request in parallel - this really helps

**Comment by andre77** [comment]
@br0x its up to you, to "wait" for a call to finish before you continue...
i guess, you missed the point

**Comment by br0x** [comment]
Oh, I believe I got you now. You mean we could use result listeners. This would help

**Comment by timmolter** [comment]
Sounds like premature optimization to me (https://softwareengineering.stackexchange.com/questions/80084/is-premature-optimization-really-the-root-of-all-evil) If it's working fine, like you say it is, then it could actually do more harm then good. I haven't heard of any issues with rescu yet either, but if people are having actual legit issues, they should definitely be addressed, but in a manner targeting a specific problem.
