### ISSUE TITLE
LTC/BTC pair not working

### ISSUE THREAD

**Issue by FarscoreDev** [timmolter/XChange#1456]
I've been trying to use the LTC/BTC pair but it doesn't seem to work at all.

Is this just for me, or?

**Comment by Achterhoeker** [comment]
@FarscoreDev Which xchange and with which function ?

**Comment by FarscoreDev** [comment]
I've tried Bittrex, YoBit, Bitfinex, BTCE and Poloniex with the LTC/BTC pair on the .getTicker(CurrencyPair.LTC_BTC). Doesn't work.

**Comment by Achterhoeker** [comment]
@FarscoreDev If I run the ticker example from btce with LTC_BTC it runs without any problems. Can you also try this example ? (xchange.examples.btce.marketdata.BTCETickerExample.java)
Only modification i made was for LTC_BTC

17:21:25.131 [default] [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating default exchange from class name 
17:21:25.163 [default] [main] DEBUG org.knowm.xchange.ExchangeFactory - Creating default exchange from class name 
17:21:25.939 [default] [main] DEBUG o.knowm.xchange.btce.v3.BTCEExchange - org.knowm.xchange.btce.v3.dto.meta.BTCEMetaData@534df152 
17:21:26.038 [default] [main] INFO  o.knowm.xchange.btce.v3.BTCEExchange - Calling Remote Init... 
Last: 0.01873
Volume: 255632.19925
High: 0.01977
Low: 0.01677
Ticker [currencyPair=LTC/BTC, last=0.01873, bid=0.01871, ask=0.01873, high=0.01977, low=0.01677,avg=0.01827, volume=255632.19925, timestamp=1494170496000]
