### ISSUE TITLE
Running examples without compiling

### ISSUE THREAD

**Issue by abitrolly** [timmolter/XChange#1467]
Is it possible to run examples with just JRE by downloading them from some binary site? Is there such thingas all-in-one bundle with all dependencies so that examples could be more easily executed?

**Comment by timmolter** [comment]
You could download the `xchange-examples` module and run the examples from the command line.

**Comment by abitrolly** [comment]
And where can I download it? (sorry, I am not from Java world)

**Comment by abitrolly** [comment]
Nevermind. Found them by following links in README.md http://search.maven.org/#search%7Cga%7C1%7Cknowm%20xchange
