### ISSUE TITLE
Add Rep as currency

### ISSUE THREAD

**Issue by golikcoin** [timmolter/XChange#1469]
in Currency.java

 public static final Currency REP= createCurrency("REP", "Augur",null);

and CurrencyPair.java
  public static final CurrencyPair BTC_REP = new CurrencyPair(Currency.BTC, Currency.REP);
  public static final CurrencyPair ETH_REP = new CurrencyPair(Currency.ETH, Currency.REP);

**Comment by richardflint** [comment]
Augur (REP) has been added as via this PR https://github.com/timmolter/XChange/pull/1501
