### ISSUE TITLE
Time outs on polo requests

### ISSUE THREAD

**Issue by Achterhoeker** [timmolter/XChange#1470]
Currently my bot is suffering a lot off bans from poloniex.
From this thread https://www.reddit.com/r/BitcoinMarkets/comments/6b9f0p/poloniex_banning_trading_bots_ips_despite_call/ I understand that we need to time out from the remote side and not on our own side. 
Question: Is xchange timing out remotely or locally ? (And if local, how can I increase this timeout value?)

(My bot is max placing 1 request per second on Poloniex)

**Comment by timmolter** [comment]
https://github.com/mmazi/rescu

There you will see how to set the timeout.

**Comment by whitfa99** [comment]
Hopefully this is related, but XChange is returning an org.knowm.xchange.exceptions.ExchangeException when I send a tradeService.placeLimitOrder.  The Exception is no more explicit than this, yet in most cases the order has actually gone through.  I'm assuming that this has to do with Poloniex's current scaling and attack problems, but should there be a way I can tell if the order was submitted or not from the LimitOrder?


I will try to set the read timeout as above, but not sure how to tell if the classpath picked up the new value in my groovy code.

Stack trace:
<trace-array>
	<trace>org.knowm.xchange.poloniex.service.PoloniexTradeServiceRaw.orderEntry(PoloniexTradeServiceRaw.java:97)</trace>
	<trace>org.knowm.xchange.poloniex.service.PoloniexTradeServiceRaw.buy(PoloniexTradeServiceRaw.java:58)</trace>
	<trace>org.knowm.xchange.poloniex.service.PoloniexTradeService.placeLimitOrder(PoloniexTradeService.java:86)</trace>
	<trace>sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)</trace>
	<trace>sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)</trace>
	<trace>sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)</trace>
	<trace>java.lang.reflect.Method.invoke(Method.java:498)</trace>
	<trace>org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:229)</trace>
	<trace>org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:52)</trace>
	<trace>org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124)</trace>
	<trace>Script1.run(Script1.groovy:172)</trace>
	<trace>com.rapidminer.operator.ScriptingOperator.doWork(ScriptingOperator.java:123)</trace>
	<trace>com.rapidminer.operator.Operator.execute(Operator.java:866)</trace>
	<trace>com.rapidminer.operator.execution.SimpleUnitExecutor.execute(SimpleUnitExecutor.java:51)</trace>
	<trace>com.rapidminer.operator.ExecutionUnit.execute(ExecutionUnit.java:711)</trace>
	<trace>com.rapidminer.operator.OperatorChain.doWork(OperatorChain.java:375)</trace>
	<trace>com.rapidminer.operator.SimpleOperatorChain.doWork(SimpleOperatorChain.java:61)</trace>
	<trace>com.rapidminer.operator.Operator.execute(Operator.java:866)</trace>
	<trace>com.rapidminer.operator.execution.SimpleUnitExecutor.execute(SimpleUnitExecutor.java:51)</trace>
	<trace>com.rapidminer.operator.ExecutionUnit.execute(ExecutionUnit.java:711)</trace>
	<trace>com.rapidminer.operator.collections.CollectionIterationOperator.doWork(CollectionIterationOperator.java:111)</trace>
	<trace>com.rapidminer.operator.Operator.execute(Operator.java:866)</trace>
	<trace>com.rapidminer.operator.execution.SimpleUnitExecutor.execute(SimpleUnitExecutor.java:51)</trace>
	<trace>com.rapidminer.operator.ExecutionUnit.execute(ExecutionUnit.java:711)</trace>
	<trace>com.rapidminer.operator.collections.CollectionIterationOperator.doWork(CollectionIterationOperator.java:111)</trace>
	<trace>com.rapidminer.operator.Operator.execute(Operator.java:866)</trace>
	<trace>com.rapidminer.operator.execution.SimpleUnitExecutor.execute(SimpleUnitExecutor.java:51)</trace>
	<trace>com.rapidminer.operator.ExecutionUnit.execute(ExecutionUnit.java:711)</trace>
	<trace>com.rapidminer.operator.OperatorChain.doWork(OperatorChain.java:375)</trace>
	<trace>com.rapidminer.operator.Operator.execute(Operator.java:866)</trace>
	<trace>com.rapidminer.Process.run(Process.java:949)</trace>
	<trace>com.rapidminer.Process.run(Process.java:873)</trace>
	<trace>com.rapidminer.Process.run(Process.java:832)</trace>
	<trace>com.rapidminer.Process.run(Process.java:827)</trace>
	<trace>com.rapidminer.Process.run(Process.java:817)</trace>
	<trace>com.rapidminer.gui.ProcessThread.run(ProcessThread.java:63)</trace>
</trace-array>

**Comment by Achterhoeker** [comment]
@whitfa99 I'm currently running my bot set with a time out set on 90 seconds. (default was 30 seconds) The exceptions you posted looks familiair. But sometimes i had also http code from poloniex in my error file. That http code sad that my ip was blocked. Thats why i looked for similar problems and found that thread on reddit. But Poloniex is at this moment not reliable. 
I'll update this post tomorrow with the results with 90 seconds.

**Comment by whitfa99** [comment]
Just after my last post I set the read timeout to 2 mins (!), and also 1000 millis between calls and I've not had any such exceptions since.

**Comment by Achterhoeker** [comment]
@whitfa99 With my timeout off 90 seconds i didn't see those exceptions either. So it seems to work better this way. (I did see some delays for +/- 40 seconds placing orders on Polo, but it was successful.)
@timmolter I assume this ticket can be closed now. (or do you want to keep it open as information for others?)

**Comment by timmolter** [comment]
Thanks. Let's keep it closed. People googling it will still be able to find it.
