### ISSUE TITLE
Filenames with trailing whitespace in stable branch

### ISSUE THREAD

**Issue by abitrolly** [timmolter/XChange#1475]
```
$ git clone --branch xchange-4.2.0 https://github.com/timmolter/XChange
$ find XChange/ -iname "* "
XChange/xchange-livecoin/api-specification.txt 
XChange/xchange-yobit/api-specification.txt 
```
Git is unable to handle these files on Windows.

**Comment by abitrolly** [comment]
Fixed in `develop` by https://github.com/timmolter/XChange/commit/430e7dd2229def52b1b134eac1c2c4eb285253f3#diff-13168082187878f15b3ebc3759086577

Is there any chance to get this into `stable`? Or when the new release is planned?

**Comment by timmolter** [comment]
I could do a release, but why can't you build your own jar for now? `mvn clean install`

**Comment by abitrolly** [comment]
I can do jars, but git fails to commit my modifications to repository.

**Comment by timmolter** [comment]
You should be able to check out any commit on `develop` you want and then build a jar.

**Comment by abitrolly** [comment]
Yes. I'll wait for a new release. Looks like there is no `stable` branch, so cherrypicking from `develop` seems like the right strategy.

**Comment by timmolter** [comment]
I'll try to get a release out soon. The stable branch is `master`. the problem is, and what makes this project unique, is that the bitcoin exchanges are a constantly moving target, so nothing is really ever stable. it's unfortunate, but the way it is.

**Comment by abitrolly** [comment]
So maybe there is no need to keep `develop` at all then? Keep master always stable and let features mature in branches/PRs?
