### ISSUE TITLE
Network connection requirements

### ISSUE THREAD

**Issue by abitrolly** [timmolter/XChange#1476]
How does XChange maintain network connections? It looks like a polling library.
Does XChange open a new connection on each polling request?
Is there a mode that maintains an open connection for polling?

Is there a subscription mode where exchange pushes notifications to XChange client? Does such subscription / push require an active connection established by client to server?

I am trying to figure out the most effective way to interact with markets without hammering them down.

**Comment by jheusser** [comment]
@abitrolly XChange is polling only, so poll requests should be done in a way which respects the polling quotas of the exchanges you connect to. XChange is using rescu as REST library, check its connectivity/serialisation settings.
