### ISSUE TITLE
Kraken returning only 1000 trade records per call..

### ISSUE THREAD

**Issue by whitfa99** [timmolter/XChange#1483]
.. regardless of whether I use 

    marketDataService.getTrades(args)

with a since(lastID) arg or not, it only returns a max of 1000 records.

Is this limitation with Kraken, or with a setting in the library (I couldn't find anything in the code)?

Now that the volume is pretty high I'm finding that this limitation is becoming a problem.

**Comment by timmolter** [comment]
You'll have to look at the code and Kraken's API documentation.

**Comment by whitfa99** [comment]
I have looked through the XChange code and I think visiting [this link](https://api.kraken.com/0/public/Trades?pair=XXBTZEUR&since=0) proves that the limitation is from the Kraken end.  I will ask them to increase and see how I fare.

**Comment by timmolter** [comment]
yes, it's a limit on Kraken's end.
