### ISSUE TITLE
Quoine: can't get BTC Balance

### ISSUE THREAD

**Issue by JojoSc** [timmolter/XChange#1485]
The following code returns 0 BTC, even though I have a non-zero balance on the exchange:

```
AccountService accountService = exchange.getAccountService();
accountService.getAccountInfo().getWallet().getBalance(Currency.BTC)
```

The same code works fine with fiat currencies.
I'm using the 4.2.1-Snapshot

**Comment by jheusser** [comment]
@JojoSc Try latest develop version, should work.

**Comment by npomfret** [comment]
I'm in the process of fixing this (it's not actually implemented).

Having a little trouble with the auth though, getting a 401 for some reason.

**Comment by timmolter** [comment]
Is this now fixed?

**Comment by npomfret** [comment]
Yep
