### ISSUE TITLE
[Bitstamp] Order Type is wrong when there is a very small transaction fill. 

### ISSUE THREAD

**Issue by kisapmata** [timmolter/XChange#1512]
This case is triggered by bitstamp rounding issue. If they have very small BTC partial fills, the USD settlement amount returned by the json object is rounded off to ZERO. Example below shows very small BTC fill and the settlement amount become 0.00 instead of 0.0000172472 (btc_usd*btc). 

{"usd": "0.00", "btc_usd": 1724.72000000, "order_id": 5863279, "datetime": "2017-05-15 09:43:04", "fee": "0.01", "btc": "-0.00000001", "type": "2", "id": 14830786, "eur": 0.0}

thus, the adaptTradeHistory() checking below will result to BID instead of ASK.

OrderType orderType = t.getCounterAmount().doubleValue() > 0.0 ? OrderType.ASK : OrderType.BID;

**Comment by timmolter** [comment]
I'm on vacation, will reply when i get back...
