### ISSUE TITLE
[Bitfinex] json Exception Format has change for exceeding rate limit.

### ISSUE THREAD

**Issue by kisapmata** [timmolter/XChange#1513]
as per their notification, they are sending this out JSON response{ "error": "ERR_RATE_LIMIT" } 

On February 21st and 22nd Bitfinex was the target of a distributed denial-of-service (DDoS) attack that disrupted service for some users.
...
...
If an IP address exceeds 90 requests per minute to the REST APIs, the requesting IP address will be blocked for 10-60 seconds and the JSON response{ "error": "ERR_RATE_LIMIT" } will be returned. Please note the exact logic and handling for such DDoS defenses may change over time to further improve reliability.

**Comment by kisapmata** [comment]
adding below works fine without breaking anything. This simply maps the error to getMessage if applicable.

  @JsonProperty("error")
  private String error;

  public String getMessage() {
    return message==null?error:message;
  }

**Comment by timmolter** [comment]
Please consider creating a pull request with the fix. It'd be highly appreciated!
