### ISSUE TITLE
 [Bitstamp] add function to get order status for bitstamp. (just like bitfinex)

### ISSUE THREAD

**Issue by kisapmata** [timmolter/XChange#1519]
We currently have no implementation for this bitstamp API. This is useful for reconciliation of individual trades.

ORDER STATUS
This call will be executed on the account (Sub or Main), to which the used API key is bound to.

Request
POST	https://www.bitstamp.net/api/order_status/

**Comment by timmolter** [comment]
Could you submit a PR for this? It looks like you perhaps fixed it on your own fork.
