### ISSUE TITLE
[Gemini] Ticker doesn't work due to wrong object structure. Also Gemini prefer user of timestampms instead of timestamp field

### ISSUE THREAD

**Issue by kisapmata** [timmolter/XChange#1520]
issue 1:
The GeminiTicker object doesn't match the json format (specs)

----Object----
public class GeminiTicker {
  private final BigDecimal mid;
  private final BigDecimal bid;
  private final BigDecimal ask;
  private final BigDecimal high;
  private final BigDecimal low;
  private final BigDecimal last;
  private final BigDecimal volume;
  private final float timestamp;

----Gemini Specs-----
Field	Type	Description
bid	decimal	The highest bid currently available
asks	decimal	The lowest ask currently available
last	decimal	The price of the last executed trade
volume		Information about the 24 hour volume on the exchange. See below
The volume field will contain information about the 24 hour volume on the exchange. The volume is updated every five minutes based on a trailing 24-hour window of volume. It will have three fields

Field	Type	Description
timestamp	timestampms	The end of the 24-hour period over which volume was measured
(price symbol, e.g. "USD")	decimal	The volume denominated in the price currency
(quantity symbol, e.g. "BTC")	decimal	The volume denominated in the quantity currency

issue 2: from Gemini (https://docs.gemini.com/rest-api/):
Timestamp
We recommend that you use the timestampms field if you are implementing against our API. The timestamp field is included for compatibility with Bitfinex, but the behavior is inconsistent; sometimes it's an integer, sometimes it has a decimal point, and other times it is returned as a string.

**Comment by timmolter** [comment]
fixed here: https://github.com/timmolter/XChange/pull/1518 ?

**Comment by kisapmata** [comment]
i see ok. ill close this issue.
