### ISSUE TITLE
[ItBIt] ticker, depth, trades and placelimitorder should handle Currency BTC (not just XBT)

### ISSUE THREAD

**Issue by kisapmata** [timmolter/XChange#1521]
Not sure if this is a feature request, but existing Kraken code is able to handle this case. ITBIT exchange recognizes only XBT, therefore sending BTC when requesting ticks, depth, trades history or placing limit order will throw error of symbol not recognized/supported.

**Comment by timmolter** [comment]
I guess you have to know to use the XBT symbol for bitcoin when using ItBit. It's unfortunate that bitcoin has two symbols.

**Comment by kisapmata** [comment]
i think you need to reconsider this as I found below is same issue already merged to develop.
 [https://github.com/timmolter/XChange/pull/1359](url). Basically just a bit more change to complete it. I will raise a PR and its up to you if u want to reject it.
