### ISSUE TITLE
CEX IO error: Error getting balance. Nonce must be incremented

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#1524]
Does anyone know what to do when getting this error from the `CexIOExchange`?

`Error getting balance. Nonce must be incremented`

**Comment by michaelscheung** [comment]
(Sorry to revive an old issue) @npomfret what was the solution to this? I'm experiencing this on every private API call with CexIOExchange. Currently using 4.3.5

**Comment by alex75it** [comment]
In that case you have to use a an API key for every instance.
