### ISSUE TITLE
QuadrigaCx - adapt currency is "lower-casing" CCY name

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#1525]
All the currency names defined are in uppercase.  The QuadrigaCx doesn't return _uppercased_ currencies (see `QuadrigaCxBalance.java` for example).  It's inconsistent with the other apis

**Comment by timmolter** [comment]
Is this still an issue?

**Comment by npomfret** [comment]
I'll get back to you.  I can't quite remember the issue.  I think when getting information out of the exchange the cry pairs were all lowercased.  But I'm pretty sure its ok now

**Comment by npomfret** [comment]
Please close, I can't reproduce.

**Comment by npomfret** [comment]
Sorry, yes it's still a problem.  I will fix now.

**Comment by npomfret** [comment]
Fixed https://github.com/timmolter/XChange/pull/1689/commits/37325cb0c545e363203cd798d06b0c2912752b18
