### ISSUE TITLE
Hi How can we use XChange in Html/css 

### ISSUE THREAD

**Issue by sajidsrq** [timmolter/XChange#1526]
How ca n we full the request from API from HTMl/CSS

**Comment by jheusser** [comment]
Not to sound snarky, but how can you expect an answer to this question? Could you try to reformulate it more clearly please.

**Comment by e1ektr0** [comment]
For using xchange from html/css you should write extracode for rest server that will provide api for working with xchange.

**Comment by sajidsrq** [comment]
Hi, I am new to it could you please tell me how to write extra code and how can I use it in my code. please provide me details like any URL hit or any other .DLL etc..

**Comment by sajidsrq** [comment]
What and how much  extra code I have to right it for rest server
