### ISSUE TITLE
Poloniex Base and Counter Currency Pair issue

### ISSUE THREAD

**Issue by SeanRobb** [timmolter/XChange#1528]
It looks like the base and counter currency pair have changed in commit 62e027a54ed641ebb545f47ae0b4622882367438.

I am now having issues with retrieving Ticker information from Poloniex. The api call works well but the values are way off.  I was wondering why this was done?

**Comment by timmolter** [comment]
Whoops. That's happened before and I forgot about it. Does anyone know why people keep submitting PRs with the bas and counter switched for poloniex?

**Comment by douggie** [comment]
Nope, I am using polinex without issue the base and counter are the right
way round.

**Comment by timmolter** [comment]
@douggie With the latest develop branch including the last change to Poloniex?

**Comment by douggie** [comment]
I am one comit behind. Will check the number a bit later.

**Comment by SeanRobb** [comment]
I started having the problem yesterday and it went away when I rolled back to a different snapshot of the same version in the project so I looked in the recent commits and saw that this was the only change.  Thank you @timmolter for your quick response and I just wanted to make you aware of the change that appears to return incorrect ticker values.

**Comment by odaken** [comment]
I vote for @SeanRobb. I am also suffered getting ticker with error by the last change. I am getting tickers from several exchanges but the change was inconsistent with other exchanges.

**Comment by douggie** [comment]
Hi,

I am using the branch with the last comitt of
3c0dcb07f2584609c1b86e3d04184c0db601690b
without issue.

**Comment by douggie** [comment]
PR https://github.com/timmolter/XChange/pull/1533 submitted

**Comment by timmolter** [comment]
OK, I'm going to look into this today and finalize a solution....

**Comment by douggie** [comment]
I can't see why the need to reverse them. I thought it might be that
polonix provides inverse currencies i.e. eth.btc as well as btc.eth but
that does not seem the case.

**Comment by timmolter** [comment]
The thing is, I keep getting pull requests that keep flipping the base and counter. I believe from what I saw, you are correct, but I want to 100% verify it and convince myself so I can correctly handle future pull requests that flip things.

**Comment by timmolter** [comment]
Addressed in commit: 55658f3a8a933c1dde2f92ec5a7e835584985a58

**Comment by douggie** [comment]
I think the comit has broken USD tether as we now have :

currencyPair.counter.getCurrencyCode().replace("USD","USDT").toUpperCase()

Submitted a PR to fix
Support currencies:
https://poloniex.com/public?command=returnCurrencies

**Comment by Achterhoeker** [comment]
@timmolter The pairs are now always swapped after this cr ? That will give troubles with the minimal trade size. It was 1.0e-e for the old base coins (most btc) Now that minimum must be used for the counter coin. That is complete different from all other xchanges.

**Comment by timmolter** [comment]
@Achterhoeker The currency pair is now like on every other exchange as far as my research led me to believe. Where is the minimal trade defined? Can you change that?

**Comment by douggie** [comment]
I believe the minimal trade size on polonix is 0.2. May be try to place the
same order manually via the web interface to see if it is correct. The
current branch is consistent with other exchanges in xchange so may be your
code is getting the couter and base round the wrong way. Have you tried
another xchange exchange is the issue consistent?

**Comment by Achterhoeker** [comment]
@timmolter and @douggie Sorry, I was mislead by the log file from my own written bot. Internally my bot was already swapping the trading pairs on Polo. The minimal amount is indeed 0.0001 when i test it on the webinterface i get "Total must be at least 0.0001 btc" So with the new pairs (BTC/ETH for example) it is correct now aplyable to the standard base coin. I thought that BTC/ETH was now swapped to ETH/BTC, but that assumption was incorrect, Sorry for that.
