### ISSUE TITLE
[Bitfinex] (DEV)  AccountInfo .getWallets() not returns wallet names  like deposit, exchange,.. 

### ISSUE THREAD

**Issue by wonkytonky** [timmolter/XChange#1535]
AccountInfo .getWallets() not returns wallet names  like deposit, exchange,.. 
It does return some info like total balance value usd and how much is used and is free but it doesn't differenciate between  deposit, exchange, margin .anymore.

**Comment by timmolter** [comment]
try the latest dev branch code please. It could already be fixed on the develop branch.

**Comment by wonkytonky** [comment]
hi, not fixed. 

i'm new to git .. but apparently the new  code is  added here : 
http://prntscr.com/fqp4bc 

i dont know what happened before this snapshot  though.. need to learn more about git myself

**Comment by timmolter** [comment]
I marked it a a bug then. You'll probably have to fix the code yourself. A PR with the fix would be appreciated by everyone.
