### ISSUE TITLE
[Gatecoin] All API responses 406

### ISSUE THREAD

**Issue by AnthonyTsang** [timmolter/XChange#1552]
I am using the follow method to create `Exchange` with my own API key and secret key.
```java
private static Exchange createExchange() {
        ExchangeSpecification exSpec = new GatecoinExchange().getDefaultExchangeSpecification();
        exSpec.setApiKey("xxx");
        exSpec.setSecretKey("xxx");
        return ExchangeFactory.INSTANCE.createExchange(exSpec);
}
```

I basically copied the example and ran `AccountInfo` and `MarketDataService.getOrderBook()`. The result is an exception `Exception in thread "main" si.mazi.rescu.HttpStatusIOException: HTTP status code was not OK: 406`

the `pom.xml` I am using is this
```XML
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-core</artifactId>
            <version>4.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-gatecoin</artifactId>
            <version>4.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-examples</artifactId>
            <version>4.2.0</version>
        </dependency>
```

**Comment by timmolter** [comment]
1. try the latest snapshot jar or compile the code from `develop`.
1. See: https://github.com/timmolter/XChange/wiki/New-Implementation-Best-Practices for how to get lower level http/JSON logs to try to debug
1. Fix it and submit a PR!
