### ISSUE TITLE
gdax order (asks/bids) (ETH_USD) returning null on order timestamp

### ISSUE THREAD

**Issue by galic1987** [timmolter/XChange#1554]
Screenshot: https://ibb.co/c5OKA5

**Comment by timmolter** [comment]
Two possibilities:

1. That's OK. It means that there is no timestamp given by the GDAX API.
2. It's a bug in the XChange code.

I'll take a look soon if you don't get to it first.

**Comment by galic1987** [comment]
I've just checked and it looks like it must be the feature in the GDAX API ;)
