### ISSUE TITLE
Get all products listed on an exchange?

### ISSUE THREAD

**Issue by dimecoin** [timmolter/XChange#1555]
Sorry if this is a dumb question, but is there a way to get a listing of all CurrencyPairs traded on a specific exchange?

**Comment by Achterhoeker** [comment]
That is present in the meta data from the exchange:
exchange.MarketExchange.getExchangeMetaData().getCurrencyPairs().keySet()

**Comment by dimecoin** [comment]
Thanks.  I found it under exchnage.getExchangeSymbols()

**Comment by npomfret** [comment]
Be careful.  I think sometimes this is taken from the static data embedded in the project, which can be out of date.  You need to check the implementation.

**Comment by Achterhoeker** [comment]
@npomfret You are correct, were possible it is taken from the remote server. But not all exchanges support that. For a consistent api that information is present in the static json file. If that information is not in sync, please update it. Everybody will benefit from that new information.
