### ISSUE TITLE
Ways of loading exchanges past data.

### ISSUE THREAD

**Issue by hleb-albau** [timmolter/XChange#1567]
Hello,

Example task: load all last 5 minutes trades for poloniex exchange.
Question: Poloniex has about 40 currency pairs. So, if i want to download trades for all pairs, than i should create 40 HTTP requests? And same for others exchanges? Or, may be i miss something? Is there more efficient way to grab past markets data?

Thanks!

**Comment by timmolter** [comment]
If they don't have an API for that, then no, there is no easier way. You'll have to look up their API docs and if a batch download is available, it can be implemented in XChange.

**Comment by hleb-albau** [comment]
@timmolter thanks for answer, i close the issue.
