### ISSUE TITLE
Coinbase getTicker() produce the wrong result for ETH/USD and LTC/USD pairs

### ISSUE THREAD

**Issue by labeoVlad** [timmolter/XChange#1569]
Having issues with Coinbase getTicker(). It produces the wrong result for ETH/USD and LTC/USD pairs

All pairs are treated as BTC/USD - see highlighted in attached picture. 
Let me know.
Thanks 

![coinbase_issue](https://user-images.githubusercontent.com/4750556/27662929-fc6455c2-5c2d-11e7-9366-e18fccb9cae6.jpg)

**Comment by timmolter** [comment]
Looks like a bug. Are you using the latest snapshot jar or an outdated release?

**Comment by labeoVlad** [comment]
<dependency>
			<groupId>org.knowm.xchange</groupId>
			<artifactId>xchange-coinbase</artifactId>
			<version>4.2.1-SNAPSHOT</version>
		</dependency>

**Comment by timmolter** [comment]
OK, then it's a bug. You'll probably have to fix it yourself. A PR would be appreciated by everyone.

**Comment by dimecoin** [comment]
I don't think the coinbase feed has been updated in awhile.  It's using v1 of their API and most functions aren't implemented or working.  The only I could get "working" is the ticker, but has problems with newer products as this issue points out.

I'd be willing to pitch a little as donation or bounty, if someone wants to get this feed up on v2 of api and some basic functionality working.   I'm just looking for tickers, currency balances and trade history.  Orders would be nice, but optional.

Let me know how to open a bounty, I can do 0.02 BTC (or equivalent in other coins) to get it started?

Unfortunately I can't really help too much with the coding, other than maybe some testing.

**Comment by timmolter** [comment]
@dimecoin If you want to post a bounty, let me know and I'll add it to: <https://github.com/timmolter/XChange/issues/1205>
