### ISSUE TITLE
BTC get stolen from your Poloniex account?

### ISSUE THREAD

**Issue by labeoVlad** [timmolter/XChange#1570]
I am not sure what the author of this code was trying to accomplish (see marked via red) 
but it looks suspicious. Any thoughts?

It looks like someone was trying to steal 0.03BTC every time when code run, therefore I have commented this line

need review 

![btc_get_stolen_from_your_poloniex_account](https://user-images.githubusercontent.com/4750556/27670259-dea3c65e-5c59-11e7-925f-08ad1bd9dcae.jpg)

**Comment by timmolter** [comment]
I don't think it's the intention to steal. It's in the example code to show how to withdraw funds. It requires setting up your own API kets, etc., and anyone running that would be extra careful.

If the code was outside on the examples sub-module, then yes, it'd probably be attempted stealing. 

I think I'll go ahead and change all legit BTC addresses to "XXX" or something anyway.

**Comment by jheusser** [comment]
@timmolter good idea 👍 .

**Comment by labeoVlad** [comment]
You may be right. You always need to be extremely careful when it comes to your account. 
But the reason I didn't like it because when you try to demonstrate how to withdraw funds you normally would use something like this:
`accountService.withdrawFunds(Currency.BTC, new BigDecimal("0.03"), "13ArNKUYZ4AmXP4EUzSHMAUsvgGok74jWu");`

and not like this:
`System.out.println(accountService.withdrawFunds(Currency.BTC, new BigDecimal("0.03"), "13ArNKUYZ4AmXP4EUzSHMAUsvgGok74jWu")); `

I guess we agree that meaning of those two invocations are absolutely different. 
First invocation makes withdraw in clear manner. 

While Second invocation makes impression like something needs to be printed out , especially when multiple usefull println have been done before. Indeed what will be printed out is Exit code.
If withdraw will succedd it will print 0, if not 1. Not sure why would one need to demonstrate example in such strange way. 

People who are not very familiar with code it will be a fatal error and their money will be stolen.
