### ISSUE TITLE
Make domain objects interfaces rather than implementations?

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#1573]
I was thinking it would be nice to have some of the domain classes as interfaces rather than implementations.  So rather than _adapting_ the exchange-native classes that you may have created into things like `LimitOrder` or `TradeOrder`, you simply implement the common interface.  It would allow the API developer to return richer objects that contain more information that the exchange might provide.

Just a thought.

**Comment by timmolter** [comment]
I don't understand how this would work. The Domain classes are carriers of information more or less, not different implementations of actions. Maybe I don't understand interfaces as well as you do. An example would be helpful.
