### ISSUE TITLE
new method getBTCequivalent() is needed

### ISSUE THREAD

**Issue by labeoVlad** [timmolter/XChange#1589]
So far we have a lot of useful methods like getAvailable(), getTotal() , etc

But what is really needed to assess your portfolio is your currency amount equivalent expressed in BTC. 
This is what all exchanges do ( poloniex and others) 
They show you the amount of currency owned and their equivalents in BTC. 

So, I thought maybe a method like getBTCequivalent() can be implemented?

**Comment by ezhik97** [comment]
I think that this is not a function for this library. You can just calculate this value by requesting wallet amounts and current exchange rates.

**Comment by labeoVlad** [comment]
agree
