### ISSUE TITLE
Gdax and okcoin's createTradeHistoryParams() return null

### ISSUE THREAD

**Issue by MartianTech** [timmolter/XChange#1597]
Both trade services will return null when calling createTradeHistoryParams() and thus we can't use getTradeHistory().

**Comment by timmolter** [comment]
For gdax it works if you pass in null I believe. However, that's confusing and not ideal the way it's implemented.

**Comment by MartianTech** [comment]
Do you mean passing null for TradeHistoryParams such as 

`GDAXTradeService.getTradeHistory(null)?`

This will still gives null pointer exception because

```
 public GDAXFill[] getCoinbaseExFills(GDAXTradeHistoryParams tradeHistoryParams) {
    return coinbaseEx.getFills(apiKey, digest, getTimestamp(), passphrase, tradeHistoryParams.getOrderId());
  }
```

**Comment by timmolter** [comment]
Sorry, I remembered that wrong. Try something like this:

```java
GDAXCurrencyTradeHistoryParams params = new GDAXCurrencyTradeHistoryParams();
    params.setCurrencyPair(currencyPair);
    UserTrades userTrades = tradeService.getTradeHistory(params);
```

**Comment by MartianTech** [comment]
In 4.2.1 SNAPSHOT:
```
GDAXCurrencyTradeHistoryParams GDAXCurrencyTradeHistoryParams // Class not available
GDAXTradeHistoryParams params = new GDAXTradeHistoryParams();
params.setCurrencyPair(currencyPair); //Doesn't support currency pair
params.setOrderId(""); //Won't specify actual order ID
UserTrades userTrades = tradeService.getTradeHistory(params);
```
will fetch whole page order history ignoring the order ID.

However if we call `params.setsetTransactionId(<Valid order ID>)`, it'd return the correct order. 

It'd be great if we can make it consistent across exchanges. Thanks for your great work.
