### ISSUE TITLE
AnxOrderBook (ANXDepth) timestamp

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#1609]
Looking at the ANX response to an order book query there are 3 possible timestamps that come back.  None of which are documented.  They are:

 * `dataUpdateTime`
 * `now`
 * `cached`

We use the code uses the one called `now`.  Does anyone know why, or what any of them mean?

I'm basically trying to figure out when the order book was last updated.

**Comment by timmolter** [comment]
Not sure. `Now` seems like the one to use, as it's when the server returned the json I presume.
