### ISSUE TITLE
Cancelling orders on the rock exchange

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#1610]
@timmolter the Rock Exchange requires more parameters than just the order id to cancel an order (it needs the CCY pair).  There's a mechanism for doing it in the code, but its a bit of a bodge and I suspect not thread safe at all.

Do you have any objections to me refactoring to add a `CancelOrderParams` object?  I think by default the API could remain largely the same and fully backward compatible.  I'd just leave the old `cancel(String orderId)` method in place and have it delegate to the new method, something like:

```
  public boolean cancelOrder(String orderId) throws IOException {
    cancelOrder(new CancelOrderParamsOrderId(orderId));
  }

  public boolean cancelOrder(CancelOrderParams params) throws IOException {
    //unrawp the params here and call the exchange
    ...
  }
```

**Comment by timmolter** [comment]
Sounds good to me.
