### ISSUE TITLE
Add Bifinex support to set additional order fields

### ISSUE THREAD

**Issue by douggie** [timmolter/XChange#1628]
HI,

Currently the BitfinexAdapters.adaptOrders creates a limit order with order type, working volume, pai, id, timestamp and price.

```
      limitOrders
          .add(new LimitOrder(orderType, order.getRemainingAmount(), currencyPair, String.valueOf(order.getId()), timestamp, order.getPrice()));
```
 Given the exchange provides the average price, the filled quantity and the status, I believe it would be useful to change the adapter to generate limit orders with a great number of fields:

```
new LimitOrder(orderType, order.getOriginalAmount(), currencyPair, String.valueOf(order.getId()), timestamp, order.getPrice(),
          order.getAvgExecutionPrice(), order.getExecutedAmount(), status
```

**Comment by timmolter** [comment]
looks to be complete.
