### ISSUE TITLE
[100 mBTC Bounty] Support the new Hitbtc API

### ISSUE THREAD

**Issue by cymp** [timmolter/XChange#1633]
[Hitbtc released a new api](https://blog.hitbtc.com/why-should-advanced-traders-choose-hitbtc-with-its-new-api-2-0/).

- Authorization is faster and easier
- Volumes are displayed in natural terms of currency, **no lots anymore**
- Error codes are standardized
- Unambiguous and uniform representation of data throughout the API
- Advanced mechanism  for new order creation
- The possibility to obtain status of trades via the REST interface

[Try new API](https://github.com/hitbtc-com/hitbtc-api/blob/master/APIv2.md).

Lots are really painful at [maintenance](https://github.com/timmolter/XChange/blob/develop/xchange-hitbtc/src/main/java/org/knowm/xchange/hitbtc/service/HitbtcTradeServiceRaw.java) and [usage](https://github.com/timmolter/XChange/issues/1645), getting rid of them would be a good thing...

**Comment by cymp** [comment]
Since I have no time to do this by myself, I am ready to pay a 50mBTC bounty. Could you please update the tag?

**Comment by cymp** [comment]
Thank you timmolter. By the way, I see that there is a "Bounty" label available, how can we use this?

**Comment by timmolter** [comment]
Added it...

**Comment by EricAnderson1000** [comment]
I'll have a go at this! I'll start work this afternoon

**Comment by npomfret** [comment]
@EricAnderson1000 if you decide not to continue let me know, I will have time to do it later this week

**Comment by cymp** [comment]
@EricAnderson1000 Have you made any progress?

**Comment by EricAnderson1000** [comment]
Yes see https://github.com/timmolter/XChange/pull/1690 ... I would say about 75% done.

**Comment by cymp** [comment]
Ok great, please take special care of [cancel replace order](https://api.hitbtc.com/api/2/explore/) if it is not already done! And please give me your BTC address so that I can send you a part of the bounty.

**Comment by EricAnderson1000** [comment]
Lets put it in my newly created Hitbtc Wallet so I can do some testing with it
14jzC9czcnY9Z22SsW4LaTSujkic5C8n6g

**Comment by EricAnderson1000** [comment]
@cymp replace or update order might prove to be a bit difficult as we are using JSR311 v1.1.1. Hitbtc uses PATCH which isn't directly supported by that library until 2.0. If the the team supports an upgrade to that library I could implement that operation in a follow up PR.

**Comment by cymp** [comment]
@timmolter any thoughts? I am too new and a bit far from this topic.

**Comment by cymp** [comment]
@timmolter Maybe you miss this last message?

**Comment by EricAnderson1000** [comment]
@cymp Also see https://github.com/mmazi/rescu/issues/95

**Comment by cymp** [comment]
Ok great!

**Comment by cymp** [comment]
@EricAnderson1000 I mentionned it on the thread you posted a link to, did you get a chance to work on it?

**Comment by EricAnderson1000** [comment]
I am still working on the second version of this PR. However it probably won't have the PATCH. This feature may take a couple of different PRs. But I hope to have the first one here merged today. Then the changes done to RESCU project done Thursday(?). Then and second PR for PATCH API on hitbtc here by the end of the week.

First attempt was merged, but then reversed merged because it was determined that we did need backwards compatibility and appropriate deprecation.

**Comment by EricAnderson1000** [comment]
BTW here is the PR for the backwards compatible change.
https://github.com/timmolter/XChange/pull/1715

**Comment by EricAnderson1000** [comment]
@npomfret @cymp Any feedback on the code merged so far?

**Comment by npomfret** [comment]
Not yet.  I'm still using the old implementation. Will move to the new one this week i hope.

**Comment by cymp** [comment]
Same here.

**Comment by cymp** [comment]
@EricAnderson1000 I have a problem. When I try to fetch the balance of the account, I don't have any value for certain currencies. For example, I receive no entry from HVN and AIR. I am not sure if this is a bug or a regression. I tried with the v2 API you just added (/api/2/account/balance) and I got several times a time out error. Did it work for you?

**Comment by EricAnderson1000** [comment]
Yes I saw those timeout, but only when I made more than one request per second. Which I believe I read somewhere is their SLA. I am not sure if that is their throttling mechanism or not.. I will follow up.

**Comment by cymp** [comment]
hmmm, I don't think there is suck an issue with this, as I am used to call the api much more than on time per second and I never get any timeout, plus the fact that the documentation says that we should receive a HTTP 429 error. Moreover, I am getting this error the very first time I am calling it. Maybe there is something wrong on their side and this api method is not plugged.

**Comment by cymp** [comment]
@EricAnderson1000 I tried to call org.knowm.xchange.hitbtc.v2.service.HitbtcMarketDataServicegetHitbtcSymbols() as well, and I have the same timeout error.
Could you please try to test this on your side and tell me if you have the same problem on the functions you implemented?

**Comment by EricAnderson1000** [comment]
I have integrated it into my own project. As of recent I am not getting any of the timeout errors from the MarketData apis. 

Let me create a little bit of a load test on the client and see where it starts to fail and how.

**Comment by cymp** [comment]
Indeed, it works as of now. I am not so confident about the stability of the v2 api, this could be a good thing to keep the legacy code of the v1 implementation.

**Comment by EricAnderson1000** [comment]
I agree, keeping both in place for now is not a bad idea. Eventually we should deprecate all V1 services and plan to remove them we we are confident in hitbtc V2 api services.

**Comment by cymp** [comment]
Yes, the cancel replace order, did you get a chance to work on this?

**Comment by EricAnderson1000** [comment]
Ah yes.. I need to patch the rest client library rescu to make that happen. Working on that now then.

**Comment by cymp** [comment]
Ok thanks!

All of my balances are here but are 0 when I use the v2 hitbtcAccountService.getAccountInfo().getWallet()... With the v1 I don't have this problem, this api is really messed up!

**Comment by cymp** [comment]
@EricAnderson1000 do you also have this all 0 balance problem?

**Comment by EricAnderson1000** [comment]
@cymp Yes looks like it is an issue with their API...

```

2:34:45,577 DEBUG [si.mazi.rescu.HttpTemplate] - Executing GET request at https://api.hitbtc.com/api/2/account/balance 
12:34:45,577 TRACE [si.mazi.rescu.HttpTemplate] - Request body = 
12:34:45,577 TRACE [si.mazi.rescu.HttpTemplate] - Request headers = {Authorization=Basic ZjdlNWQyMzE2M2Y4ZmMwZGFhZTEzNjZiM2UyM2Y1ODA6ZDRiNTdmMDU1MDQzYzc2N2I0MWYyM2JkOGRhY2FhNTI=} 
12:34:45,578 TRACE [si.mazi.rescu.HttpTemplate] - Header request property: key='Accept-Charset', value='UTF-8' 
12:34:45,578 TRACE [si.mazi.rescu.HttpTemplate] - Header request property: key='User-Agent', value='ResCU JDK/6 AppleWebKit/535.7 Chrome/16.0.912.36 Safari/535.7' 
12:34:45,578 TRACE [si.mazi.rescu.HttpTemplate] - Header request property: key='Authorization', value='Basic XXXXXXXXXX=' 
12:34:45,578 TRACE [si.mazi.rescu.HttpTemplate] - Header request property: key='Accept', value='application/json' 
12:34:46,552 DEBUG [si.mazi.rescu.HttpTemplate] - Request http status = 200 
12:34:46,741 TRACE [si.mazi.rescu.HttpTemplate] - Http call returned 200; response body: 
[{"currency":"BTC","available":"0.00000000","reserved":"0.00000000"},{"currency":"ETH"....

```

Despite the UI Website showing the 0.05 BTC transfered to me and available for trading.

**Comment by EricAnderson1000** [comment]
They haven't answered my open ticket... I have asked for an update. Support seems less than needed from hitbtc.

**Comment by EricAnderson1000** [comment]
@cymp Here is the rest of this change. PATCH support working and tested

https://github.com/timmolter/XChange/pull/1855

**Comment by timmolter** [comment]
merged #1855

**Comment by cymp** [comment]
@EricAnderson1000 Thanks, I think I owe you 50 mBTC, right? Please give me your BTC address. By the way, did you manage to get some non 0 balance from the api v2 getBalances api call? I tried this week and I still have 0 everywhere...

**Comment by cymp** [comment]
@EricAnderson1000 By the way, what is the difference between clientOrderId and requestClientId  in this method?

**Comment by EricAnderson1000** [comment]
https://hitbtc.com/api#cancel-replace-orders
What this really does is cancel the previous Order and Creates similar new one with the new parameters. 

requestClientId: the new unique order id (system wide) for the new order. If left empty the system will create it.
clientOrderId: The uniqueOrderId of the order you want to cancel (replace).

OK I think I have figured it out the account balance. 
The API call provided only shows the balance of funds in the 'Main' account, not the 'Trading' account. Looking over the API I don't immediately see a call to get the funds available to trading. I can see the API call to move them back and forth.
https://github.com/hitbtc-com/hitbtc-api/blob/master/APIv2.md#rest-api-reference

I'm going to keep looking at this a bit more tonight.


Bitcoin Address : 15mwWLtQXecQyUSVi484n9BpfZ3Y2foGMW

**Comment by EricAnderson1000** [comment]
>By the way, did you manage to get some non 0 balance from the api v2 getBalances api call? I tried this week and I still have 0 everywhere, except for BTG...

Yes I did. Make sure you are calling the correct API for the Main vs the Trading. I have added a unit test here. You will have to provide your key and secret to the test as described in the Base Test class.

Here is an example. https://github.com/timmolter/XChange/pull/1859

**Comment by cymp** [comment]
@EricAnderson1000 I paid you. By the way, I think you have forgotten to add the price parameter in updateMarketOrderRaw.

**Comment by cymp** [comment]
@EricAnderson1000 After having tried to fetch the balances, I think there might be a problem related to the format Hitbtc returns the balances: what is this negative "available" value?
Example:
![image](https://user-images.githubusercontent.com/3685318/32324158-b427d382-bfca-11e7-9edb-13834b55cd7a.png)
![image](https://user-images.githubusercontent.com/3685318/32324175-c2163510-bfca-11e7-930a-a35bf4f92199.png)

**Comment by EricAnderson1000** [comment]
>By the way, I think you have forgotten to add the "price" parameter in updateMarketOrderRaw.
Indeed. I have updated the code and tested it with real funds. Works with price and quantity updates now. Here is the PR 
https://github.com/timmolter/XChange/pull/1862

>After having tried to fetch the balances, I think there might be a problem 
The way I see that screen is that you have .31 placed on a pending order that is not full-filled. And .23 in your trading account. That means you have -.08 on margin. Correct me if I am wrong.

**Comment by cymp** [comment]
@EricAnderson1000 In this case with the Balance.getTotal() implementation, it will return .31+.23-.08 = .46? Looks a bit strange imo... Is this consistent with the other exchanges data?

I have also noticed that getTicker**s** implementation v2 is missing (getHitbtcTickers is implemented in HitbtcMarketDataServiceRaw v1) :

> Tickers
> GET /api/2/public/ticker
> GET /api/2/public/ticker/{symbol}

Thanks very much for your overall very good work!

**Comment by EricAnderson1000** [comment]
>I have also noticed that getTickers implementation v2 is missing (getHitbtcTickers is implemented in HitbtcMarketDataServiceRaw v1) :

Yes this was missing in the RAW service
https://github.com/timmolter/XChange/pull/1863

>In this case with the Balance.getTotal() implementation, it will return .31+.23-.08 = .46? Looks a bit strange imo... Is this consistent with the other exchanges data?

I am a little confused here. I'm not sure how you would call getTotal on the Balance object since there are only three methods
```
  public String getCurrency()

  public BigDecimal getAvailable() 

  public BigDecimal getReserved()
```

It did get me thinking about about the AccountInfo object and how it adds up totals. It looks like if you add more than a single Wallet to the AccountInfo object, it throws an exception when trying to get balance. See the unit test I added `testAdaptWallet_getBalance`. Not sure if this is what you are referring to.

>Is this consistent with the other exchanges data?

I am not sure how many exchanges have the concept of a trading wallet and a 'bank' wallet. Gemini doesn't. I am obviously open to changes in how this should work in the code!

**Comment by EricAnderson1000** [comment]
@timmolter I suggest we close this ticket as implemented.
@cymp If there are any more follow up issues, please create new issues and tag me. Thanks!

**Comment by cymp** [comment]
Ok will do, I didn't answer you because I had to work on something else and I haven't thought more about it yet.

**Comment by timmolter** [comment]
Can this be closed yet?

**Comment by cymp** [comment]
Yes.
