### ISSUE TITLE
Fee target metadata [addition request]

### ISSUE THREAD

**Issue by pvk444** [timmolter/XChange#1635]
A piece of information that seems to be missing is the target of the fee charge. The trading fees are typically charged in either of 4 ways:

1. charge the quote currency
2. charge the base currency 
3. charge the currency bought
4. charge the currency sold

It would be useful to be be able to add some capability to capture this metadata (for instance in AccountInfo). Btw, this is complementary to the taker / maker and other fee related information.

**Comment by npomfret** [comment]
This has being discussed a couple of times recently. Do you have any thoughts or suggestions on how the json config should look.

**Comment by pvk444** [comment]
Just to be clear: I have only seen discussions regarding the taker / maker attribute, volume depend fee structures, and alternative fee calculation models. I have not seen the fee target included in those discussions. 

In any case, I don't think any exchange publishes this information via their API. At least I have not seen any of them doing so. I was thinking of adding another attribute to the AccountInfo class which can then be set manually, or add  a map of account specific parameters, similar to the one included in the Exchange class (exchangeSpecificParameters).

Of course, one could simply reuse this exchageSpecificParameters in the Exchange class to capture this info, but AccountInfo seems the more logical place.

**Comment by timmolter** [comment]
It should stay with the metadata, not account info. Jackson can handle polymorphism, which could be the solution here.
