### ISSUE TITLE
Numeric exception during response parsing

### ISSUE THREAD

**Issue by adamMo** [timmolter/XChange#1641]
Hello I got a problem with bitfinex module: 

> 23:26:06.915 [main] DEBUG si.mazi.rescu.ResponseReader - Parsing response as class [Lorg.knowm.xchange.bitfinex.v1.dto.trade.BitfinexOrderStatusResponse; failed: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (3097475654) out of range of int

**Comment by timmolter** [comment]
Looks like the field should be updated to a long.

**Comment by adamMo** [comment]
Hmm, I see that snapshot version is already fixed from few months, so sorry for bothering you @timmolter !
