### ISSUE TITLE
Add number of decimal places to Currency

### ISSUE THREAD

**Issue by 23492904284930234** [timmolter/XChange#1646]
First I want to thank everyone for contributing to this nice project.

Any thoughts on adding the number of decimal places a currency has to the Currency class? It's an essential information that the class is lacking of.

Currently I think the number of decimal places is determined through the Exchanges.

Imho it makes sense to bind this information within the Currency class. For example if one wants to use the Currency class without retrieving actual data from an exchange API. It makes the library more flexible and allows better reuse of the Currency class in other projects.

For example:
EUR - 2 decimal places
BTC - 8 decimal places

**Comment by npomfret** [comment]
That information is defined in the static _exchange_.json files found in the root of the class path on each project.  The `ExchangeMeta` class exposes it via the `getCurrencies` method.

**Comment by 23492904284930234** [comment]
These files define the number of decimal places for each currency (pair) an exchange returns. It's not the same as the fixed maximal number of decimal places a currency has. 

By putting this information into the currency class one could reuse that class independently of that exchange stuff as it has all the necessary information. There would be no need in writing another adapter just to this information. Once could directly use that class as a 'standard' in the java crypto world. The Exchange APIs could still rely on the exchange specific information.

**Comment by timmolter** [comment]
You could use JodaMoney: http://www.joda.org/joda-money/apidocs/org/joda/money/CurrencyUnit.html#getDecimalPlaces--
, but I don't think it supports Crypto. 

I'm not too interested in adding it at the moment, but if there were really good reasons and had the support from others, I'd be OK with it.
