### ISSUE TITLE
Add Bitfinex WebSocket API support

### ISSUE THREAD

**Issue by EzBar** [timmolter/XChange#1647]
Hi,

Bitfinex REST API has a DDoS protection mechanism when sending more than 90 requests per minute (see: https://www.bitfinex.com/posts/188). This limit can be easily passed when polling multiple markets/pairs  at the maximal polling-rate.
Do you plan to implement Bitfinex WebSocket API (https://docs.bitfinex.com/docs/ws-general) which supports high frequency connections?

P.S. Thank you all for creating and supporting this amazing project!

Thanks,
EzBar

**Comment by jheusser** [comment]
XChange currently does explicitly not support streaming but rest-only APIs. There's a fork that does look at streaming only I believe, see here:
https://github.com/bitrich-info/xchange-stream

But I assume worth reconsidering this from time to time as websocket becomes more consistently used.
