### ISSUE TITLE
Does the next release contain Kraken BCH

### ISSUE THREAD

**Issue by swissistent** [timmolter/XChange#1651]
and when would it be released?

**Comment by npomfret** [comment]
There's a PR with BCH waiting to go through.  I guess it'll appear in the next 4.2.2-SNAPSHOT build.

**Comment by swissistent** [comment]
thanks!

**Comment by npomfret** [comment]
Annoyingly Bittrex, and I guess maybe some others, have used a different symbol (BCC instead of BCH).  I actually thoughts BBC was already taken, which is why BCH was being sued now.

@timmolter is there a way to deal with this in the project already?

**Comment by labeoVlad** [comment]
Hi guys, 

This is what needs to be changed in KrakenUtils.java in order to bring this new Currency into play. Enjoy 

![image](https://user-images.githubusercontent.com/4750556/28854564-e773ae54-7705-11e7-8130-5ba8eb0a3826.png)
