### ISSUE TITLE
BCH/BTC : [EQuery:Unknown asset pair]

### ISSUE THREAD

**Issue by labeoVlad** [timmolter/XChange#1652]
I have added a new currency BCH in KrakenUtils.java
` DIGITAL_CURRENCIES.add(KrakenAdapters.adaptCurrency("BCH"));`
   

When requesting  a ticker 
` System.out.println(marketDataService.getTicker(new CurrencyPair(Currency.BCH, Currency.BTC))) ;`

I am still getting ExchangeException
`[main] INFO org.knowm.xchange.kraken.KrakenExchange - Calling Remote Init...
Exception in thread "main" org.knowm.xchange.exceptions.ExchangeException: [EQuery:Unknown asset pair]
	at org.knowm.xchange.kraken.service.KrakenBaseService.checkResult(KrakenBaseService.java:82)
	at org.knowm.xchange.kraken.service.KrakenMarketDataServiceRaw.getKrakenTicker(KrakenMarketDataServiceRaw.java:38)
	at org.knowm.xchange.kraken.service.KrakenMarketDataService.getTicker(KrakenMarketDataService.java:31)`

Why it is happening. I thought a pair may be created as soon a Currency is introduced. Isn't it? Do you need to create a pair manually?

Give a hint what else must be edited to correct it?

Thanks

**Comment by Achterhoeker** [comment]
I'm doing the same. It seems that kraken isn't supporting BTH on their api. See for example: https://api.kraken.com/0/public/AssetPairs
The unknown asset pair error is from kraken.

**Comment by labeoVlad** [comment]
what about `https://api.kraken.com/0/public/Ticker?pair=BCHXBT` 
it looks like Kraken API is working. Therefore I am expecting same  from XChange API

**Comment by labeoVlad** [comment]
Moreover, a pair called `BCHXBT` can be easily found in https://api.kraken.com/0/public/AssetPairs

**Comment by Achterhoeker** [comment]
@labeoVlad You are correct. They are present now. For 15 minutes ago it wasn't... I'm currently again debugging what is going wrong.

**Comment by labeoVlad** [comment]
I think this is what causing issues in KrakenBaseService.java

`  public KrakenAssets getKrakenAssets(Currency... assets) throws IOException {

    KrakenAssetsResult assetPairsResult = kraken.getAssets(null, delimitAssets(assets));

    return new KrakenAssets(checkResult(assetPairsResult));
  }

  protected <R> R checkResult(KrakenResult<R> krakenResult) {

    if (!krakenResult.isSuccess()) {
      String[] errors = krakenResult.getError();
      if (errors.length == 0) {
        throw new ExchangeException("Missing error message");
      }
      String error = errors[0];
      if ("EAPI:Invalid nonce".equals(error)) {
        throw new NonceException(error);
      } else if ("EGeneral:Temporary lockout".equals(error)) {
        throw new FrequencyLimitExceededException(error);
      }

      throw new ExchangeException(Arrays.toString(errors));
    }

    return krakenResult.getResult();
  }`

**Comment by Achterhoeker** [comment]
@labeoVlad Sorry, I'm using an older version of kraken, The latest version isn't  usable for me anymore. Open orders on Dash are for example reported as DAS. I don't have the time currently to find out which PR causes these new errors. On the old version all exceptions for GNO are also needed for BTH to create a correct kraken asset pair.

**Comment by labeoVlad** [comment]
Bittrex is working with new currency just fine 

`Ticker ticker = marketDataService.getTicker(new CurrencyPair("BCC", "BTC"));`

Unlike Kraken, they return a ticker using BCC/BTC pair

`[main] INFO org.knowm.xchange.bittrex.v1.BittrexExchange - Calling Remote Init...
Ticker [currencyPair=BCC/BTC, last=0.11000010, bid=0.11000010, ask=0.11012500, high=0.14789000, low=0.00300000,avg=null, volume=23546.31626708, timestamp=1501617907347]
`

**Comment by Achterhoeker** [comment]
@labeoVlad I have it working on Kraken, but on an older version. :-( The utils for kraken are trying to add an Z or X to all currencypairs. For BCH that isn't needed. (like GNO) You also need to add the pairs to the json file if you use the reported pairs from an xchange.

**Comment by npomfret** [comment]
Does this API support the face that different exchanges may use different symbols for the same currency?  Is is that something you have to deal with yourself?

**Comment by labeoVlad** [comment]
**@Achterhoeker** oh, that was a great hint! Thanks

**Comment by Achterhoeker** [comment]
@npomfret That is an open question. Currently it is a chaos. Polo is using bcc for an other altcoin. Bittrex is using bcc for bch. Bitfinex is using bcc for a strange older split off coin. (and bch communicated for bch). Kraken is using bch. Currently i think that the best option is to use bch and let the bittrex xchange translate that to bch. And these are only the xchanges i use in my bot with bch.

**Comment by labeoVlad** [comment]
This is what needs to be changed in KrakenUtils.java

![image](https://user-images.githubusercontent.com/4750556/28854500-7a46dd42-7705-11e7-9432-463c1f897486.png)

**Comment by douggie** [comment]
HI,

I beleive we need to have Kraken adapters not add in the X's and Z's into a pair when submitting the request where the quote currency is BCH.

Currently the latest develop branch is market data request by sending
https://api.kraken.com/0/public/Trades?pair=ZBCHXXBT, as ZBCHXXBT is not a valid pair (https://api.kraken.com/0/public/AssetPairs) the valid pair is just BCHXBT.

Essentially when the quote currency is BCH the kraken adapter should not add the Z and X's to create the pair.

Happy to fix it up later today, or if someone else is taking a look, great!

**Comment by npomfret** [comment]
Thanks @labeoVlad PR?

**Comment by Achterhoeker** [comment]
@labeoVlad @douggie @timmolter I've started rewriting the Kraken implementation with the translations. The code is now using the assets retrieved from the exchange. So no hardcoded translations needed anymore. Only left problem is the dark markets, i think i can ignore them ? Does anyone uses those markets ? (dark markets is without order books, only placing orders is allowed)
Last evening I didn't have the time to finish it. Today there is also no time left. I'll try to push this change tomorrow evening. (UTC+2)

**Comment by douggie** [comment]
Wow sounds like a nice change. I dont use dark markets

**Comment by npomfret** [comment]
That does sound like a good change.  (And I also don't use dark markets).  

I think we still need to consider a general solution to this problem though.  Not all exchanges will have the necessary API calls to do it _magically_.
