### ISSUE TITLE
[60 mBTC Bounty] Implement Yobit Trade and Account Services

### ISSUE THREAD

**Issue by cymp** [timmolter/XChange#1653]
It looks like Yobit trade and account services are not implemented yet, [only the market data service is](https://github.com/timmolter/XChange/tree/develop/xchange-yobit/src/main/java/org/knowm/xchange/yobit/service).

I am not available to implement them myself thus I am offering a 60mBTC bounty to anyone who can do it.

**Comment by cymp** [comment]
Could you please add the "Bounty" label timmolter? I can't find how to do that.

**Comment by npomfret** [comment]
I might get time to look at this.  Thanks for offering a bounty.

**Comment by cymp** [comment]
You are welcome.

**Comment by EricAnderson1000** [comment]
@npomfret  if you don't have time right away, I would love to contribute to this project through this request. But I don't want to duplicate efforts. Let me know!

**Comment by npomfret** [comment]
I'm almost done with an initial implementation, will commit my first attempt soon.

**Comment by npomfret** [comment]
@cymp first implementation is here  https://github.com/timmolter/XChange/pull/1679

It's pretty basic, but all available endpoints are implemented (I think) and ready for testing.  I've placed an order, queried it, cancelled it, got the wallets data, got address data.  As I'm writing this I realise I didn't execute a trade with it...

**Comment by cymp** [comment]
Okay, please paste here your bitcoin address, I'll send you half the bounty and the other half once you are finished. Sounds good to you?

**Comment by npomfret** [comment]
Sure.  1K5dYadQBBkTR3L4RkktMiNaJbx8uRRyyq

**Comment by cymp** [comment]
30mBTC are on their way to 1K5dYadQBBkTR3L4RkktMiNaJbx8uRRyyq.

**Comment by npomfret** [comment]
@cymp https://github.com/timmolter/XChange/pull/1679#event-1200895509 has been merged so feel free to do some testing.  Alll available endpoints have been implemented.  I've got plenty of clean up to do still, but as your were paying I wanted to get something to you as quickly as possible.  I don't anticipate any major changes in behaviour as a result of further work.

@EricAnderson1000 if you wanted to help in order to start contributing, I can point you at some stuff that could do with improving.

**Comment by cymp** [comment]
@npomfret Thank you, I will try to make some test ASAP. Please tell me when you think your cleanup is finished as well.

By the way, I've just noticed in the [API description](https://www.yobit.net/en/api/), "v3" section that they now provide multi results with one call, which is a nice feature. Would you agree to look into this as well? I would extend your bounty to 10mBTC more.

**Comment by npomfret** [comment]
I'll take a look at the multi-results thing.  It might take quite a big refactor to get it into this API properly though, so it may be quite a big job.

**Comment by cymp** [comment]
Thank you!

**Comment by npomfret** [comment]
@cymp I've submitted a https://github.com/timmolter/XChange/pull/1685 which has all the clean up i intended plus implementations for the multi-currency calls that are documented.  They are not a part of the public api yet, that's a question we need to ask @timmolter .

To access the new market data calls you need to use:

```
  public Iterable<Ticker> getTickers(TickersRequestParams params) throws IOException {...

  public Iterable<OrderBook> getOrderBooks(OrderBooksRequestParam params) throws IOException {...

  public Trades getTrades(PublicTradesRequestParams params) throws IOException {...

```

There are implementations of the `params` objects available (currently inside the YoBit namespace) that allow multiple currency pairs to be specified.  I've also added single currency-pair implementations for convenience.

@timmolter I'm wondering if the above methods would be good replacements for the existing market data interface.  They provide 2 things of use:

 * multi-market calls for those exchanges (such as YoBit) that support them
 * a sensible placed for the `desiredDepth` parameter for exchanges that support partial order book responses. I think it's a improvement on the current _varargs_ parameter in the `getOrderBook` method signature.

**Comment by cymp** [comment]
Thank you @npomfret, I will not be available until Wednesday so I can't test, but I guess I can send you the remaining of the initial bounty, which is 30 mBTC, they are already on their way to 1K5dYadQBBkTR3L4RkktMiNaJbx8uRRyyq. I will give you feedback once I have tested.

 I will give you the extra 10mBTC once this multi currency call case is closed. Do you agree?

Thanks again for your quick and good work!

**Comment by npomfret** [comment]
thanks @cymp that's all fine.  I'm confident the multi currency stuff is working.  if or not we integrate into the public api is a different question, and maybe quite a big refactor - but I think it should go in.

**Comment by timmolter** [comment]
@npomfret I've seen multiple requests for these methods now, so it might be a good time to introduce them. Why `Iterable` though as opposed to `List`?

**Comment by npomfret** [comment]
`Iterable`... only because I prefer to pass around immutable data structures

**Comment by cymp** [comment]
@npomfret I am starting to test, and when I do 
`marketDataService.getTickers(new MultiCurrencyPairTickersRequestParams(exchange.getExchangeSymbols()));`
I get an HTTP 414. Indeed, as far as I know the http urls are limited to 2k characters and here we have something like 1k currency pairs, exceeding this limit. 

What do you think should be done? Split the calls and then aggreagate the results in the Yobit specific code?

**Comment by npomfret** [comment]
I didn't test that scenario, thanks for letting me know.  

I think handling that in yobit specific code might not be the best solution.  The result would be multiple API calls when the user thinks they're only doing 1, which might have an adverse effect when rate limiting kicks in.  Perhaps for now we should just add a more helpful error message that explicitly says there are too many currency pairs.

**Comment by cymp** [comment]
You are right, for now I will split the calls in my client application in order to continue testing. I am going to add a todo as well.

**Comment by npomfret** [comment]
I'll make a change later today and add a better error message.

**Comment by npomfret** [comment]
@timmolter this can be closed
