### ISSUE TITLE
quoine 401

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#1656]
I'm working no fixing and added to quoine.  I'm getting a 401 on certain endpoints such as `/trades`.  Anyone seen this?

**Comment by npomfret** [comment]
I've just noticed the body of the 401 response has "Path does not match".  This is true for both _/trades_ and _/executions/me_

**Comment by AdityaNayak** [comment]
Were you able to identify the issue?

**Comment by npomfret** [comment]
Yes, fixed committed and merged

**Comment by kryptokurrency** [comment]
@npomfret I have the same issue now. Do you mind sharing what you did to fix the error? Thanks

**Comment by npomfret** [comment]
Its working fine for me.

**Comment by kryptokurrency** [comment]
Yup its working now too for me. Left out a '/' in the URL!
Thanks
