### ISSUE TITLE
BTC Markets 'since' parameter - what are the units!?

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#1659]
I'm failing to get a call to `/order/trade/history` working.  I only get data back if I specify a zero date for the _since_ parameter.  Anyone know what the units are?  The code is converting using unix time, but that's not working (and neither is the _mills_ alternative).

**Comment by douggie** [comment]
says

type = type of trade (optional)
    all = all types (default)
    any position = any position (open or closed)
    closed position = positions that have been closed
    closing position = any trade closing all or part of a position
    no position = non-positional trades
trades = whether or not to include trades related to position in
output (optional.  default = false)
start = starting unix timestamp or trade tx id of results (optional.  exclusive)
end = ending unix timestamp or trade tx id of results (optional.  inclusive)
ofs = result offset


may be try an order id.

**Comment by npomfret** [comment]
Where did you find that documentation?  I'm looking here https://github.com/BTCMarkets/API/wiki/Trading-API#trade-history

**Comment by npomfret** [comment]
Fixed.
