### ISSUE TITLE
Implemented features matrix on main page

### ISSUE THREAD

**Issue by cymp** [timmolter/XChange#1662]
Hello,

What do you think about adding this kind of matrix on the main page? Something like:

```
            |  MarketService  | TradeService | ....
------------|-----------------|--------------|--------------
Poloniex    |         v       |      v       |
Hitbtc      |         v       |      x       |
Kraken      |         v       |      v       |
...         |                 |              |
```
We could also consider adding "Since version", "Api version", ... tabs.

**Comment by npomfret** [comment]
I think that's a good idea.  I'd go further and detail which methods on which service are working. 

 It'd be nice to have a test suite that you prime with keys that could generate the data... but that might be a bit ambitious.  Especially when it comes to actually making trades.

**Comment by timmolter** [comment]
See:<https://github.com/timmolter/XChange/wiki/Exchange-Support>

Anyone can update, I believe.
