### ISSUE TITLE
Kraken Exchange should throw FrequencyLimitExceededException when rate limit is exceeded

### ISSUE THREAD

**Issue by 23492904284930234** [timmolter/XChange#1671]
When I hit the frequency limit on Kraken exchange API  an `ExchangeException` is thrown:
`org.knowm.xchange.exceptions.ExchangeException: [EAPI:Rate limit exceeded]`

Interpreting the exception msg leads to the conclusion that a `FrequencyLimitExceededException` exception should be thrown instead of an `ExchangeException`.

**Comment by timmolter** [comment]
You're probably correct. It probable just hasn't been implemented yet. Feel free to submit a PR with the update!

**Comment by timmolter** [comment]
See GDAX implementation on how to handle exceptions and rethrow `FrequencyLimitExceededException`. This needs to be implemented better across all exchanges, starting with Kraken.
