### ISSUE TITLE
Kraken GetTicker: Invalid Arguments

### ISSUE THREAD

**Issue by swissistent** [timmolter/XChange#1673]
A couple of currencies lead to an (SNAPSHOT 4.2.2)

GNO/BTC
REP/CAD
XRP/GBP

ExchangeException: [EGeneral:Invalid arguments]

**Comment by Achterhoeker** [comment]
@swissistent If i run the kraken ticker example with GNO/BTC : 
private static void generic(Exchange krakenExchange) throws IOException {

    // Interested in the public market data feed (no authentication)
    MarketDataService marketDataService = krakenExchange.getMarketDataService();
    // Get the latest ticker data 
    Ticker ticker = marketDataService.getTicker(new CurrencyPair("GNO","BTC"));

20:55:01.439 [default] [main] INFO  o.k.xchange.kraken.KrakenExchange - Calling Remote Init... 

Ticker: Ticker [currencyPair=GNO/BTC, last=0.06153200, bid=0.06147700, ask=0.06153200, high=0.06437100, low=0.05121700,avg=0.06034120, volume=113.94741401, timestamp=null]
 
So seems to work for me ?

**Comment by swissistent** [comment]
GNO/BTC seams to work then:
THis one still throws the Exception:
	
MarketDataService marketDataService = ex.getMarketDataService();
		Ticker ticker = marketDataService.getTicker(new CurrencyPair(Currency.XRP,Currency.GBP));
		System.out.println(ticker);

**Comment by Achterhoeker** [comment]
That exception is correct, Kraken doesn't seem to contain the XRP/GBP pair anymore. It should be removed from the kraken json file. (I assume that's why it still is in the pair list from xchange Kraken)
