### ISSUE TITLE
Why Bittrex Not Implement GetOrder ??

### ISSUE THREAD

**Issue by nntaoli** [timmolter/XChange#1681]
I've found that a number of trading platform only implement part of the method？

**Comment by timmolter** [comment]
Yes, that's true indeed. Not everything is 100% complete.

**Comment by npomfret** [comment]
@nntaoli sometimes the exchanges just don't support the API methods exposed in this project.  Other times people just haven't implemented it.

**Comment by nethergrim** [comment]
Will it be okay for you if I fork XChange, implement getOrder method, and create a pull request?

**Comment by timmolter** [comment]
of course!
