### ISSUE TITLE
please revert new HitBTC stuff

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#1705]
Hi @timmolter 

Can I request that we revert the new HitBTC implementation as we've lost some functionality. 

I recently added methods to move funds between the accounts in `HitbtcAccountService` but they've been deleted.  This functionality is crucial for my software, and is still supported by the exchange, there's no reason to remove it.

Could you please revert the commit until any missing functionality is added back in?

**Comment by npomfret** [comment]
@EricAnderson1000 what's happened to the hitbtc stuff that allows a user to transfer funds between the _main_ and _trading_ accounts? These methods were only just added and need to be supported still Without them you can trade with deposited funds, and similarly you can't withdraw funds from your trading account because you need to move them to the main account first.  Also, it's necessary to be able to query both of these balances and I think those methods have gone too.

Can we please revert this change for now until it's complete?

**Comment by npomfret** [comment]
Ok, i've tested and can confirm that using `transferFunds` replaces the old functionality correctly.  However, I don't see why the method names were changed as the underlying functionality is still supported - this could have been done as a backward compatible change.

I think the method for doing internal transfers `transferFunds` is confusing and should be renamed something like `internalTransfer`.

Also, I think we should have the 2 explicit methods as we did before.  The reason is that the website still calls the two accounts _main_ and _trading_, whereas the API calls them _bank_ and _exchange_ (they couldn't have picked a worse name!).  So I think it would be helpful to have methods that reflect these names that delegate to `transferFunds`.  Something like `internalTransferToMain` and `internalTransferToTrading` (which use the same naming convention as the website).  I think it's too easy for users to confuse `transferFunds(BTC, 1, EXCHANGE_TO_BANK)` with `withdrawFundsRaw`, especially as there's no bank involved in the former.

**Comment by EricAnderson1000** [comment]
I believe the names of the methods were closely named to the API calls. Since they have changed the API the names changed a bit. However that is good feedback. 

I wasn't quite ready for the merge to happen (thus the *** NOT READY FOR MERGE*** at the top of the PR.

However I would like to take your suggestions and move forward with a new PR I can get going rather than reverting if that is OK?

**Comment by npomfret** [comment]
On a separate note.  It looks like the price scale information from the `hitbtc.json` is thrown away.  Again, this needs to be merged into the data that comes bank from the exchange.  Please can we fix or revert until fixed?

**Comment by npomfret** [comment]
If it's not ready to merge I suggest reverting.  My software is quite broken at the moment.

**Comment by EricAnderson1000** [comment]
We need to add more tests to this sub-module then. Since none of the existing tests caused failure. 

However can't you use a previously released version?

**Comment by npomfret** [comment]
Getting the previous snapshot is difficult, i don't even know how (my build just picks up the latest snapshot).  That not the point though, if this change wasn't ready and then shouldn't be merged.

Yes there are test missing, and that's unfortunate (and certainly not your fault), but that's also no reason to keep this change and everyone who uses the snapshots will be using an unfinished PR. I think there are a lot of people using the snapshots.

**Comment by npomfret** [comment]
It think `adaptToExchangeMetaData ` should look like this:

```
  public static ExchangeMetaData adaptToExchangeMetaData(List<HitbtcSymbol> symbols, Map<Currency, CurrencyMetaData> currencies, Map<CurrencyPair, CurrencyPairMetaData> currencyPairs) {

    if (symbols != null) {
      for (HitbtcSymbol symbol : symbols) {
        CurrencyPair pair = adaptSymbol(symbol);

        BigDecimal maximumAmount = null;
        Integer priceScale = null;
        if(currencyPairs.containsKey(pair)) {
          CurrencyPairMetaData currencyPairMetaData = currencyPairs.get(pair);
          maximumAmount = currencyPairMetaData.getMaximumAmount();
          priceScale = currencyPairMetaData.getPriceScale();
        }

        CurrencyPairMetaData meta = new CurrencyPairMetaData(symbol.getTakeLiquidityRate(), symbol.getTakeLiquidityRate(), maximumAmount, priceScale);

        currencyPairs.put(pair, meta);
      }
    }

    return new ExchangeMetaData(currencyPairs, currencies, null, null, null);
  }
```

**Comment by EricAnderson1000** [comment]
https://github.com/timmolter/XChange/pull/1707

**Comment by timmolter** [comment]
OK, merge reverted. Thanks for working together on this!
