### ISSUE TITLE
[50 mBTC bounty] Fully implement Cryptopia API

### ISSUE THREAD

**Issue by cymp** [timmolter/XChange#1708]
I am offering a 50mBTC bounty for this.

At the moment, the [Cryptopia API supported by XChange](https://github.com/timmolter/XChange/tree/develop/xchange-cryptopia/src/main/java/org/knowm/xchange/cryptopia/service) only has its market data service implemented.  It would be nice to complete it if needed and have its Trade and Account APIs implemented as well.

**Comment by npomfret** [comment]
If you can up your offer to 100 I can start this tomorrow.  Estimate I'd have something ready for testing within 48 hours.

**Comment by cymp** [comment]
I need to control my global budget since I have some additional bounties to open here, but I can offer you 75mBTC total if you plan to start this early as you said, with immediate 35 mBTC transfer to whichever address you want as soon as you agree and the remaining 40mBTC once you are finished.

What do you think?

**Comment by npomfret** [comment]
Ok, lets do that.

**Comment by cymp** [comment]
Ok great, please paste your btc address.

**Comment by npomfret** [comment]
that's ok, pay me when its done and save some transaction fees.

**Comment by npomfret** [comment]
@cymp the bulk of the work is done, i'll submit a PR tomorrow.  I'm just waiting on some funds to clear so I can test placing orders and trading.  It's taking forever.

**Comment by npomfret** [comment]
There'll be a delay unfortunately. The work is done, bar some final testing but my home broadband isn't working and is showing no signs of being fixed :( Will push when I have some proper internet

**Comment by npomfret** [comment]
@cymp #1723 has been submitted.  The cryptopia API isn't as fully featured as some others but I've implemented everything that fits into this project.

Have tested making orders, cancelling orders, getting trade history, account balances, wallet addresses etc.

Please take a look and test whenever your ready.

My BTC wallet address is 1K5dYadQBBkTR3L4RkktMiNaJbx8uRRyyq - sorry for the delay, had no internet for a few days.

Also, could you pay the remaining 10mbtc for the multi currency stuff?  I use it in my project and it seems to work well.

**Comment by cymp** [comment]
Thank you! I will test everything next week, but your 85mBTC payment (75 + 10 if I am correct) has been sent to 1K5dYadQBBkTR3L4RkktMiNaJbx8uRRyyq.

**Comment by npomfret** [comment]
@cymp thanks very much, funds received.  Please let me know if anything isn't quite as expected.
