### ISSUE TITLE
[Okcoin] Withdraw crypto not working

### ISSUE THREAD

**Issue by MartianTech** [timmolter/XChange#1710]
There are a few things wrong with the current implementation. 
First it's the currency symbol. It should be changed to something like this. We also need to differentiate okcoin.com (International) with `btc_usd` and okcoin.cn with `btc_cny`.

```
--- a/xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinAccountService.java
+++ b/xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinAccountService.java
@@ -44,15 +44,27 @@ public class OkCoinAccountService extends OkCoinAccountServiceRaw implements Acc
   }
 
   @Override
-  public String withdrawFunds(Currency currency, BigDecimal amount, String address) throws IOException {
-    String okcoinCurrency = currency == Currency.BTC ? "btc_usd" : "btc_ltc";
+  public String withdrawFunds(Currency currency, BigDecimal amount, String withdrawAddress) throws IOException {
+         //    String okcoinCurrency = currency == Currency.BTC ? "btc_usd" : "btc_ltc";
 
-    OKCoinWithdraw result = withdraw(null, okcoinCurrency, address, amount);
+         String withdrawCurrency = null;
 
-    if (result != null)
-      return result.getWithdrawId();
+         if (currency == Currency.BTC) {
+                 withdrawCurrency = "btc_cny";
+         } else if (currency == Currency.LTC) {
+                 withdrawCurrency = "ltc_cny";
+         } else if (currency == Currency.ETH) {
+                 withdrawCurrency = "eth_cny";
+         } else {
+                 throw new IllegalArgumentException("Unsupported currency");
+         }
 
-    return "";
+         OKCoinWithdraw result = withdraw(null, withdrawCurrency, withdrawAddress, amount);
+
+         if (result != null)
+                 return result.getWithdrawId();
+
+         return "";
   }
```

Then it's the fee. They have different required fees for currencies. It can be changed into something like this - 
```--- a/xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinAccountServiceRaw.java
+++ b/xchange-okcoin/src/main/java/org/knowm/xchange/okcoin/service/OkCoinAccountServiceRaw.java
@@ -1,14 +1,14 @@

 public class OkCoinAccountServiceRaw extends OKCoinBaseTradeService {
   private final String tradepwd;
 
@@ -38,9 +38,22 @@ public class OkCoinAccountServiceRaw extends OKCoinBaseTradeService {
     return returnOrThrow(futuresUserInfoCross);
   }
 
-  public OKCoinWithdraw withdraw(String assetPairs, String assets, String key, BigDecimal amount) throws IOException {
-    OKCoinWithdraw withdrawResult = okCoin.withdraw(exchange.getExchangeSpecification().getApiKey(), assets, signatureCreator, "0.0001", tradepwd,
-        key, amount.toString());
+  public OKCoinWithdraw withdraw(String assetPairs, String assets, String withdrawAddress, BigDecimal amount) throws IOException {
+         String fee;
+         
+         if (assets.equals("btc_cny")) {
+                 fee = "0.0001";
+         } else if (assets.equals("ltc_cny")) {
+                 fee = "0.001";
+         } else if (assets.equals("eth_cny")) {
+                 fee = "0.01";
+         } else {
+                 throw new IllegalArgumentException("Unsupported currency");
+         }
+         fee = "0";
+         
+    OKCoinWithdraw withdrawResult = okCoin.withdraw(apikey, assets, fee, tradepwd,
+                   withdrawAddress, amount.toString(), "okcom", signatureCreator);
 
     return returnOrThrow(withdrawResult);
   }
```
The withdraw method in OkCoin.java is missing a parameter "target" as required in the API doc
https://www.okcoin.com/about/rest_api.do
```
target: withdraw address type. okcoin.cn:"okcn" okcoin.com:"okcom" okes.com："okex" outer address:"address"
```

After I fix those, I keep getting a 10007 error code meaning "Signature does not match". I'm using the same API key and secrete key for trading, which works fine. 

Then I'm stuck because I don't know how to debug the signing.

Thanks in advanced if anyone can help.

**Comment by timmolter** [comment]
The signing it sometimes tough to debug, and is more or less trial and error. Is it only failing for certain endpoints or all endpoints in general?

**Comment by MartianTech** [comment]
@timmolter Just failing for withdrawing crypto. Account info and Trading service are working fine. Trying to fix this for a while and even reached out to their technical team but couldn't figure out the signing. Hope to get some help here.

**Comment by timmolter** [comment]
Can you submit a PR for the fixes you've already implemented? Then I can look at the withrow impl. You're saying the following is not working right?

`POST /api/v1/withdraw BTC/LTC/ETH Withdraw` from <https://www.okcoin.com/about/rest_api.do>

**Comment by MartianTech** [comment]
That's correct. I'd follow up with a PR. Thanks in advance.

**Comment by MartianTech** [comment]
@timmolter Following up with #1717

**Comment by timmolter** [comment]
Sorry, I looked into it, but I don't see any obvious mistakes. I don't know how to further help you on this! :(

**Comment by odaken** [comment]
@MartianTech
I don't have much confident with directly connect your issue but I experience a wrong signature issue before because of wrong encoding 'tradepwd'.  PR #1722

**Comment by MartianTech** [comment]
@odaken Thanks for working on this! I'd love to try it out. Does it work for you?

**Comment by MartianTech** [comment]
Btw, Okcoin is charging absurdly high network transaction fee - 0.002 for BTC. At the current price it's over $8 per withdraw. Comparable to bank wire transfer.

**Comment by MartianTech** [comment]
@odaken Hey man, I patched your PR and tested again. Although it was still failing, you were correct that it was due to encoding. My trade password had special symbols, which caused problem in encoding. I changed the trade password and now it works! Your insight is much appreciated.

**Comment by odaken** [comment]
@MartianTech I am grad hearing from you that it works. I did not confirm this patch works in trade password includes special characters but the patch is working without special characters password.

I totally agree Okcoin expensive trade fee. They did not accept withdrawal in case we gives lower fee and interestingly even specify higher fee. As far as I experiencet the fee has to be exactly adjusted up to date value.

@timmolter  Although this patch may not fix 100% cases but I think better to apply.

**Comment by MartianTech** [comment]
Yea what's even worse that the okcoin only apply a small portion of the fee they charge for actual transfer transaction. It means they kept the rest. 

This PR is legit. We should merge it. Thanks for your work again.

**Comment by timmolter** [comment]
Excellent work!
