### ISSUE TITLE
Kraken : Withdrawing to a bitcoin address 

### ISSUE THREAD

**Issue by mannuodesk** [timmolter/XChange#1719]
I want to know that how will I be able to use kraken API for withdrawing BTC to a bitcoin address without adding that address as a beneficiary in the Kraken User Web Portal???

As I am getting error for invalid withdraw key in case providing BTC Address to withDraw function.

**Comment by MartianTech** [comment]
As far as I know, you can't. Notice that the withdraw key isn't the actual BTC address, but the description you put in when you adding the address via web UI.

**Comment by asoedibjo** [comment]
Is there a way then to retrieve programatically/through API those address / keys we configured via web UI?
I can't find API docs that explain this.

Thanks,
Andy
