### ISSUE TITLE
[Kraken] CurrencyPair misspelled CHE/UR -->BCH/EUR

### ISSUE THREAD

**Issue by IceSte86** [timmolter/XChange#1720]
`private static void generic(Exchange krakenExchange) throws IOException {

    // Interested in the private trading functionality (authentication)
        TradeService tradeService = krakenExchange.getTradeService();

    // Get the trade history
        Trades trades = tradeService.getTradeHistory(tradeService.createTradeHistoryParams());
        List<Trade> tradeHistory = trades.getTrades();
        for (Trade t : tradeHistory) {
              System.out.println(t.getCurrencyPair().toString();}
}`

In this case of a trade with Currency Pair is "BCH/EUR" the system will return "**CHE/UR**" (currencyPair=**CHE/UR** - printing the whole Trade Objst) - same happen printing the whole Trade object for the " feeCurrency='**UR**'" - There is no get method for feeAmount and feeCurrency.

To be noticed that the currecnyPair si recognised while getting open orders instead (currencyPair=**BCH/EUR**) - even if it is not defined among the available CurrencyPair (e.g. CurrencyPair.XRP_EUR).

Thanks for your help!

**Comment by npomfret** [comment]
Have you tried the latest snap shot build?

**Comment by IceSte86** [comment]
Hi Nick!
Yes, I am using the latest release. Could not solve it niether using workaround creating the Currency Pair

```
CurrencyPair cpSelfMadeBCHEUR = new CurrencyPair("BCH", "EUR");

CurrencyPair cpSelfMadeBCHEUR2 = new CurrencyPair(new Currency("BCH"), Currency.EUR);

CurrencyPair cpSelfMadeBCHEUR3 = new CurrencyPair("BCH/EUR");
```

None of this work. I noticed something similar with DASH, CurrencyPair comes as DAS/EUR from open orders and can't be used for creating a new one - this can be solve by intercepting this case and creating the CurrencyPair manually...

Can't find solution for BCH, let me know if you have any hints on this.

Thanks!

**Comment by npomfret** [comment]
I'm sorry I don't fully understand the problem.  You're saying that a BCH/EUR trade on Kraken come out in the trade history as CHE/UR?  If so it looks like the 'B' is missing, yes?

**Comment by Achterhoeker** [comment]
@IceSte86 So an open order is reported as DAS/EUR ? That is strange, i've just checked it, an open order is in my used code reported as DASH/EUR (as expected) You are really sure you are using the latest available code ? (for several weeks ago open orders were reported as DAS/EUR. )

**Comment by timmolter** [comment]
Note: latest snapshot code (develop branch) is more up to date than the latest release (on Maven central).

**Comment by IceSte86** [comment]
Hi all!
You're right. I am using the latest release 4.2.1 (both Core and Kraken)(http://search.maven.org/#search%7Cga%7C1%7Corg.knowm.xchange), not the latest snapshot. At this point I build some work-around, so I will wait for the next stable release before updating my code. 
Only one thing I could not adjust, the creation of a Currency BCH recognised by Kraken (thus I cannot trade programmaticaly with that currency).
As you said this is already solved in the actual SNAPSHOT, so if it is not too far away I will wait for it to be published as official release.
Thanks all of you for the support.

**Comment by timmolter** [comment]
FYI, here's info on the release schedule.

<https://github.com/timmolter/XChange/wiki/Frequently-Asked-Questions>

**Comment by IceSte86** [comment]
Great! Thanks again!
PS nice job by providing support and regular development support for all these platform. I just start interacting with the cryptocurrency world... hope that as developer I may help in the future.
