### ISSUE TITLE
GDAX Deposit History

### ISSUE THREAD

**Issue by coreshift** [timmolter/XChange#1727]
I was going to ask on Twitter since this may not be an issue, but the account doesn't seem to be very active. Sorry if this is the wrong place to ask.

Going by the example code "Get Bitcoin Account Info from Bitstamp", I looked at GDAXAccountServiceRaw to find the proper method. It doesn't contain any deposit methods and neither does GDAXAccountService. 

I also looked at GDAXAccountService.getFundingHistory() thinking it might be related, but it just throws a NotYetImplementedForExchangeException.

Is getting GDAX deposit history not yet implemented or am I just looking in the wrong places?

**Comment by npomfret** [comment]
That's correct, it's not implemented on gads yet.

**Comment by npomfret** [comment]
... and its a really useful feature that's missing in quite a few implementations (although some exchanges strangely don't support it).

**Comment by timmolter** [comment]
Was this completed in your last PR by chance?

**Comment by npomfret** [comment]
Yes.  

We found a better API call in the coinbase API that give more information (such as the external txn id) but haven't worked out a nice way to use the coinbase URI in the gdax implementation yet.  

Maybe I'll do some more work on it soon, but for now please close.

**Comment by timmolter** [comment]
OK, thanks!
