### ISSUE TITLE
[Gdax] [Feature request] getFundingHistory implementation 

### ISSUE THREAD

**Issue by MartianTech** [timmolter/XChange#1728]
Currently GDAXAccountService doesn't have implementation for 
`public List<FundingRecord> getFundingHistory(TradeHistoryParams params) throws IOException`
It'd be very useful if someone can implement this. 

I've looked into the API. Although they don't have direct support for this method, we can use 
`GET /accounts/<account-id>/ledger` and look for type of `transfer`

https://docs.gdax.com/#get-account-history

**Comment by npomfret** [comment]
What about https://docs.gdax.com/#list-fundings ?  Is that different?

**Comment by npomfret** [comment]
Also `/reports`??

**Comment by MartianTech** [comment]
https://docs.gdax.com/#list-fundings is for margin funding 
"Every order placed with a margin profile that draws funding will create a funding record."

https://docs.gdax.com/#reports is for generating pdf or csv of fills or account statements.

I think https://docs.gdax.com/#get-account-history is the closest thing we can use.

**Comment by MartianTech** [comment]
I saw you already have a PR #1744.
Looking soon. Thanks!

**Comment by npomfret** [comment]
I had a go at implementing it.  There's no network transaction id unfortunately, it must be available somehow because I can see it on the site.

The implementation I've done isn't great but it sort of works.  It handles paging for you internally (like the ANX implementation) so effectively one java API call effectively ends up making several http calls.  It's messy but it's a start.

**Comment by MartianTech** [comment]
For network transaction id, Gdax links to an external website https://etherscan.io but I didn't find any API that will tell you the network transaction id.

**Comment by npomfret** [comment]
Yeah, but in order to make that link they must have the txn id in their system somewhere.  I couldn't find it in the API either though.

**Comment by MartianTech** [comment]
Ok I just found this 
https://developers.coinbase.com/api/v2#transactions
Gdax is a bit unconventional because Coinbase handles the crypto deposit and withdraw with external accounts and then transfer from and to Gdax. 
![image](https://user-images.githubusercontent.com/29751536/29994109-a5d0c664-8f7c-11e7-894a-3a61640096cd.png)

I supposed it could be pretty complicated to implement this since it involve two API end points. Would it be too challenging to do this?

**Comment by npomfret** [comment]
Good find!  I'll take a look later.

**Comment by MartianTech** [comment]
Thanks Nice. Appreciate your great work.

**Comment by MartianTech** [comment]
Thanks Nick. Appreciate your great work.
