### ISSUE TITLE
[60mBTC bounty] Implement full livecoin API support

### ISSUE THREAD

**Issue by cymp** [timmolter/XChange#1730]
I am offering a 60mBTC bounty to whomever finishes the implementation of the Livecoin API, which I believe is [already started](https://github.com/timmolter/XChange/tree/develop/xchange-livecoin/src/main/java/org/knowm/xchange/livecoin).

**Comment by npomfret** [comment]
75 and I could work on it today. I think it could get an initial PR with full implementation within a day or so.

**Comment by cymp** [comment]
Fine, there you go!

**Comment by npomfret** [comment]
Cool.

I've done the bulk of the work but the API has been down since I started so haven't been able to test at all.  Have raised support tickets and queried them on twitter but no response so far.  Will try again tomorrow.

**Comment by npomfret** [comment]
Got a message from livecoin saying that their api is partially disabled due to a DDOS attack.  Will try again later today.

**Comment by npomfret** [comment]
The livecoin API finally came back. Here's the https://github.com/timmolter/XChange/pull/1751

**Comment by cymp** [comment]
@npomfret I finally got a chance to start working on this. Thanks for your work.

For now: 
- Missing getAllTickers
- Missing getAllOrderBooks
- getOrderBook misses parameter groupByPrice
- some coinbase code has been copied/pasted, maybe some cleaning is needed here and there as some variables have coinbase names

I will continue working on it tomorrow.

**Comment by npomfret** [comment]
Hi
Thanks for the feedback. Am away right now but will look at it when I get
back.

Nothing has been copy pasted by me, where exactly did you find this?

**Comment by cymp** [comment]
LivecoinMarketDataServiceRaw, there are some "coinbaseEx" occurences, maybe not you though, as the livecoin implementation had already been started by someone else.

**Comment by npomfret** [comment]
Ah yes, I think I remember

**Comment by npomfret** [comment]
@cymp I checked the code, there's no coinbaseEx references except for one parameter in the adapter class (which I've renamed).  Maybe you were looking at some old code.

**Comment by cymp** [comment]
You must be right, I was looking at 4.2.2-SNAPSHOT, maybe I haven't updated the sources.

**Comment by npomfret** [comment]
@cymp are you able to pay the bounty on this yet? 1K5dYadQBBkTR3L4RkktMiNaJbx8uRRyyq

**Comment by cymp** [comment]
Ok sure, I am paying it right now. Did you get a chance to work on the feedbacks I provided you?

**Comment by npomfret** [comment]
I couldn't find the things you mentioned

**Comment by npomfret** [comment]
`getAllTickers` is a non standard call that a couple of exchanges have chosen to implement.  It's not on the the exchange api  _public API_ call.

Same for `getAllOrderBooks`. We've discussed adding this to the public API, but it hasn't been done yet.

> getOrderBook misses parameter groupByPrice

Not quite sure what you mean here, but as above I think this is non-standard behaviour.

> some coinbase code has been copied/pasted

Couldn't see this.

**Comment by cymp** [comment]
I am using 'PoloniexMarketDataServiceRaw.getAllPoloniexDepths', which calls 'Poloniex.getAllOrderBooks' and is very convenient in order to have all of the books in just one API call. 'getAllTickers' is very useful for the same reason. These features are vital (at least for me) because the Livecoin API call restrictions are not very permissive.

It is true that it is not in the xchange public api, but my request, as written in the title, was to "implement the full livecoin api" and I expected these call to be implemented. 

Please let me know if you don't wish to implement them.

I have just realized that I had to give you 75mBTC and not 60mBTC. The remaining 15mBTC are on their way to 1K5dYadQBBkTR3L4RkktMiNaJbx8uRRyyq.

Thank you for you work!

**Comment by npomfret** [comment]
We've discussed adding these methods to the public api - maybe now is the time.  

@timmolter thoughts on migrating the API?  i made a similar change a while back that allowed more complex parameters to be specified for exchanges that support them.

**Comment by npomfret** [comment]
@cymp for future work you should be clear that you need the full exchange api, and not just the public xchange api implementing.  I personally wouldn't take on this work. Some of these exchanges API's are enormous and/or crazy hard to implement.  If the work is limited to the xchange public API it's a much more defined scope and therefor it's much easier to predict how much work there will be.

**Comment by cymp** [comment]
@npomfret I thought "Implement full livecoin API support" was clear enough, sorry if I didn't make myself clear, I will write more than 2 lines in the future :)

**Comment by cymp** [comment]
I created a [PR](https://github.com/timmolter/XChange/pull/1793) for getAllOrderbooks, and getAllTickers was already there in the end.

**Comment by timmolter** [comment]
Can this be closed?

**Comment by cymp** [comment]
@timmolter Yes sure
