### ISSUE TITLE
There is no way to use this project, and too many methods are missing implement

### ISSUE THREAD

**Issue by nntaoli** [timmolter/XChange#1732]
There is no way to use this project, and too many methods are missing implement

**Comment by Achterhoeker** [comment]
Perhaps i'm a strange person, but my own written bot is using this project successful for several years now.

**Comment by e1ektr0** [comment]
For most popular exchanges most of important methods are implemented and working fine.

**Comment by nntaoli** [comment]
sorry，I am a quick temper ，in the future my code pull request to xchange。

**Comment by douggie** [comment]
Cointrader auromated trading platform has been using this project for many
years without issue.
