### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by e1ektr0** [timmolter/XChange#1734]
I'm using https://jitpack.io for cmpile project, and it's failed:
(https://jitpack.io/com/github/timmolter/XChange/7c3ca254fd/build.log)

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/jitpack/build/xchange-yobit/src/main/java/org/knowm/xchange/yobit/YoBitAdapters.java:[134,18] cannot find symbol
  symbol:   method join(java.lang.String,java.util.List<java.lang.String>)
  location: class java.lang.String

As i undestad problem with  String.join("-", pairs)

What should i do? Wait while some one fixed it or create pull request for fix or change java compile version?

**Comment by npomfret** [comment]
What JVM are you using?

**Comment by e1ektr0** [comment]
As i say, i build it with jitpack io. And as i undestand, it using maven-compiler-plugin 1.7, cose this version set in pom.xml

**Comment by timmolter** [comment]
Is String.join() Java 8? If so that should be replaced.

**Comment by e1ektr0** [comment]
Yes, it's java 8. Should i create a pull request for it, or better wait while some one fix it, coze i'm not good in java :-)

**Comment by npomfret** [comment]
That was probably me.  I'd accidentally commit some java 8 stuff but thought i'd removed it.  The build went green I'm sure.

**Comment by npomfret** [comment]
https://github.com/timmolter/XChange/pull/1736

**Comment by timmolter** [comment]
It's strange to me that Travis CI and my IDEs (Eclipse and Intellij) didn't catch this issue because the JRE is defined as 1.7 in the `pom.xml`. I'm using JDK 8, but it used to work fine and catch these issues.
