### ISSUE TITLE
[QUESTION] metadata json file 

### ISSUE THREAD

**Issue by lucarosellini** [timmolter/XChange#1735]
Hello everybody,
is there a reason why the metadata override json file is loaded from the filesystem instead of the classpath in [BaseExchange#applySpecification](https://github.com/lucarosellini/XChange/blob/develop/xchange-core/src/main/java/org/knowm/xchange/BaseExchange.java#L77) ?

The absolute filename of the json file is not always easy to retrieve, especially in tests.

Thanks in advance,
Luca

**Comment by npomfret** [comment]
As far as I know it's always loaded from the classpath.

**Comment by timmolter** [comment]
By default it loads it from the classpath. If you want to override that one which comes with the project in "resources" you can do two things:

1. Replace the one in resources with your own.
1. Point to one on the file system somewhere.
