### ISSUE TITLE
bitcoin cash BCH v's BCC

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#1738]
Does anyone have a good strategy for dealing with the fact that different exchanges use different names for the same currency.  The most obvious example is bitcoin cash, which is defined as BCH in this project.  I've found 4 exchanges (BleutradeExchange, DSXExchange, HitbtcExchange, YoBitExchange) that call it BCC.

**Comment by Achterhoeker** [comment]
Bittrex is also cash naming bcc. I've a local translation table for every exchange above xchange that can translate these extraordinaire cases.

**Comment by npomfret** [comment]
I'm beginning to think adding bitcoin cash as BCH was the wrong thing to do.  It looks like maybe more exchanges are using BCC despite the fact that BCC is already in use on some exchanges for a totally different coin.

Maybe this project is just missing an abstraction.  Perhaps the API should be using a higher level concept?  Imagine constants `BITCOIN` and `BITCOIN_CASH`, one for each currency, and it's these that are used in the public API instead of the current `Currency` objects.  Then each exchange maps that constant to a symbol.  Most exchanges would use exactly the same mapping, but those with _non-standard_ naming conventions for their symbols could map their data appropriately.  Each exchange would then be responsible for mapping their own (potentially non-standard) symbols into the constants defined by the public API.

@timmolter any thoughts?

**Comment by EzBar** [comment]
Why can't it just be defined as an alternative code, the same way XBT is defined for BTC?
I.e., updating BCH definition in Currency.class and adding BCC (which isn't listed) as a reference:
public static final Currency BCH = createCurrency("BCH", "BitcoinCash", "BCC");
public static final Currency BCC = getInstance("BCH");

**Comment by Achterhoeker** [comment]
@EzBar That would give the problem that bcc is always seen as bch. And that is incorrect for some exchanges where bcc is in use for a total other altcoin. Bittrex for example has bcc and bch (2 different coins and markets). Those markets would be seen as the same using your proposal.

**Comment by EzBar** [comment]
I don't think there's a BCH currency at Bittrex.
I think the only conflict is with Livecoin's BCC which refers to BitConnect (limiting only to supported exchanges). 
Is it possible to change Bittrex at the Adapter level? Translating any occurrence of BCC to BCH

**Comment by Achterhoeker** [comment]
@EzBar 
sorry, you are correct, I was to quick with my answer. 
The exchange with both currencies is bitfinex. BCH is there bitcoin cash and BCC is a local virtual coin.
Poloniex is also signaling BCC and BCH, but BCC doesn't seem to have any markets there anymore. (BCC as an other altcoin!)

BCC is BCH on bittrex and Bleutrade.
