### ISSUE TITLE
Question on extending FundingRecord types

### ISSUE THREAD

**Issue by Arthurm1** [timmolter/XChange#1741]
Currently `FundingRecord#Type`supports `WITHDRAWAL`and `DEPOSIT `.

Kraken API also returns a `TRADE` type (which is ignored) and I see GDAX has `MATCH`, `FEE `and `REBATE` although I'm not using GDAX

I'd like to add `TRADE ` as a type and then implement it for Kraken and I can see where to do this but I don't know enough about the code to know if this is a good idea or whether full ledgers have been implemented already elsewhere.

The downside of this is that anyone currently retrieving the Kraken funding history would then get all the trade records as well unless they've specifically set the `HistoryParamsFundingType`.

My reason for this is I'd like to be able to calculate balances on a specific date which is not possible with the deposit/withdrawal/trade history on Kraken as it doesn't give enough information about fees.

**Comment by npomfret** [comment]
This feels to me something that could be achieved by exposing this data from a public method on `KrakenAccountServiceRaw`.  In fact is it there already `getKrakenLedgerInfo`?  

As it's a Kraken specific _thing_ I don't think it belongs in the public API.

**Comment by Arthurm1** [comment]
Thanks.  If it's OK to put exchange specific stuff into the `XXXAccountServiceRaw `classes then I'll do that.
