### ISSUE TITLE
BTCChina makes gradle build fail

### ISSUE THREAD

**Issue by andrewlin0410** [timmolter/XChange#1752]
So whenever I add btcchina into my app it fails. 
Error:Execution failed for task ':app:transformResourcesWithMergeJavaResForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK FIX44.xml
	File1: C:\Users\Andrew Lin\.gradle\caches\modules-2\files-2.1\org.quickfixj\quickfixj-messages-fix44\1.6.3\2fa788e985e84209b9ec93bd3ba9d54d6ea3da9d\quickfixj-messages-fix44-1.6.3.jar
	File2: C:\Users\Andrew Lin\.gradle\caches\modules-2\files-2.1\org.quickfixj\quickfixj-core\1.6.3\ec343bfa7cc95cafc1559242349331ba34dd456c\quickfixj-core-1.6.3.jar

How to solve?

**Comment by timmolter** [comment]
I don't know, but try googling: `com.android.builder.packaging.DuplicateFileException`. Might need to exclude the FIX44.xml file in the gradle config.

**Comment by andrewlin0410** [comment]
Can you reopen this since I can't find an answer on google. I believe this very much likely occurs to other people as well.

**Comment by andrewlin0410** [comment]
It seems this only happens to android

**Comment by timmolter** [comment]
btc china has been removed from XChange.
