### ISSUE TITLE
[Kraken] Placing order timeout

### ISSUE THREAD

**Issue by MartianTech** [timmolter/XChange#1758]
I've been having issues of its placing orders takes super long time to return and often result in a timeout. I don't have this problem with other exchanges. Is this a known issue on XChange or Kraken's end?

**Comment by timmolter** [comment]
You can increase the timeout param: <https://github.com/timmolter/XChange/wiki/Frequently-Asked-Questions#where-if-anywhere-are-the-http-read-timeouts-configured>

**Comment by MartianTech** [comment]
I've increased it to 30s, which is way longer than reasonable. In the event of timeout, what's your best practice?

**Comment by timmolter** [comment]
I would catch the exception and do whatever makes the most sense. I've heard Kraken's API is really bad under load.

**Comment by MartianTech** [comment]
Yea what i'm doing in case of timeout exception. I'd check the open orders and filled trade to see if that order has been placed. Have to code much more defensively for Kraken. Wanna see if other folks are also experiencing this issue. If yes, then it's mostly their server side's.

**Comment by MartianTech** [comment]
I think I can conclude that it's just their server's performance is bad because this also happens on the web UI. I'm going to close this issue.

**Comment by Achterhoeker** [comment]
Kraken is a big mess currently. I've set my timeout to several minutes. You need a time out from their side. If your side has a timeout and you use the api again, Kraken gives you a ban for several minutes. Almost all times a time out from the Kraken side the order isn't placed. (or a service unavailable error). A 502 error is a big guess what happened (trade done or not)

**Comment by MartianTech** [comment]
@Achterhoeker Thanks for confirming this. I had to write a lot of code to verify if an order has been placed or not. Even with that, it became unusable because their server's availability and performance are too bad to use for my trading strategy. It'd be great if you can let me know when they fix this. Their customer services are pretty good on the other hand.

**Comment by ww3456** [comment]
I stopped using Kraken over two months ago because of the large number of timeouts and general unreliability. I was thinking of seeing whether things have improved but it seems not!
