### ISSUE TITLE
Nonce precision

### ISSUE THREAD

**Issue by MartianTech** [timmolter/XChange#1759]
This might be a dumb question but why some exchange's implementation round down the nonce value from system clock? 

For example 
```
Gdax 
public class CurrentTime1000NonceFactory implements SynchronizedValueFactory<Long> {

  @Override
  public Long createValue() {

    return System.currentTimeMillis() / 1000L;
  }
}
```

```
Gemini
private static final long START_MILLIS = 1356998400000L; // Jan 1st, 2013 in milliseconds from epoch
  private final AtomicLong lastNonce = new AtomicLong((System.currentTimeMillis() - START_MILLIS) / 250L);
```

According to Gemini, "We recommend using a timestamp at millisecond or higher precision. "
https://docs.gemini.com/rest-api/#private-api-invocation

So why don't we use `System.currentTimeMillis()` directly but need to round it down?

**Comment by timmolter** [comment]
I'm not sure how that got in there. You're analysis makes sense though. Would you test it and if it works, submit a PR with the improvement?

**Comment by MartianTech** [comment]
PR #1770
