### ISSUE TITLE
How to turn off those DEBUG messages

### ISSUE THREAD

**Issue by Leungfranklin** [timmolter/XChange#1763]
When I run the demo program, I usually get many DEBUG statements like below in my output:
10:50:19.695 [default] [main] DEBUG
si.mazi.rescu.HttpTemplate - Request http status = 200

How can I turn it off? I try to remark all those logger.info, logger.debug statements but those still appear in my output

**Comment by timmolter** [comment]
See step 3: <https://github.com/timmolter/XChange/wiki/New-Implementation-Best-Practices>

Look for the `logback.xml` file to set the log level.

**Comment by playscorer** [comment]
How do we do if we are using the xchange library as dependency?
By changing it my own log4j.xml it does not take in account.
