### ISSUE TITLE
Bitfinex v2 support (Bounty 0.1 BTC)

### ISSUE THREAD

**Issue by serhansevim** [timmolter/XChange#1764]
Any plans on adding bitfinex rest/websocket v2 api into the library? 
OHLC data is now supported so it would be very nice add. 

Thanks,

**Comment by timmolter** [comment]
Websocket = No. See README for a link to our partner websocket lib. I don't know of anyone working on the REST V2 API. If you posted a bounty, it'd surely get done!

**Comment by serhansevim** [comment]
Just updated this issue with 0.1 BTC bounty. Let's see how this will work out.

**Comment by timmolter** [comment]
I added the bounty tag.

**Comment by EricAnderson1000** [comment]
Very interested... might have time this weekend if someone else doesn't claim it first.

**Comment by serhansevim** [comment]
@EricAnderson1000 sure it's yours. Open a pull request when completed. Upon merging into the main library I'll have it transferred to your bitcoin account.

**Comment by EricAnderson1000** [comment]
I'm still working on this... it looks like bitfinex made some crazy API response choices.
```
curl https://api.bitfinex.com/v2/tickers?symbols=tBTCUSD,fUSD
[["tBTCUSD",5959.9,82.07324724,5960,95.39246846,-180.2,-0.0293,5960,57085.70887683,6166.8,5705],["fUSD",0.00184007,0.001321,30,2551369.97249744,0.001391,2,262513.21961291,-0.000297,-0.186,0.0013,151359033.7897417,0,0]]

 curl https://api.bitfinex.com/v1/pubticker/BTCUSD
{"mid":"6011.65","bid":"6010.0","ask":"6013.3","last_price":"6012.9","low":"5705.0","high":"6166.8","volume":"57846.53102329","timestamp":"1508686613.9543736"}

```
Notice the missing property names in the JSON responses in the new API.

**Comment by EricAnderson1000** [comment]
@serhansevim Code is coming along nicely. I have all the MarketData calls implemented and tests added. Here is the branch I am working on

https://github.com/timmolter/XChange/compare/develop...EricAnderson1000:bitfinexV2Support

**Comment by EricAnderson1000** [comment]
@serhansevim Are you still interested in this feature? I just need to implement about 35% more.

**Comment by lukaszaoralek** [comment]
Hi, I've written xchange-stream module for bitfinex (based on wss://api.bitfinex.com/ws/2). I made PR there (https://github.com/bitrich-info/xchange-stream/pull/22). But, you can test it now (https://github.com/lukaszaoralek/xchange-stream/tree/poloniex/xchange-bitfinex)

...and if you like it I don't complain for bounty. :)
