### ISSUE TITLE
Bitfinex open orders adaptation

### ISSUE THREAD

**Issue by pavlo-pastushok** [timmolter/XChange#1766]
I propose set remaining amount instead of original to LimitOrder on adapting Bitfinex open orders (reason: amount in open orders never change until full order operation)

Place: BitfinexAdapters.java, 294 line

`limitOrders.add(new LimitOrder(orderType, order.getOriginalAmount(), currencyPair, String.valueOf(order.getId()), timestamp, order.getPrice(),
          order.getAvgExecutionPrice(), order.getExecutedAmount(), status));` 

-> 

`limitOrders.add(new LimitOrder(orderType, order.getRemainingAmount(), currencyPair, String.valueOf(order.getId()), timestamp, order.getPrice(),
          order.getAvgExecutionPrice(), order.getExecutedAmount(), status));`

**Comment by timmolter** [comment]
Can you submit a PR for this?

**Comment by pavlo-pastushok** [comment]
okay, I will do that.

**Comment by pavlo-pastushok** [comment]
done, please check my PR
