### ISSUE TITLE
createExchange method with generic

### ISSUE THREAD

**Issue by rostuha1** [timmolter/XChange#1767]
I think it will be better to use generic instead of String exchangeClassName.

For example we can replace this method ->
public Exchange createExchangeWithoutSpecification(String exchangeClassName)

with it ->

    public Exchange createExchangeWithoutSpecification(Class<? extends Exchange> exchange) {
        try {
            return exchange.newInstance();
        } catch (InstantiationException e) {
            throw new ExchangeException("Problem creating Exchange (instantiation)", e);
        } catch (IllegalAccessException e) {
            throw new ExchangeException("Problem creating Exchange (illegal access)", e);
        }
    }

And call: Exchange exchange = createExchangeWithoutSpecification(BittrexExchange.class); without getName() and possible exceptions with it

**Comment by timmolter** [comment]
I considered this, but I'm not so sure it's a problem needing fixing. The most common way to create an Exchange is to use the method with an ExchangeConfiguration, which uses a String for the exchange class name. I think this is advantageous for serialization or creating instances in the most generic way possible, from a config file for example.

I did add overloaded methods with this argument type though!
