### ISSUE TITLE
Any more complete example for submitting orders?

### ISSUE THREAD

**Issue by andrewlin0410** [timmolter/XChange#1769]
I am looking for some examples that submit orders and then check it is filled after sometime. If not, cancel and replace the orders. I need them for making a trading bot.
Are there similar examples? Or anyone willing to share?
Thank you

**Comment by digitalchaotics** [comment]
I'm interested in hearing an answer to this question as well.  I've tried the obvious...

- polling tradeService.getOpenOrders (on Bittrex it's always empty)
- polling tradeService.getTradeHistory (same)

For my next trick I'll be looking for changes in the account balances.  I'll let you know.

**Comment by timmolter** [comment]
Sorry, there are no complex examples like that in XChange. Such code would be welcome though!
