### ISSUE TITLE
Any objections to bumping Java compatibility to Java 8?

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#1771]
For my needs, I don't need Java 7 support. I recall a long time ago, bumping to Java 8 would affect Android developers using XChange. If there are no objections, I'd like to bump XChange up to Java 8.

**Comment by cymp** [comment]
Yes I would love to bump to Java 8. By the way, J9 is released in a couple of days, would it be too risky to directly try to support J9 in XChange?

**Comment by allenday** [comment]
J8 yes, J9 please no

**Comment by cymp** [comment]
Please tell why, could be interesting.

**Comment by allenday** [comment]
Android.
https://www.infoworld.com/article/3180758/mobile-development/android-switches-to-native-java-8-support.html
