### ISSUE TITLE
Poloniex getting order book does not work?

### ISSUE THREAD

**Issue by andrewlin0410** [timmolter/XChange#1774]
It seems it doesn't work. When I put BTC_USD, it returns an empty arraylist. I heard that poloniex uses usdt. Is that the issue?

**Comment by cymp** [comment]
Yes.

**Comment by andrewlin0410** [comment]
How can this not be fixed? It is one of the biggest exchanges.

**Comment by cymp** [comment]
Please try USDT instead of USD.

**Comment by andrewlin0410** [comment]
But there is no USDT in the currency pairs. Did I miss it?

**Comment by timmolter** [comment]
`new CurrencyPair("BTC", "USDT");`
