### ISSUE TITLE
Compilation error in BitfinexAdapter

### ISSUE THREAD

**Issue by pavlo-pastushok** [timmolter/XChange#1777]
In last SNAPSHOT of Bitfinex module, there is compilation error

`limitOrders.add(new LimitOrder(orderType, order.getOriginalAmount(), order.getRemainingAmount(), currencyPair, String.valueOf(order.getId()), timestamp, order.getPrice(),
          order.getAvgExecutionPrice(), order.getExecutedAmount(), status));`

to fix this:

`limitOrders.add(new LimitOrder(orderType, order.getRemainingAmount(), currencyPair, String.valueOf(order.getId()), timestamp, order.getPrice(),
          order.getAvgExecutionPrice(), order.getExecutedAmount(), status));`

And I have a question:
SNAPSHOT version of application is build from develop branch or master?

**Comment by timmolter** [comment]
`develop`. 

It seems to compile just fine: https://travis-ci.org/timmolter/XChange/builds

**Comment by npomfret** [comment]
Not sure what you mean - it's compiling for me right now.  Maybe update your local repo, perhaps a compile error was merged and then fixed?

**Comment by pavlo-pastushok** [comment]
okay, thanks, I will check my local repo

**Comment by pavlo-pastushok** [comment]
sorry, their was problem with SNAPSHOT versions locally, thanks
