### ISSUE TITLE
Does this always get you the latest snapshot? If not, how?

### ISSUE THREAD

**Issue by andrewlin0410** [timmolter/XChange#1780]
allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}

dependencies {
	        compile 'com.github.timmolter:XChange:master-SNAPSHOT'
	}

**Comment by timmolter** [comment]
That looks like gradle. I'm not familiar with it, so I cannot give you an answer.

**Comment by andrewlin0410** [comment]
It is gradle. Other people may be able to answer so can you reopen it?

**Comment by npomfret** [comment]
If you want the snapshot use 

    compile 'org.knowm.xchange:xchange-anx:4.2.3-SNAPSHOT'
    compile 'org.knowm.xchange:xchange-bitbay:4.2.3-SNAPSHOT'
    compile 'org.knowm.xchange:xchange-bitcoinaverage:4.2.3-SNAPSHOT'
    ...

If you don't want the snapshot just use the version number without `-SNAPSHOT`.

**Comment by andrewlin0410** [comment]
In case somebody else stumbles upon this, it should be like this:
repositories {
mavenCentral()
maven { url 'https://jitpack.io' }
}
dependencies {
testCompile group: 'junit', name: 'junit', version: '4.12'
compile 'com.github.timmolter:XChange:develop-SNAPSHOT'
}
