### ISSUE TITLE
Does this library support concurrent data downloading?

### ISSUE THREAD

**Issue by andrewlin0410** [timmolter/XChange#1781]
I am trying to download market data from multiple exchanges for multiple coins at the same time. For example, I create a MarketDataService instance for GDAX. Then I will call .getOrderBook(...) for multiple coins in different threads. Will they block each other and slow down the download? Should I create a MarketDataService instance for each thread? Which way will be faster?
What I did was the second way. But the data downloading is extremely slow. I don't know if it is because I am inexperienced at programming or because this library shouldn't be used in this way.

**Comment by timmolter** [comment]
You'll want it to be multi-threaded. I use [Sundial](https://github.com/timmolter/Sundial) to run repeatable jobs that run in their own threads.

I've done both a global `MarketDataService` as well as creating a new one each time, and the speed is the same. It doesn't matter.

**Comment by andrewlin0410** [comment]
It seems creating an exchange takes about 500 ms on my computer. That converts to more than 10 seconds since I create instances for a few coins on many exchanges. I did every exchange creation in a callable and used executorservice's submit. Is this not the right way for multi-threading? Or is it just my computer is not fast enough? I run the program in Intellij and my computer's processor is i7 8550u.

**Comment by timmolter** [comment]
500 ms is a long time so you should just create one instance per exchange and store them globally accessable by the threads. Do don't need one per currency pair either.

**Comment by andrewlin0410** [comment]
Can you briefly explain how you store the instances globally. What I tried is creating a class called Variables and I create instances like this.     
static MarketDataService gdaxMarketDataService = ExchangeFactory.INSTANCE.createExchange(GDAXExchange.class.getName()).getMarketDataService();
But then when I try 
                   Ticker ticker = Variables.gdaxMarketDataService.getTicker(CurrencyPair.BTC_EUR);
It gives me no class defined error. I guess the reason is that when the thread is getting ticker, the instance has not been created yet??? So I made the thread where my Executorservice is in to sleep for 15 seconds to wait for instance creations, but it still gives me NoClassDefFoundError.

**Comment by timmolter** [comment]
Sorry, I cannot help you with that. Good luck!
