### ISSUE TITLE
TradeService.cancelOrder(String orderId) can't always be implemented

### ISSUE THREAD

**Issue by cymp** [timmolter/XChange#1797]
Hello,

I found out that some exchanges don't provide the API required to implement TradeService.cancelOrder(String orderId). For example, at least Livecoin and Binance require to provide the currency pair, in addition to the order ID. This method being one of the most used, I am not sure what to do here: changing it to TradeService.cancelOrder(LimitOrder order) provides overall compatibility but looks too restrictive since most of the exchanges only need the order ID, whereas leaving it as it is and put some specific code in the involved exchanges implementation trade services is not good for the global use of the library.

Any thoughts?

**Comment by npomfret** [comment]
This has been added, but it might not be supported by the exchange you are using.  The method in question is

`public boolean cancelOrder(CancelOrderParams orderParams)`

And the parameter can support id and currency pair... if it's been implemented (see `TheRockCancelOrderParams` for an example).  Implementing it is usually trivial.

**Comment by cymp** [comment]
Ok thank you I will look into this.
