### ISSUE TITLE
HitBTC v1 - cancel Order  doesn't work

### ISSUE THREAD

**Issue by schabe77** [timmolter/XChange#1803]
I'm unable to cancel an HitBTC Order.

HitBTC's documentation https://hitbtc.com/api#cancelorder states that the cancel request must provide the orginal orderId ("clientOrderId") and an newly generated orderId ("cancelRequestClientOrderId").

  org.knowm.xchange.hitbtc.service.HitbtcTradeServiceRaw.cancelOrderRaw(String):157

uses the same orderId for both fields.

**Comment by EricAnderson1000** [comment]
I can take look into this.

**Comment by EricAnderson1000** [comment]
@schabe77 Please see PR request above.

**Comment by schabe77** [comment]
I tried it and it works fine! Thank you.
