### ISSUE TITLE
http proxy for exchanges

### ISSUE THREAD

**Issue by kyr7** [timmolter/XChange#1823]
Hello,

I'd like to add http proxy support. Rescu has it. I could add proxy host/port to ExchangeSpecification,  and then apply these host/port into every call of RestProxyFactory.createProxy via ClientConfig. Would such pull request be accepted?

**Comment by timmolter** [comment]
The proxy settings could be added as well, as in #1798

**Comment by timmolter** [comment]
I think this is now finished and merged
