### ISSUE TITLE
[60mBTC bounty] Liqui implementation

### ISSUE THREAD

**Issue by cymp** [timmolter/XChange#1825]
Hello,

I would need full XChange implementation for Liqui, including support for a getAllDepths (or getAllOrderBooks), with its 'limit' parameter and a getAllActiveOrdersForAllCurrencyPairs implementation.

I had a very quick look at the api, and it seems pretty straightforward and standard.

[Liqui API](https://liqui.io/api)

**Comment by cerko2** [comment]
I would like to pick this up later this week or during the weekend.

**Comment by cerko2** [comment]
I'm already working on it although only on the weekends atm. Got the public api done, the trade api is almost done as raw services. You can check out the public api in my fork for now.

**Comment by Unbr8kbal** [comment]
@cymp If @cerko2 needs help or if we could work something out, i would be willing to dedicate full-time to this.

**Comment by cerko2** [comment]
Dont really need any help, got almost everything done now just finishing up the adapters for the xchange api's.

**Comment by cerko2** [comment]
Alright, everything should be done now in #1908 including getAllDepths and getAllTickers.
For getAllActiveOrdersForAllCurrencyPairs is getActiveOrders.
The accountService methods I've left unimplemented since Liqui doesnt seem to support any of them.

**Comment by cymp** [comment]
I started to test the library, it seems to work globally thanks. I committed a small bug fix in #1922.

@cerko2 I think getAccountInfo() implementation is missing in the account service, yet Liqui support the wallet information with getInfo. Is there any reason why you did not implement it?

**Comment by cerko2** [comment]
@cymp  My mistake I missed it. It's added in #1925

**Comment by cymp** [comment]
@cerko2 Everything I tested looks fine atm, if you like money, please give me a btc address.

**Comment by cerko2** [comment]
@cymp Awesome, my btc address is 33Se6ELb8kPJnPLYYMVuDc1X3mRw73EYrp

**Comment by cymp** [comment]
60mBTC are on their way to 33Se6ELb8kPJnPLYYMVuDc1X3mRw73EYrp.

**Comment by cerko2** [comment]
Thanks!

**Comment by cymp** [comment]
@cerko2 Would you have any idea about https://github.com/knowm/XChange/issues/2636 ?
