### ISSUE TITLE
getFundingHistory(...) only returns BTC or USD events on Kraken Exchange

### ISSUE THREAD

**Issue by Xion345** [timmolter/XChange#1829]
**Issue Description**
The method `getFundingHistory()` on Kraken Exchange only returns funding events related to BTC or USD when called with the default TradeHistoryParams. Funding events related to other crypto currencies or other fiat currencies are not reported.

Excerpt from the list of *ledger* events (from which the list of funding events is obtained) returned by Kraken:
     
     # Trade ID, Time, Currency
     L4A7EY-DTEIW-QGFBNI 1.5065393701179E9 XXBT <--
     LVEQ4C-EZBY7-XGZ4O5 1.5065365499928E9 XXBT
     LBG4MT-II7DH-T5PZ3K 1.5045581837892E9 XXBT
     LI2P2W-PZ2XZ-YERQNL 1.5045563265951E9 XXBT
     LYOXUE-X5KIJ-T7LTXU 1.5027575075888E9 XXBT
     [...]

Full list of *ledger* events:
 
     LKHKT5-JZ2OZ-4QJ7GT 1506598123.08 ZEUR
     LX3BQJ-ENKTW-YZ2GGL 1506598123.08 XZEC
     LL4JOO-CU3SA-3O2TZL 1506595936.28 ZEUR
     LYH5FF-4AYE3-UWFP2X 1506595936.28 XZEC
     LAN4ZK-IRYA4-6ZOXM4 1506592039.93 ZEUR
     L4CORX-N24IZ-VLNL5T 1506592039.93 XZEC
     LCBN36-X2VCN-TMLOC4 1506543750.7 ZEUR
     LT5Z4K-M53BD-R426DR 1506543750.7 XZEC
     L4TSAZ-SQ3FX-M4DZW5 1506543750.69 ZEUR
     LBDN77-QCRR5-4NUN3I 1506543750.69 XZEC
     L4A7EY-DTEIW-QGFBNI 1506539370.12 XXBT <-- First entry seen by XChange, 
                                                other entries are filtered
     LCOXBC-TADDN-VEGZ2C 1506536550.01 ZEUR
     LVEQ4C-EZBY7-XGZ4O5 1506536549.99 XXBT

**How to reproduce**

    Exchange krakenExchange = ExchangeFactory.INSTANCE.createExchange(
    KrakenExchange.class.getName());
    krakenExchange.getExchangeSpecification().setApiKey("API KEY");
    krakenExchange.getExchangeSpecification().setSecretKey("SECRET");
    krakenExchange.applySpecification(krakenExchange.getExchangeSpecification());
    
    AccountService service = krakenExchange.getAccountService();
    TradeHistoryParams params = service.createFundingHistoryParams();

    // Display ledger entries at the end of KrakenAccountServiceRaw.getKrakenLedgerInfo(...)
    // displayLedger(ledgerResult);

    [...]
    static void displayLedger(Map<String, KrakenLedger> map) {
        ArrayList<Map.Entry<String, KrakenLedger>> entries = new ArrayList<>(map.entrySet());
	entries.sort(new Comparator<Map.Entry<String, KrakenLedger>>() {
            @Override
            public int compare(Map.Entry<String, KrakenLedger> o1,
                        Map.Entry<String, KrakenLedger> o2) {
                if (o1.getValue().getUnixTime() < o2.getValue().getUnixTime()) {
                    return 1;
                } else {
                    return -1;
                }
                }});

        for(Map.Entry<String, KrakenLedger> entry: entries) {
            System.out.println(entry.getKey() + " " + 
                entry.getValue().getUnixTime() + " " + 
                entry.getValue().getAsset());
	  }
     }

**Discussion**

Using the logging framework of mmazi/rescu, I have noticed that XChange adds the `asset=XXBT%2CZUSD` form parameter, even when called with blank arguments. This parameter should be omitted to obtain funding events related to all currencies. My question is the same as for issue #1820 : Is it expected behavior that XChange only returns funding events for BTC and USD by default, or is it a bug ? If it is expected behavior, I think it should be mentioned in the documentation. 

   17:21:11.278 [main] DEBUG si.mazi.rescu.HttpTemplate - Executing POST request at https://api.kraken.com/0/private/Ledgers
   17:21:11.278 [main] TRACE si.mazi.rescu.HttpTemplate - Request body = asset=XXBT%2CZUSD&type=all&nonce=1508426471276

**Comment by timmolter** [comment]
That sounds like a bug.

**Comment by Xion345** [comment]
Ok, I think the root cause is https://github.com/timmolter/XChange/blob/f9638acafb0cdc9c7036d0d8ef4936936f1a30e0/xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenAccountService.java#L68

 KrakenFundingHistoryParams are explicitely created with BTC USD as currency.

**Comment by timmolter** [comment]
Yes, please feel free to fix it and submit a PR!
