### ISSUE TITLE
Are All Chinese Exchanges really shutdown and inactive?

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#1833]
I used to use our BTCC module for market data and one day data flow stopped. What about Huobi, BitVC, other Chinese exchanges? Are any still active?

**Comment by winwish** [comment]
As the crackdown of Bitcoin exchanges in China, BitVC is closed, Huobi moved out as www.huobi.pro, and okcoin moved to www.okex.com, btcchina is closed - I think its overseas branch www.btcc.com is still in operation.

**Comment by timmolter** [comment]
I'll probably remove those modules from XChange then...

**Comment by winwish** [comment]
Maybe they can be modified to
okex:
https://www.okex.com
okex API:
https://www.okex.com/intro_apiOverview.html

huobi.pro:
https://www.huobi.pro
huobi.pro API:
https://github.com/huobiapi/API_Docs_en/wiki

**Comment by timmolter** [comment]
@winwish I changed the endpoints for okex, and none of the demos worked.

**Comment by timmolter** [comment]
@winwish I removed Huobi completely as the new API is completely different so it seems.

**Comment by timmolter** [comment]
I also removed Jubi, chbtc, btc38.
