### ISSUE TITLE
Kraken interval

### ISSUE THREAD

**Issue by Saloed123** [timmolter/XChange#1834]
Hello, how me add period of candles to kraken trades request

**Comment by bibryam** [comment]
KrakenOHLCs krakenOHLC = marketDataService.getKrakenOHLC(CurrencyPair.BTC_USD, interval, last);
intervals could be: 5, 15, 30, 60 (1h), 240 (4h), 1440  (24h), 10080 (1 week), 21600 (15 days)

**Comment by Saloed123** [comment]
Senq, i foubd this solution, but for historical data need use trades

вт, 31 жовт. 2017 о 18:42 Bilgin Ibryam <notifications@github.com> пише:
