### ISSUE TITLE
" Could not find a key matching the given X-BFX-APIKEY." for Bitfinex

### ISSUE THREAD

**Issue by anklavez** [timmolter/XChange#1837]
Hello,

I've tried common code for getting account balance:
```
       ExchangeSpecification exSpec = new BitfinexExchange().getDefaultExchangeSpecification();
        exSpec.setApiKey("apiKey");
        exSpec.setSecretKey("secretKey");
        Exchange exchange = ExchangeFactory.INSTANCE.createExchange(exSpec);
        AccountService accountService = exchange.getAccountService();
        AccountInfo accountInfo = accountService.getAccountInfo();
```
It's works perfect for most of exchanges (Bittrex, Kraken, Poloniex, etc), but for Bitfinex I got an error:
"org.knowm.xchange.exceptions.ExchangeException: org.knowm.xchange.bitfinex.v1.dto.BitfinexException: Could not find a key matching the given X-BFX-APIKEY."

Also  I double checked the keys them self (implement this function with http client), keys work well.

Any thoughts why it doesn't work specifically for Bitfinex?

**Comment by deepland** [comment]
Mr. ankavez can y explain how y resolve it essure? Thank y!
