### ISSUE TITLE
C-CEX listing on the "Exchange Support" wiki is incorrect

### ISSUE THREAD

**Issue by digitalchaotics** [timmolter/XChange#1845]
C-CEX does not have full support for the AccountService or TradeService.

They are both incorrectly listed as  being supported, but I see many instances of "throw new NotAvailableFromExchangeException()" and "throw new NotYetImplementedForExchangeException()" in the implementation.  CCEXAccountService is especially bad, but CCEXTradeService is also missing some critical functions.

Please change those two columns to "N" and "N"

**Comment by timmolter** [comment]
done.
