### ISSUE TITLE
org.knowm.xchange.exceptions.ExchangeException: 0: null.What does this message mean?

### ISSUE THREAD

**Issue by makarid** [timmolter/XChange#1846]
Hello, i have encounter this Exception when i am trying to place a limit order on Bitbay exchange.The code i have write is this:

                            TradeService tradeService = bitbayExchange.getTradeService();
                            BigDecimal tradeableAmount = new BigDecimal("5.00");
                            BigDecimal price = new BigDecimal("4901.15");

                            LimitOrder limitOrder = new LimitOrder(Order.OrderType.BID,tradeableAmount,CurrencyPair.BTC_EUR,null,null,price);

                            String orderID = tradeService.placeLimitOrder(limitOrder);
                            System.out.println("Limit Order ID: "+ orderID);

Does anyone knows what i have write wrong? Thanks a lot!

**Comment by Xion345** [comment]
Hi makarid,

I think this might be a bug in the implementation of bitBinance or a lack of parameter checking. It would be easier for people to help you if you included a stack trace.

**Comment by makarid** [comment]
Hi Xion345,
 thanks for your reply! I am sorry that i didn't put the stack trace.Here it is :

Exception in thread "main" org.knowm.xchange.exceptions.ExchangeException: 0: null
	at org.knowm.xchange.bitbay.service.BitbayBaseService.checkError(BitbayBaseService.java:37)
	at org.knowm.xchange.bitbay.service.BitbayTradeServiceRaw.placeBitbayOrder(BitbayTradeServiceRaw.java:41)
	at org.knowm.xchange.bitbay.service.BitbayTradeService.placeLimitOrder(BitbayTradeService.java:64)

**Comment by npomfret** [comment]
If you turn on the logging properties that dump out the actual JSON response from the exchange you might see the error in more detail.

**Comment by makarid** [comment]
Hi npomfret,
thank you for your reply.I don't know if this is the thing that you talking about,but i debugg the program and this printed on my console:

4835 [main] INFO org.knowm.xchange.bitbay.BitbayExchange - Calling Remote Init...
4836 [main] INFO org.knowm.xchange.bitbay.BitbayExchange - No remote initialization implemented for Bitbay. The exchange meta data for this exchange is loaded from a json file containing hard-coded exchange meta-data. This may or may not be OK for you, and you should understand exactly how this works. Each exchange can either 1) rely on the hard-coded json file that comes packaged with XChange's jar, 2) provide your own override json file, 3) properly implement the `remoteInit()` method for the exchange (please submit a pull request so the whole community can benefit) or 4) a combination of hard-coded JSON and remote API calls. For more info see: https://github.com/timmolter/XChange/wiki/Design-Notes#exchange-metadata
4846 [main] INFO org.knowm.xchange.bitbay.BitbayExchange - Calling Remote Init...
4846 [main] INFO org.knowm.xchange.bitbay.BitbayExchange - No remote initialization implemented for Bitbay. The exchange meta data for this exchange is loaded from a json file containing hard-coded exchange meta-data. This may or may not be OK for you, and you should understand exactly how this works. Each exchange can either 1) rely on the hard-coded json file that comes packaged with XChange's jar, 2) provide your own override json file, 3) properly implement the `remoteInit()` method for the exchange (please submit a pull request so the whole community can benefit) or 4) a combination of hard-coded JSON and remote API calls. For more info see: https://github.com/timmolter/XChange/wiki/Design-Notes#exchange-metadata

**Comment by npomfret** [comment]
Search the docs for how to turn on the exchange json logging. Sorry, can't remember exactly how to do it right now.

**Comment by makarid** [comment]
Thanks a lot for your fast response!!! I will search it and post if i found something.Thanks again!

**Comment by timmolter** [comment]
@makarid Look at `BitbayBaseService.java:37` and you will discover the issue.

**Comment by makarid** [comment]
Hello timmolter,

thanks for your response.I am sorry but i am not a pro on programming and i am not sure if i can understand the error here correctly.In line 37 there is an if statement checking if the bitbay response on the request or not.If it is not responding then throws an error like ours? The only thing that come's to my mind is that i haven't put some parameters correctly(or not at all) on the getExchangeSpecification method that i call when i am creating the exchange instance.I have put only setApiKey and setSecretKey and then i call the applySpecification method.
Thanks for your response and your help.

**Comment by timmolter** [comment]
You'll have to quickly become a pro then! :) 

Clone the source code, and debug the code, looking at the values of everything. Unfortunately, the error response doesn't give much info.

**Comment by makarid** [comment]
This problem happens after the bitbay 3.0 version released.I hadn't any problem on bitbay 2.0 version.This is the code that i use to create my bitbay exchange instance if something seems strange please tell me,thanks:

    private  static Exchange bitbayApiConnection(){

        final String username = "***";
        final String bitbayApiKey = "***";
        final String bitbayApiSecret = "****";

        Exchange bitbayExchange =ExchangeFactory.INSTANCE.createExchange(BitbayExchange.class.getName());

        bitbayExchange.getExchangeSpecification().setApiKey(bitbayApiKey);
        bitbayExchange.getExchangeSpecification().setSecretKey(bitbayApiSecret);
        bitbayExchange.getExchangeSpecification().setUserName(username);

        bitbayExchange.applySpecification(bitbayExchange.getExchangeSpecification());

        return bitbayExchange;
    }

**Comment by makarid** [comment]
I no longer get this error anymore.Thanks for you help!!!

**Comment by justeasyman** [comment]
@makarid can You tell me how You did manage it? I get the same error "No remote initialization for Bitbay". My code where im creating exchange instance looks the same like Yours.
