### ISSUE TITLE
Yobit Exchange Any Example Demo Has Error

### ISSUE THREAD

**Issue by mike789vvv** [timmolter/XChange#1847]
Hi everyone)
I try to run any example demo of Yobit Exchange, but everytime has errror,
>>Exception in thread "main" java.lang.IllegalStateException: cannot create digest,

Maybe I do somehting wrong ? May be I need set some parameters ?

**Comment by MirkoTeran** [comment]
Just set api key and secret to some fake values and it should work.

**Comment by mike789vvv** [comment]
Many thanks)))
