### ISSUE TITLE
Error: getClientConfig()Lsi/mazi/rescu/ClientConfig

### ISSUE THREAD

**Issue by fredfortier** [timmolter/XChange#1848]
I'm getting an error with this code:
```java
Exchange exchange = ExchangeFactory.INSTANCE.createExchange(KrakenExchange.class.getName());
```

Here is the error message:
`org.knowm.xchange.kraken.service.KrakenBaseService.getClientConfig()Lsi/mazi/rescu/ClientConfig;`

I used Kraken for this particular example but I've observed the same behavior with Binance. Bitfinex and Poloniex seem to behave correctly.

I'm new to the library so I may be missing something obvious. Any guidance would be appreciated.

**Comment by Xion345** [comment]
I had the same problem before updating to rescu 2.0.1, you _might_ have the same issue:

            <dependency>
                <groupId>com.github.mmazi</groupId>
                <artifactId>rescu</artifactId>
                <version>2.0.1</version>
            </dependency>

**Comment by fredfortier** [comment]
It had a bad version number in one of my dependencies.
