### ISSUE TITLE
Bitfinex: Date argument ignored in getTrades()

### ISSUE THREAD

**Issue by fredfortier** [timmolter/XChange#1851]
My code goes like this:
```java
String endDateString = "06/01/2017";
DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
Date endDate = df.parse(endDateString);

Exchange exchange = ExchangeFactory.INSTANCE.createExchange(BitfinexExchange.class.getName());
MarketDataService marketDataService = exchange.getMarketDataService();

Trades trades = marketDataService.getTrades(CurrencyPair.ETH_BTC, endDate.getTime());
```

I get trades but the last trade occurs today while I'd expect it to occur on 06/01/2017. I know that the Bitfinex V2 'trades' service accepts start and end date parameters.

I tried the same code with other exchanges. I ran into either the same issue or just could not instantiate a `MarketDataService`. Any pointer would be appreciated.

**Comment by Saloed123** [comment]
In this lib implemented v1 for Bitfinex

```
@GET
  @Path("trades/{symbol}")
  BitfinexTrade[] getTrades(@PathParam("symbol") String symbol, @QueryParam("timestamp") long timestamp) throws IOException, BitfinexException;
```

**Comment by EricAnderson1000** [comment]
Hello @fredfortier can you try passing in just the date object? If that doesn't work I can add a unit test and figure out what is going on.

```
Trades trades = marketDataService.getTrades(CurrencyPair.ETH_BTC, endDate);
```

Please let me know if this does or does not work. Thank you

**Comment by timmolter** [comment]
@fredfortier You need to look at the implementation and see exactly what it's expecting. Every exchange is unique (unfortunately).
