### ISSUE TITLE
Serialize order book, trades, trade etc?

### ISSUE THREAD

**Issue by andrewlin0410** [timmolter/XChange#1858]
Can you developers implement Serializable for these? I want to save some of the objects locally. Please tell me if this will be done. Otherwise I will have to do some cumbersome work.

**Comment by timmolter** [comment]
try the snapshot jar, as I already did serialize them. Should be released soon.

**Comment by andrewlin0410** [comment]
Hi I am using the Snapshot. However, I don't see implement Serializable in Trade or Trades classes. My gradle file looks something like this:

repositories {
    mavenCentral()
    maven { url 'https://jitpack.io' }
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile 'com.github.timmolter:XChange:-SNAPSHOT'
}

Is this the wrong way to get Snapshot?

**Comment by timmolter** [comment]
I guess your doing it wrong, as `Trade` implements Serializable:

https://github.com/timmolter/XChange/blob/develop/xchange-core/src/main/java/org/knowm/xchange/dto/marketdata/Trade.java

See the readme, and adapt to Gradle about SNAPSHOTS.

**Comment by andrewlin0410** [comment]
In case somebody else stumbles upon this, it should be like this:

repositories {
mavenCentral()
maven { url 'https://jitpack.io' }
}
dependencies {
testCompile group: 'junit', name: 'junit', version: '4.12'
    compile 'com.github.timmolter:XChange:develop-SNAPSHOT'
}
