### ISSUE TITLE
Batch retrieve orders, cannot get "status"

### ISSUE THREAD

**Issue by deltacat** [timmolter/XChange#1860]
I'm using GDAX classes to operate my orders.
When use "tradeService.getOrder(String orderId)" to get one order, the returned data contains "status" correctly. But if I use the batch version to retrieve orders, status of the returned orders are always "PENDING_NEW".

I checked related source code such as "GDAXAdapter", found that the batch get function does not process "status".

I'm not sure it is a issue or incorrect usage. Please help check, thanks.

**Comment by Xion345** [comment]
Yes, I had the same issue, and I was even planning to fix it. I'm 90% confident it is a bug. A quick fix is to use `GDAXTradeServiceRaw.getOrder(...)` but I think the adapter should be properly implemented.

**Comment by timmolter** [comment]
I fix and a PR would be appreciated.
