### ISSUE TITLE
Binance throws ssl handshake exception

### ISSUE THREAD

**Issue by lukasz-kaniowski** [timmolter/XChange#1882]
When I'm executing `getAccountInfo` on binance I'm getting `sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`
Ideas?

**Comment by timmolter** [comment]
Googling that error will lead you in the right direction. Also see: https://github.com/timmolter/XChange/wiki/Installing-SSL-Certificates-into-TrustStore

**Comment by ww3456** [comment]
Updating the JRE fixed this exception for me.

**Comment by lukasz-kaniowski** [comment]
@ww3456 Thanks, this worked.

**Comment by cantellow** [comment]
@ww3456 So this is JRE bug?

**Comment by ww3456** [comment]
No, it is not a JRE bug, it is just that certificate authority details in the truststore change over time. Older JRE versions will have an outdated truststore. To get the latest details it would be simplest to upgrade the JRE. If you cannot do this for some reason then you will have to follow the link above to manually update your JRE truststore.
