### ISSUE TITLE
min-apk > 26 on Android after 4.3.0

### ISSUE THREAD

**Issue by piatekjulien** [timmolter/XChange#1884]
On the 4.2.3 version, everything was okay, but when I tried to upgrade to 4.3.0, I got the following error when I try to build my app:

Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing javax/ws/rs/client/FactoryFinder.class

Error:com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)

**Comment by timmolter** [comment]
We bumped to Java 8: https://knowm.org/open-source/xchange/xchange-change-log/

Maybe you need to update your JDK???

**Comment by piatekjulien** [comment]
@timmolter Sorry for the delayed reply.
I already use JDK8 on Android Studio. To be sure I updated it to the last version but the problem persists... 
The error message just changed a little bit: 

Error:com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.

Error:com.android.tools.r8.ApiLevelException: Default interface methods are only supported starting with Android N (--min-api 24): java.lang.Object javax.ws.rs.client.CompletionStageRxInvoker.delete()

Error:Execution failed for task ':app:transformClassesWithDexBuilderForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.dexing.DexArchiveBuilderException: com.android.builder.dexing.DexArchiveBuilderException: Failed to process /Users/xxxx/.gradle/caches/modules-2/files-2.1/javax.ws.rs/javax.ws.rs-api/2.1/426a0862406536e690c7caa8bb6ed32191986fac/javax.ws.rs-api-2.1.jar

Do you know which version of the JDK8 is used ? Maybe I should have the exact same one 😅 

Thank you.

**Comment by johnzweng** [comment]
As it seems the Android runtime (ART / Dalvik) don't support all features of Java 8 on older versions. To be clear, this has nothing to do with the software you use on your developer machine, that's the runtime inside the Android device which executes the application (https://source.android.com/devices/tech/dalvik/).

Here is a list of APIs in Java 8 which will only work on API level 24 and higher: https://developer.android.com/studio/write/java8-support.html

I'm not sure if and how you can get libraries working on older Android versions which use these Java 8 APIs.

**Comment by timmolter** [comment]
@piatekjulien It would be an interesting test to see if you temporarily bumped up the min API level to 24, and then tried. Or as your error message suggested >=26.

But I googled that error and it looks related to Guava. Try: https://stackoverflow.com/questions/45873274/google-guava-invokedynamic-requires-min-sdk-version-26

So I think it's more likely a guava issue on your end.

**Comment by piatekjulien** [comment]
@timmolter @johnzweng Thanks a lot for your help !
I was able to run it on API 21 by adding these lines to my build.gradle file : 

buildToolsVersion '26.0.2'
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

This URL was very useful https://developer.android.com/studio/write/java8-support.html

By the way, thank you for this fabulous Library.
