### ISSUE TITLE
Java 8

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#1886]
I just noticed the change to java 8 which is pleasing.  @timmolter what was the reason? are you planning to move to any of the java 8 APIs?  

I was thinking `java.time` (in place of java.util.Date) would be nice.

**Comment by timmolter** [comment]
There was an issue about it a couple weeks ago, but I cannot find it.

No plans to "upgrade" to the Java 8 way, but now at least people can use it.

**Comment by cymp** [comment]
On reason I know of is that PATCH support was needed in rescu in order to implement somes hitbtc v2 api calls, which required Java 8: https://github.com/mmazi/rescu/pull/100.
