### ISSUE TITLE
Any plan to support Bitflyer and Coincheck?

### ISSUE THREAD

**Issue by winwish** [timmolter/XChange#1887]

**Comment by timmolter** [comment]
no plans yet.

**Comment by lukaszaoralek** [comment]
Bitflyer streaming support https://github.com/bitrich-info/xchange-stream/pull/27

**Comment by Unbr8kbal** [comment]
@winwish Would you be willing to donate a bounty?

**Comment by winwish** [comment]
After I receive the postcard from them to pass verification, I think I can donate some or share with someone with the same needs.

**Comment by joggerjoel** [comment]
bitmex too

**Comment by lukaszaoralek** [comment]
If you are only interested in public (market data) API, the xchange-stream (websocket) supports Bitflyer and Bitmex now

**Comment by cristianlucaci** [comment]
hey, does anyone has any updates on Bitflyer implementation? I intended to start the implementation, but I have difficulties enabling the API keys.

**Comment by timmolter** [comment]
closing as duplicate of:

* https://github.com/timmolter/XChange/issues/1264
* https://github.com/timmolter/XChange/issues/1959
