### ISSUE TITLE
Access AccountService, error: org.knowm.xchange.bitstamp.dto.BitstampException: API key not found (HTTP status code: 403)

### ISSUE THREAD

**Issue by skyliang168** [timmolter/XChange#1891]
Hi,
I used Example 2: Private Account Info to access AccountService, I got the error: org.knowm.xchange.bitstamp.dto.BitstampException: API key not found (HTTP status code: 403).
When I enter my Kraken account, I can see my account information, everything is good.
What is the problem? How can I resolve it?
Thank you so much!

**Comment by skyliang168** [comment]
Hi,
When I execute to accountService.getAccountInfo() every time, I get the error.
Why getAccountInfo() in AccountService does not work.
Thank you so much!
Sky

**Comment by skyliang168** [comment]
Hi,
I use the dependencies:
<dependencies>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-core</artifactId>
            <version>4.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-examples</artifactId>
            <version>4.3.0</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-XYZ</artifactId>
            <version>4.3.0</version>
        </dependency>
    </dependencies>
Does someone know the reason? or need I set anything else?
Thank you so much!

**Comment by timmolter** [comment]
bitstamp != kraken

**Comment by skyliang168** [comment]
Hi Tim,

I am using the code now from your GitHub repository:

ExchangeSpecification exSpec = new
BitstampExchange().getDefaultExchangeSpecification();
exSpec.setUserName("34387");
exSpec.setApiKey("a4SDmpl9s6xWJS5fkKRT6yn41vXuY0AM");
exSpec.setSecretKey("sisJixU6Xd0d1yr6w02EHCb9UwYzTNuj");Exchange
bitstamp = ExchangeFactory.INSTANCE.createExchange(exSpec);
// Get the account informationAccountService accountService =
bitstamp.getAccountService();AccountInfo accountInfo =
accountService.getAccountInfo();System.out.println(accountInfo.toString());

Then how can I get my Kraken and Poloniex account information using XChange?

Thank you for your response!
Best regards,

Sky

**Comment by skyliang168** [comment]
Hi Tim,

I use Exchange bitstamp = ExchangeFactory.INSTANCE.createExchange(PoloniexExchange.class.getName(),userName,password,apiKey,secretKey) now.
I can get the account information now.
Thank you!
