### ISSUE TITLE
Intermittent Kraken Order execution issues 

### ISSUE THREAD

**Issue by jcuypers** [timmolter/XChange#1899]
I would like to get some feedback on the following behavior and see if there's a way around it.

When I execute an order on Kraken, via the raw xchange interface  I get any of the following behaviors:
1) works as expected.  get a normal KrakenOrderResponse.
2) connection timeout.  obvious that a retry is necessary
3) exchange exception.  Eservice unavailable and the like.  obvious that a retry is necessary.
4) HTTP status code errors. like 502 "bad gateway" and others.  Request fails/timeout reached/response null **(Order is executed anyway)**  these are similar errors you get when accessing through cryptowat.ch/kraken web (cloudflare errors) etc 

The above behavior is random, so first 2 request can be OK.  than another request option 3, then next retry option 2, and then still another one 4.  

I tried already to increase the HTTPreadtimeout but that doesn't seem to help.  Maybe the readtimeout would only be valid to the cloudflare servers and not between their servers and the kraken ones.  (have to be honest, i didnt manage to get the rescu.properties working so i change it through exchangespecification.sethttpreadtimeout)

As Kraken itself is very unstable i wonder if there is a way around it.  It's kind of crazy to not know for sure what happened in the end.  needing to retry more or try to find out and executed order (of which you didnt get the orderid back) to match a request

**Comment by jcuypers** [comment]
On option 4.  sometimes the order goes through.  not consistent

**Comment by timmolter** [comment]
I don't have any experience with Kraken beside the public market data interface, and I just ignore errors. I'll leave this open, and maybe someone else can offer some advice.

**Comment by ww3456** [comment]
"a way round it" - use a different exchange if possible? The Kraken Twitter feed is promising "major upgrades" in early December so there might be better things on the way. 

https://twitter.com/krakenfx/status/933183555772882945
https://twitter.com/krakenfx/status/932910443785367552
https://twitter.com/krakenfx/status/932917134513934336

As you've noticed, it is currently highly unreliable at the moment, see also #1758

**Comment by jcuypers** [comment]
Based on Kraken's feedback:  they are working on a new trading backend, regarding this problems.  for now they recommend setting/checking the userref parameter as a bypass/validation in case something goes wrong.  I guess this topic can be closed. thanks
