### ISSUE TITLE
Ticker volume: volume or volume quote?

### ISSUE THREAD

**Issue by cymp** [timmolter/XChange#1901]
I've had an issue with using the "volume" value of the Ticker object, should its unit be read as the base or counter currency ? Documentation says "24h volume", and it seems that it is at least filled once as a base currency volume (in binance implementation), but instinctively I would have set it to the counter currency volume.
What should we do here? Document?  Or did I miss something?

**Comment by jcuypers** [comment]
base seems more logic.     as in ticker gives lets say 1 BASE is worth X counter currency and there has been already Y volume of BASE in volume today.       you can make your own calculation from there like base volume x counter for total real value.   if the volume would be expressed in counter it would become ambiguous as it changes all the time.

**Comment by cymp** [comment]
Makes sense, but on the exchanges the volumes are most of the time displayed in counter currency unit. As a win/win solution, what do you think of adding in Ticker something like:
```
 private final BigDecimal quoteVolume;

 public BigDecimal getQuoteVolume(){
     return quoteVolume != null ? quoteVolume : volume.divide(last);
 }
``` 
\+ constructor parameter.

Quote volume is often provided by ticker api call on several exchanges and this would prevent from calculating it when needed.

**Comment by jcuypers** [comment]
From a programming point of view I would say its as good as it gets.  From a functional point of view its important that you always know exactly what you get back.  it's great to get a value, but if you assume it to be something else than it is then it might do more bad than good.   Also, be aware of scale issues and divide issues... seems like tricky.

**Comment by cymp** [comment]
Yes. I think there is something similar in Balance ( sthg like getTotal() { total != null : total : available + reserved} ).
@timmolter any thoughts?

**Comment by timmolter** [comment]
I always assumed volume referred to the base. I'm not overly excited about adding that extra method, but on the other hand it's small and doesn't hurt. If you want to submit a PR for it, go ahead.

**Comment by cymp** [comment]
@timmolter I've just submitted the PR, you can close this once it is accepted.
