### ISSUE TITLE
proxy to change IP address to bypass limit calls

### ISSUE THREAD

**Issue by mahalamobile** [timmolter/XChange#1902]
Hi,

Anyway of doing this. I need to make 2 calls for example to luno every 10 seconds, however, the API only allows 1 call every 10s. for example i need the bid, ask and then the bidvolume and askvolume under 1 timestamp. So impossible

Any advice welcome

thanks

**Comment by timmolter** [comment]
Sorry, cannot be done in XChange itself AFAIK. It'd be beyond the scope of this lib, too.
