### ISSUE TITLE
YoBit "getTradeHistory" is always empty?

### ISSUE THREAD

**Issue by digitalchaotics** [timmolter/XChange#1926]
Has anyone using YoBit ever seen any results from "getTradeHistory"?  If so, what params are you passing?  It's always empty for me.  I've tried a number of variants.

Note that the code below is working for Bittrex, HitBTC, Poloniex, Livecoin, Bleutrade, and Cryptopia.

`
      try {
        List<UserTrade> trades = yobitExchange.getUserTrades(currencyPair, new Date(0), new Date());
        if (trades.isEmpty()) {
          logger.info(exchangeName + "->getUserTrades FAILED (No UserTrades found)");
        }
        else {
          logger.info(exchangeName + "->getUserTrades PASSED");
        }
      }
      catch (Throwable x) {
        logger.error(exchangeName + "->getUserTrades FAILED", x);
      }

where...

  public List<UserTrade> getUserTrades(CurrencyPair currencyPair, Date start, Date end) throws IOException {
      TradeHistoryParamsCurrencyPairTimeSpan params = new TradeHistoryParamsCurrencyPairTimeSpan(currencyPair, start, end);
      return tradeService.getTradeHistory(params).getUserTrades();
  }

`

**Comment by digitalchaotics** [comment]
Build version is 4.3.0-SNAPSHOT (built locally)

**Comment by npomfret** [comment]
Unfortunately each exchange works differently and at the moment you need to check the exchange specific implementation to see what parameters the exchange uses.  We don't have a good solution for this yet.

For obit, the following works:

                    TradeHistoryParamsAll params = new TradeHistoryParamsAll();
                    params.setCurrencyPair(currencyPair);
                    params.setStartTime(since);
                    params.setEndTime(now);

Then increase the value for `since` to get the next batch of trades.

**Comment by digitalchaotics** [comment]
Strange.  That's functionally equivalent to what I have.  Maybe it's just me...  :(

**Comment by lucarosellini** [comment]
@digitalchaotics did the suggestion provided by @npomfret works for you? I still get an empty trade history regardless of the time window I use to perform the query. I have a few trades in my YoBit account and they are visible from the web ui.

**Comment by lucarosellini** [comment]
@digitalchaotics @npomfret nevermind, it seems YoBit do not return orders older than one week.

**Comment by npomfret** [comment]
It's a really bad exchange.  I've stopped using it.

**Comment by cymp** [comment]
Same...

**Comment by digitalchaotics** [comment]
Yep.  Finally gave up on YoBit here, as well.  Sloppy all 'round.

**Comment by digitalchaotics** [comment]
@lucarosellini - no, the workaround didn't work for me.  I'm not sure why.  I've given up on YoBit for now.
