### ISSUE TITLE
ArithmeticException: Rounding necessary

### ISSUE THREAD

**Issue by lumyus** [timmolter/XChange#1944]
Hey,

I am all of a sudden getting the following error:

> Exception in thread "main" java.lang.ArithmeticException: Rounding necessary
> 	at java.base/java.math.BigDecimal.commonNeedIncrement(BigDecimal.java:4502)
> 	at java.base/java.math.BigDecimal.needIncrement(BigDecimal.java:4558)
> 	at java.base/java.math.BigDecimal.divideAndRound(BigDecimal.java:4466)
> 	at java.base/java.math.BigDecimal.setScale(BigDecimal.java:2793)
> 	at org.knowm.xchange.gdax.GDAXAdapters.adaptToExchangeMetaData(GDAXAdapters.java:221)
> 	at org.knowm.xchange.gdax.GDAXExchange.remoteInit(GDAXExchange.java:50)
> 	at org.knowm.xchange.BaseExchange.applySpecification(BaseExchange.java:111)
> 	at org.knowm.xchange.ExchangeFactory.createExchange(ExchangeFactory.java:168)

Any idea why this is happening? My code used to work perfectly until 1-2 days ago.

**Comment by timmolter** [comment]
https://github.com/timmolter/XChange/issues/1936
