### ISSUE TITLE
[60mBTC bounty] Gate.io implementation

### ISSUE THREAD

**Issue by cymp** [timmolter/XChange#1945]
Hello,

I offer a 60mBTC bounty to whom finishes the full implementation of Gate.io [API](https://gate.io/api2) before December 7th (2017, yes). If it is done before December 12th, the bounty would be 40 mBTC. If it is not done by then, I may be available to do it by myself.

And I always pay my bounties: [hitbtc](https://github.com/timmolter/XChange/issues/1633), [liqui](https://github.com/timmolter/XChange/issues/1730), [livecoin](https://github.com/timmolter/XChange/issues/1825), [yobit](https://github.com/timmolter/XChange/issues/1653), [cryptopia](https://github.com/timmolter/XChange/issues/1708)

**Comment by timmolter** [comment]
I did it today by converting bter to gate.io.

https://github.com/timmolter/XChange/commit/85e6925373e917cf86edacb4077ecd3913193ca8

Haven't tested it through though, nor do I plan to.

**Comment by cymp** [comment]
You just saved me 60mBTC if so. I am going to test it asap.?

**Comment by cymp** [comment]
Works so far (balance, ticker, place order), thank you.
