### ISSUE TITLE
new hitbtc api question

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#1974]
@timmolter @EricAnderson1000  

I just noticed the deletion of the old hitbtc implemention.  Are we sure the new one is ready to go?  At a glance I just noticed the code for `getFundingHistory`:

```
  @Override
  public List<FundingRecord> getFundingHistory(TradeHistoryParams params) throws IOException {

    List<HitbtcTransaction> transactions = getTransactions();

    List<FundingRecord> records = new ArrayList<>();
    for (HitbtcTransaction transaction : transactions) {
      records.add(HitbtcAdapters.adapt(transaction));
    }
    return records;
  }
```

This doesn't look right to me, it calls `getTransactions` and converts all responses into _FundingRecords_, is this correct?  Surely not every transaction can be assumed to be a FundingRecord.

**Comment by npomfret** [comment]
@timmolter would it be possible to bring the old hitbtc implemention back until the v2 api is finished?

**Comment by EricAnderson1000** [comment]
Sorry it's been a busy week with Christmas coming up. I'll look into fixing this method this morning.

**Comment by npomfret** [comment]
A revert might just be the quickest thing to do in the short term - then we can get the new one finished later.

**Comment by EricAnderson1000** [comment]
I would prefer to understand what is not working better before just reverting (I didn't remove it). It is better to go forward rather than backwards if possible.
@npomfret Can you give me an example where this is broken? 

Here is the API for hitbtc
https://api.hitbtc.com/#get-transactions-history

Possible return types are 
```One of: payout - crypto withdraw transaction, payin - crypto deposit transaction, deposit, withdraw, bankToExchange, exchangeToBank
```

Here is how we are mapping the responses to Funding of Withdraw or Deposit..

```
  /**
   * @param type
   * @return
   * @see https://api.hitbtc.com/api/2/explore/ Transaction Model
   * possible types: payout, payin, deposit, withdraw, bankToExchange, exchangeToBank
   */
  private static Type convertType(String type) {
    switch (type) {
      case "payout":
      case "withdraw":
      case "exchangeToBank":
        return Type.WITHDRAWAL;
      case "payin":
      case "deposit":
      case "bankToExchange":
        return Type.DEPOSIT;
      default:
        throw new RuntimeException("Unknown HitBTC transaction type: " + type);
    }
  }
```

**Comment by npomfret** [comment]
Does the transactions endpoint only give deposits and withdrawal data?

**Comment by EricAnderson1000** [comment]
>Does the transactions endpoint only give deposits and withdrawal data?

That appears so. I think it is a poorly named API on hitbtc's side.

>And if so, how do I page through them? The TradeHistoryParams params are ignored.

This is true! And needs to be fixed.

**Comment by npomfret** [comment]
Oh I see - my bad.  But yes, params are needed.

**Comment by timmolter** [comment]
> It is better to go forward rather than backwards if possible.

Exactly my opinion too. It was marked as deprecated, I'm pretty sure. 

@npomfret If you'd like to resurrect V1, I'm OK with it. Just try to keep it under a V1 sub package so it's clearly separated from V2. I think there are examples of this in other modules.

**Comment by EricAnderson1000** [comment]
@npomfret @timmolter 
Here is a PR
https://github.com/timmolter/XChange/pull/2001
