### ISSUE TITLE
Hitbtc getTradeHistory ignores paging

### ISSUE THREAD

**Issue by sirilicious** [timmolter/XChange#1981]
I noticed that getTradeHistory of Hitbtc ignores the paging parameters - and always returns the latest 100 trades.

e.g:
```
TradeHistoryParamsAll params = new TradeHistoryParamsAll();
params.setPageLength(10);
UserTrades trades = exchange.getTradeService().getTradeHistory(params);
```

**Comment by npomfret** [comment]
I'm not sure how complete the new implementation is (see https://github.com/timmolter/XChange/issues/1974).  @timmolter could you revert the deletion of the old one until it's tested a bit more?

**Comment by sirilicious** [comment]
I'm a litte bit confused after i looked into the code of `org.knowm.xchange.hitbtc.v2.service.HitbtcTradeService`, because it is already doing something with pagination parameters.

**Comment by EricAnderson1000** [comment]
I'll try and get a PR for this later today.

**Comment by npomfret** [comment]
@EricAnderson1000 still can't get my trades from hitbtc - are you able to fix?

**Comment by npomfret** [comment]
#2121

**Comment by EricAnderson1000** [comment]
Sorry got busy. Does the above PR resolve the issue?

**Comment by npomfret** [comment]
It's a minimal implementation, but yes it fixes paging.  There are other parameters that the exchange supports that aren't implemented.

@timmolter I'm still disappointed that the old implementation was removed before the new one was completed (it still isn't i think).  The old and new sat quite happily side by side, I think it was a big step backward to zap v1 so prematurely.  In the future could if there are 2 compatible implementations could we simply deprecate the old one while the new one is being finished?
