### ISSUE TITLE
Adding and deleting CurrencyPair Symbols on exchanges

### ISSUE THREAD

**Issue by makarid** [timmolter/XChange#1982]
Hello, i would like to ask you how can i add/remove new currency pairs on many exchanges on the project?I am seeing some new currency pairs on some exchanges and i would like to add them to the operational pairs of the exchanges.
Thanks

**Comment by k2cieslak** [comment]
Hi @makarid 

Please take a look at https://github.com/timmolter/XChange/pull/1973/commits/f6dffd317ceed39ce8a76bda98f543271cd522da
You need to amend those two classes to add currencies and currency pairs respecitevely.

&k

**Comment by makarid** [comment]
Thanks a lot for your response.After i do that,how can i add them to the ExchangeSymbol method.Thanks

**Comment by makarid** [comment]
About my previous question i think i found it!

I want to add some new CurrencyPairs to some exchanges (because they have add support on those) in order, when i call the getExchangeSymbols method of that exchange, i will get the new List of CurrencyPairs that this exchange supports. My question is, in order to do that, do i need to modify the .json file of the specific exchange and add the new CurrencyPairs in the currency_pairs column of the exchange json file?

Thanks a lot

**Comment by timmolter** [comment]
See the part about Exchange MetaData: <https://github.com/timmolter/XChange/wiki/Design-Notes>

**Comment by cbeaujoin** [comment]
`        MarketDataService marketDataService = bitmex.getMarketDataService();
        Currency c = Currency.getInstance("XBTZ18");
        Currency c2 = Currency.getInstance("");
        CurrencyPair cp = new CurrencyPair(c,c2);
        Ticker ticker = marketDataService.getTicker(cp);
        System.out.println(ticker.toString());`
