### ISSUE TITLE
Gdax Exception - Rate limit exceeded

### ISSUE THREAD

**Issue by nycrom** [timmolter/XChange#1984]
Hi,

i get sometimes this exception, what is this and how can i catch it? 
I only call the function every 5 minutes...

> [Thread-3] INFO org.knowm.xchange.gdax.GDAXExchange - Calling Remote Init...
> Exception in thread "Thread-3" org.knowm.xchange.gdax.dto.GDAXException: Rate limit exceeded (HTTP status code: 429)

```
gdax = ExchangeFactory.INSTANCE.createExchange(GDAXExchange.class.getName());
		marketDataServicegdax = gdax.getMarketDataService();
		try {
			ticker = marketDataServicegdax.getTicker(CurrencyPair.BTC_EUR);
		} catch (NotAvailableFromExchangeException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (NotYetImplementedForExchangeException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ExchangeException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
```

**Comment by timmolter** [comment]
You could read the Exception message and compare to a String (Rate limit exceeded) or you could update to the latest snapshot jar and catch a `RateLimitExceededException`, which I recently added for GDAX.

**Comment by nycrom** [comment]
Thank you very much!
