### ISSUE TITLE
Poloniex - createExchange(PoloniexExchange.class.getName()) throwing ExchangeException

### ISSUE THREAD

**Issue by Thleruth** [timmolter/XChange#1986]
It is not possible for me to create an instance for PoloniexExchange. I tracked it down and it seems like it comes from the remoteInit() [within BaseExchange] which tries to access (as a test): "https://poloniex.com/public?command=returnCurrencies". However, the page has CAPTCHA enabled and thus return 403 (from a "Remote host closed connection during handshake" error) which in turns throw a new ExchangeException. 

That's at least how I tracked it down. Am I missing something?

**Comment by jcuypers** [comment]
when I try the URL directly in a browser, it actually return the correct result without any problem.  No need to fill in/complete any captcha.  you might have hit some security measures (similar as google has if you hit it too many times from the same IP).   please go to the page again directly and complete the captcha succesfully and try again.

**Comment by Thleruth** [comment]
I sadly tried that and I am still getting the same issue :(

**Comment by jcuypers** [comment]
Please refer to the following links, It will give you an idea on how you might solve it.
It seems to be a common issue. 

https://github.com/dutu/poloniex-api-node/issues/20
https://github.com/ZhengyaoJiang/PGPortfolio/issues/4

good luck.

**Comment by Thleruth** [comment]
Appreciated, I will look into that :)

**Comment by GrigoriyDidorenko** [comment]
did you solve?
