### ISSUE TITLE
Binance bogus currencypair

### ISSUE THREAD

**Issue by jcuypers** [timmolter/XChange#1994]
DEV 4.2.3 - '123/456` returned when querying available pairs.  all the rest seems normal.

**Comment by ww3456** [comment]
Hi, that is not an XChange error, it is just what Binance is returning from [https://www.binance.com/api/v1/ticker/allPrices](https://www.binance.com/api/v1/ticker/allPrices) i.e. 
```
{"symbol":"123456","price":"0.00030000"}
```
If it is causing a problem perhaps you could raise it with their support to find out what is going on.
