### ISSUE TITLE
HitBTC exposes USDT balance as USD

### ISSUE THREAD

**Issue by trekmbikes** [timmolter/XChange#1998]
This is more of a question than an issue, but should XChange adapt requests for "USDT" to "USD" for HitBTC since the v2 api exposes it as such?

See https://api.hitbtc.com/api/2/explore/ , authorize with an API keypair and try either /account/balance or /trading/balance

**Comment by timmolter** [comment]
No, you should use USDT as the counter currency.

**Comment by trekmbikes** [comment]
I agree, I have funds on the site in USDT, but when I call XChange wallet.getBalance(Currency.USDT) it returns zero, because HitBTC v2 API actually returns this balance as USD.

**Comment by timmolter** [comment]
Does HitBTC return it as USD or does the xchange code convert it somewhere?

**Comment by trekmbikes** [comment]
HitBTC returns it as USD

**Comment by timmolter** [comment]
That seems to me like a failure on HitBTC's part, and I wouldn't want to "correct" it in XChange.

**Comment by devinrsmith** [comment]
I think this is a shortcoming of XChange. HitBTC uses the id "USD" to reference Tether. I don't think HitBTC supports US dollars.

```json
{
  "id": "USD",
  "fullName": "Tether",
  "crypto": true,
  "payinEnabled": true,
  "payinPaymentId": false,
  "payinConfirmations": 2,
  "payoutEnabled": false,
  "payoutIsPaymentId": true,
  "transferEnabled": true,
  "delisted": false,
  "payoutFee": "0"
}
```

**Comment by timmolter** [comment]
It looks like the HitBTC raw layer should parse that JSON as USDT, probably in the adapter code somewhere.
