### ISSUE TITLE
Documentation error Bid/Ask (mixed up)

### ISSUE THREAD

**Issue by Thleruth** [timmolter/XChange#1999]
I found an issue with one of Java docs it is stating: "Either BID (buying) or ASK (selling)" for the Type of MarketOrder.

In the case of a MarketOrder we are an investor, thus, the bid is actually the sell price and the ask is the buy price.

If we are placing a limit order (we are then a market maker), it is actually correct that placing a bid price will result in a buy (if hit) and placing a ask will result in a sell (if hit).

Can somebody that used the placeMarketOrder and placeLimitOrder confirm the behavior?

**Comment by timmolter** [comment]
The Javadocs in this case are correct. As the investor, if you want to buy you are bidding. If you want to sell you are asking (for a price). However for a market order you're not bidding or asking, just buying or selling, but we reuse the OrderTypes.
