### ISSUE TITLE
Probable incorrect 'else if' in LivecoinAdapters

### ISSUE THREAD

**Issue by digitalchaotics** [timmolter/XChange#2000]
Pointing out a likely oversight that I stumbled across.

Starting at line 152 of LivecoinAdapters.java:

`

    if (typeName.equals("MARKET_SELL"))

      type = OrderType.ASK;

    else if (typeName.equals("LIMIT_SELL"))

      type = OrderType.ASK;

    else if (typeName.equals("LIMIT_BUY"))

      type = OrderType.BID;

    else if (typeName.equals("LIMIT_SELL"))

      type = OrderType.ASK;

    else

      throw new IllegalStateException("Don't understand " + map);`

**_The second 'typeName.equals("LIMIT_SELL"))' is probably incorrect_**, since it's redundant.  Looking at the code, it seems that there should be a "MARKET_BUY" option there.

I don't use MarketOrders, so I'm not able to test or explore a solution.  However, I thought I'd point it out.

**Comment by npomfret** [comment]
Good spot.
