### ISSUE TITLE
How to get the rates from bitcoin.de

### ISSUE THREAD

**Issue by nycrom** [timmolter/XChange#2015]
Hi,

im trying for hour now and i need help please. I have the json with my api keys and want to read the buy prices from bitcoin.de.

But i get always this message and an error when i want to call getTicker. 

` Exchange bitcoindeExchange = ExchangeUtils.createExchangeFromJsonConfiguration();
MarketDataService marketDataService = bitcoindeExchange.getMarketDataService();
ticker = marketDataService.getTicker(CurrencyPair.BTC_EUR);`

So a hardcoded json ist okay but how to get this prices ... 

> " No remote initialization implemented for Bitcoin.de. The exchange meta data for this exchange is loaded from a json file containing hard-coded exchange meta-data. This may or may not be OK for you, and you should understand exactly how this works. Each exchange can either 1) rely on the hard-coded json file that comes packaged with XChange's jar, 2) provide your own override json file, 3) properly implement the `remoteInit()` method for the exchange (please submit a pull request so the whole community can benefit) or 4) a combination of hard-coded JSON and remote API calls. For more info see: https://github.com/timmolter/XChange/wiki/Design-Notes#exchange-metadata"

Thank you for your help!

**Comment by timmolter** [comment]
getTicker isn't implemented yet for Bitcoin.de AFAIK.

**Comment by nycrom** [comment]
how to get the BTC EUR prices instead?

**Comment by timmolter** [comment]
You'll have to implement it in XChange. A PR would be appreciated if you get it working.

**Comment by nycrom** [comment]
As you can see im a newbie to java ... i think its out of my league

**Comment by timmolter** [comment]
Yeah, could be. If you're determined, it'd be a great way to learn Java and related tools! Just fork and clone, get an IDE and Maven setup and start looking at code and trying things out. It's a steep learning curve, but very rewarding. 

Regarding bitcoin.de the ticker endpoint is not implemented, which is why you aren't able to successfully get that data. Only Trades and order book are implemented.
