### ISSUE TITLE
Get all prices in one shot

### ISSUE THREAD

**Issue by assaad** [timmolter/XChange#2018]
Hello is there a function where we can get all prices from a market in one shot? 
Iterating through different tickers is too slow. 
Many thanks!

**Comment by timmolter** [comment]
Only if the exchange in question offers an endpoint for it, which in my experience is not usually the case.

**Comment by digitalchaotics** [comment]
I've only found that capability on the endpoints for Livecoin, HitBTC, Cryptopia, and Poloniex.  It's not supported in the XChange API, but the Poloniex MarketDataServiceRaw ("Map<String, PoloniexMarketData> getAllPoloniexTickers()") gets them all at once, caches the result for one second.  It returns the requested pair ticker you requested, and continues to do so until the data is more than one second old.

I've wrapped the others listed above in similar code for my own purposes, and it works great.  The "get all tickers" functions for those exchanges drops from several minutes (including rate-limit delays) to scan all pairs to just a few seconds.

**Comment by douggie** [comment]
Hi,

feel free to take a look at https://github.com/timolson/cointrader it gets
each market on seperate threads so can handel getting data from 100's
markets simultanously.

**Comment by digitalchaotics** [comment]
Yes - operating each exchange API on a separate thread will help a LOT.

**Comment by timmolter** [comment]
IIRC, there is a different open issue about adding such a generic method the MarketdataService API. If you wanted to implement it, I'd be welcome.

**Comment by assaad** [comment]
On binance you have this capacity as well. With one html request. Bittrex same

**Comment by caleb-allen** [comment]
@timmolter it looks as if Bittrex, Binance, Kraken, and Poloniex all support market "summaries". I'll likely implement those in `MarketDataService` and submit a PR if that's alright

**Comment by caleb-allen** [comment]
Maybe not. Looks like there may not be a generic way to incorporate that data--not much of a consensus on what exactly it contains.

**Comment by timmolter** [comment]
sure, go for it

**Comment by caleb-allen** [comment]
Solved by #2446
