### ISSUE TITLE
Problem on Trade Demo at Bitstamp

### ISSUE THREAD

**Issue by makarid** [timmolter/XChange#2034]
Hello, i went to this link "https://knowm.org/open-source/xchange/xchange-example-code/" which has examples of code using the API. I have copy paste the following lines:

final OpenOrdersParamCurrencyPair openOrdersParamsBtcEur = (OpenOrdersParamCurrencyPair) tradeService.createOpenOrdersParams();
    openOrdersParamsBtcEur.setCurrencyPair(CurrencyPair.BTC_EUR);

When i am trying to test it,i get a NullPointerException error. 
Have you change the way this works? I want to get back all the open Orders that i have on a specified currencyPair.(in this example BTC.EUR).
Thanks!

**Comment by timmolter** [comment]
I'm not sure why it wouldn't be working, as it seems correct. I don't have a Bitstamp account to test it with, sorry. Maybe try the example from the source code directly: `BitstampTradeDemo.java`...
