### ISSUE TITLE
Bitfinex STOP-LIMIT order available as type but not handled

### ISSUE THREAD

**Issue by paulbistr** [timmolter/XChange#2036]
Is the stop order supported in the Bitfinex module ? I could find the BitfinexOrderType.STOP but there is no way to specify the stop price only the limit price.

**Comment by hurricup** [comment]
This order type is for `Stop` order, not `Stop Limit`. According to Bitfinex API (v1) documentation, stop-limit is not supported with it: https://bitfinex.readme.io/v1/reference#rest-auth-new-order

> Either “market” / “limit” / “stop” / “trailing-stop” / “fill-or-kill” / “exchange market” / “exchange limit” / “exchange stop” / “exchange trailing-stop” / “exchange fill-or-kill”. (type starting by “exchange ” are exchange orders, others are margin trading orders)

Btw, `Stop` is not implemented in XChange. This i can fix.
Btw, you may now use Limit orders with OCO to be able to specify stop value.
