### ISSUE TITLE
Running the code on a VPS with a cronjob

### ISSUE THREAD

**Issue by DanVeira** [timmolter/XChange#2045]
Hello,

I am aware this isn't the best place to ask this but I have no idea where else to do it.

I never used Java before, but I have plenty of experience with PHP. I managed to write the code and all is working fine on my Windows machine.

Now I need to put it on a VPS and have a cronjob run it every few seconds. I have an account with DigitalOcean so maybe I can do it there.

I'm not looking for a full tutorial, just need someone to point me in the right direction as I'm completely lost.

So how do I go about getting this code into a VPS and have it run automatically there?

Thank you!

**Comment by KevinJannis** [comment]
Look at springboot.
It can run cron jobs.

**Comment by douggie** [comment]
1) install java 8
`sudo yum install java-1.8.0`
2) copy your jar across
` rsync -azv --progress -e "ssh -i [pem file]" [full path to jar] [ssh user]@[host dns name]:.`
3) create a shell script that will start your jav process (give the correct exeuction permsisions to the user that will run it)
`#!/bin/sh
cd "[jar location]"
source [any user profiles
cat /dev/null > nohup.out
PRGCOU=`ps -eaf | grep -i java | grep [jar name] | grep -v grep | wc -l`
if [ $PRGCOU -eq 0 ]
then
java [java parmas and jar location] & 
sleep 5
exit
fi`
4) open crontab editor
`crontab -e`
5) add a cron job to run every x mins
`*/x * * * * [location of run script]`
