### ISSUE TITLE
Binance Signing

### ISSUE THREAD

**Issue by DizmalXC** [timmolter/XChange#2065]
I get this message when trying to access my wallets/account information:

23:05:22.896 [default] [main] DEBUG o.k.x.b.service.BinanceHmacDigest - value to sign: timestamp=1514523922846,  signature: [omitted]
23:05:22.896 [default] [main] DEBUG o.k.x.b.service.BinanceHmacDigest - old invocationUrl: https://www.binance.com/api/v3/account?timestamp=1514523922846&signature=org.knowm.xchange.binance.service.BinanceHmacDigest%40d278d2b
23:05:22.896 [default] [main] DEBUG o.k.x.b.service.BinanceHmacDigest - new invocationUrl: https://www.binance.com/api/v3/account?timestamp=1514523922846&signature=[omitted]
BinanceExchange has had this issue:-1021: Timestamp for this request is outside of the recvWindow.

Is this functional?  
Is the requestDeposit method going to be implemented in the future?  

I took at look at it last week and tried to mimic what another working java Binance API was doing, but I couldn't quite get it.  Maybe a little insight will help me figure out how to fix it.

Thanks,
Dan

EDIT:  Part of my question was answered here.  https://github.com/timmolter/XChange/issues/1993

**Comment by KevinJannis** [comment]
Try doing sth like this:

```
        ExchangeSpecification specification = exchange.getDefaultExchangeSpecification();
        specification.setExchangeSpecificParametersItem("recvWindow", 1000L * 60); // 1 minute, or increase some more
```

K.

**Comment by DizmalXC** [comment]
I tried that and varied the recv window quite a bit, but it still gives the same error.
