### ISSUE TITLE
Implement API for kucoin

### ISSUE THREAD

**Issue by jamding** [timmolter/XChange#2074]
API docs: https://kucoinapidocs.docs.apiary.io/#introduction/language-parameters

**Comment by goleary91** [comment]
seconded

**Comment by brunocvcunha** [comment]
+1

**Comment by makarid** [comment]
+100

**Comment by Mawster** [comment]
On it

**Comment by jamding** [comment]
Especially the get funding and get trade history APIs :D, lmk if u need
help--might have cycles in next few weeks

**Comment by odrotleff** [comment]
I started off almost at the same time as Mawster, although I'm not sure how fast I will be able to finish. Current progress in my fork.

**Comment by timmolter** [comment]
merged #2235
