### ISSUE TITLE
[gdax] gdax.json metadata file doesn't include BCH information

### ISSUE THREAD

**Issue by bryantharris** [timmolter/XChange#2075]
End of December 2017 GDAX added BCH to it's trading platform.

Minor fix, I've updated gdax.json locally, happy to push a 'Pull request'.

**Comment by bryantharris** [comment]
The edits are so minor, uploading gdax.json with the changes I propose.

[gdax.json.gz](https://github.com/timmolter/XChange/files/1594781/gdax.json.gz)

**Comment by bryantharris** [comment]
Actually, although my updated gdax.json file works in the short term, the gdax exchanges supports the /products request which seems to return the appropriate info.  It would seem querying the exchange would future proof the API better than expanding the hardcoded gdax.json file.

**Comment by timmolter** [comment]
It does now.
