### ISSUE TITLE
Chain.java default constructor

### ISSUE THREAD

**Issue by azlax** [timmolter/XChange#2087]
When integrating with spring mongoDB CurrencyPair fails to be persisted to db since CurrencyPair has no default constructor.

Could it be possible to add a simple default constructor:

public CurrencyPair(){}

Failed to instantiate org.knowm.xchange.currency.CurrencyPair using constructor NO_CONSTRUCTOR with arguments

**Comment by timmolter** [comment]
I don't think that will solve your problem because `CurrencyPair` also does not have setters for base and counter, which are also `final` members. Adapting this to your needs would require a major API rewrite.

**Comment by npomfret** [comment]
Making API changes to support some third party systems isn't ever a good thing to do.
