### ISSUE TITLE
[Dev] Add java source/target version to wiki and project metadata

### ISSUE THREAD

**Issue by hurricup** [timmolter/XChange#2094]
I'd like to use streams api. Can I?

**Comment by timmolter** [comment]
https://github.com/bitrich-info/xchange-stream

**Comment by hurricup** [comment]
I mean this one https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html :)
The question is: can I use Java 8 features,

**Comment by timmolter** [comment]
yes.
