### ISSUE TITLE
Quoine: API authentication fails for Quoine openorders

### ISSUE THREAD

**Issue by Leungfranklin** [timmolter/XChange#2116]
I can retrieve the orderbook. Yet when I test 'getOpenorders'', it returns the message with ''API authentication failed". I re-check my security setting for my API. Basically, all access rights(read/write) allowed to be turned on have already been turned on.

**Comment by winwish** [comment]
It seems to need commons-codec 1.9, in the xchange-core it uses 1.4 version.

**Comment by Leungfranklin** [comment]
Thanks, let me try
