### ISSUE TITLE
What does XChange do?

### ISSUE THREAD

**Issue by elongl** [timmolter/XChange#2117]
I want to establish my own Exchange Service.
I don't want to create my own market, I just want to be the linker.
User enters BTC Address and deposits USDs to my site, and then my service will make the exchange and send the BTC to his address.
Exactly like Changelly.
For that I need an API that would make the exchanges for me.
Is that something XChange can do?
**Note: I also want Fiat Currencies to Crypto Currencies exchanges and vice versa.**
Thanks.

**Comment by timmolter** [comment]
See the README and the Wiki.
