### ISSUE TITLE
java 9 java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter     at org.knowm.xchange.binance.service.BinanceHmacDigest.digestParams (BinanceHmacDigest.java:63)

### ISSUE THREAD

**Issue by jnorthrup** [timmolter/XChange#2129]
same as https://github.com/jexler/grengine/issues/5

java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
    at org.knowm.xchange.binance.service.BinanceHmacDigest.digestParams (BinanceHmacDigest.java:63)

**Comment by rafalkrupinski** [comment]
Can this be closed now?
