### ISSUE TITLE
Is there an XChange forum where...

### ISSUE THREAD

**Issue by digitalchaotics** [timmolter/XChange#2168]
...we can ask general "how-to" or clarifications when the docs & source code aren't enough?

For example, I want to ask the following:  _(unclear documentation, or maybe me overthinking it)_

How are the trading fees calculated for a given trade?  The trading fee from the currency-pair metadata (e.g., "0.001") - is that a fraction (i.e., 0.1%) or a fixed amount?

Same question for the withdrawal fees in the currency metadata.  Does the meaning of the value vary from exchange to exchange?

Similar question regarding minimum trading amounts from the currency-pair metadata.  Is the number there a fraction or fixed amount of counter units?

**Comment by digitalchaotics** [comment]
I've just found https://github.com/timmolter/XChange/issues/1072 , which is a partial answer to my subordinate questions concerning fees (% vs flat).  The only part the bothers me is the use of the word "usually"...  :(

**Comment by timmolter** [comment]
In many cases you have to look at the particular exchange module for the details. If the java docs are lacking, which is often the case, then improvements are needed. There is room for improvement almost everywhere in this project, and it's a community effort.

**Comment by traviscollins** [comment]
What about setting up a https://gitter.im?

**Comment by DovAmir** [comment]
+1 in https://gitter.im,
also would like to know what the fields scale or price_scale mean ?
it appears for example in 
https://github.com/timmolter/XChange/blob/develop/xchange-cexio/src/main/resources/cexio.json

**Comment by Arshaku** [comment]
+1 for having a forum/messaging platform!

**Comment by digitalchaotics** [comment]
@DovAmir - pretty sure that the scale and price_scale are referring to the number of digits to the RIGHT of the decimal point.

**Comment by makarid** [comment]
So we will create a gitter forum?

**Comment by timmolter** [comment]
Here we go: https://gitter.im/Java-XChange/Lobby

**Comment by digitalchaotics** [comment]
Excellent!  https://gitter.im/Java-XChange/Lobby
