### ISSUE TITLE
Quadriga Authentication Issue

### ISSUE THREAD

**Issue by makarid** [timmolter/XChange#2191]
Hello, i am trying to make a private call on Quadriga for displaying the balance of btc for example but i get a java.lang.NullPointerException. My code is this:

        final String quadricaApiKey ="xxxxxxxxxx";
        final String quadricaApiSecret ="xxxxxxxxxx";

        Exchange quadricaExchange =ExchangeFactory.INSTANCE.createExchange(QuadrigaCxExchange.class.getName());

        quadricaExchange.getExchangeSpecification().setApiKey(quadricaApiKey);
        quadricaExchange.getExchangeSpecification().setSecretKey(quadricaApiSecret);
        quadricaExchange.applySpecification(quadricaExchange.getExchangeSpecification());

        return quadricaExchange;

Does anyone knows if i need to but something more in order to get private api connection? Thanks a lot

**Comment by makarid** [comment]
Well the NullPointerException i get is because this line "mac256.update(clientId.getBytes());" returns null.So this means that i haven't specify the clientId which is the setUsername on getExchangeSpecification.When i specify it i get a {code=101, message=Invalid API Code or Invalid Signature} (HTTP status code: 200) message.Does anyone has the some problem like me? I get the same thing when i am trying to connect to Bitstamp , although the message is 403 status error.Thanks

**Comment by makarid** [comment]
I try to connect to private API many other exchanges and i did it.Only 2 exchanges i get similar error.The first one is quadriga and the second is quoinex.Has anyone successfully connected to private API on those 2 exchanges? Thanks

**Comment by dmitry-kanunnikoff** [comment]
Thanks for your answer.
I have already specified all the needed parameters... So, will search...
