### ISSUE TITLE
[Binance]Signature for this request is not valid

### ISSUE THREAD

**Issue by mahieddine** [timmolter/XChange#2198]
Hi, 
I started experimenting this library with binance but i have this error when i try to pull my balances from binance 

`getAccountService().getAccountInfo().getUsername();`

> org.knowm.xchange.binance.dto.BinanceException: -1022: Signature for this request is not valid.
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
> 	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
> 	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
> 	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
> 	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:138)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:405) -1022: Signature for this request is not valid.02:37:22.147

I also tried to set the recvWindow param to 60000 like i saw on other threads on other binance client libraries like the following 

`exSpec.setExchangeSpecificParametersItem("recvWindow", 60000L);`

But same error, where does this come from ?

**Comment by daniloguimaraes** [comment]
@mahieddine , this seems to be a very common error at Binance API.
And there is no specific reason to occur.

Have you tried to generate another API Key / Secret on Binance's platform?
Try this and tell us the result, please.

**Comment by mahieddine** [comment]
@daniloguimaraes i've deleted and regenerated another key pair but keep getting the same error, here is my code

```
ExchangeSpecification exSpec = new BinanceExchange().getDefaultExchangeSpecification();
            exSpec.setApiKey(HelperConfig.get(API_KEY));
            exSpec.setSecretKey(API_SECRET);
           // exSpec.setExchangeSpecificParametersItem("recvWindow", 60000L);
            Exchange instance = ExchangeFactory.INSTANCE.createExchange(exSpec);
            Map<String, Wallet> wallets = instance.getAccountService().getAccountInfo().getWallets();
```
Thank you for the help

**Comment by mahieddine** [comment]
@daniloguimaraes i generated another key pair and it worked 
i'm closing this issue, thank you so much for the help
