### ISSUE TITLE
Developer needed

### ISSUE THREAD

**Issue by makarid** [timmolter/XChange#2205]
Hello, 
i would like ask you if someone is interested to code for me small pieces of code that has to do with this project.Most of the code can be implemented to this project because it has to do with connection issues or improvements on some exchanges.I will pay him for every task that he will complete.
If someone is interested to learn more info please send me an email. Thank you.

**Comment by fritzrichter** [comment]
could maybe help, just send me a mail to fritz@work.de

**Comment by makarid** [comment]
Thanks for your reply fritz,i will send you an email sortly.
