### ISSUE TITLE
Create getMetaData or getTradingParis method to MarketDataService interface 

### ISSUE THREAD

**Issue by douggie** [timmolter/XChange#2216]
Hi,

More and more exchanges are provided an API call to get the product information, that might be useful to calling applications to get a list of all the symbols that are trading.

As such what are the thoughts on adding a new method to the MarketDataService interface  that would allow calling applications to get a list of symbols and corresponding metadata (min order size, precisions, margin etc etc) any thoughts on what to call the method?

getSymbols
getTradingPairs
getMetadata

**Comment by rafalkrupinski** [comment]
Are you looking for ExchangeMetaData?

**Comment by douggie** [comment]
doh! Forget about the .getExchangeMetaData() at the Exchange level!
