### ISSUE TITLE
Bitfinex: Please add tickers DSHUSD and NEOUSD

### ISSUE THREAD

**Issue by crush777** [timmolter/XChange#2229]
Please add specific cryptoccurrencies for Bitfinex

**Comment by npomfret** [comment]
Can’t you just request them?

**Comment by crush777** [comment]
They are present on Bitfinex, but they are absent into CurrencyPair class

**Comment by npomfret** [comment]
You can just create your own instances of CurrencyPair.  The constants are only there for convenience.

**Comment by crush777** [comment]
Thanks, it works fine
