### ISSUE TITLE
How to access header fields in response

### ISSUE THREAD

**Issue by bryantharris** [timmolter/XChange#2230]
In abucoins, the page position of the orders returned is returned as part of the header in the HTTP response.  These values are needed to place additional orders calls using the paging values to retrieve different portions of the order book.

Is there an example of where I can intercept the HTTP response so I can extract those header fields?  The body contains JSON but I'd like to also return the values of these header fields as they are technically part of the response.

**Comment by daniloguimaraes** [comment]
Short answer: 
No.

Complete answer:
You could check with @mmazi , the rescu's project leader.

[There is a way to intercept the HTTP request](https://github.com/mmazi/rescu/wiki/Interceptors), but the response headers aren't exposed to the outside world.

I've read about at [rescu issue #72](https://github.com/mmazi/rescu/issues/72) and, in usual conditions, probably you won't intercept the HTTP response. The response headers are exposed only when some error ocurrs, through `HttpResponseAware` interface.

-----

@mmazi , and about add a list of response headers in [`InvocationResult` class](https://github.com/mmazi/rescu/blob/0dec70ac1c96ff8a2ace51162a0acbfd246ec168/src/main/java/si/mazi/rescu/InvocationResult.java)?
Would be easy to do this at [`HttpTemplate.receive`](https://github.com/mmazi/rescu/blob/0dec70ac1c96ff8a2ace51162a0acbfd246ec168/src/main/java/si/mazi/rescu/HttpTemplate.java#L120) method, don't you think?

**Comment by npomfret** [comment]
Looks reasonable. You make them a field of the InvocationResult

**Comment by daniloguimaraes** [comment]
Yeah, @npomfret .
An extra argument at constructor and a getter sounds great 👍

**Comment by mmazi** [comment]
Yes, headers could be added to InvocationResult, but this is not readily available to the client.

I prefer what I suggested here:
https://github.com/mmazi/rescu/issues/103#issuecomment-358254675

**Comment by npomfret** [comment]
Do you mean the `HttpResponseAware` stuff?

**Comment by npomfret** [comment]
Did we come to a consensus on adapting the code in order to provide access to the header fields.

I'm looking at implementing some stuff in gdax and to do it properly I need access to the cb-after field in the header which is required for paging.

There is a work around so it's not urgent.

**Comment by mmazi** [comment]
I've fixed https://github.com/mmazi/rescu/issues/103. You can just implement `HttpResponseAware` on your response classes where you need access to headers. Let me know if this works for you.

**Comment by npomfret** [comment]
Thanks.  Not quite sure where to use `HttpResponseAware` though.  I've search for an example but come up empty.

**Comment by mmazi** [comment]
There is an example in tests, committed today.

**Comment by npomfret** [comment]
Thanks. In which repo?

**Comment by mmazi** [comment]
Here's the commit:

https://github.com/mmazi/rescu/commit/e28befa57720598c8d918908f94e6bf4cdc18122

**Comment by npomfret** [comment]
Thanks.

**Comment by npomfret** [comment]
Tried it out but the `setResponseHeaders` method never got called.  I think we're using rescu 2.0.2 - do we need a more recent version maybe?

**Comment by mmazi** [comment]
2.0.2 was released a few hours ago, that's as recent as it gets :)

The test in the mentioned commit is supposed to demonstrate that it works. Please check your code, or show it if you need more help.

**Comment by npomfret** [comment]
The class I'm adding the interface to is `xchange-gdax/src/main/java/org/knowm/xchange/gdax/dto/GdaxTransfer.java`.  I added the interface, implemented the methods (copied exactly from your example).

```
public class GdaxTransfer implements HttpResponseAware {
...
    private Map<String, List<String>> headers;

...
    @Override
    public void setResponseHeaders(Map<String, List<String>> headers) {
        this.headers = headers;// <- this does not get called
    }

    @Override
    public Map<String, List<String>> getResponseHeaders() {
        return headers;
    }

```

Maybe I have a class path issue and it's picking up an old one?

**Comment by mmazi** [comment]
Looking at the XChange code, this is probably about the following method (the only where GdaxTransfer is used):

    @GET
    @Path("accounts/{account_id}/transfers")
    @Consumes(MediaType.APPLICATION_JSON)
    List<GdaxTransfer> transfers(
      ...

This method does not return GdaxTransfer but rather a List<GdaxTransfer> which is not HttpResponseAware.

I'm not sure how to help you here. Perhaps Jackson allows for json arrays to be serialized into an object of a custom class (not List) that have the List as a member and at the same time implements HttpResponseAware, but I don't know of such functionality in Jackson.

**Comment by npomfret** [comment]
Understood.  So maybe I can just encapsulate the List in my own object which can also have the new interface?

**Comment by npomfret** [comment]
It worked.  Thanks for your help.

@timmolter i think we can close this - i'm about to commit an example in the gdax code that demonstrates how to get access to headers.
