### ISSUE TITLE
Ticker don't have baseVolume

### ISSUE THREAD

**Issue by garciapd** [timmolter/XChange#2231]
Hi, first I have to say that the project is really good.

There is a special reason why the Ticker don't have the base Volume? I have seen that the volume it is a 24h counter Volume, I guess some of the exchanges don't provide that but for instance Bittrex does.

There is another way of getting it or a restriction why it is not in the normalized model? Otherwise I could add it in the org.knowm.xchange.dto.marketdata.Ticker

Regards.

**Comment by cymp** [comment]
I already did something regarding this: https://github.com/timmolter/XChange/issues/1901

**Comment by cymp** [comment]
And the PR: https://github.com/timmolter/XChange/pull/1903

**Comment by garciapd** [comment]
Ok I see, thanks @cymp :)
