### ISSUE TITLE
[50 mBTC Bounty] Implement Bibox

### ISSUE THREAD

**Issue by cymp** [timmolter/XChange#2260]
Hello,

I am paying a 50mBTC bounty to whomever fully implements the [Bibox API](https://github.com/Biboxcom) before Februrary 13rd. 35mBTC otherwise until I close the issue.

Top priority implementations required:
- Place/cancel orders
- Get order books
- Get user balances
- Get user active orders
- Get tickers
- Get symbols (available markets)

Thanks.

Bounties I already paid:  [HitBTC](https://github.com/timmolter/XChange/issues/1633), [YObit](https://github.com/timmolter/XChange/issues/1653), [Livecoin](https://github.com/timmolter/XChange/issues/1730), [Liqui](https://github.com/timmolter/XChange/issues/1825), [Bit-Z](https://github.com/timmolter/XChange/issues/2049), [Coinegg](https://github.com/timmolter/XChange/issues/2049)

**Comment by odrotleff** [comment]
I'll have a look

**Comment by odrotleff** [comment]
Current progress in my fork. Testing would be greatly appreciated :)

**Comment by odrotleff** [comment]
now done with 
- Place/cancel orders
- Get order books
- Get user balances

I might be able to do the rest of your list by this time tomorrow.

**Comment by odrotleff** [comment]
didnt quite finish, but now also done:
- Get user active orders
- Get tickers

**Comment by odrotleff** [comment]
Withdrawal seems impossible to do. It requires the Google Authenticator code :-1:

**Comment by odrotleff** [comment]
Will implement the funding history this evening. Is there anything else you expect for the bounty?

**Comment by cymp** [comment]
Have you implemented the getSymbols? If so, I think this is perfect. I am away for the rest of the week (sorry that was unexpected) but I will test all this as soon as I come back. Please give me an address for the full 50mbtc bounty.

**Comment by odrotleff** [comment]
I dont really find a getSymbols call in their API, XChange also doesnt require such call (I'm guessing you mean a list of all currencies on the exchange). The AccountService.getAccountInfo call returns all currencies with your balance.
I could also fake it by just taking all unique currencies from the available pairs? Do you just need all symbols or what information do you need for the symbols?

**Comment by odrotleff** [comment]
address is 3Q7vE3H3F8bZ7zywP2RpDzAkC8cVF5e7Um
<3

**Comment by cymp** [comment]
I meant getting all the markets, all the currency pairs available for trading.

**Comment by odrotleff** [comment]
yeah thats in. :)

**Comment by cymp** [comment]
@odrotleff Did you find an endpoint giving all the order books in one go? Otherwise everything seems to work perfectly, I will give you more feedback today.

**Comment by odrotleff** [comment]
I will check tomorrow if there's a way. I still did not receive the 50 mBTC btw.

**Comment by cymp** [comment]
They are somewhere on the blockchain, you should receive them.

**Comment by cymp** [comment]
I also frequently get 
```
java.lang.NullPointerException: null
	at org.knowm.xchange.bibox.dto.BiboxSingleResponse.get(BiboxSingleResponse.java:15)
	at org.knowm.xchange.bibox.service.BiboxTradeServiceRaw.placeBiboxLimitOrder(BiboxTradeServiceRaw.java:39)
	at org.knowm.xchange.bibox.service.BiboxTradeService.placeLimitOrder(BiboxTradeService.java:48)
```
Did you encounter this error as well? Looks like the response is empty...

**Comment by odrotleff** [comment]
got the bounty, thanks!

about your questions:

- There is no specific endpoint to retrieve all order books. There might however be a chance to retrieve multiple (and maybe even all) orderbooks, by using the functionality to send multiple requests in one call. Create multiple requests at once by doing BiboxCommands.of(command1, command2, ...), then look at the class BiboxMultipleResponses for parsing the response
- I have never gotten that exception. Does it happen randomly (might be their API fucking up) or can you show me a code snippet that produces this error?

**Comment by cymp** [comment]
- Multiple calls is not a good solution imo, each XChange call must call the exchange API once since it can't deal with exchange limitations  (rate limitation for example).

- It happens randomly but I will let you know if I manage to isolate the case.

Thanks again!

**Comment by odrotleff** [comment]
I dont mean it like that. The Bibox API has (a weird) structure, where you can request multiple responses in just one request (see https://github.com/Biboxcom/api_reference/wiki/home_en#31-formats).

**Comment by cymp** [comment]
Sorry I read what you wrote too fast. Indeed that might be a good solution. Please keep me posted if you find a way to do this.

**Comment by odrotleff** [comment]
Hey man I think this works. Rather untested tho. Tell me if it works as intended, good luck :+1:

**Comment by cymp** [comment]
I will test tomorrow thanks

**Comment by cymp** [comment]
Works perfectly. Do you think it is this possible to implement a cancelAllActiveOrders with the same mechanism?

Thanks again!

**Comment by cymp** [comment]
Regarding the 
`java.lang.NullPointerException: null
	at org.knowm.xchange.bibox.dto.BiboxSingleResponse.get(BiboxSingleResponse.java:15)`
I think I may get this error when I try to place an order with insufficient funds. The problem is that I get no error message on XChange. Could you please try to reproduce ?

**Comment by cymp** [comment]
I have just seen that in the getAllBiboxOrderBooks(Integer depth) you implemented, you call getExchangeSymbols() in order to get all the pairs. I think it should be a good thing to have a getBiboxOrderBooks(Integer depth, Set<CurrencyPair currencyPairs) which would only fetch the desired currencyPairs, allowing to not query getExchangeSymbols() everytime we need to fetch a list of order books. What do you think?

**Comment by odrotleff** [comment]
> Do you think it is this possible to implement a cancelAllActiveOrders with the same mechanism?

Sure, but this will be the last feature I implement. I have other projects, too :)

> I think I may get this error when I try to place an order with insufficient funds. The problem is that I get no error message on XChange. Could you please try to reproduce ?

Intersting, will take a look.

> allowing to not query getExchangeSymbols() everytime we need to fetch a list of order books

getExchangeSymbols() is not a query, it just takes the symbols from the remoteInit() which is ran once when the exchange is initialized. That is why I didn['t create a getBiboxOrderBooks(Integer depth, Set<CurrencyPair currencyPairs).

**Comment by cymp** [comment]
Fine, thank you.

**Comment by cymp** [comment]
Sorry for my stubbornness, I will still add a getOrderBooks(Integer depth, Set<CurrencyPair currencyPairs) as it is less demanding server side and response message size is shorter, thus and can improve performance.

I left the getAllOrderBooks method though.

Please synchronize.

**Comment by odrotleff** [comment]
Damn I didn't read this until after I made PR #2350. This should fix the NullPointerExceptions and it adds the call to cancel multiple orders in one go.

**Comment by cymp** [comment]
Thanks, I'll close the issue once our PR are accepted.
