### ISSUE TITLE
[Cex.io] API key is not activated

### ISSUE THREAD

**Issue by cymp** [timmolter/XChange#2273]
Hi,

I am getting this error message everytime I try to make an authenticated call on Cex. This is the first time I am using Cex.io, is this something I need to do other than what I did:
- Activate the key via the web interface
- authenticating with apikey/password/username

Thanks

**Comment by Wilwilly** [comment]
This is a bug on CexIO. You fix it by disabling 2FA, then you should activate the api key on the exchange page and reenable 2FA.

I had the same problem yesterday, somehow 2FA is making the activation fail, even though it says the key was activated.

Cheers

**Comment by cymp** [comment]
Thanks.

**Comment by gewure** [comment]
This should be reported to CexIo
