### ISSUE TITLE
Liqui getOrder considers "amount" to be cumulative instead of remaining

### ISSUE THREAD

**Issue by trekmbikes** [timmolter/XChange#2282]
Per the Liqui API for Method OrderInfo:
https://liqui.io/api

start_amount: The initial amount at the time of order creation.
amount: The remaining amount of currency to be bought/sold.

However LiquiAdapters.adaptOrderInfo uses "amount" as the LimitOrder's cumulative amount (completed)

**Comment by cymp** [comment]
@cerko2 You worked on this [here](https://github.com/timmolter/XChange/issues/1825). I am not available for one week but maybe you can check this out before I come back.

**Comment by trekmbikes** [comment]
This was previously fixed for LiquiAdapters.adaptActiveOrder at 
https://github.com/timmolter/XChange/pull/1921/commits/640978b0fe374d436be358977707c3ab3c3e9631
but the fix simply needs to be made to adaptOrderInfo() as well

**Comment by cymp** [comment]
Fixed it with https://github.com/timmolter/XChange/pull/2344.

**Comment by cymp** [comment]
Regarding `LiquiAdapters.adaptOrderId needs to use initOrderId not orderId`, I can't test that now but feel free to do it since it looks like to know how to code.
