### ISSUE TITLE
How to Add PASSPHRASE to ExchangeSpecification for GDAXExchange?

### ISSUE THREAD

**Issue by jsl303** [timmolter/XChange#2286]
When I tried to authenticate with GDAXExchange, I get
org.knowm.xchange.gdax.dto.GDAXException: CB-ACCESS-PASSPHRASE header is required (HTTP status code: 400)
How can I add PASSPHRASE to ExchangeSpecification for GDAXExchange?
I tried to set with setPassword(password), but it didn't seem to work.
I looked in the GDAExchange example, but it only had public api with no authentication.
Thank you for your help in advance!

**Comment by ecopoesis** [comment]
Use something like this:

```
exSpec.setExchangeSpecificParametersItem("passphrase", gdax_pass)
```

**Comment by jsl303** [comment]
That works! Thanks! Close!
