### ISSUE TITLE
NotAvailableFromExchangeException string message constructor is private

### ISSUE THREAD

**Issue by bryantharris** [timmolter/XChange#2294]
It would be nice to be able to include some context with NotAvailableFromExchangeException.  For example if a CurrencyPair is not supported (but others are), an implementation could include the CurrencyPair that is not supported as part of the text message (currently private).

At the very least, if there's a philosophical disagreement on this exception having a custom message, would you at least be willing to make the message based constructor protected instead of private so that a subclass could potentially alter the string?

**Comment by timmolter** [comment]
Sure. How about a CurrencyPairNotValidException and a `handleException()` method like in the GDAX module to re-throw the best exception?
The `NotAvailableFromExchangeException` was intended for methods that had no corresponding endpoint on the exchange.

**Comment by bryantharris** [comment]
Sounds good to me, would you like me to add it in core or is that something you'd like to do?  I'll update xchange_abucoins since I've had the most time in there if it's added.  (And will probably add it in other exchanges if it annoys me).

**Comment by timmolter** [comment]
You can add it.
