### ISSUE TITLE
[50 mBTC Bounty] Implement IDEX 

### ISSUE THREAD

**Issue by mrhead66** [timmolter/XChange#2322]
Hi,

As I've seen others do, I am paying a 50mBTC bounty to whomever implements the IDEX API before March 5th 2018. 35mBTC otherwise until I close the issue.

While this is a DEX, a python implementation exists, so I am hoping it is possible.
https://python-idex.readthedocs.io/en/latest/orders.html

Methods need to accept symbols like other exchanges in Xchange, rather than smart contract addresses. 

Top priority implementations required:

Get tickers
Place/cancel orders
Get user balances

Thanks.

**Comment by jnorthrup** [comment]
i have 3 new  xchanges im testing now. idex has moved to the top of the list.

**Comment by odrotleff** [comment]
Tell me if for some reason you cant do it. I'll have some time next week.

**Comment by jnorthrup** [comment]
i have the code talking to idex, grabbing the wallet, balances, tickers, and orderbooks.  

this is not the usual XChange module however, the trades and signatures operate with ethereum addresses directly and the expectations are with the ethereum wallets and not the usual web api's 
 
i can hook up on hangouts/whatsapp and do a short gap analysis to deliver earlier with the most needed features if you want it right away.  it's just busywork now writing adapters, the entired documented interfaces are completely generated

**Comment by jnorthrup** [comment]
im currently experiencing what appears to be serverside react breakage.  

same as https://github.com/sammchardy/python-idex/issues/1

**Comment by mrhead66** [comment]
Thanks for the update. Sounds like good progress so far. 

Can the API abstract away from the fact that they operate with Ethereum addresses?

Happy to opine if you have a particular usecase that you're thinking of explicitly and we can get some others to pitch in some thoughts too.

**Comment by jnorthrup** [comment]
the wallet api complies when the contract synbol is listed on CMC -- and CMC lists relative to BTC.  the API currencypairs are against base-currency, so i think the answer to your first question is yes.  so for OMG, you can get a price from CMC which is approximate to the aurora dex ETH price.  i don't know what XChange supports in terms of dereferencing BTC or USD via ETH,  I went with CMC as a main source of ticker data because of the variances in API adaptations.

it appears the tickers only come in one mode, all-at-once.  the api says send the string naming which one you want to read, but ignores the param.  so now we need a concurrent locking blocking cache for the firehose results -- there are 1200+ contracts as ticker.

wrt to trades,  see https://github.com/jnorthrup/XChange/blob/swagger-gen/xchange-idex/src/main/resources/idex.md#trade

this has been last on my list to tackle.  how badly do you need bot-trading on IDEX? if @timmolter can shed some light on eth contracts in any previous efforts, and the tools, eit would answer soe questions i have about ETH, NEO, WAVES, etc. abstractions i haven't seen mentioned to date.

**Comment by jnorthrup** [comment]
tickers done.  they like to send "N/A" ticker data values.  buyer beware.

**Comment by jnorthrup** [comment]
@mrhead66 @timmolter 

whats done
 * Get tickers
 * Get user balances


what's not realistic: 

 * Place/cancel orders

when you say "trades", you are creating ethereum transactions to be verfied and mined("Trade" json model below).  if you can show me some webj3 or other code I'll do my best, otherwise we should review the needed @mrhead66 usecases and wrap up quickly

```java
public class TradeReq {
  @SerializedName("orderHash")
  private String orderHash = null;

  @SerializedName("amount")
  private String amount = null;

  @SerializedName("nonce")
  private String nonce = null;

  @SerializedName("address")
  private String address = null;

  @SerializedName("v")
  private String v = null;

  @SerializedName("r")
  private String r = null;

  @SerializedName("s")
  private String s = null;

  public TradeReq orderHash(String orderHash) {
    this.orderHash = orderHash;
    return this;
  }
```

**Comment by makarid** [comment]
Hello,thanks for adding the IDEX!Because i cannot find a file with idex name can you please tell me if you have put the code in some other module or file on the Xchange project.Thanks a lot!

**Comment by mrhead66** [comment]
Can you use the python module above as an example? A create_order function is implemented there. 

https://python-idex.readthedocs.io/en/latest/_modules/idex/client.html#Client.create_order

**Comment by makarid** [comment]
Is this a private implementation?

**Comment by jnorthrup** [comment]
progress is viewable thru #2322
 
@mrhead66 python-idex is certainly a good resource, I started looking at it for guidance but noticed it's taking some API liberties of its own and I wanted to be as transparent as possible to the underlying API spec/services 

as of last commit 

 * orders are implemented in the module now
 * balances
 * individual tickers -- the same api call serves a ticker firehose and single-specified ticker. The java code generation cannot supply both. 
 * history
 * accountinfo
 * volume api does not respond as documented, sorry, that's on IDEX to sort out.

@makarid please use my swagger-gen branch at  https://github.com/jnorthrup/XChange/blob/swagger-gen/ and test/refine what you see

**Comment by makarid** [comment]
Thanks for the link @jnorthrup.

**Comment by jnorthrup** [comment]
@mrhead66  I'm running out of unimplemented features and I only use the AccountInfo features in my own operations.  I'd like to sign off on this asap, if you have any refinements or want me to change what's checked in, please follow up

**Comment by mrhead66** [comment]
Thanks @jnorthrup - I've been away, just getting around to checking this now.

Are these packages checked-in? 

import org.knowm.xchange.idex.dto.*
import org.knowm.xchange.idex.service.*
import org.knowm.xchange.idex.util.*

I don't see them listed here, although I am not too familiar with kotlin. 

https://github.com/jnorthrup/XChange/tree/swagger-gen/xchange-idex/src/main/java/org/knowm/xchange/idex

If it would be easier, we could do this initial testing via email/whatsapp etc. and then revert back on this chain.

**Comment by jnorthrup** [comment]
first run mvn install, opening XChange/pom.xml in intellij should be almost painless 

if you use intellij already, you will notice the kotlin language looks like the same thing intellij shows you when you edit java anyways.

whatsapp +6287884284193

im on the last lap of trades/ethereum hashing religion;l.  the python reference is clearer than the docs.

**Comment by jnorthrup** [comment]
..still, very carefully, writing the hash function for the orders.

**Comment by makarid** [comment]
Will you make a pull request to the develop branch in the future?Thanks

**Comment by jnorthrup** [comment]
The pr is done awaiting review and bounty payment @mrhead66 @timmolter

**Comment by mrhead66** [comment]
@jnorthrup I will test this weekend. Thanks.

**Comment by jnorthrup** [comment]
@mrhead66 that's great, we're clear on the date of completion March 1, right?

**Comment by mrhead66** [comment]
Just to post an update on this issue, unfortunately PlaceOrder remains unfinished due to complexities the contributor was facing in signing transactions. 
 
Furthermore, as this implementation was written in Kotlin rather than Java, it also unlikely that the pull request will be accepted and so won't be able to benefit the project as a whole. 

Despite the solution not being workable for me, as a sign of good faith for the work done I have sent 35mBTC. 

I will close the issue for now as I will not be able to sponsor an alternative solution with the bounty. However hope that someone else also working on an IDEX solution will be able to contribute. Thanks.

**Comment by jnorthrup** [comment]
presently idex is not serving bid/ask or orderbook making the automated trades infeasable.  order seems to works
