### ISSUE TITLE
Can You add a new currency pair - LTC_PLN

### ISSUE THREAD

**Issue by justeasyman** [timmolter/XChange#2331]
Hello, I need currency pair ltc_pln on BitBay, can You add it?

**Comment by npomfret** [comment]
You can just create your own currency pairs if the one you need isn't available as a constant.

**Comment by justeasyman** [comment]
I was trying to do that but that didnt go well.. Can You tell me where to create that currency pair?  I cant add them to CurrencyPair.class  because i can't modify that class, it is read only.. I'm not very good programmer, i know basics..

**Comment by makarid** [comment]
Add a new CurrencyPair in your project.You can copy paste a CurrencyPair from the library of CurrencyPairs and just switch Currencies.

**Comment by justeasyman** [comment]
Ok, thanks. it works now.
