### ISSUE TITLE
PoloniexAdapters->adaptPoloniexPublicTrade always return Trade of type ASK

### ISSUE THREAD

**Issue by gmario75** [timmolter/XChange#2338]
Hello,

The method `public static Trade adaptPoloniexPublicTrade(PoloniexPublicTrade poloniexTrade, CurrencyPair currencyPair)` in the `PoloniexAdapter` class always return Trade of type ASK; this seems due to the `poloniexTrade.getType()` returning "0" or "1" while the method is expecting a match with "buy" or "sell".

Thanks,
Mario

**Comment by cymp** [comment]
I can read "buy" and "sell" with [this api call](https://poloniex.com/public?command=returnTradeHistory&currencyPair=BTC_NXT&start=1410158341&end=1410499372). In which case can you see "0" or "1"?

**Comment by traviscollins** [comment]
Don't know if this is the root cause, but Poloniex does have two API versions (1 and 2). Ensure you're using the right one with the library.

**Comment by gmario75** [comment]
thank you both I was using Poloniex API version 2. Using version 1 fixed the issue
