### ISSUE TITLE
NullPointerException while requesting 'restrictions' from Livecoin

### ISSUE THREAD

**Issue by dmitry-kanunnikoff** [timmolter/XChange#2346]
`LivecoinAdapters.java`, method `adaptToExchangeMetaData(...)`, row 94:

`BigDecimal minSize = product.getMinLimitQuantity().setScale(product.getPriceScale(), BigDecimal.ROUND_UNNECESSARY);`

Generates `NullPointerException`, when trying to set scale on `MinLimitQuantity`. 
Products are created after API request to https://api.livecoin.net/exchange/restrictions , if I right.
And in the returning JSON can be `null` for `minLimitQuantity` key.

So, Livecoin can't init.

I think there is need to check `product.getMinLimitQuantity()` on `null` before setting the scale.

**Comment by cymp** [comment]
I have the same error too.

**Comment by cymp** [comment]
I temporarily fixed it like that:
`      BigDecimal minSize;
      if (product.getMinLimitQuantity() == null) {
        minSize = BigDecimal.ZERO;
      } else {
        minSize = product.getMinLimitQuantity().setScale(product.getPriceScale(), BigDecimal.ROUND_UNNECESSARY);
      }`

Not sure if we should put 0 or null though.

**Comment by cymp** [comment]
Can be closed when https://github.com/timmolter/XChange/pull/2344 PR is accepted.
