### ISSUE TITLE
binance accountService.requestDepositAddress returning null for valid assets

### ISSUE THREAD

**Issue by hillerm** [timmolter/XChange#2351]
package xchange-binance 4.3.3

quick example
            String crypto = "BTC"
            Currency currency = Currency.getInstance(crypto);
            AccountService accountService = binanceExchange.getAccountService();
            return accountService.requestDepositAddress(currency);

Fix:
return string address for a given asset

**Comment by hillerm** [comment]
looks like the problem might be related to binance.json not being populated ? i wasn't expecting this to be empty as its a standard of other parts of the code. remoteinit() is calleds before requestDespositAddress() hostwever.

 Also accountService.getAccountInfo().getWallet() correctly populates the the currency symbol.

**Comment by hillerm** [comment]
took a quick look at RemoteInit() and it appears to be populating the correct CurrenyMetaData(). is this method just not implemented yet in 4.3.3 ?

**Comment by brilliantnut** [comment]
I believe this was an instability on the exchange side. I use the Binance code, and it returns valid deposit addresses most of the time, but a few days ago, it had a spurt of returning nulls instead. Then it started working again. Haven't checked what the current status is.
