### ISSUE TITLE
BinanceExchange sending timeInForce in MarketOrders.

### ISSUE THREAD

**Issue by woxip0** [timmolter/XChange#2353]
Hi, first of all, great job, this library is stunning! 

When I place a market order in binance I get the error below:
```
org.knowm.xchange.binance.dto.BinanceException: -1106: Parameter 'timeInForce' sent when not required.
```
In debug I get:
```
DEBUG o.k.x.b.service.BinanceHmacDigest - value to sign: symbol=XRPBTC&side=SELL&type=MARKET&timeInForce=GTC&quantity....
```
The code I'm using:
```
 MarketOrder marketOrder = new MarketOrder(Side.SELL, amount, pair);
```
....

```
exchange.getTradeService().placeMarketOrder(marketOrder)
```
Cheers.

**Comment by timmolter** [comment]
try the latest snapshot jar. Maybe this issue has already been fixed.

**Comment by woxip0** [comment]
Hi, I appreciate your answer.

It comes to Xchange-examples (we had it as dependency), after I removed it everything worked as expected.

Regards.
