### ISSUE TITLE
About LimitOrder.Builder

### ISSUE THREAD

**Issue by makarid** [timmolter/XChange#2387]
Hello, i am using LimitOrder in order to create a new limitOrder to my programs. What is the new LimitOrder.Builder feature,can someone point me to the documentation of that? Does offer any new functionality that LimitOrder cannot do,or it is only for easy-cleaner code creation.
Thanks for your response

**Comment by bryantharris** [comment]
The builder pattern just provides for cleaner construction.  You can confirm in the code what values are being set.  If you use the constructor you have to cross check it with the constructor to manually make sure you have put all the right parameters in the right place.

You'd use it like this

`new LimitOrder.Builder(OrderType.ASK, CurrencyPair.BTC_USD)`
`       .limitPrice( new BigDecimal("5000"))`
`       .originalAmount( new BigDecimal("2.5"))`
`       .build();`

**Comment by makarid** [comment]
@bryantharris thanks a lot for your response! So it is only for easy of use and not any new feature added.Thanks!
