### ISSUE TITLE
NullPointException when i am calling Kucoin.hashcode() on userTrades

### ISSUE THREAD

**Issue by makarid** [timmolter/XChange#2397]
Hello, i get this error when i am trying to print  hasCode() of a userTrade from KucoinExchange. My code works with other Exchanges and prints hashCode.So there is something wrong with Kucoin implemetnation.Does anyone encounter the same issue? Thanks

**Comment by makarid** [comment]
I believe i found the reason for that error. It seems that Kucoin returns null on every Trade.id variable. So when the hashcode takes the id variable,it is null and returns a NullPointException. How can i fix this problem without affecting all the other exchanges? Please tell me your suggestion in order to update the code of the Xchange.

**Comment by timmolter** [comment]
Can you post a stack trace please?

**Comment by makarid** [comment]
Here you are:

Exception in thread "main" java.lang.NullPointerException
	at org.knowm.xchange.dto.marketdata.Trade.hashCode(Trade.java:112)
	at org.knowm.xchange.dto.trade.UserTrade.hashCode(UserTrade.java:94)
	at com.Test.kucoinMain.lambda$main$0(kucoinMain.java:40)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.Test.kucoinMain.main(kucoinMain.java:39)

**Comment by makarid** [comment]
If you print one userTrade to see the information that contains, on Kucoin id = null ,always. Maybe if we Override the hashcode method on a Kucoin class, but i don't know in which class to add it.

**Comment by timmolter** [comment]
OK, I implemented a fix. Objects.hashCode(Object o) will do a null check. It will return 0 if the object is null.

**Comment by makarid** [comment]
Thanks for your fast response and your fix! This means that if the id is null but the other arguments have value,the hashcode will return 0, or that the hashcode will not consider the id value in the calulation?Thanks

**Comment by timmolter** [comment]
According to UserTrade code, 

```
  public int hashCode() {
    return Objects.hash(super.hashCode(), orderId, feeAmount, feeCurrency);
  }
```
if `super.hashCode()` is zero, it still considers (hashes) the other fields.

**Comment by makarid** [comment]
Thanks for clarifing that!

**Comment by npomfret** [comment]
Yeah, trades have to have an id at the moment.  Is it possible to put the value for orderId in the tradeId?
