### ISSUE TITLE
return 0 balance only on Kucoin LTC currency

### ISSUE THREAD

**Issue by makarid** [timmolter/XChange#2408]
Hello, there is a weird error that i get when i am trying to take the balance of my LTC on Kucoin.Even if i have a balance bigger than 0 on Kucoin the response brings me that i have 0 balance in LTC.When i am trying to get my balance on ETH ,i get my actual balance which is bigget than 0.

So is it possible that the problem here is on the Kucoin side.Maybe they have make an error on the LTC parser? Does any one experience the same issue? Thanks

**Comment by michaelscheung** [comment]
I had the same issue, and I found the root cause. It is indeed a fencepost bug where the last page of balances is being ignored. I will submit a pull request

**Comment by michaelscheung** [comment]
Nevermind, it was fixed in this commit: https://github.com/timmolter/XChange/commit/842fb698f7c46af9de44e1a4a90fa253d2b38e08

**Comment by makarid** [comment]
Thanks!

**Comment by makarid** [comment]
Fixed!
