### ISSUE TITLE
okcoin - {"error_code":1007} 

### ISSUE THREAD

**Issue by npomfret** [timmolter/XChange#2416]
Just trying to get started with okcoin but am just getting errors from the api.  For example getting the depth (https://www.okex.com/api/v1/depth.do?ok=1&symbol=btc_usd ) results in:

`{"error_code":1007} `

Any ideas?

**Comment by cymp** [comment]
Maybe you should try the okex endpoints: https://www.okcoin.com/api/v1/depth.do?symbol=btc_usd

**Comment by npomfret** [comment]
I see the `Use_Intl` flag now.  Thanks

**Comment by npomfret** [comment]
Ok, next problem: `{"result":false,"error_code":10005} ` -> `org.knowm.xchange.exceptions.ExchangeException: secretKey does not exist
`
