### ISSUE TITLE
src/test/resources data lacks packages

### ISSUE THREAD

**Issue by jnorthrup** [timmolter/XChange#2431]
there's a risk of misleading results and cut and paste errors with the test data living in "/x/y.json" on the class path.  while the modules are slightly insulated the module authors have not shown a uniform convention and there is much bitrot and the likeleyhood for classpath getByResource to be abused getting sucked in from test code seems like a high probability.

before addressing metadata inequities, it makes sense to put tests and resources in the same packages retroactively when new mods are added on a module.  if a module is open alone without the parent tree in intellij this can be done relatively safely and swiftly.  the problem of refactoring and addressing enchancements becomes evident when trying to isolate any single module's test resources  when the others are open in the IDE.  since the services and DTO's have package encapsulation, it follows that test data should at least have the exchange name in the path whether its a directory, or package name

**Comment by timmolter** [comment]
I never had this issue neither in IntelliJ nor Eclipse. Not saying the issue isn't real...

**Comment by jnorthrup** [comment]
![image](https://user-images.githubusercontent.com/73514/37938483-4ab3d68c-3188-11e8-93d2-b45e137d5294.png)
