### ISSUE TITLE
[gdax] Are Stop orders correctly implemented

### ISSUE THREAD

**Issue by bryantharris** [timmolter/XChange#2434]
I'm trying to use stop orders on gdax.  The API is hooked up, in the sense that it calls the GDAX REST API, but I don't see it setting the stop values properly anywhere.

`GDAXPlaceOrder` has 5 fields in it
size
price
side
product_id
type

I don't see how market or stop orders could be properly formed with the above POJO for the JSON.  Can someone else confirm?  It looks like it's trying to set the order type to 'stop' as opposed to properly setting the stop and stop_price fields.

So here's my question, Do Market and Stop Orders work on gdax as implemented?  They appear to be executing as Limit orders in my experience.

Here's the gdax documentation

Common
Param | Description
-- | --
client_oid | [optional] Order ID selected by you to identify your order
type | [optional] limit or market (default is limit)
side | buy or sell
product_id | A valid product id
stp | [optional] Self-trade prevention flag
stop | [optional] Either loss or entry. Requires stop_price to be defined.
stop_price | [optional] Only if stop is defined. Sets trigger price for stop order.

Limit Orders
Param | Description
-- | --
price | Price per bitcoin
size | Amount of BTC to buy or sell
time_in_force | [optional] GTC, GTT, IOC, or FOK (default is GTC)
cancel_after | [optional]* min, hour, day
post_only | [optional]** Post only flag

Market Orders
Param | Description
-- | --
size | [optional]* Desired amount in BTC
funds | [optional]* Desired amount of quote currency to use

**Comment by timmolter** [comment]
Sorry, I cannot say, as I don't use that feature. Hopefully someone will chime in...

**Comment by bryantharris** [comment]
Looking at the gdax documentation it was pretty off.  It probably worked for some types of orders, but there's no question the underlying capability of the gdax API wasn't exposed 1:1.

I've refactored the area around the order operations to expose the underlying APIs full variety of order types.
