### ISSUE TITLE
Disabling log4j

### ISSUE THREAD

**Issue by TobCar** [timmolter/XChange#2435]
I get the following warning whenever I try to run an instance of the Quadriga exchange. Is there a way to disable or configure log4j? Creating a log4j.xlm file in src/ and src/resources/ didn't do anything.

log4j:WARN No appenders could be found for logger (org.knowm.xchange.ExchangeFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

**Comment by timmolter** [comment]
log4j really shouldn't be appearing in any shape or form from a clean XChange project. We use slf4j, and users can use whatever implementation they want, such as log4j. In the examples, we use logback.
