### ISSUE TITLE
Kraken - getTrades()

### ISSUE THREAD

**Issue by jurepetrovic** [timmolter/XChange#2444]
Hello guys, 

is there any possibility to get trades for multiple currency pairs 
with the same API call? 

Thank you,
Jure

**Comment by timmolter** [comment]
If the Module (exchange) supports it AND it's implemented at the "raw" layer in XChange then yes. But no, not at the generic layer.

**Comment by jurepetrovic** [comment]
Thanks Tim. I checked it out myself in the meantime. 
You cannot do it with trades, but it is possible to get multiple tickers. 
I think this will suffice for my case.  Generally I did it like this.

`
CurrencyPair[] pairs = new CurrencyPair[] { CurrencyPair.ETH_EUR, CurrencyPair.LTC_EUR };
mds = (KrakenMarketDataService)exchange.getMarketDataService();
Map<String, KrakenTicker> ticks = mds.getKrakenTicker(pairs);
`
Nice work guys, keep up the good work!
