### ISSUE TITLE
New Code Style Proposal

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#2452]
The [code style guide](https://github.com/timmolter/XChange/wiki/Code-Style) we made in 2014 was a step in the right direction, but it didn't really work out perfectly because I could never get Eclipse and IntelliJ to format the same as each other nor was there a way to format from the command line for people not using those IDEs. 

In #2443 , the proposed solution is to use the `fmt-maven-plugin` plugin, which formats your code using [google-java-format](https://github.com/google/google-java-format), which also has Eclipse and IntelliJ plugins.

If we switch to this system, the diff files will be much easier to read for me, which I'm having to do a lot these days (5+ PRs per day sometimes).

#### formatting

    mvn com.coveo:fmt-maven-plugin:format
    
Formats your code using [google-java-format](https://github.com/google/google-java-format) which follows [Google's code styleguide](https://google.github.io/styleguide/javaguide.html).

If you want your IDE to stick to the same format, check out the available configuration plugins:

#### Eclipse

Download [`google-java-format-eclipse-plugin_*.jar`](https://github.com/google/google-java-format/releases) and place in `/Applications/Eclipse Java.app/Contents/Eclipse/dropins`. Select the plugin in `Preferences > Java > Code Style > Formatter > Formatter Implementation`. Restart Eclipse.

#### IntelliJ

In the plugins section in IntelliJ search for `google-java-format` and install the plugin. Restart IntelliJ.

**Comment by jnorthrup** [comment]
my main goal was #2432 -- remove the collisions of each modules src/test/resources when merged -- i had to invent a custom execution script in the past because uberjar/maven-assembly-plugin/maven-shade-plugin all failed in various ways relating to file collisions and classpath duplications, no specifics recalled here.

there is a no automated script for that.  #2432 cost me at least a day of hand refactoring each module and testing.

#2443  -- the line endings grew out of the volume of touched files causing unreadable diffs 1700 modifications changed 42000 lines -- and the formatter was a very similar general solution to also make deltas more readable over time.

the .gitattributes makes line-ending automatic on commit for all developers

the maven-plugin overlaps the line-ending functionality by converting at time of format for the files touched

the maven formatter plugin allows the exist 4.3.5-SNAPSHOT codebase to absorb the relocated test resources and unit tests before other patches go in, because the code is changed only where the testresources are loaded.   (one or two file-to-stream conversions also took place)

**Comment by IanWorthington** [comment]
I'd agree with the proposal to permit but not mandate lombok.

**Comment by jnorthrup** [comment]
@timmolter not much interest has been expressed in the formatter, but I have contributed days and days to massaging the tree in purely cosmetic ways and trying to give you comfort and keep you informed and blow out the big changes and fix the line-ending calamity,  and now deeply concerned that I will be spending more days of workarounds or permanent kludges for code that I submitted that's not being used/accepted.  what was the objection to the test resource relocation?  or to using the formatted tree before merging in the 10 new PR's that showed up after that was done and reviewed?

**Comment by timmolter** [comment]
Sorry to keep you in the dark. Tomorrow I will add the formatting stuff and cut a release. Then I'll ask you to submit a PR with the `test/resources` path refactor. I can only work on this in tiny pieces one day at a time. In the future, smaller atomic PRs from you will help things tremendously, as giant monlithic ones tend to be hard to handle.

**Comment by jnorthrup** [comment]
that sounds awesome.  i noticed a problem with maven assembly/shade plugin and created a workaround for what i'm doing months ago.

i think maven reactor projects are good for half a dozen modules, but the XChange project benefits greatly from merging the modules into a single compilation which is enabled by those ... 1700 test resource line changes... which incidentally trigger 35000+ whitespace line changes.  

...at least when you consider refactoring the metadata against a posted bounty

**Comment by timmolter** [comment]
I updated the Wiki page for code style: <https://github.com/timmolter/XChange/wiki/Code-Style>

#### Maven

    mvn com.coveo:fmt-maven-plugin:format
    
Formats your code using [google-java-format](https://github.com/google/google-java-format) which follows [Google's code styleguide](https://google.github.io/styleguide/javaguide.html).

If you want your IDE to stick to the same format, check out the available configuration plugins:

#### Eclipse

Download [`google-java-format-eclipse-plugin_*.jar`](https://github.com/google/google-java-format/releases) and place in `/Applications/Eclipse Java.app/Contents/Eclipse/dropins`. Restart Eclipse. Select the plugin in `Preferences > Java > Code Style > Formatter > Formatter Implementation`. 

#### IntelliJ

In the plugins section in IntelliJ search for `google-java-format` and install the plugin. Restart IntelliJ.

**Comment by timmolter** [comment]
@jnorthrup I'm ready for the line ending refactor. Preferably you just add the changes needed for the line endings, and I'll use the new tool to do the change the line endings myself. That way I can try it out for myself first and make sure it works and there are no issues.

**Comment by npomfret** [comment]
I'm using intellij - what's the right way to do formatting now?

**Comment by timmolter** [comment]
https://github.com/timmolter/XChange/wiki/Code-Style
