### ISSUE TITLE
Authentication failed with the Coinbase API

### ISSUE THREAD

**Issue by privato2009** [timmolter/XChange#2456]
Goodmorning everyone,
I have an authentication problem with my account, through the Coinbase.com API.

I tell you what's happening to me:

- I opened a private account on Coinbase.com,
- I created my API Keys,
- I have enabled all the permissions to the keys, this means that I can perform all the operations possible with those APIs.
- I read the developer's guide and I tried to write a small script to test the authentication, but nothing completely useless ..., I return this error:

[code]
{"errors":[{"id":"authentication_error","message":"invalid signature"}],"warnings":[{"id":"missing_version","message":"Please supply API version (YYYY-MM-DD) as CB-VERSION header","url":"https://developers.coinbase.com/api#versioning"}]}bool(true)
[/code]

Since the examples are in other languages ​​but I use PHP, I think I have made a mistake during the conversion of the script.

This is the link of the official guide:

https://developers.coinbase.com/docs/wallet/api-key-authentication

This is my script:

[code]
<?
$API_KEY = '<---MY API KEY--->';
$API_SECRET = '<---MY API KEY SECRET--->';

$body = '';
$timestamp = time();
$message = $timestamp . 'GET' . 'https://www.mysite.it' . $body;
$signature = hash_hmac('SHA256', $message, $API_SECRET);

$headers = array(
					'CB-ACCESS-SIGN: '.$signature,
					'CB-ACCESS-TIMESTAMP: '.$timestamp,
					'CB-ACCESS-KEY: '.$API_KEY
				); 

$api_url = 'https://api.coinbase.com/v2/user';

$ch = curl_init(); 
curl_setopt($ch, CURLOPT_URL, $api_url);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "GET");
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, 1);
	
$data = curl_exec($ch); 

if(curl_errno($ch))
{ 
    echo "Errore: " . curl_error($ch); 
}
else
{ 
    var_dump($data); 
    curl_close($ch); 
} 
?>
[/code]

Do you give me your opinion?
I've been stuck here for 5 days and I can not understand what I'm missing.
The assistance of Coinbase does not answer me and I have a project to deliver blocked.

Thank you very much for any useful advice.

**Comment by bryantharris** [comment]
I'm not sure what your question has to do with this project, since it looks like your are trying to write to the API directly and not through the Java API provided in this project.

But at first glance I don't see where you are including the passphrase (CB-ACCESS-PASSPHRASE).  You'll need to include the passphrase, api key, and access-timestamp in the headers then use the secret key to sign it.

**Comment by privato2009** [comment]
Yes, I use the API "rest",
I managed to authenticate myself I think.
this is the script that works:

```
<?
$api_key = 'XmUCrOPXYcyRUa95';
$api_secret = 'iP12pS88jeXJEJfYlWzc4OxjvnUlCFxs';

$time = time();
$method = "GET";
$path = '/v2/exchange-rates?currency=EUR';
$sign = base64_encode(hash_hmac("sha256", $time.$method.$path, $api_secret));

$headers = array(
					"CB-VERSION: 2018-03-30",
					"CB-ACCESS-SIGN: ".$sign,
					"CB-ACCESS-TIMESTAMP: ".$time,
					"CB-ACCESS-KEY: ".$api_key,
					"Content-Type: application/json"
);

$ch = curl_init('https://api.coinbase.com'.$path);

curl_setopt($ch, CURLOPT_HTTPGET, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$result = curl_exec($ch);

if(curl_errno($ch))
{ 
    echo '<Error>: '.curl_error($ch);
}
else
{
    var_dump($result);
}

curl_close($ch);
?>
```
I return this:

`{"data":{"currency":"EUR","rates":{"AED":"4.52","AFN":"85.24","ALL":"130.04","AMD":"590.55","ANG":"2.20","AOA":"263.37","ARS":"24.76","AUD":"1.60","AWG":"2.19","AZN":"2.09","BAM":"1.96","BBD":"2.46","BCH":"0.00174977","BDT":"102.06","BGN":"1.95","BHD":"0.464","BIF":"2189","BMD":"1.23","BND":"1.61","BOB":"8.50","BRL":"4.07","BSD":"1.23","BTC":"0.00017300","BTN":"80.06","BWP":"11.76","BYN":"2.40","BYR":"23978","BZD":"2.47","CAD":"1.59","CDF":"1987.68","CHF":"1.17","CLF":"0.0272","CLP":"743","CNH":"7.72","CNY":"7.73","COP":"3435.39","CRC":"697.67","CUC":"1.23","CVE":"110.55","CZK":"25.30","DJF":"218","DKK":"7.44","DOP":"60.74","DZD":"140.22","EEK":"17.97","EGP":"21.71","ERN":"18.45","ETB":"33.90","ETH":"0.00304920","EUR":"1.00","FJD":"2.51","FKP":"0.88","GBP":"0.88","GEL":"2.99","GGP":"0.88","GHS":"5.43","GIP":"0.88","GMD":"58.28","GNF":"11070","GTQ":"9.12","GYD":"255.11","HKD":"9.66","HNL":"29.09","HRK":"7.43","HTG":"79.45","HUF":"312","IDR":"16921.50","ILS":"4.29","IMP":"0.88","INR":"80.05","IQD":"1462.470","ISK":"121","JEP":"0.88","JMD":"154.75","JOD":"0.873","JPY":"131","KES":"123.92","KGS":"84.00","KHR":"4920.00","KMF":"492","KRW":"1305","KWD":"0.369","KYD":"1.03","KZT":"392.71","LAK":"10222.53","LBP":"1864.62","LKR":"191.44","LRD":"161.87","LSL":"14.54","LTC":"0.01021085","LTL":"3.97","LVL":"0.81","LYD":"1.630","MAD":"11.33","MDL":"20.28","MGA":"3954.2","MKD":"61.57","MMK":"1646.17","MNT":"2939.49","MOP":"9.95","MRO":"437.1","MTL":"0.84","MUR":"40.84","MVR":"18.94","MWK":"892.60","MXN":"22.34","MYR":"4.75","MZN":"75.02","NAD":"14.54","NGN":"442.80","NIO":"38.41","NOK":"9.65","NPR":"128.10","NZD":"1.70","OMR":"0.474","PAB":"1.23","PEN":"3.97","PGK":"3.97","PHP":"64.17","PKR":"142.32","PLN":"4.21","PYG":"6826","QAR":"4.48","RON":"4.65","RSD":"118.30","RUB":"70.27","RWF":"1053","SAR":"4.61","SBD":"9.56","SCR":"16.57","SEK":"10.26","SGD":"1.61","SHP":"0.88","SLL":"9518.98","SOS":"716.17","SRD":"9.19","SSP":"160.22","STD":"24472.64","SVC":"10.77","SZL":"14.54","THB":"38.34","TJS":"10.85","TMT":"4.32","TND":"2.947","TOP":"2.74","TRY":"4.86","TTD":"8.39","TWD":"35.65","TZS":"2778.57","UAH":"32.58","UGX":"4540","USD":"1.23","UYU":"34.90","UZS":"10006.05","VEF":"49497.06","VND":"28029","VUV":"130","WST":"3.12","XAF":"654","XAG":"0","XAU":"0","XCD":"3.32","XDR":"1","XOF":"654","XPD":"0","XPF":"119","XPT":"0","YER":"307.87","ZAR":"14.55","ZMK":"6461.28","ZMW":"11.66","ZWL":"396.50"}}}bool(true)`

I do not know if it is what it really needs to return or is a generic result.

I do not understand anything, it works even if I comment the command with the header: 
`curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);`

But another method in PHP without going crazy like that exists?
I see some sample clips use classes written in PHP, for example:

https://github.com/coinbase/coinbase-php

But I can not install Composer or other libraries / dependencies in the Host, it's not mine I do not have permission to do anything.

Is there a way to use that project without Composer?
