### ISSUE TITLE
[kucoin] User trade does not hold originating orderId but only trade Id

### ISSUE THREAD

**Issue by nikos** [timmolter/XChange#2457]
When fetching the trade history from kucoin API (dealt order), the ID of the trade is used currently in the adapter to be set to the originating order Id (and the originating order Id is missing).

**Comment by michaelscheung** [comment]
`UserTrade` already has both an order ID and a fill/transaction ID. [Fix here](https://github.com/timmolter/XChange/pull/2461)

**Comment by nikos** [comment]
@bryantharris thanks for adding your reference to your proposed addition of Fills, from my point of view that would absolutely make sense to improve the developer experience when it comes to observing order completion.
