### ISSUE TITLE
Support for bitfinex market orders

### ISSUE THREAD

**Issue by bcoiffe** [timmolter/XChange#381]
Hi,
Please add support for bitfinex market orders. The implementation is similar to limit order in the tradeservice with the order type set to market ( for margin) or exchange market.

As a side note:
- the xchange API will take in a bid order type to execute a buy and an ask order type to execute a sell. It is semantically wrong... Prices a re usually quoted as bid/ask (cheap/expensive). We buy expensive and sell cheap - we pay the spread on a 2 way transaction. Easy to fix but will create a backward compatibility problem.
- semantics: a currency pair has a base ( strongest ccy) and a term currency ( weakest currency). A deal has a dealt/given/notional ccy and a settled/counter ccy.

Keep up the good work,
Thanks.

**Comment by timmolter** [comment]
This looks to have been implemented.
