### ISSUE TITLE
Implement MintPal

### ISSUE THREAD

**Issue by jarheadjred** [timmolter/XChange#388]
Looking at the Alt-coin related exchanges my next target because of relatively high volume is MintPal.
http://www.cryptocoincharts.info/v2/markets/info

Their V2 API looks to include wallet and automated trading options:
http://www.mintpal.com/api/v2

Just documenting issue, don't see how to add the Feature Request label though.

**Comment by timmolter** [comment]
I removed the module as it now seems quite dead. It could always be resurrected from git.
