### ISSUE TITLE
Implement CoinMkt

### ISSUE THREAD

**Issue by jheusser** [timmolter/XChange#390]
They just released their API: https://coinmkt.com/#!api

They have significant volume and many currency pairs, would be very interesting to have this implemented.

**Comment by radumiron** [comment]
I would want to get involved into this one, but their API specification link gives me an empty page: https://coinmkt.com/info/api

@jheusser , can you take a look if it's the same situation with you?

**Comment by jheusser** [comment]
Thanks, I think they might not be very relevant anymore, haven't heard much from them recently.

**Comment by laisee** [comment]
CoinMkt got taken over by ANX. I  think any trades would be executed through
ANX now. 

From:  radumiron <notifications@github.com>
Reply-To:  timmolter/XChange
<reply+005a1aea7af80818c976ac8392791bbf59badca8bd98946392cf0000000111955d359
2a169ce01e0b7d0@reply.github.com>
Date:  Sunday, 14 June, 2015 10:18 pm
To:  timmolter/XChange <XChange@noreply.github.com>
Subject:  Re: [XChange] Implement CoinMkt (#390)


I would want to get involved into this one, but their API specification link
gives me an empty page: https://coinmkt.com/info/api

@jheusser <https://github.com/jheusser>  , can you take a look if it's the
same situation with you?


Reply to this email directly or view it on GitHub
<https://github.com/timmolter/XChange/issues/390#issuecomment-111840806> .

**Comment by radumiron** [comment]
Thanks for letting me know!

I guess this feature request is pretty much over then, huh? :)
