### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by kpysniak** [timmolter/XChange#449]
Serialization is not really supported in XChange yet. However, it could be very useful in many use cases. Is there any reason for the lack of serialization support?

If not, I would proceed with implementing serialization starting from CurrencyPair.

**Comment by timmolter** [comment]
@bryan4887 Serious question. I'm now also starting to use Apache Storm. So far, I've noticed that it handles serialization of objects automatically as long as the object's members are String, primitives, etc. And I haven't had to add `Serializable` anywhere. Do you have issues with `CurrencyPair` and Storm still?

**Comment by bryan4887** [comment]
@timmolter At least for me, Storm will not let me create a topology where a CurrencyPair is instantiated when a bolt or spout is instantiated.  You can use these objects without serialization if you instantiate them in the `open()` methods of spouts or `prepare()` methods of bolts.

That said, I have ditched Storm for crypto trading, so I no longer care about serialization of XChange objects.  Ultimately Storm is too slow and more of a pain than what it's worth (in this application) in my opinion.

**Comment by timmolter** [comment]
OK, I understand now. I was referring to passing objects between bolts. I didn't try instantiating.
