### ISSUE TITLE
Generic interface tests

### ISSUE THREAD

**Issue by jheusser** [timmolter/XChange#560]
With growing number of exchanges, noticing which exchanges currently "broke" in some way gets harder. I wonder if it wouldn't be easy to write some JUnit tests which instantiate every Exchange implementation and call the public xchange-core interface methods and assert that the output is a non-http error code and contains some data. Not sure this would be feasible for private methods, but it is much better than without it. Perhaps this could even be hooked up with github. What do you think? I know we had a similar discussion months ago but perhaps worth starting again.

**Comment by timmolter** [comment]
I added a mechanism for this and one sample test class under ANX. I'll probably add more soon. Let me know if you see a problem with how I implemented this.

**Comment by timmolter** [comment]
Done. Almost all of the modules now have a single integration test. See Step 9 at: https://github.com/timmolter/XChange/wiki/New-Implementation-Best-Practices

**Comment by rafalkrupinski** [comment]
I have a problem with that. Now the build takes forever, and it fails on mercado due to missing certificate. Should really `mvn clean install` require meddling with jre cerificates?

**Comment by timmolter** [comment]
You could add the "skip tests" maven flag if you want to make it go faster and skip the integration tests.

`mvn test` will run only the unit tests. `mvn verify` will run unit and integration tests, as well as `mvn install` of course. 

You can also add `CertHelper.whatever` to the Mercado module integration test. I did that for another one that failed for me.
