### ISSUE TITLE
Bulk getTickers as a generic method

### ISSUE THREAD

**Issue by zholmes1** [timmolter/XChange#578]
I'm wondering what you guys think of making a generic method for PollingMarketDataService getTickers. It could just return a List<Ticker>. It seems like all exchange APIs that I've looked at support this function. I would be able to do some of the implementation.

**Comment by timmolter** [comment]
@zholmes1 @jamespedwards42 Are any of you still interested in implementing this? I's be willing to help out.

**Comment by zholmes1** [comment]
Sure, I think that this is a feature that should definitely be supported by XChange. I'll have some time this week to start. I'll submit a PR when it's ready.

**Comment by timmolter** [comment]
Any interest for this feature anymore?

**Comment by rafalkrupinski** [comment]
I was implementing this for BTC-e but I'm OK with keeping it as exchange-specific API.

**Comment by kethan** [comment]
Yes interested it would be nice.

**Comment by baffo32** [comment]
Just added exchange-specific version for Hitbtc.

It sounds like everybody thinks this is a good idea but nobody has banged it together.

It looks like the busywork needed is to add the thing to xchange-core/src/main/java/com/xeiam/xchange/service/polling/marketdata/PollingMarketDataService.java and then go through every single implementation and add a stub that raises the appropriate exception.

Might be helpful to make a common base class which raises an exception for every method.

**Comment by zholmes1** [comment]
Honestly... That's the main reason I haven't done it yet. With the number
of exchanges supported, it's a pretty daunting task to go through each one
separately, check if this feature is supported, add an adapter, add the
method to every PollingMarketDataService.

Now that so many exchanges are supported, we could re-work the polling
services so that when it is extended, not every method needs be
implemented. A generic "method not implemented" exception could be thrown.

For instance, say someone is adding a new exchange implementation to
XChange. They're doing the market data service implementation. The exchange
doesn't have an API method for bulk tickers. The dev doesn't have to think
about getBulkTickers(). They don't even mention it in their
NewExchangePollingMarketDataService, and if an end user attempts to call
the method, they just see that the method is not available for NewExchange.

**Comment by timmolter** [comment]
there exists that type of exception already and was used since day one. `NotYetImplemented` I believe it's called.

**Comment by jheusser** [comment]
Outdated imo. Reopen if not the case.
