### ISSUE TITLE
bitfinex swap rate

### ISSUE THREAD

**Issue by lsdjqwq** [timmolter/XChange#597]
it says "In percentage per 365 days" in bitfinex api document, however xChange's comment says "   * @param rate The fixed rate of return for a day".

New offer (lending or borrowing)
POST /offer/new
rate (price): Rate to lend or borrow at. In percentage per 365 days.

 /**
   * @param type Either BID (debtor) or ASK (creditor)
   * @param currency The loan currency code
   * @param tradableAmount Units of currency
   * @param dayPeriod Loan duration in days
   * @param id An id (usually provided by the exchange)
   * @param timestamp The absolute time for this order
   * @param rate The fixed rate of return for a day
   */
  public FixedRateLoanOrder(OrderType type, String currency, BigDecimal tradableAmount, int dayPeriod, String id, Date timestamp, BigDecimal rate) {
    super(type, currency, tradableAmount, dayPeriod, id, timestamp);

    this.rate = rate;
  }

**Comment by timmolter** [comment]
Any status update on this?

**Comment by evdubs** [comment]
I have not made any changes to this as I believe the core loan order implementations are not fully implemented.
