### ISSUE TITLE
Add Support for Bitfinex's WebSocket Feeds

### ISSUE THREAD

**Issue by evdubs** [timmolter/XChange#630]
Here are two emails I have from Raphael of Bitfinex regarding the trade and order book feeds for both liquidity swaps and currency pairs:

## Liquidity swaps
So you can connect to our websocket by connecting to wss://ws.bitfinex.com:3333
To subscribe to channel you have to send the following message format:
["websocket_rails.subscribe", {"data":{"channel": "<channel name>" }}]

To get access to the last swaps match, you have to subscribe to the channel swap.currency
For example, for USD swaps, you subscribe to swap.usd, with the following message:
["websocket_rails.subscribe", {"data":{"channel": "swap.usd" }}]

On those channel you will receive "swap.new" events, with a message detailing the swap rate, the period, the timestamp, the amount of the new swap open.
Example of message:
{"currency"=>"USD", "rate"=>"0.00116", "amount"=>"157.19701514", "period"=>2, "side"=>2, "timestamp"=>"1407157560.841075061"}

Similarly, you can subscribe to the channels swapdepth.currency to get notification of orderbook depth change. You will get events called "depth.change", with messages like this:
{"currency"=>"USD", "rate"=>"0.00117808219178082192", "period"=>2, "type"=>"offer", "total_amount"=>"50.0", "change"=>"50.0", "timestamp"=>"1407157376.464844678"}

(total amount is the total amount of depth at this rate and period, while "change" is the difference after the current change.

## Currency pairs
The trades are on "trade.<pair>" channels, while the change of depth are on "depth.<pair>" channels.

For trade.pair channels, you will receive trade.new events:
Example:
{"pair"=>"BTCUSD", "price"=>"519.0", "amount"=>"0.1", "side"=>0, "timestamp"=>"1408728031.842133865"}

For depth.pair channels you will receive depth.change events, like this:
 {"pair"=>"BTCUSD", "price"=>"624.24", "type"=>"ask", "change"=>"0.02",
"timestamp"=>"1406031564.387416988"}

**Comment by timmolter** [comment]
No streaming API as I can see.

**Comment by evdubs** [comment]
The streaming API does indeed work. I have gotten it to work with tyrus-standalone-client for WebSockets over HTTPS, which is not supported with the published (and XChange dependency) Java-Websocket project. One thing that has made it clunky to use is that Bitfinex and RapidSSL have both updated their certificates since at least the RapidSSL certificate was included with a Java 7 JRE. To get it working, you need to manually add the certificates to a Java keystore. From there, all of the above documentation from Raphael is consistent with the functionality of the WebSocket service. Another thing that makes it clunky is that the currency pair feed doesn't include a "total_amount" field. This can make synchronizing between the order book REST GET and order book update feed somewhat cumbersome. It is also apparently still in beta, so it may be changed without notice.

**Comment by xspdr** [comment]
Hello there
I am having trouble with the websocket handshake. Could someone help me out?

This code is working on Okcoin, but not on Bitfinex:

      self.url = 'wss://ws.bitfinex.com:3333'
      self.hostname = 'ws.bitfinex.com'
      self.path = '/'
      self.port = 3333
      self.key = base64.b64encode(os.urandom(16))


Handshake message:

      GET / HTTP/1.1
      Host: ws.bitfinex.com
      Connection: Upgrade
      Upgrade: websocket
      Sec-WebSocket-Key: base64.b64encode(os.urandom(16))
      Origin: wss://ws.bitfinex.com:3333
      Sec-WebSocket-Version: 13

Message example:

b'GET / HTTP/1.1\r\nHost: ws.bitfinex.com\r\nConnection: Upgrade\r\nUpgrade: websocket\r\nSec-WebSocket-Key: IiToTk2Hn+Cuf10G418CQA==\r\nOrigin: wss://ws.bitfinex.com:3333\r\nSec-WebSocket-Version: 13\r\n\r\n'

Bitfinex return message:

      HTTP/1.1 404 Not Found
      Server: nginx
      Date: Fri, 05 Jun 2015 21:31:17 GMT
      Content-Type: text/html
      Content-Length: 162
      Connection: keep-alive

      <html>
      <head><title>404 Not Found</title></head>
      <body bgcolor="white">
      <center><h1>404 Not Found</h1></center>
      <hr><center>nginx</center>
      </body>
      </html>


Could someone give me a hand or post their handshake upgrade request so I can give it a try?

Thank you

**Comment by brobits** [comment]
http://docs.bitfinex.com/#ssl-websocket-connection
