### ISSUE TITLE
Remove "XYZ returned an error: " ?

### ISSUE THREAD

**Issue by zholmes1** [timmolter/XChange#684]
I'm wondering if it would be a good idea to remove instances of the prefix that is sometimes applied to ExchangeException (for example "BTC-E returned an error: " + e.getMessage()). It would allow more flexibility in displaying error messages to end users. Regardless, we should choose one or the other and make it consistent across all exchange implementations.

**Comment by timmolter** [comment]
Done. Methods now throw IOException or some subclass of `ExchangeException`, which you can catch the specifc ones and handle things properly.
