### ISSUE TITLE
Bitfinex Unable to get OrderID for TradeHistory

### ISSUE THREAD

**Issue by cristianlucaci** [timmolter/XChange#691]
Hi ,

Do you  know if there is something I can do to get the Trades History,including an OrderID for each trade? In current implementation, all I get is a list of executions, but no order id, which makes it difficult to use when you have 10 orders active. All I could find is a way using OrderStatus, but wanted an easier option. Very weird the exchange does not provide such a useful string in each trade.

Trades
GET /trades/:symbol
"Get a list of the most recent trades for the given symbol."

**Comment by timmolter** [comment]
> Issue with order_id is solved in 2.2.0 dev build.
