### ISSUE TITLE
Netagio API implementation bounty - 500mBTC

### ISSUE THREAD

**Issue by jheusser** [timmolter/XChange#696]
Netagio just released it's API. 500mBTC bounty on an implementation. If you want to take this bounty let's talk about timing and code quality briefly. 

https://github.com/Netagio/Netagio-Exchange-APIs
https://secure.netagio.com/

**Comment by jheusser** [comment]
@zholmes1 I would be happy to finish this now by myse.f and pay out the bounty if the existing code is pushed to the repo. Cheers

**Comment by hughneale** [comment]
@jheusser Can I take over this bounty please?

**Comment by jheusser** [comment]
@hughneale  It's fully implemented, just need to take time to push

**Comment by hughneale** [comment]
@jheusser ok nice one, thanks!

**Comment by timmolter** [comment]
exchange no longer exists
