### ISSUE TITLE
BitfinexTradeResponse.timestamp is a float

### ISSUE THREAD

**Issue by apaygh** [timmolter/XChange#726]
BitfinexTradeService.getBitfinexTradeHistory(String, long, int) returns an array of BitfinexTradeResponse. Unfortunately, BitfinexTradeResponse's timestamp is a float. 

Bitfinex sends Unix timestamps like 1414584870.60842865, what includes seconds and fractions down to nano seconds. A float cannot represent such a number. Therefore, this should at least be a double. But as far as I understand it, double would also loose precision (a few nanos). String or BigDecimal would be optimal.

It'd be great if this could be changed. Thanks!

**Comment by timmolter** [comment]
This was finished in the above PR.
