### ISSUE TITLE
Mock Exchange implementation

### ISSUE THREAD

**Issue by mmazi** [timmolter/XChange#747]
I just had an idea to implement a mock exchange (eg. in a `xchange-mock` subproject). It would basically be a simple in-memory exchange, so no http calls etc. whatsoever, and would implement, with basically correct logic (assuming at least some of that is simple), all the standard XChange interfaces.

The purpose of this would be to facilitate testing the business logic of applications that use XChange (its general interfaces) as a library.

This is just a rough idea. I'm sure it would help a lot, but it's probably also a lot of work to do it, or to do it right. On first thought it seems that quite some thought would have to be put into figuring out how to implement "outside market" behavior correctly, ie. simulate what the other users of the exchange do, and how to let the library user control this in a useful way.

For now I'd just like to get some feedback if this seems like a useful thing to do, or if it has perhaps come up in the past; we can talk about how to do it later on.

**Comment by bryan4887** [comment]
Just checking back in on this.  I'm going to start working on a `xchange-simulator` submodule.  To get started however, this will be doing no order matching.  Initially, what I need the most is a way of replaying historical data.  So this simulator will have to accept some kind of interface that provides it with the marketdata that would have otherwise been provided via websocket or http request.

Comments or suggests are appreciated!

**Comment by bryan4887** [comment]
On second thought...I think there is too much diversity in ways one could feed their db into an `Exchange` to warrant the need for another module.  Each user just has to extend `BaseExchange` and provide a source of data specific to their situation.

**Comment by shuklaalok7** [comment]
@bryan4887 I need such a mock exchange to test my logic. Do you have the code public? Where can I see it?

**Comment by bryan4887** [comment]
@shuklaalok7 It's not public yet.

**Comment by timmolter** [comment]
I'm assuming this isn't happening. If yes, please feel free to reopen.

**Comment by rafalkrupinski** [comment]
Starting a new project. Please vote for features :)

**Comment by daniloguimaraes** [comment]
@rafalkrupinski , why not a XChange Maven module?
Why another isolated project/repo?

I've seen that you discussed this subject a couple years ago, but I didn't understood the reasons.

Thank you.

**Comment by rafalkrupinski** [comment]
It's out of scope of XChange
