### ISSUE TITLE
Hitbtc WebSocket

### ISSUE THREAD

**Issue by rafalkrupinski** [timmolter/XChange#764]
I'm trying to implement Hitbtc WebSocket API client.

I got stuck because I don't receive any messages from the trading connection. I've contacted the Hitbtc so called support...

have anyone else noticed how hard they're trying **not** to answer the questions?

**Comment by timmolter** [comment]
Any progress on this or shall I close this issue?

**Comment by rafalkrupinski** [comment]
Currently abandoned
