### ISSUE TITLE
Bitstamp Streaming PusherService - String Comparision

### ISSUE THREAD

**Issue by jgraef** [timmolter/XChange#766]
Hi,

I hacked support for the "diff_order_book" channel for Bitstamp streaming into xchange-bitstamp. But take a look at BitstampPusherService.java line 89. Shouldn't you use "equals" there instead of "=="?
The strange thing is that this worked until I added the if for "diff_order_book".

Regards,
Janosch

**Comment by timmolter** [comment]
I recently, fixed the Bitstamp streaming code. It wasn't working at all. I suppose Bitstamp changed their API. Anyway, both order book streaming events now produce and Orderbook, even the one that it just a delta. For now it's fine that way because at least the information is there.
