### ISSUE TITLE
Implement FoxBit (Blinktrade)

### ISSUE THREAD

**Issue by felipelalli** [timmolter/XChange#803]
New Brazilian exchange (not sure if it has only stream API for now [?]).

https://foxbit.exchange/
https://github.com/blinktrade/frontend/blob/master/jsdev/bitex/api/bitex.js

This exchange is based on open-source BlinkTrade https://blinktrade.com/ platform. It means once implemented, others can be easily supported as well like:

https://urdubit.com/
https://chilebit.net/
https://surbitcoin.com/
https://guaranibitcoin.com/

**Comment by timmolter** [comment]
Added to Wiki

**Comment by webcaetano** [comment]
+1

**Comment by fastcom2015** [comment]
+1
