### ISSUE TITLE
Replace nonce implementation of BitcoinToYou and Mercado Bitcoin to the generic ones

### ISSUE THREAD

**Issue by felipelalli** [timmolter/XChange#806]
To BitcoinToYou it can be replaced by https://github.com/timmolter/XChange/blob/develop/xchange-core/src/main/java/com/xeiam/xchange/utils/nonce/LongTimeNonceFactory.java

The rule of BitcoinToYou is: any number, but always a number bigger than the last one. The millis is suitable because although limiting to 1 call / milli, the API does not recommend less than one call / sec.

The Mercado Bitcoin also can use LongTimeNonceFactory.java, but it have to be divided by 1000 because the rule of Mercado Bitcoin is Unix Epoch Time in seconds. I am not sure if IntTimeNonceFactory.java can be used.

**Comment by timmolter** [comment]
Done.
