### ISSUE TITLE
BitcoinToYou: NullPointerException when trying to create order without enough funds

### ISSUE THREAD

**Issue by felipelalli** [timmolter/XChange#818]
Handle better this error and throw appropriate exception.

Probably this error occurs because in this error situation the result format is different than expected (just a guess).

**Comment by timmolter** [comment]
@felipelalli Can you provide a stack trace please?

**Comment by felipelalli** [comment]
@timmolter I'm sorry, I can't right now because my system made in Scheme SISC uses XChange as an external library and all I got was "NullPointerException". I can simulate the error but to do that I have to create a new fresh empty account because my current account is being heavily used by my bot.

This issue is not so critical, set it as low priority or feel free to delete it. This error can be avoided if you check first the funds before create an order.
