### ISSUE TITLE
Bitso implementation

### ISSUE THREAD

**Issue by mmazi** [timmolter/XChange#819]
Anyone doing Bitso yet? If not, I might implement parts of it in the near future (just the Ripple Gateway parts, ie. Ripple/Bitcoin withdrawal and probably Bitcoin deposit address).

**Comment by mmazi** [comment]
Documentation: https://bitso.com/api_info

**Comment by timmolter** [comment]
No one is doing it that I'm aware of.

**Comment by mmazi** [comment]
Implementing Bitso is simple since their API is largely compatible with Bitstamp's. Here's the general recipe for implementation that worked for me:

1. Copy the Bitstamp classes
2. Search/replace bitstamp -> bitso
3. Search/replace usd -> mxn
4. Remove what Bitso doesn't support
5. Some tweaking (eg. some methods that return boolean with Bitstamp return "ok" string with Bitso).
6. Test.

Authentication using API keys is already implemented in my initial PR.

I found the Bitso technical team very helpful and quick to respond.

So all in all, completing this implementation should be a straightforward and easy task.

**Comment by jheusser** [comment]
This is done now?

**Comment by mmazi** [comment]
This is mostly done (PollingMarketDataService.getTrades implementation is still missing though).
