### ISSUE TITLE
OKCoin returns wrong BTC/USD values - XChange Development version

### ISSUE THREAD

**Issue by pavel4n** [timmolter/XChange#831]
OKCoin returns wrong BTC/USD values. XChange Development version.

I think it could be caused that XChange probably requests other currency pair than BTC/USD?

OKCoin Ticker [currencyPair=BTC/USD, last=1299.88, bid=1299.58, ask=1299.88, high=1322.0, low=1253.5, volume=120247.20059996, timestamp=1421824134678]

Here is example testing code.

package com.xeiam.xchange.examples.bitstamp.marketdata;

import java.io.IOException;

import com.xeiam.xchange.Exchange;
import com.xeiam.xchange.ExchangeFactory;
import com.xeiam.xchange.bitstamp.BitstampExchange;
import com.xeiam.xchange.bitstamp.dto.marketdata.BitstampTicker;
import com.xeiam.xchange.bitstamp.service.polling.BitstampMarketDataServiceRaw;
import com.xeiam.xchange.currency.CurrencyPair;
import com.xeiam.xchange.dto.marketdata.Ticker;
import com.xeiam.xchange.okcoin.OkCoinExchange;
import com.xeiam.xchange.okcoin.dto.marketdata.OkCoinTickerResponse;
import com.xeiam.xchange.okcoin.service.polling.OkCoinMarketDataServiceRaw;
import com.xeiam.xchange.service.polling.PollingMarketDataService;

/**
 * Demonstrate requesting Ticker at Bitstamp. You can access both the raw data from Bitstamp or the XChange generic DTO data format.
 */
public class TickerDemo {

  public static void main(String[] args) throws IOException {

    // Use the factory to get Bitstamp exchange API using default settings
    Exchange bitstamp = ExchangeFactory.INSTANCE.createExchange(OkCoinExchange.class.getName()); //BitstampExchange

    // Interested in the public polling market data feed (no authentication)
    PollingMarketDataService marketDataService = bitstamp.getPollingMarketDataService();

    generic(marketDataService);
    raw((OkCoinMarketDataServiceRaw) marketDataService); //BitstampMarketDataServiceRaw
  }

  private static void generic(PollingMarketDataService marketDataService) throws IOException {

    Ticker ticker = marketDataService.getTicker(CurrencyPair.BTC_USD);

    System.out.println(ticker.toString());
  }

  private static void raw(OkCoinMarketDataServiceRaw marketDataService) throws IOException { //BitstampMarketDataServiceRaw

    OkCoinTickerResponse ticker = marketDataService.getTicker(CurrencyPair.BTC_USD); //BitstampTicker getBitstampTicker(); 

    System.out.println(ticker.toString());
  }

}

Returned displayed output:
08:19:41.960 [default] [main] DEBUG com.xeiam.xchange.ExchangeFactory - Creating default exchange from class name 
Ticker [currencyPair=BTC/USD, last=1297.93, bid=1297.66, ask=1298.18, high=1322.0, low=1253.5, volume=120434.62959997, timestamp=1421824786515]
com.xeiam.xchange.okcoin.dto.marketdata.OkCoinTickerResponse@6aadae91

**Comment by jheusser** [comment]
@pavel4n  XChange OkCoin implements OkCoin China by default. If you want Okcoin International you need to set `Use_Intl` to true as exchange specific parameter in the exchange specification. I will document this better in the java doc.

**Comment by pavel4n** [comment]
Thanks for letting know. I will try that.

The issue with setting and using some specific parameter for an exchange in the scenario where you use ExchangeFactory class to create multiple Exchange instances probably is not optimal. If you simply want BTC_USD pair. 

Would not be XChange library better behaviour to set it automatically if you need BTC_USD?

**Comment by jheusser** [comment]
Not sure I understand, but it works fine like that imo. Also it's not that you want a specific currency pair only, you switch the whole underlying exchange. OkCoin is OkCoin China, until you request International. If you want BTC_USD from Bitfinex you can't instantiate BTC-E :). I have a method similar to:

```
  private Exchange createExchange(final ExchangeConfig exchangeConfig) {

    ExchangeSpecification exSpec = new ExchangeSpecification(exchangeConfig.exchangeClass());
    exSpec.setExchangeSpecificParameters(exchangeConfig.exchangeSpecificParameters());

    exSpec.setSecretKey(exchangeConfig.secretKey());
    exSpec.setApiKey(exchangeConfig.apiKey());
    if(!Strings.isNullOrEmpty(exchangeConfig.userName())) {
      exSpec.setUserName(exchangeConfig.userName());
    }

    Exchange exchange = ExchangeFactory.INSTANCE.createExchange(exSpec);
    return exchange;
  }
```

then can create as many `Exchange` instances as I have `ExchangeConfig` instances (`ExchangeConfig` is my own configuration representation of an exchange).

Hope that helps

**Comment by pavel4n** [comment]
Thanks.

I have this TickerFetcher class code. Which uses class name for creation of exchange.
That it is why in the case of OkCoin Use_Intl issue, I need to insert there an if statement to be able to set which OkCoin I need.

 Here is part of the code.

public class TickerFetcher extends Thread {
	private Exchange exchange;
	private PollingMarketDataService marketDataService;
	private CurrencyPair currencyPair;
	private TickerData last;

	public TickerFetcher(String exchangeClassName, CurrencyPair currencyPair) {
		// Use the factory to get Bitstamp exchange API using default settings
		exchange = ExchangeFactory.INSTANCE
				.createExchange(exchangeClassName);
		
		if (exchangeClassName.equals(OkCoinExchange.class.getName())) {
			ExchangeSpecification es = exchange.getDefaultExchangeSpecification();
			es.setExchangeSpecificParametersItem("Use_Intl", true);
			exchange.applySpecification(es);
		}

		// Interested in the public polling market data feed (no authentication)
		marketDataService = exchange.getPollingMarketDataService();
		
		this.currencyPair = currencyPair;
		
		new Thread(this).start();
	}

....
....
....
}
