### ISSUE TITLE
2.1.0+IntelliJ 14

### ISSUE THREAD

**Issue by steve-osfda** [timmolter/XChange#833]
I am trying out the 2.1.0 version of the "StreamingDemo" for BitStamp (I had previously gotten the 1.X version to work in IntelliJ 12...)

I am using this code:

http://grepcode.com/file/repo1.maven.org/maven2/com.xeiam.xchange/xchange-examples/2.1.0/com/xeiam/xchange/examples/bitstamp/marketdata/StreamingDemo.java

And this pom.xml for Maven:

http://grepcode.com/file/repo1.maven.org/maven2/com.xeiam.xchange/xchange-examples/2.1.0/META-INF/maven/com.xeiam.xchange/xchange-examples/pom.xml?av=f

My IntelliJ is version 14.0.2

For the first import:

    import com.xeiam.xchange.Exchange;

I am getting: "cannot resolve symbol 'Exchange'" (I re-imported the Maven settings and rebuilt the project, to make sure it wasn't a "staleness" issue...)

What's wrong here?

**Comment by steve-osfda** [comment]
Hmmm; the CLASSPATH had to be updated; but it seemed that IntelliJ 12 did that automatically.

Am resolving more maven issues now...

**Comment by steve-osfda** [comment]
I'm just wondering now if a maven dependency would suffice for log4js (I'm now getting an exception for the class LoggingFactory not being found...)

**Comment by rafalkrupinski** [comment]
try

    <dependency>
        <groupId>org.slf4j</groupId>
        <artifactId>slf4j-simple</artifactId>
        <version>1.7.7</version>
    </dependency>

instead (api -> simple)

**Comment by steve-osfda** [comment]
Had tried that, and just retried it (also did a reimport of the maven 
module after making that change...)
IntelliJ says it's not found for that dependency (but it /*does*/ find 
slf4j-api, version 1.7.7...)

**Comment by rafalkrupinski** [comment]
try building once with maven, also check the event log.

**Comment by steve-osfda** [comment]
No go; after a rebuild, slf4j-simple is still showing as red 
(unresolved...) on the tab for pom.xml in IntelliJ (14...)

But as I said earlier, slf4j-api is showing as resolved.

I think I'll have to download the jar (<joke>how quaint...</joke>)

**Comment by rafalkrupinski** [comment]
I don't think I can provide any more help. It's not the right place anyway, as this is not an xchange issue.

Good luck

**Comment by steve-osfda** [comment]
I just thought it would be nice to help make the demo instructions as 
slick as possible;
but thanks anyway...

**Comment by steve-osfda** [comment]
OK; it appears that IntelliJ 14 requires you to specify runtime libraries through the [menu] "File, Project Structure, Libraries"; AND ALSO mark them as Runtime dependencies. I don't remember doing that in the older version of IntelliJ that I had the example working with; I seem to remember specifying all dependencies through the associated pom.xml.

But you were right about using slf4j-simple.

So to get the 2.1.0 version of the Xchange example to work:

STEP 1; Specified the following pom.xml:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>xchange-examples</artifactId>
    <name>XChange Examples</name>
    <description>Provides a set of examples that demonstrate how to use XChange in client applications</description>
    <url>http://xeiam.com</url>
    <inceptionYear>2012</inceptionYear>
    <organization>
        <name>Xeiam, LLC</name>
        <url>http://xeiam.com</url>
    </organization>
    <dependencies>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-core</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-cavirtex</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-openexchangerates</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-btce</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-bitcurex</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-bitkonan</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-bitstamp</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-bittrex</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-campbx</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-bitcoincharts</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-btcchina</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-blockchain</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-kraken</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-bitfinex</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-bitcoinium</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-justcoin</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-coinbase</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-bitcoinaverage</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-cexio</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-cryptotrade</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-bter</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-coinfloor</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-anx</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-itbit</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-cryptsy</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-hitbtc</artifactId>
            <version>2.1.0</version>
        </dependency>
        
        <dependency>
            <groupId>com.xeiam.xchange</groupId>
            <artifactId>xchange-btccentral</artifactId>
            <version>2.1.0</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.xeiam.xchart</groupId>
            <artifactId>xchart</artifactId>
        </dependency>
    </dependencies>
</project>

That covers the compile-time dependencies.

STEP 2; In IntelliJ 14, under [menu] "File, Project Structure, Libraries", I added:

org.slf4j:slf4j-simple:1.7.10
com.github.mmazi:rescu:1.7.2
com.pusher:pusher-java-client:0.3.1

(this list was assembled through trial-and-error runs to see what classes would not be found at runtime...)

You will find a plus sign ("+"; there are multiple ones on this IntelliJ page...) that indicates with a mouse-over: "New Project Library". After clicking on that plus, you select from a popup menu: "From Maven..."; this renders a dialog that will allow you to enter each of the aforementioned libraries, and then click on a magnifying glass to choose the (possibly...) latest+greatest matching maven jar.

STEP3; In IntelliJ 14, under [menu] "File, Project Structure, Modules, Dependencies", each of those libraries specified in step 2 now appear, and I checked them; and under the "Scope" column for each, I toggled the dropdown to "Runtime".

**Comment by timmolter** [comment]
@steve-osfda last week I downloaded IntelliJ14 and imported the xchange-parent project and ran a random example class from xchange-examples. It all worked fine. 

There's absolutely no reason to have to fiddle around with intelliJ to get this to work as it should "just work". Perhaps you imported wrongly? I think I imported it as a Maven project. If you import it as a Java project it might cause issues.

**Comment by steve-osfda** [comment]
It was definitely marked as a Maven project.
Maybe there's a setting somewhere which will automate what I was doing...

**Comment by steve-osfda** [comment]
Thanks, worked out. pom.xml evidently only specified compile-time 
dependencies...

**Comment by steve-osfda** [comment]
Ah, found it; if you're going to have a run-time dependency specified in 
pom.xml, you need:

    <scope>runtime</scope>

(this way you don't have to copy down jars...)

**Comment by steve-osfda** [comment]
And what appear to work when added to the pom.xml (I did a rebuild+run...):
     .
     .
     .
     <dependency>
         <groupId>org.slf4j</groupId>
         <artifactId>slf4j-api</artifactId>
         <version>1.7.7</version>
         <scope>runtime</scope>
     </dependency>
     <dependency>
         <groupId>com.github.mmazi</groupId>
         <artifactId>rescu</artifactId>
         <version>1.7.2</version>
         <scope>runtime</scope>
     </dependency>
     <dependency>
         <groupId>com.pusher</groupId>
         <artifactId>pusher-java-client</artifactId>
         <version>0.3.1</version>
         <scope>runtime</scope>
     </dependency>
     .
     .
     .
