### ISSUE TITLE
There's "code smell" with the init() method in `Exchange`

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#836]
Something seems unclean to me with this. I'm currently trying to understand how to make it better.

**Comment by rafalkrupinski** [comment]
Could you be more specific?

**Comment by timmolter** [comment]
As a user, it's confusing. Do I need it? When? What does it do?

As a maintainer, can I clean this up?

**Comment by timmolter** [comment]
@rafalkrupinski Not yet, still looking into it. It just feels "not right" to me at this point.

**Comment by rafalkrupinski** [comment]
> As a user, it's confusing. Do I need it? When? What does it do?

A javadoc problem?

> As a maintainer, can I clean this up?
?

**Comment by rafalkrupinski** [comment]
So, by asking I may help you realize the exact problem :)

Is it one (or more) of the implementations, or the concept of init() itself?
