### ISSUE TITLE
Proposal to change Map<CurrencyPair, ? extends TradeMetaData> getTradeMetaDataMap()..

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#837]
to `Map<CurrencyPair, TradeMetaData> getTradeMetaDataMap()` in `PollingTradeService`, where `TradeMetaData` is a regular ol' DTO containing the union of all the meta data params found across all exchanges. 

We would then add an adapter and adapt call in the *Raw tradeservice class, just like for everything else.

@rafalkrupinski This is mostly a question directed towards you. I'd like to change it to be consistent with the rest of XChange's API. I guess I need to know how you're using this method. Are guess you are casting to a specific MetaData Impl like:

    HitbtcTradeMetaData eur = (HitbtcTradeMetaData) metaMap.get(CurrencyPair.BTC_EUR);

It's important to me to that this library follows the principle of least surprise and this "outlier" breaks the pattern.

Do you have a compelling reason for it to be the way you created it?

**Comment by rafalkrupinski** [comment]
I agree with your arguments, @timmolter , but how many fields would you like to add?

I'd suggest implementing more exchanges and better see what are we talking about, before we go for more common solutions.

**Comment by timmolter** [comment]
@rafalkrupinski That's the million dollar question as usual!

Your approach is interesting. You still need to cast though, so your logic needs to be aware of what exchange it is operating on to do the cast and call the specific methods it needs to get those unique exchange meta data values. It's not completely generic as desired. Correct me if I'm wrong. That's why I asked how you were using it. 

Your approach doesn't give any advantage over casting to a *Raw service to get to the exchange-specific info (if we moved the metadata stuff there). BTW, I'm not criticizing, but rather just making an observation. Please let me know if I'm missing something. 

I'll be thinking through all this over the next couple of days.

**Comment by rafalkrupinski** [comment]
Primary purpose of the metadata was min amount and scales, and the whole idea came out of validating user orders. Fees were put there only by the way, so I might have not think it through :)

**Comment by timmolter** [comment]
@rafalkrupinski As you will see, I started a refactor. I apologize in advance for messing with your code.

**Comment by rafalkrupinski** [comment]
@timmolter If you fill like apologizing, then don't mess with it ;)

Seriously though, if you can make it better, it's also better for me :)

**Comment by timmolter** [comment]
@rafalkrupinski  It needs to be messed with. ;) In the end it will be better, but there might be some growing pains, and for that I apologize. 

In my last commit, I broke some of your code. I also added 2 TODOs in `ANXAdapters`. You have `PRICE_SCALE` hard coded in that class. How can we migrate that to the `TradeMetaData`? I'm shopping for ideas.

**Comment by rafalkrupinski** [comment]
@see HitbtcTradeService:78

**Comment by rafalkrupinski** [comment]
Regarding comments to 7550e6a, would it be possible to continue this work in a separate branch, and move develop back to 75a20b9 ?

**Comment by timmolter** [comment]
@rafalkrupinski I would rather not. Just think of it this way: Instead of casting the way you were before, you now cast to the *Raw Trade Service and get your meta data. I'll pipe it to the Generic interface soon hopefully. 

I'm thinking about adding the currency pairs to the props file as well as other meta data like maxPollingRate and stuff like that. I might merge the *Adapter classes into the *Service hierarchy somewhere too so the adapter code has access to the metadata too. Any help or opinions would be appreciated.

**Comment by rafalkrupinski** [comment]
Actually I'm not casting anything. Like I said, I added the fees just by the way - they were already there, in the raw DTOs

**Comment by rafalkrupinski** [comment]
@timmolter I asked for a separate branch simply because it looked to me like work in progress, when you removed a method from a generic interface and said that it would be back soon.

**Comment by timmolter** [comment]
@rafalkrupinski I purged all the trademetainfo code on the main 3.0.0 develop branch. It's on the  `trademetainfo` for now. I will revisit it after the 3.0.0 release, as I want to get that pushed out the door ASAP.

**Comment by rafalkrupinski** [comment]
No 'no user left behind' policy? ;(

**Comment by timmolter** [comment]
The trademetadata/init/verify stuff was simply not well thought out enough. We can do better. 

We should plan on a permanent solution to this problem and implement it in V3.1.0.

In a nutshell the problem can defined as this: "Each exchange has a few unique metadata pieces of information that is needed to properly interact with the exchange (e.g. lot sizes, minimum amounts). Right now it's all hardcoded and/or fetched. How do we move the hardcoded stuff to a consistent metadatafile and interface and make it accessible to the code that needs it?"

Things that would be nice to have:

1. Metadata not available from the exchange directly should be provided via `exchange.getMetadata()`
1. A "TradeHelper" class which the tradeservice can use to create and verify orders or whatever else is needed.
1. An initTradeHelper() method that can be implemented to pull together any metadata from 1 or more sources/endpoints (config file, N exchange REST endpoints)

@rafalkrupinski What do you think about that?

For now, for 3.0.0, metadata should be hardcoded or fetched. A simple note such as `TODO add to metadata` or `TODO add to TradeHelper` can be added to help document what all needs to be provided by the future metadata/helper service.

**Comment by rafalkrupinski** [comment]
@timmolter I think I'll just do what I did until now - make a branch (of 3.0) with the last metadata code and test it with my app. Unfortunately I don't have a time for any coding right now, but I hope I can make it before the release. Is there a planned release date?

**Comment by timmolter** [comment]
I'm hoping by next weekend to do the release.

**Comment by rafalkrupinski** [comment]
@timmolter 
> Metadata not available from the exchange directly should be provided via exchange.getMetadata()

If `exchange.getMetaData()` is to be generic, it should return some common DTO type, not just data unavailable for some given exchange. I think raw/generic DTO model applies here: `getRawMetaData()` could return exchange-specific object read from JSON, and `getMetaData()` could return that common DTO*, built from the local and remote data.

> A "TradeHelper" class which the tradeservice can use to create and verify orders or whatever else is needed.
> An initTradeHelper() method that can be implemented to pull together any metadata from 1 or more sources/endpoints (config file, N exchange REST endpoints)

The problem I see here is that not just users need the metadata. E.g. if it contains lot sizes, then trade and market data service need it, so the initialization might be required before the first use.

* In the first post you said that the common MetaData class should contain "the union of all the meta data params found across all exchanges." I think it's against the approach that we use in this project. Usually the classes contain more or less minimal common subset of fields, with sensible exceptions.

**Comment by timmolter** [comment]
So are you saying have a raw and generic meta data DTO like the rest of the XChange API? I think what you're saying sounds good, but I'd need to see your implementation. I'm really bust right now though and don't have the time for right now. If you want to send a PR with the barebones changes to show what you mean that would help and make it really easy for me to review. Otherwise, I'll try to make some time and look at your `meta` branch.

**Comment by rafalkrupinski** [comment]
> have a raw and generic meta data DTO like the rest of the XChange API?

That's correct

> send a PR with the barebones changes to show what you mean

No problem. I want to add one more exchange before I start testing it with my client code, but right now you can see the changes in the core, ANX and BTC-e.

**Comment by rafalkrupinski** [comment]
@timmolter I think this issue is resolved now

**Comment by timmolter** [comment]
Thanks!
