### ISSUE TITLE
I'd like to remove all deprecated code

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#844]
Hi fellow developers,

There is deprecated code in the following modules:

1. BTC-E V2
1. BTCChina
1. CaVirtex V1

Are there any objections to removing the deprecated code before the 3.0.0 release? The deprecated code has been around for a long while now.

@veken0m are you still using Cavirtex v1?

**Comment by veken0m** [comment]
I'm not using the BTC-e v2 and CaVirtex v1 modules anymore, so I'm OK with removing both modules. Removing deprecated BTCChina code is good with me as well unless it affects the module's core functionality.

Thanks for the much needed clean up!

**Comment by sutra** [comment]
Removing the deprecated code of BTCChina is OK.

**Comment by timmolter** [comment]
done.

**Comment by mmazi** [comment]
Sorry to be late about this (I only noticed this when my project's compile failed), but I think there are several features in BTC-e v2 that don't exist in v3; at least that was the case a while ago. See eg. #756 .
