### ISSUE TITLE
accountInfo.result might be null

### ISSUE THREAD

**Issue by DISSIDIA-986** [timmolter/XChange#845]
18:35:46.546 [default] [pool-2-thread-1] TRACE si.mazi.rescu.HttpTemplate - Http call returned 200; response body:
{"frozen_btc_display":"0.0000","total":"0.00","loan_ltc_display":"0.0000","net_asset":"0.00","loan_cny_display":"0.00","available_ltc_display":"0.0000","loan_btc_display":"0.0000","frozen_ltc_display":"0.0000","available_cny_display":"0.00","frozen_cny_display":"0.00","available_btc_display":"0.0000"} 
18:35:46.582 [default] [pool-2-thread-1] ERROR DETAIL_APPENDER - 查询账户信息异常: java.lang.NullPointerException: null
	at com.xeiam.xchange.huobi.service.polling.HuobiAccountServiceRaw.getHuobiAccountInfo(HuobiAccountServiceRaw.java:24) ~[xchange-bitvc-3.0.0-SNAPSHOT.jar:na]
	at com.xeiam.xchange.huobi.service.polling.HuobiAccountService.getAccountInfo(HuobiAccountService.java:26) ~[xchange-bitvc-3.0.0-SNAPSHOT.jar:na]

as above ,accountInfo.getResult() might be null.

**Comment by timmolter** [comment]
Someone really needs to put some effort into completing the BitVC/Huobi implementation. There are no unit tests or example classes. Whoever made it, just slapped something quickly together. That's helpful, but to make it really robust, someone needs to add samples json responses, unit tests, and example classes.

See: https://github.com/timmolter/XChange/wiki/New-Implementation-Best-Practices

**Comment by jheusser** [comment]
@timmolter I am the guilty :) I am using the implementation heavily and it works very well though, including borrowing, switching between Huobi providers etc. I will look into adding unit tests / json responses.

@DISSIDIA-986 @timmolter this should have been fixed with https://github.com/timmolter/XChange/pull/822 which I can't see represented in 3.0.0 for some reason?

**Comment by timmolter** [comment]
@jheusser 3.0.0 has that patched code in issue #822. The problem reported above is that there is no `result` json field, hence the `result` field in `HuobiAccountInfo` is null, leading to `if (accountInfo.getResult()...` throwing a NPE. It's weird though that in his posted JSON, everything is 0 (zero). So there might be a different problem there.

Would you be willing to push some redacted json as a basis for unit tests? If you do that, I can make the unit tests.

**Comment by DISSIDIA-986** [comment]
@timmolter  @jheusser  The account is new created,so everything is 0.

**Comment by jheusser** [comment]
@timmolter yes I will provide that, hopefully this weekend. I plan on improving the implementation anyway and include all of Huobi's exchanges (BitYes has the same API as well).

**Comment by timmolter** [comment]
@jheusser Awesome. What's the deal with Huobi and BitVC? It looks like they are both crammed into the bitvc module? The only thing they share are the DTOs and the adapter class, right? Perhaps we should create two modules and have the bitvc one depend on the huobi one? What do you think?

**Comment by jheusser** [comment]
@timmolter BitVc and Huobi are the same company. BitVc is basically the margin trading side of Huobi, you can execute trades on BitVc on Huobis market data. So it really is a combination of the two sites, the market data you get from Huobi, and trading / account information comes from BitVc. 
As their the APIs are 95% identical (everything except some account info fields) it makes no sense to copy&paste the entire code base twice (or actually three times now with BitYes, which is the same except for USD), and fix bugs / changes and keep the two repos in sync.

Perhaps it would make more sense if everything went under the name "Huobi" (just like the company) and you select which implementation you want to use through an exchange specific parameter, either Huobi (market data and trading), BitVc (huobi market data and bitvc trading)?

**Comment by timmolter** [comment]
Yeah, kinda like the `Use_Intl` flag in OKCoin (IIRC). Putting it all under Huobi like you suggested meks a lot of sense.

**Comment by jheusser** [comment]
Lots of changes since then, closing this for now.
