### ISSUE TITLE
Crypto-Trade is shutdown temporarily

### ISSUE THREAD

**Issue by timmolter** [timmolter/XChange#849]
https://www.crypto-trade.com/maintenance

**Comment by timmolter** [comment]
> We are undergoing complete transformation of our company and recruiting new development and management staff which will take at least 3 months.All the unpaid user balances and CT shares are intact with us.Feel free to contact us at ctnewteam@crypto-trade.com

**Comment by rafalkrupinski** [comment]
#1016
