### ISSUE TITLE
Bitfinex cancel order API problem

### ISSUE THREAD

**Issue by DISSIDIA-986** [timmolter/XChange#856]
I have a cancel order request with response:
{
	"id" : 186295545,
	"symbol" : "btcusd",
	"exchange" : null,
	"price" : "230.0",
	"avg_execution_price" : "0.0",
	"side" : "sell",
	"type" : "exchange limit",
	"timestamp" : "1423180814.0",
	"is_live" : true,
	"is_cancelled" : false,
	"was_forced" : false,
	"original_amount" : "0.294",
	"remaining_amount" : "0.294",
	"executed_amount" : "0.0"
}
from  response "is_cancelled" : false,but when I looked up the open orders on the page, this order was not found at that time.

**Comment by DISSIDIA-986** [comment]
How to avoid this ? making ordering app works in multiThread.

**Comment by timmolter** [comment]
Looks like a bug in their API to me. You cancel it, they respond by saying "not cancelled". You later check and it was cancelled.

**Comment by Panchen** [comment]
Interestingly, I regularly see the "opposite" with BitFinex cancels:

BitfinexTradeServiceRaw.cancelBitfinexOrder(String orderId) returns true, so presumably no BitfinexException exception is thrown in bitfinex.cancelOrders(...), but the order is left open and fills with a trade time stamp seconds after the cancel. I am trying to isolate the exact cause of this and get a reliable indicator of a BitFinex's order status after a cancel without success so far.

NB I don't see this issue with exactly the same code used against BitStamp where BitstampTradeServiceRaw.cancelBitstampOrder(int orderId) reliably returns a correct boolean cancel order indicator / throws an exception after a cancel.

**Comment by timmolter** [comment]
The code looks good to me.
