### ISSUE TITLE
Turning off stderr logging in Coinsetter StreamingExchangeService

### ISSUE THREAD

**Issue by bryan4887** [timmolter/XChange#858]
Does anyone know how to turn off the logging to stderr?  I get a stderr message like the following for every event received through the `StreamingExchangeService`. 
```
Feb 09, 2015 4:42:16 PM io.socket.IOConnection transportMessage
INFO: < 5:::{"name":"ticker","args":[{"bid":{"price":221.72,"size":0.05,"exchangeId":"SMART","timeStamp":1423521736241},"ask":{"price":221.81,"size":3.32,"exchangeId":"SMART","timeStamp":1423521736241},"last":{"price":221.72,"size":2.75,"exchangeId":"COINSETTER","timeStamp":1423521728086},"volume24":640.60877658,"volume":509.07015012}]}
```

My instantiation looks like this:
```
Exchange exchange = ExchangeFactory.INSTANCE.createExchange(CoinsetterExchange.class.getName());
		CoinsetterStreamingConfiguration streamCfg = new CoinsetterStreamingConfiguration();
		streamCfg.addAllMarketDataEvents();
	    service = exchange.getStreamingExchangeService(streamCfg);
	    service.connect();
```

Thanks!

**Comment by rafalkrupinski** [comment]
Would you check the source of io.socket.IOConnection and see what logger they use?
I bet it's java.util.logging, In which case we need to add and configure org:slf4j:jul-to-slf4j.

**Comment by bryan4887** [comment]
Sorry, @rafalkrupinski, I'm not quite sure where I'd find that.  Mind pointing me where to look?

**Comment by timmolter** [comment]
Correct. It's using `java.util.logging.Logger`

**Comment by sutra** [comment]
You may find a trick in CoinsetterSocketIOServiceDemo

// Bridge/route all JUL log records to the SLF4J API.
removeHandlersForRootLogger();
SLF4JBridgeHandler.install();

**Comment by bryan4887** [comment]
That worked.  That's a lot, everyone!
