### ISSUE TITLE
Version 3.0.0 BitStamp Streaming Service Order timestamp is null

### ISSUE THREAD

**Issue by Panchen** [timmolter/XChange#859]
The BitStamp public streaming exchange service now returns order book events with overall timestamp=null so there is no time information in order book events since timestamp has always been null on individual orders in the book.  
NB The polling service returns a valid overall timestamp for the same orderbook. 

Streaming Service returns:
17:42:22.958 OrderBook [timestamp: null, asks=[	LimitOrder [limitPrice=222.55, Order [type=ASK, tradableAmount=1.39239189, currencyPair=BTC/USD, id=, timestamp=null]], .....

Polling service returns:
17:42:23.617 OrderBook [timestamp: Wed Feb 11 17:42:16 GMT 2015, asks=[	LimitOrder [limitPrice=222.55, Order [type=ASK, tradableAmount=1.39239189, currencyPair=BTC/USD, id=, timestamp=null]], .....

ExchangeEvent evt = streamServiceBS.getNextEvent();
switch (evt.getEventType()) {
        // Listen to order update events
        case SUBSCRIBE_ORDERS:
            orderBookBS = (OrderBook) evt.getPayload();
            orderBookBS.getTimeStamp() ==> null

**Comment by timmolter** [comment]
If Bitstamp doesn't return a timestamp, the the OrderBook timestamp will be null. If Bitstamp DOES return a timestamp, then we need to add code to make sure it's being put in the OrderBook. I doubt, Bitstamp is providing a timestamp though.

**Comment by Panchen** [comment]
Agreed but if I run the same code built using version 2.2.0 then the streaming order book event contains a valid overall timestamp. E.g.

Streaming service returns:
09:58:21.088 OrderBook [timestamp: Thu Feb 12 09:58:21 GMT 2015, asks=[LimitOrder [limitPrice=219.66, Order [type=ASK, tradableAmount=0.22754164, currencyPair=BTC/USD, id=, timestamp=null]], 

Polling service returns:
09:58:21.142 OrderBook [timestamp: Thu Feb 12 09:58:20 GMT 2015, asks=[LimitOrder [limitPrice=219.66, Order [type=ASK, tradableAmount=0.22754164, currencyPair=BTC/USD, id=, timestamp=null]], 

so it appears to me that the behaviour has changed from v2.2.0 to v3.0.0. For the streaming service I think it is important to be able to test if the event is stale.

**Comment by timmolter** [comment]
In commit 34f4754, I removed all instances where `new Date()` was coded for timestamps for consistency and sticking with our original intention for the timestamp field. In retrospect, we should have named it `servertime`, as that's what it represents. The timestamp according to the API endpoint.

**Comment by Panchen** [comment]
I understand the need for consistency and the fact that BitStamp aren't actually providing us with this streaming data but, from a practical perspective, this feels like a somewhat retrograde step to me. 

- Orders / the order book are transient so should have a time context.
- The streaming BitStamp order book is now inconsistent with the polling order book.
- BitStamp provides approx 30 sec snapshots of the order book via the polling interface and labels these with a timestamp so they have a context.
- BitStamp makes live snapshots of the order book available whenever it changes via the pusher streaming interface. BitStamp doesn't provide the server timestamp 
with these messages but by their very nature they should be labelled with the current time at preferably source or failing that destination.
- My understanding is that the pusher Orderbook snapshots arrive and are processed asynchronously by clients using the consumerEventQueue. This means that the inherent 
time context of the order book can be lost. E.g. if the client's processing cycle is slower than the snapshot arrival rate.

If no time context is (sent or) added when the snapshots arrive and are placed on the event queue how would you recommend clients determine if the events are stale? 
How about implementing an event local timestamp which is created when the event goes on the queue and is exposed via a getEventTime() method so that the order book timestamp can be kept pure as the servertime?
