### ISSUE TITLE
proposal to change StreamingExchangeService 

### ISSUE THREAD

**Issue by mkatkov** [timmolter/XChange#870]
Hi,

The current implementation of StreamingExchangeService, at least for bitstamp, consist of blocking queue. Therefore, if one wants to poll different exchanges he/she should wait for the next event to come. To resolve this issue, I suggest to add a new method, say, numEventsAvilable that will return the number of events currently available in the queue, so that all events can be pooled, or pooling can be skipped if no events available.

**Comment by rafalkrupinski** [comment]
Why not allow users to register listeners?

**Comment by timmolter** [comment]
done.
