### ISSUE TITLE
CurrencyPair parsing fails for ItBit

### ISSUE THREAD

**Issue by jheusser** [timmolter/XChange#879]
ItBit returns `XBTUSD` as currency pair in its json response, however the constructor for CurrencyPair expects the format `AAA/XXX`. I'm not entirely sure why this now starts failing. Any ideas why constraint has been added to CurrencyPair instantiation? @timmolter 

Instantiation of [simple type, class com.xeiam.xchange.currency.CurrencyPair] value failed: Could not parse currency pair from 'XBTUSD'
si.mazi.rescu.HttpStatusIOException: Instantiation of [simple type, class com.xeiam.xchange.currency.CurrencyPair] value failed: Could not parse currency pair from 'XBTUSD'
	at si.mazi.rescu.ResponseReader.read(ResponseReader.java:106) ~[btctrade-epl-0.6.17-SNAPSHOT-jar-with-dependencies.jar:na]
	at si.mazi.rescu.RestInvocationHandler.mapInvocationResult(RestInvocationHandler.java:137) ~[btctrade-epl-0.6.17-SNAPSHOT-jar-with-dependencies.jar:na]
	at si.mazi.rescu.RestInvocationHandler.receiveAndMap(RestInvocationHandler.java:125) ~[btctrade-epl-0.6.17-SNAPSHOT-jar-with-dependencies.jar:na]
	at si.mazi.rescu.RestInvocationHandler.invoke(RestInvocationHandler.java:104) ~[btctrade-epl-0.6.17-SNAPSHOT-jar-with-dependencies.jar:na]
	at com.sun.proxy.$Proxy22.getTicker(Unknown Source) ~[na:na]
	at com.xeiam.xchange.itbit.v1.service.polling.ItBitMarketDataServiceRaw.getItBitTicker(ItBitMarketDataServiceRaw.java:25) ~[btctrade-epl-0.6.17-SNAPSHOT-jar-with-dependencies.jar:na]
	at com.xeiam.xchange.itbit.v1.service.polling.ItBitMarketDataService.getTicker(ItBitMarketDataService.java:34) ~[btctrade-epl-0.6.17-SNAPSHOT-jar-with-dependencies.jar:na]

**Comment by timmolter** [comment]
@jheusser I just looked at the history of the `CurrencyPair` class, and I don't see any time where such a constructor existed. I could of course have overlooked something. Do you see where that constraint has been added?

**Comment by jheusser** [comment]
@timmolter No don't see it either, but the ItBit adapter hasn't been changed either, that's why I'm a bit confused. And I'm pretty sure a lot of exchanges don't report currency pairs with a middle-slash, so all those should fail as well (which they don't). The exception clearly comes from the CurrencyPair constructor and "XBTUSD" is passed in as argument.

**Comment by rafalkrupinski** [comment]
I think the CurrencyPair(String) ctor used to create USD/XYZ pairs. Is it possible that it was returning "USD/XBTUSD" ?

**Comment by jheusser** [comment]
@rafalkrupinski I think that's possible, but I doubt all 20+ exchanges only send currency pairs in the `BTC/USD` format? 

The API call has always been:
https://api.itbit.com/v1/markets/XBTUSD/ticker

**Comment by rafalkrupinski** [comment]
from xchange 2.1.0:

    public CurrencyPair(String baseSymbol) {
        this(baseSymbol, Currencies.USD);
    }

It means that CurrencyPair returned by an exchange and mapped directly by rescu must have been interpreted as "XBTUSD/USD"

**Comment by nimrood** [comment]
This class may be useful:  `com.xeiam.xchange.utils.jackson.CurrencyPairDeserializer`

**Comment by timmolter** [comment]
Ah, yes. I do recall removing that constructor. And there was a `fromString` static method that handled the String with a `/` in it. So it seems like the situation right now is that many of the implementations will have this issue. But also before, the currency pairs were not being parsed correctly either as @rafalkrupinski noted.

**Comment by rafalkrupinski** [comment]
The problem would only occur when DTO used CurrencyPair and json data had a string not in the expected format. ITBit didn't show any error, because it has no tests for parsing DTOs.

**Comment by jheusser** [comment]
Right, thanks for figuring out the issue. So one fix could be to simply remove the CurrencyPair argument for the `ItBitTicker`, or make `CurrencyPair` try to parse 6-letter currency pair strings on instantiation.

**Comment by rafalkrupinski** [comment]
@jheusser I'd rather avoid guessing the format in the constructor. You can change CurrencyPair to String in the DTO and parse it later, or look into @nimrood suggestion. Probably the first option is better, since ItBit uses XBT instead of more common BTC.

**Comment by jheusser** [comment]
@rafalkrupinski good point, will do. Thanks.
