### ISSUE TITLE
unable to set futures contract on com.xeiam.xchange.dto.trade.LimitOrder

### ISSUE THREAD

**Issue by douggie** [timmolter/XChange#911]
Hi,

Happy to fix up okcion futures trading, but wondered if you would like me to add an additional constructor to  com.xeiam.xchange.dto.trade.LimitOrder that support the setting of FuturesContract in addition to the currency pair to to extend LimitOrder with an ok coin specific limitOrder, but would seem a bit messy as then people would have to import the exchange specific implementation. 

Let me know which you prefer and I will make the udpates.

**Comment by jheusser** [comment]
Have a look at the latest OkCoin changes. Don't think this suggestion is necessary.

**Comment by douggie** [comment]
Hi Jonathan,

You are always one step ahead! Will pull down the latest code.

Regards

Douggie

**Comment by douggie** [comment]
HI Jonathan,

Looks good. Will do some more testing on the order side.

Thanks once again.

**Comment by jheusser** [comment]
Np Douggie

**Comment by douggie** [comment]
Hi Jonathan, 

Took a look, I believe the implementation is as follows
1) add new contracts to exchange specification using Futures_Contract or Futures_Contract_String
2) then initiliase exchange vai the .createExchange(exchange spec) method.

For the other markets, you can create the exchange spec without having to specify the contract/currrency pair, it can just be passed to the pollingmarketdata service getTrades() method. 

Wondered if you had any thoughts around making it consistent for the derivatives and cash instruments?
