### ISSUE TITLE
[Bitfinex] Unable to get trade history "Key timestamp should be a timestamp string."

### ISSUE THREAD

**Issue by zholmes1** [timmolter/XChange#921]
Here's my code:

    tradeService.getTradeHistory(currencyPair, Long.valueOf(0L), Integer.MAX_VALUE);

I've been messing around with the parameters but I can't seem to get anything to work. Did Bitfinex change the format of their timestamps?

**Comment by rodriguezvalencia** [comment]
As an addenda, I have an experience similar with the following code (in Scala, that's why it looks a bit different):
```Scala
tradeService.asInstanceOf[BitfinexTradeServiceRaw].getBitfinexTradeHistory("BTCUSD", 0, 300)
```
This code has been working in production for months **until April 4th** when it suddenly started failing... I also believe they must have changed their format recently.

**Comment by zholmes1** [comment]
I spoke with Raphael from Bitfinex and he resolved the issue. Old code should be working now.
