### ISSUE TITLE
How to handle URL that contains API key?

### ISSUE THREAD

**Issue by matthewdowney** [timmolter/XChange#930]
Bitcoin.de has an API that is accessed like: https://bitcoinapi.de/v1/{–APIKEY–}/trades.json
So in my BitcoindeExchange class I call `.setSslUri()` with `https://bitcoin.de/v1/`
Like this:
```
ExchangeSpecification exchangeSpecification = new exchangeSpecification(this.getClass().getCanonicalName());

exchangeSpecification.setSslUri("https://bitcoinapi.de/v1/");
exchangeSpecification.setHost("bitcoin.de");
// ... rest of exchange specification stuff
```

What should my approach be for allowing the API key to be set and integrated into the URL? If this is the correct sslUri to use, which class should I modify to allow the API key to be set?

My goal for a final product is something like:
```
Exchange bitcoinde = ExchangeFactory.INSTANCE.createExchange(BitcoindeExchange.class.getName());

bitcoinde.setAPIKey("my api key"); // not sure how this step should be done

PollingMarketDataService marketDataService = bitcoinde.getPollingMarketDataService();

Ticker ticker = marketDataService.getTicker(CurrencyPair.BTC_EUR);

System.out.println(ticker.toString());
```

**Comment by timmolter** [comment]
In your class `BitcoindeBasePollingService extends BaseExchangeService ` create the rest proxy like this:

        this.bitcoinde = RestProxyFactory.createProxy(BitcoideAuthenticated.class, exchange.getExchangeSpecification().getSslUri() + "/" exchange.getExchangeSpecification().getAPIKey());

or something similar.

**Comment by matthewdowney** [comment]
Thanks!  That makes perfect sense.  Where then should I set the API key?  I can't do `bitcoinde.getExchangeSpecifications().setAPIKey("my key");`

**Comment by timmolter** [comment]
exchangeSpecification.setApiKey("safgsdfgh");

**Comment by matthewdowney** [comment]
I feel like an idiot, I wasn't creating the Exchange object from an ExchangeSpecification object.  This ended up working perfectly:

```
/* configure the exchange to use our api key */
ExchangeSpecification exchangeSpecification = new ExchangeSpecification(BitcoindeExchange.class.getName());
exchangeSpecification.setApiKey(MY_API_KEY);

/* create the exchange object */
Exchange bitcoindeExchange = ExchangeFactory.INSTANCE.createExchange(exchangeSpecification);

/* create a data service from the exchange */
PollingMarketDataService marketDataService = bitcoindeExchange.getPollingMarketDataService();

/* display our ticker data */
try {
        Ticker ticker = marketDataService.getTicker(CurrencyPair.BTC_EUR);
        System.out.println(ticker.toString());
} catch (IOException e) {
        e.printStackTrace();
}

```
