### ISSUE TITLE
Coinbase: incorrect handling of a server error response for orders with too low amounts

### ISSUE THREAD

**Issue by mmazi** [timmolter/XChange#935]
It seems that with Coinbase, when the user tries to place a (market) order for an amount that would result in a purchase for less than USD 1 (which is [the minimum allowed by Coinbase](https://support.coinbase.com/customer/portal/articles/1404398-what-is-the-minimum-amount-of-bitcoin-that-i-can-purchase-)), the XChange API call will fail with an incorrect message. The message is "Error parsing as date".

Here's some example code that should reproduce this case (can be tried in `CoinbaseTradeDemo`):

```
 MarketOrder marketOrder = new MarketOrder(Order.OrderType.BID, new BigDecimal("0.004"), new CurrencyPair(Currencies.BTC, Currencies.USD));
 String orderId = tradeService.placeMarketOrder(marketOrder);
```

I would fix this myself, but I can't use Coinbase's API because I'm not a US resident.

**Comment by jheusser** [comment]
Anyone working on finishing `CoinbaseEx` now that it's also available in the UK (market data orderbook, trades)?

**Comment by mmazi** [comment]
@jheusser can you briefly explain why this was closed? Is it solved? Not reproducible?

**Comment by jheusser** [comment]
@mmazi might have been overzealous 😄 . Rational was that it's from 2015, the exchange has changed name in the meantime, gone through some API changes, and nobody replied to my last query for 1.5 years.

**Comment by jheusser** [comment]
Also, Coinbase can be used as non-US resident as well: https://support.coinbase.com/customer/portal/articles/1826671-what-countries-us-states-are-supported-for-coinbase-exchange-

**Comment by mmazi** [comment]
Good enough :)

I don't have the original issue any more so I'm fine with closing it, just as long the reason for closing is recorded.

**Comment by jheusser** [comment]
Ok agree, will add reason on closes from now on.
