### ISSUE TITLE
OER Can't Get Ticker

### ISSUE THREAD

**Issue by sslx** [timmolter/XChange#958]
After I upgraded to 3.0, my OER stopped working.
			ExchangeSpecification exchangeSpecification = new ExchangeSpecification(OERExchange.class);
		exchangeSpecification.setApiKey("...");
Exchange openExchangeRates = ExchangeFactory.INSTANCE.createExchange(exchangeSpecification);
	PollingMarketDataService marketDataService = openExchangeRates.getPollingMarketDataService();
		Ticker ticker = marketDataService.getTicker(new CurrencyPair("CNY", "USD"));
java.lang.NullPointerException
Thanks,

**Comment by timmolter** [comment]
can you paste a stack trace?

**Comment by sslx** [comment]
java.lang.NullPointerException
     at com.xeiam.xchange.oer.OERAdapters.adaptTicker(OERAdapters.java:24)
     at 
com.xeiam.xchange.oer.service.polling.OERMarketDataService.getTicker(OERMarketDataService.java:60)
     at Trade.main(Trade.java:238)

**Comment by timmolter** [comment]
I pushed a fix. please try the latest snapshot jar. I did not test my fix because I don't have an account at OER, but it should now work. Let me know if there is still an issue.

**Comment by sslx** [comment]
Does maven have repository for snapshots?
I only see 3.0.

**Comment by timmolter** [comment]
See XChange's readme under the Maven section. Or google about snapshot artifacts. You can also build the jar yourself, which is simple as `mvn package` on the command line.
