### ISSUE TITLE
com.xeiam.xchange.exceptions.ExchangeException: Nonce is too small.

### ISSUE THREAD

**Issue by wskinner** [timmolter/XChange#961]
I'm seeing this often when placing orders on BitFinex. https://github.com/timmolter/XChange/issues/464 referenced a similar issue, but in my case it's happening when *placing*, not *canceling* orders.

**Comment by rafalkrupinski** [comment]
Could you check out this branch?
https://github.com/rafalkrupinski/XChange/tree/fix/bitfinex-nonce

It should throw NonceException instead, so you can handle it.
