### ISSUE TITLE
commit message format

### ISSUE THREAD

**Issue by br0x** [timmolter/XChange#970]
Guys, can we please include exchange name (or specific component name) in the commit message, if it is not common. Like this:
[btce] Removed unnecessary code

**Comment by rafalkrupinski** [comment]
Yes, we can! :)

**Comment by timmolter** [comment]
Yup, good idea. Feel free to add a note to the README and/or the WIki.

**Comment by jheusser** [comment]
+1

**Comment by bryan4887** [comment]
+1

**Comment by dimecoin** [comment]
+1

**Comment by timmolter** [comment]
added here: <https://github.com/timmolter/XChange/wiki/New-Implementation-Best-Practices>
