### ISSUE TITLE
okcoin streaming service timestamps only mills from midnight CST

### ISSUE THREAD

**Issue by douggie** [timmolter/XChange#976]
Currently the okcoin provides the millisecond time stamp from midnight CST (i.e. UTC+8h), so 49803000 is CST Midnight + 14:50:03.

If a direct epoch conversion is done, 49803000 is Thu  1 Jan 1970 14:50:03 BST. 

Should we look to add CST midnight of the current China day to the timestamp provided by the exchange so that the the full epoch is returned. Possibly the changes could be in OkCoinJsonAdapters.java

**Comment by timmolter** [comment]
Yes. Or put it in OKCoinUtils.java if that exists. Or create it it not.

**Comment by douggie** [comment]
Will do. Thanks Tim!
