### ISSUE TITLE
1000 mBTC bounty – implement meXBT Exchange

### ISSUE THREAD

**Issue by williamcoates** [timmolter/XChange#986]
Documentation for the meXBT exchange API is here: https://mexbt.com/api/http. Best way to get playing around is to test in the sandbox, more information on the previous link. 

You can also check our clients for Ruby, Node and Python:

Ruby: https://github.com/meXBT/mexbt-ruby
Node.js: https://github.com/meXBT/mexbt-node
Python: https://github.com/meXBT/mexbt-python

To qualify for the bounty the code should also contain sufficient unit test coverage.

Authentication to the exchange API is basically identical to Bitstamp but with different parameter names, so should be able to re-use some code there. 

Feel free to drop me any questions!

**Comment by sutra** [comment]
So this is the list of API to be implemented?

Public API

api.ticker()
api.orders()
api.trades()
api.currency_pairs()

Private API

api.create_order(1234.56, pair='btcmxn', side='buy', order_type='market')
api.cancel_order(123)
api.cancel_all_orders()
api.modify_order(123, 'move_to_top')
api.modify_order(123, 'execute_now')
api.account_info()
api.account_balance()
api.account_orders()
api.account_trades(start_index=-1, count=10)
api.account_addresses()
api.withdraw(1.23456789, 'foo')

**Comment by williamcoates** [comment]
This is quite an exhaustive overview of the exchange api:

http://docs.mexbtprivateapi.apiary.io

But I was assuming it's only important to implement what is needed to integrate with the XChange interface... is there much value in implementing custom exchange API that is not part of the XChange core?

**Comment by rafalkrupinski** [comment]
@williamcoates you're the sponsor, it's a question for you. What do you want to pay for?

**Comment by sutra** [comment]
Do not find any special, seems just all common methods.
Taking this issue, ideally 1 or 2 weeks could finish the work.

**Comment by williamcoates** [comment]
At least the minimum XChange core API, thoroughly tested.

**Comment by sutra** [comment]
```
Content-Type: application/json
{
  "isAccepted": "true",
  "serverOrderId": "18",
  "dateTimeUtc": "952132543213543"
}  
```
Hi @williamcoates , what's the notation of the dateTimeUtc? Haven't found any description about it.

**Comment by sutra** [comment]
OK, I finally found it:
```
Sadly, the timestamp is a .NET tick :( To convert to a regular JS date you can use this function:

convertDotNetTick = function(tick) {
    new Date((tick - 621355968000000000) / 10000);
}
```

**Comment by williamcoates** [comment]
Apologies @sutra  for not getting back to you earlier

**Comment by sutra** [comment]
Hi @williamcoates , this work should have been finished. Please check.

**Comment by williamcoates** [comment]
Thanks, I will try and check it next week.

**Comment by williamcoates** [comment]
@timmolter We are happy to release the bounty now, what is the normal procedure?

**Comment by timmolter** [comment]
Normally @sutra would post the public address in this issue and you'd  pay it. you and @sutra can decide on an alternative method if that's not acceptable.

**Comment by sutra** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Please send to the following address:
bitcoin:1Q8VKnEhL1RciXNw9m3dt628F5QQCYatvA?amount=1.00000000&label=https%3A%2F%2Fgithub.com%2Ftimmolter%2FXChange%2Fissues%2F986

https://github.com/sutra
2015-07-02
-----BEGIN PGP SIGNATURE-----

iEYEARECAAYFAlWVOQUACgkQLUcPhHYLUeOJggCgt6GP8xdVUCYI4gN3pGGErCaj
1rwAoIRAMz2U37zJbKLmdmr53oWMwbdJ
=aCHs
-----END PGP SIGNATURE-----
```

**Comment by williamcoates** [comment]
Paid :)
